import type { EndingDef } from '../engine/content-types'

export const ENDINGS: EndingDef[] = [
  {
    id: 'tragic_death',
    nameVi: 'Kết cục: Đường về dang dở',
    nameEn: 'Ending: A Road Left Unfinished',
    epitaphVi: 'Người ta chỉ tìm thấy chiếc giỏ linh thảo đổ giữa lối mòn.',
    epitaphEn: 'They found only an overturned herb basket on the trail.',
  },
  {
    id: 'keeper_of_names',
    nameVi: 'Kết cục: Người giữ tên',
    nameEn: 'Ending: Keeper of Names',
    epitaphVi: 'Ngươi trả từng cái tên cho người sống lẫn người chết. Từ đó, không ai bị cứu bằng cách bị xóa đi nữa.',
    epitaphEn: 'You return names to the living and the dead. From then on, no one is saved by being erased.',
  },
  {
    id: 'rootless_star',
    nameVi: 'Kết cục: Sao không rễ',
    nameEn: 'Ending: The Rootless Star',
    epitaphVi: 'Linh căn phế không chữa được; nó trở thành khe hở để ánh sáng đi qua.',
    epitaphEn: 'The broken root is never repaired; it becomes the opening through which light passes.',
  },
  {
    id: 'city_of_ghosts',
    nameVi: 'Kết cục: Thành phố của những người nhớ',
    nameEn: 'Ending: City of Remembering Ghosts',
    epitaphVi: 'Ngươi bán ký ức để cứu thành phố khỏi đói. Đêm nào ngoài cửa sổ cũng có người gọi đúng tên ngươi.',
    epitaphEn: 'You sell memory to save a city from hunger. Every night, someone outside remembers your name exactly.',
  },
  {
    id: 'iron_lantern',
    nameVi: 'Kết cục: Đèn sắt trước cổng',
    nameEn: 'Ending: The Iron Lantern',
    epitaphVi: 'Gương bị khóa trong nhà chung, chìa khóa chia cho dân làng. Bình yên không còn cần một vị cứu tinh.',
    epitaphEn: 'The mirror is locked in a common house, its key divided among villagers. Peace no longer needs one saviour.',
  },
  {
    id: 'borrowed_face',
    nameVi: 'Kết cục: Gương mặt mượn',
    nameEn: 'Ending: The Borrowed Face',
    epitaphVi: 'Ngươi thắng được ký ức của kiếp trước, rồi dần quên mất gương mặt nào là của mình.',
    epitaphEn: 'You master the past life’s memory, then slowly forget which face was ever yours.',
  },
  {
    id: 'rift_kingdom',
    nameVi: 'Kết cục: Vương quốc khe nứt',
    nameEn: 'Ending: Kingdom of the Rift',
    epitaphVi: 'Hà dẫn ngươi qua chiếc gương, nhưng không bao giờ bước ra. Ngươi dựng một thành trì cho người bị quên, với cái giá là chính người dẫn đường.',
    epitaphEn: 'Ha leads you through the mirror, but never steps out. You build a refuge for the forgotten at the cost of the one who guided you.',
  },
  {
    id: 'forgiven_enemy',
    nameVi: 'Kết cục: Mùa xuân của kẻ thù',
    nameEn: 'Ending: Spring for an Enemy',
    epitaphVi: 'Khoa không tha thứ ngay. Nhưng hai người cùng trồng lại cây đã bị chặt, và mùa xuân đến muộn một năm.',
    epitaphEn: 'Khoa does not forgive at once. But you replant the felled tree together, and spring arrives a year late.',
  },
  {
    id: 'blank_page',
    nameVi: 'Kết cục: Trang giấy trắng',
    nameEn: 'Ending: The Blank Page',
    epitaphVi: 'Ngươi không còn biết kiếp trước đã hứa gì. Lần đầu tiên, điều đó không khiến ngươi sợ.',
    epitaphEn: 'You no longer know what the last life promised. For the first time, that does not frighten you.',
  },
  {
    id: 'jade_heir',
    nameVi: 'Kết cục: Người thừa kế ngọc vỡ',
    nameEn: 'Ending: Heir to Broken Jade',
    epitaphVi: 'Ngươi không chọn gương hay lửa; ngươi dạy người khác cách tự chọn. Chiếc trâm vỡ được trao lại qua nhiều đời.',
    epitaphEn: 'You choose neither mirror nor fire; you teach others to choose. The broken jade pin passes through many hands.',
  },
  {
    id: 'quiet_harmony',
    nameVi: 'Kết cục: An cư dưới mái tranh',
    nameEn: 'Ending: Harmony Under a Thatched Roof',
    epitaphVi: 'Không thành tiên, nhưng mỗi sáng đều có cháo nóng, tên thật, và tiếng cười.',
    epitaphEn: 'No immortality, but every morning has warm porridge, true names, and laughter.',
  },
  {
    id: 'nameless_ascension',
    nameVi: 'Kết cục: Phi Thăng Vô Danh — và 200 linh hồn được gọi lại',
    nameEn: 'Ending: Nameless Ascension — and Two Hundred Souls Called Back',
    epitaphVi: 'Ngươi xóa Hệ Thống trước khi bước lên đỉnh. Hai trăm cái tên trở về, gọi lần lượt nhau dưới trời, và không một ai biết người giải phóng chúng đã đi đâu.',
    epitaphEn: 'You erase the System before stepping onto the summit. Two hundred names return, calling one another under the sky, and no one knows where the one who freed them has gone.',
  },
]
