import type { ItemDef } from '../engine/content-types'
import { ITEM_HERB, ITEM_MANUAL, ITEM_TALISMAN } from '../engine/constants'

export const ITEMS: ItemDef[] = [
  {
    id: ITEM_HERB,
    nameVi: 'Linh thảo',
    nameEn: 'Spirit Herb',
    descVi: 'Cỏ ba lá ngọc, nhai giòn tan, khí ấm lan ra.',
    descEn: 'A jade trefoil; chewy, with warmth spreading after.',
    aliases: ['herb', 'linh thao', 'thao'],
    usable: true,
    effects: { qi: 8 },
    buyPrice: null,
    sellPrice: 12,
  },
  {
    id: 'wooden_staff',
    nameVi: 'Mộc trượng cũ',
    nameEn: 'Old Wooden Staff',
    descVi: 'Cây trượng theo ngươi từ làng; nặng vừa đủ để tự tin hơn.',
    descEn: 'The village staff; just heavy enough to inspire confidence.',
    aliases: ['staff', 'moc truong', 'wooden staff'],
    usable: false,
    equipmentSlot: 'weapon',
    buyPrice: null,
    sellPrice: 3,
  },
  {
    id: 'tattered_robe',
    nameVi: 'Áo vải vá',
    nameEn: 'Patched Cloth Robe',
    descVi: 'Vết vá ngang dọc nhưng vẫn giữ được khí thế.',
    descEn: 'Patched in every direction, yet it retains a certain presence.',
    aliases: ['robe', 'ao vai', 'patched robe'],
    usable: false,
    equipmentSlot: 'robe',
    buyPrice: null,
    sellPrice: 2,
  },
  {
    id: 'pill_hp',
    nameVi: 'Viên hồi nguyên',
    nameEn: 'Restoration Pill',
    descVi: 'Ngọt hậu vị đắng, máu chạy như suối mùa xuân.',
    descEn: 'Sweet then bitter; blood runs like a spring stream.',
    aliases: ['hp pill', 'vien hoi nguyen', 'hoi nguyen', 'healing pill'],
    usable: true,
    effects: { hp: 25 },
    buyPrice: 35,
    sellPrice: 17,
  },
  {
    id: 'pill_qi',
    nameVi: 'Viên tụ khí',
    nameEn: 'Qi-Gathering Pill',
    descVi: 'Tan trên lưỡi như sương, dạ dày ấm áp khí.',
    descEn: 'Melts like dew on the tongue; the belly hums with qi.',
    aliases: ['qi pill', 'vien tu khi', 'tu khi', 'qi'],
    usable: true,
    effects: { qi: 20 },
    buyPrice: 30,
    sellPrice: 15,
  },
  {
    id: ITEM_TALISMAN,
    nameVi: 'Bùa trừ tà',
    nameEn: 'Warding Talisman',
    descVi: 'Nét chữ đỏ còn thơm mùi son, dán lên ngực là yên lòng.',
    descEn: 'Vermilion strokes still smelling of cinnabar; press it to your chest and breathe easy.',
    aliases: ['talisman', 'bua tru ta', 'bua', 'ward'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'jade_charm',
    nameVi: 'Ngọc bội',
    nameEn: 'Jade Charm',
    descVi: 'Lạnh tay, đẹp một cách không cần chứng minh.',
    descEn: 'Cool to the touch, beautiful without needing to prove anything.',
    aliases: ['jade', 'ngoc boi', 'charm', 'ngoc'],
    usable: false,
    equipmentSlot: 'accessory',
    buyPrice: 60,
    sellPrice: 45,
  },
  {
    id: ITEM_MANUAL,
    nameVi: 'Bí kíp cong queo',
    nameEn: 'The Crooked Manual',
    descVi: 'Bản chép tay lệch nét dành riêng cho linh căn khuyết tật.',
    descEn: 'A crooked-handwritten copy made for defective spirit roots.',
    aliases: ['manual', 'bi kip', 'sach'],
    usable: false,
    teachesTechniqueId: 'crooked_circulation',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'rift_step_scroll',
    nameVi: 'Ngọc giản Khe Bộ',
    nameEn: 'Rift Step Scroll',
    descVi: 'Ngọc giản run khẽ như muốn đi trước chân ngươi.',
    descEn: 'The jade slip trembles as if it wants to step before you do.',
    aliases: ['rift step', 'khe bo', 'rift scroll'],
    usable: false,
    teachesTechniqueId: 'rift_step',
    buyPrice: null,
    sellPrice: 55,
  },
  {
    id: 'ironwood_saber',
    nameVi: 'Thiết mộc đao',
    nameEn: 'Ironwood Saber',
    descVi: 'Đao gỗ đen nặng tay, đổi lại rất biết nói chuyện với giáp mỏng.',
    descEn: 'A heavy blackwood saber that speaks clearly to thin armor.',
    aliases: ['ironwood saber', 'thiet moc dao', 'saber'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 1,
    buyPrice: 90,
    sellPrice: 45,
  },
  {
    id: 'mistweave_vest',
    nameVi: 'Vân văn giáp y',
    nameEn: 'Mistweave Vest',
    descVi: 'Lớp áo nhẹ, đường chỉ mây ẩn đi ngay khi nhìn kỹ.',
    descEn: 'A light vest whose cloud-stitching vanishes when inspected.',
    aliases: ['mistweave vest', 'van van giap y', 'vest'],
    usable: false,
    equipmentSlot: 'robe',
    requiredStage: 1,
    buyPrice: 80,
    sellPrice: 40,
  },
  {
    id: 'spirit_ring',
    nameVi: 'Nhẫn tụ linh',
    nameEn: 'Spirit-Gathering Ring',
    descVi: 'Vòng bạc mờ, đeo lâu thì đầu ngón tay cũng ấm lên.',
    descEn: 'A dim silver ring that warms the fingertips over time.',
    aliases: ['spirit ring', 'nhan tu linh', 'ring'],
    usable: false,
    equipmentSlot: 'accessory',
    requiredStage: 2,
    buyPrice: 180,
    sellPrice: 90,
  },
  {
    id: 'cloudpiercer_spear',
    nameVi: 'Xuyên vân thương',
    nameEn: 'Cloudpiercer Spear',
    descVi: 'Cán thương sáng, dài và rất không hợp để cất trong túi.',
    descEn: 'A bright long spear, thoroughly unsuitable for a small bag.',
    aliases: ['cloudpiercer spear', 'xuyen van thuong', 'spear'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 3,
    buyPrice: 280,
    sellPrice: 140,
  },
  {
    id: 'herbal_breath_manual',
    nameVi: 'Dược Hơi Quyển',
    nameEn: 'Herbal Breath Manual',
    descVi: 'Mỗi trang còn vương mùi hương thảo vừa phơi nắng.',
    descEn: 'Every page still carries the scent of sun-dried herbs.',
    aliases: ['herbal breath', 'duoc hoi', 'herbal manual'],
    usable: false,
    teachesTechniqueId: 'herbal_breath',
    requiredStage: 1,
    buyPrice: 120,
    sellPrice: 60,
  },
  {
    id: 'iron_skin_manual',
    nameVi: 'Thiết Bì Quyển',
    nameEn: 'Iron Skin Manual',
    descVi: 'Lời mở đầu bảo ngươi đừng thử nó bằng đầu.',
    descEn: 'Its first line asks you not to test it with your head.',
    aliases: ['iron skin', 'thiet bi', 'iron skin manual'],
    usable: false,
    teachesTechniqueId: 'iron_skin',
    requiredStage: 1,
    buyPrice: 110,
    sellPrice: 55,
  },
  {
    id: 'cloudwalk_manual',
    nameVi: 'Vân Du Giản',
    nameEn: 'Cloudwalk Manual',
    descVi: 'Nét chữ trôi như chân người viết chưa bao giờ chạm đất.',
    descEn: 'The handwriting drifts as if its author never touched ground.',
    aliases: ['cloudwalk', 'van du', 'cloudwalk manual'],
    usable: false,
    teachesTechniqueId: 'cloudwalk',
    requiredStage: 2,
    buyPrice: 210,
    sellPrice: 105,
  },
  {
    id: 'peak_cleaver_manual',
    nameVi: 'Phá Phong Đao Phổ',
    nameEn: 'Peak-Cleaving Manual',
    descVi: 'Bìa sách cháy sém, nhưng trang dạy cách chém vẫn còn nguyên.',
    descEn: 'The cover is scorched, but the page on striking remains intact.',
    aliases: ['peak cleaver', 'pha phong', 'peak manual'],
    usable: false,
    teachesTechniqueId: 'peak_cleaver',
    requiredStage: 3,
    buyPrice: 360,
    sellPrice: 180,
  },
  {
    id: 'dew_pill',
    nameVi: 'Ngọc lộ đan',
    nameEn: 'Dewdrop Pill',
    descVi: 'Viên đan nhỏ như giọt sương, ngậm miệng là mát cả họng.',
    descEn: 'A pill small as a dewdrop; hold it on the tongue and coolness spreads.',
    aliases: ['dew pill', 'ngoc lo dan', 'dew'],
    usable: true,
    effects: { hp: 15 },
    buyPrice: 25,
    sellPrice: 12,
  },
  {
    id: 'plum_qi_wine',
    nameVi: 'Mai hoa tửu',
    nameEn: 'Plum Qi Wine',
    descVi: 'Một ngụm chua ngọt, khí trong người ùa lên như hoa nở muộn.',
    descEn: 'One tart-sweet sip and your qi blooms late, like plum flowers.',
    aliases: ['wine', 'mai hoa tuu', 'plum wine'],
    usable: true,
    effects: { qi: 12 },
    buyPrice: 22,
    sellPrice: 10,
  },
  {
    id: 'ninefold_pill',
    nameVi: 'Cửu chuyển hồi nguyên đan',
    nameEn: 'Ninefold Restoration Pill',
    descVi: 'Chín vòng khói khi mở nắp hộp; uống xong xương cũng thấy nhẹ.',
    descEn: 'Nine rings of smoke when the box opens; afterward even bones feel light.',
    aliases: ['ninefold pill', 'cuu chuyen dan', 'grand healing pill'],
    usable: true,
    effects: { hp: 50 },
    requiredStage: 2,
    buyPrice: 95,
    sellPrice: 47,
  },
  {
    id: 'marrow_gather_pill',
    nameVi: 'Tụ linh cốt đan',
    nameEn: 'Marrow-Gathering Pill',
    descVi: 'Đắng tận cuống lưỡi, nhưng khí chạy xuống tủy xương mới chịu dừng.',
    descEn: 'Bitter to the root of the tongue; qi only rests once it reaches marrow.',
    aliases: ['marrow pill', 'tu linh cot dan', 'grand qi pill'],
    usable: true,
    effects: { qi: 40 },
    requiredStage: 2,
    buyPrice: 88,
    sellPrice: 44,
  },
  {
    id: 'trail_rations',
    nameVi: 'Lương khô hành tráng',
    nameEn: 'Trail Rations',
    descVi: 'Bánh nếp cứng đầu môi, nhưng no lâu và rất trung thành.',
    descEn: 'Sticky rice cakes that fight back at first bite, then keep you going for hours.',
    aliases: ['rations', 'luong kho', 'food'],
    usable: true,
    effects: { hp: 8 },
    buyPrice: 8,
    sellPrice: 3,
  },
  {
    id: 'moon_moss',
    nameVi: 'Rêu nguyệt',
    nameEn: 'Moonmoss',
    descVi: 'Rêu xanh lục chỉ sáng dưới trăng; dược sư trả giá không thương lượng.',
    descEn: 'Moss that glows only under moonlight; herbalists haggle over it endlessly.',
    aliases: ['moon moss', 'reau nguyet', 'moss'],
    usable: false,
    buyPrice: null,
    sellPrice: 18,
  },
  {
    id: 'cold_iron_ore',
    nameVi: 'Hàn thiết quặng',
    nameEn: 'Cold Iron Ore',
    descVi: 'Đá lạnh đến mức phải quấn vải mới ôm nổi về chợ.',
    descEn: 'So cold you must wrap it in cloth just to carry it to market.',
    aliases: ['iron ore', 'han thiet', 'ore'],
    usable: false,
    buyPrice: null,
    sellPrice: 26,
  },
  {
    id: 'beast_fang',
    nameVi: 'Nha thú',
    nameEn: 'Beast Fang',
    descVi: 'Chiếc răng còn sắc; treo lưng túi thì yêu thú nhỏ né đường.',
    descEn: 'Still sharp at the tip; hung from a satchel it makes lesser beasts detour.',
    aliases: ['fang', 'nha thu', 'tooth'],
    usable: false,
    buyPrice: null,
    sellPrice: 15,
  },
  {
    id: 'cloudsilk_thread',
    nameVi: 'Tơ vân',
    nameEn: 'Cloudsilk Thread',
    descVi: 'Sợi tơ mảnh hơn tóc mà kéo đứt tay cũng chưa chắc đứt.',
    descEn: 'Finer than hair; pull until your arm aches and it still holds.',
    aliases: ['cloudsilk', 'to van', 'silk'],
    usable: false,
    buyPrice: null,
    sellPrice: 22,
  },
  {
    id: 'crane_feather',
    nameVi: 'Vũ hạc',
    nameEn: 'Crane Feather',
    descVi: 'Lông trắng không bao giờ bám bụi; ai cũng bảo nó của tiên nhân.',
    descEn: 'A white plume dust can never settle on; everyone swears it fell from an immortal.',
    aliases: ['crane feather', 'vu hac', 'feather'],
    usable: false,
    buyPrice: null,
    sellPrice: 65,
  },
  {
    id: 'bamboo_saber',
    nameVi: 'Trúc đao thanh mộc',
    nameEn: 'Greenwood Bamboo Saber',
    descVi: 'Gỗ trúc già bọc thép mỏng; nhẹ hơn trượng, nặng hơn lời hứa.',
    descEn: 'Old bamboo bound with a thin steel edge; lighter than a staff, heavier than a promise.',
    aliases: ['bamboo saber', 'truc dao', 'bamboo'],
    usable: false,
    equipmentSlot: 'weapon',
    buyPrice: 45,
    sellPrice: 20,
  },
  {
    id: 'travelers_coat',
    nameVi: 'Hành lữ bào',
    nameEn: "Traveler's Coat",
    descVi: 'Áo dày vá kín cổ; gió núi đọc đi đọc lại vẫn không tìm được khe hở.',
    descEn: 'A thick coat sealed at the collar; mountain wind reads it twice and finds no gap.',
    aliases: ['traveler coat', 'hanh lu bao', 'coat'],
    usable: false,
    equipmentSlot: 'robe',
    buyPrice: 55,
    sellPrice: 26,
  },
  {
    id: 'bone_ward_charm',
    nameVi: 'Xương phù bội',
    nameEn: 'Bone Ward Charm',
    descVi: 'Khắc chữ hộ thân lên xương thú; hơi lạnh tỏa ra rất biết đúng lúc.',
    descEn: 'Ward-script carved into beast bone; its chill arrives exactly when needed.',
    aliases: ['bone charm', 'xuong phu', 'ward charm'],
    usable: false,
    equipmentSlot: 'accessory',
    buyPrice: 38,
    sellPrice: 17,
  },
  {
    id: 'frostfang_saber',
    nameVi: 'Hàn nha đao',
    nameEn: 'Frostfang Saber',
    descVi: 'Mũi đao lạnh như đêm đầu đông; vết cắt cũng im lặng hơn thường lệ.',
    descEn: 'Its edge is cold as the first night of winter; even its cuts are quieter than most.',
    aliases: ['frostfang saber', 'han nha dao', 'frostfang'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 2,
    buyPrice: 190,
    sellPrice: 92,
  },
  {
    id: 'cloudveil_robe',
    nameVi: 'Vân vi mạc',
    nameEn: 'Cloudveil Robe',
    descVi: 'Tròng áo lên thì sương tự xếp lớp; người khác nhìn ba lần mới thấy ngươi.',
    descEn: 'Wear it and mist arranges itself in layers; look three times before others find you.',
    aliases: ['cloudveil robe', 'van vi mac', 'cloudveil'],
    usable: false,
    equipmentSlot: 'robe',
    requiredStage: 2,
    buyPrice: 170,
    sellPrice: 82,
  },
  {
    id: 'moonstone_pendant',
    nameVi: 'Nguyệt quang bội',
    nameEn: 'Moonstone Pendant',
    descVi: 'Viên đá bắt ánh trăng giữ lại một phần cho chủ nhân.',
    descEn: 'The stone keeps a share of moonlight and lends it quietly to its owner.',
    aliases: ['moonstone pendant', 'nguyet quang boi', 'moonstone'],
    usable: false,
    equipmentSlot: 'accessory',
    requiredStage: 3,
    buyPrice: 260,
    sellPrice: 125,
  },
  {
    id: 'tide_breath_manual',
    nameVi: 'Triều tức quyển',
    nameEn: 'Tide-Breath Manual',
    descVi: 'Trang giấy gợn như mặt nước; đọc xong hơi thở có nhịp riêng.',
    descEn: 'Pages ripple like water; finish it and your breath finds its own tide.',
    aliases: ['tide breath', 'trieu tuc', 'tide manual'],
    usable: false,
    teachesTechniqueId: 'tide_breath',
    requiredStage: 2,
    buyPrice: 230,
    sellPrice: 110,
  },
  {
    id: 'stone_aegis_manual',
    nameVi: 'Thạch kính phổ',
    nameEn: 'Stone Aegis Manual',
    descVi: 'Bìa đá mỏng, chữ khắc sâu; dạy cách đứng vững như chưa từng sợ.',
    descEn: 'A thin stone cover with deep-cut script; it teaches standing as if fear were invented later.',
    aliases: ['stone aegis', 'thach kinh', 'aegis manual'],
    usable: false,
    teachesTechniqueId: 'stone_aegis',
    requiredStage: 3,
    buyPrice: 340,
    sellPrice: 165,
  },
  {
    id: 'evidence_route_mercy',
    nameVi: 'Cuộn điểm danh bảy nhà',
    nameEn: 'Roll call of seven homes',
    descVi: 'Mai Hoa đóng dấu son lên cuộn điểm danh. Đây không phải lời hứa nữa; đây là tên những người có thể đứng ra làm chứng.',
    descEn: 'Meihua presses vermilion onto the roll. This is no longer a promise; these are names that can testify.',
    aliases: ['roll call', 'evidence mercy', 'cuon diem danh'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'evidence_route_wealth',
    nameVi: 'Nửa phù khế của Bảo',
    nameEn: 'Bao’s half-contract ward',
    descVi: 'Bảo bẻ phù làm đôi, giữ một nửa và nhét nửa kia vào tay ngươi. Trên mặt phù có dấu hiệu của kẻ đã trả tiền theo dõi ngươi.',
    descEn: 'Bao snaps the ward in two, keeping one half and pushing the other into your palm. Its face bears the mark of whoever paid to watch you.',
    aliases: ['bao ward', 'evidence wealth', 'pha khe bao'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'evidence_route_truth',
    nameVi: 'Bản sao của cái tên thứ tám',
    nameEn: 'Copy of the eighth name',
    descVi: 'Ngô gấp bản sao thành một mảnh nhỏ vừa đủ để giấu trong tay áo. Nét mực hiện lại trên giấy.',
    descEn: 'Ngo folds the copy into a slip small enough for your sleeve. The ink returns to the page.',
    aliases: ['eighth name', 'evidence truth', 'ban sao ten thu tam'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
]

export function getItem(itemId: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === itemId)
}

export const SHOP_STOCK: string[] = ITEMS.filter((i) => i.buyPrice !== null).map((i) => i.id)
