import type { ItemDef } from '../engine/content-types'
import { ITEM_HERB, ITEM_MANUAL, ITEM_TALISMAN } from '../engine/constants'

export const ITEMS: ItemDef[] = [
  {
    id: ITEM_HERB,
    nameVi: 'Linh thảo',
    nameEn: 'Spirit Herb',
    descVi: 'Cỏ ba lá ngọc, nhai giòn tan, khí ấm lan ra.',
    descEn: 'A jade trefoil; chewy, with warmth spreading after.',
    aliases: ['herb', 'linh thao', 'thao'],
    usable: true,
    effects: { qi: 8 },
    buyPrice: null,
    sellPrice: 12,
  },
  {
    id: 'wooden_staff',
    nameVi: 'Mộc trượng cũ',
    nameEn: 'Old Wooden Staff',
    descVi: 'Cây trượng theo ngươi từ làng; nặng vừa đủ để tự tin hơn.',
    descEn: 'The village staff; just heavy enough to inspire confidence.',
    aliases: ['staff', 'moc truong', 'wooden staff'],
    usable: false,
    equipmentSlot: 'weapon',
    buyPrice: null,
    sellPrice: 3,
  },
  {
    id: 'tattered_robe',
    nameVi: 'Áo vải vá',
    nameEn: 'Patched Cloth Robe',
    descVi: 'Vết vá ngang dọc nhưng vẫn giữ được khí thế.',
    descEn: 'Patched in every direction, yet it retains a certain presence.',
    aliases: ['robe', 'ao vai', 'patched robe'],
    usable: false,
    equipmentSlot: 'robe',
    buyPrice: null,
    sellPrice: 2,
  },
  {
    id: 'pill_hp',
    nameVi: 'Viên hồi nguyên',
    nameEn: 'Restoration Pill',
    descVi: 'Ngọt hậu vị đắng, máu chạy như suối mùa xuân.',
    descEn: 'Sweet then bitter; blood runs like a spring stream.',
    aliases: ['hp pill', 'vien hoi nguyen', 'hoi nguyen', 'healing pill'],
    usable: true,
    effects: { hp: 25 },
    buyPrice: 35,
    sellPrice: 17,
  },
  {
    id: 'pill_qi',
    nameVi: 'Viên tụ khí',
    nameEn: 'Qi-Gathering Pill',
    descVi: 'Tan trên lưỡi như sương, dạ dày ấm áp khí.',
    descEn: 'Melts like dew on the tongue; the belly hums with qi.',
    aliases: ['qi pill', 'vien tu khi', 'tu khi', 'qi'],
    usable: true,
    effects: { qi: 20 },
    buyPrice: 30,
    sellPrice: 15,
  },
  {
    id: ITEM_TALISMAN,
    nameVi: 'Bùa trừ tà',
    nameEn: 'Warding Talisman',
    descVi: 'Nét chữ đỏ còn thơm mùi son, dán lên ngực là yên lòng.',
    descEn: 'Vermilion strokes still smelling of cinnabar; press it to your chest and breathe easy.',
    aliases: ['talisman', 'bua tru ta', 'bua', 'ward'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'jade_charm',
    nameVi: 'Ngọc bội',
    nameEn: 'Jade Charm',
    descVi: 'Lạnh tay, đẹp một cách không cần chứng minh.',
    descEn: 'Cool to the touch, beautiful without needing to prove anything.',
    aliases: ['jade', 'ngoc boi', 'charm', 'ngoc'],
    usable: false,
    equipmentSlot: 'accessory',
    buyPrice: 60,
    sellPrice: 45,
  },
  {
    id: ITEM_MANUAL,
    nameVi: 'Bí kíp cong queo',
    nameEn: 'The Crooked Manual',
    descVi: 'Bản chép tay lệch nét dành riêng cho linh căn khuyết tật.',
    descEn: 'A crooked-handwritten copy made for defective spirit roots.',
    aliases: ['manual', 'bi kip', 'sach'],
    usable: false,
    teachesTechniqueId: 'crooked_circulation',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'rift_step_scroll',
    nameVi: 'Ngọc giản Khe Bộ',
    nameEn: 'Rift Step Scroll',
    descVi: 'Ngọc giản run khẽ như muốn đi trước chân ngươi.',
    descEn: 'The jade slip trembles as if it wants to step before you do.',
    aliases: ['rift step', 'khe bo', 'rift scroll'],
    usable: false,
    teachesTechniqueId: 'rift_step',
    buyPrice: null,
    sellPrice: 55,
  },
  {
    id: 'ironwood_saber',
    nameVi: 'Thiết mộc đao',
    nameEn: 'Ironwood Saber',
    descVi: 'Đao gỗ đen nặng tay, đổi lại rất biết nói chuyện với giáp mỏng.',
    descEn: 'A heavy blackwood saber that speaks clearly to thin armor.',
    aliases: ['ironwood saber', 'thiet moc dao', 'saber'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 1,
    buyPrice: 90,
    sellPrice: 45,
  },
  {
    id: 'mistweave_vest',
    nameVi: 'Vân văn giáp y',
    nameEn: 'Mistweave Vest',
    descVi: 'Lớp áo nhẹ, đường chỉ mây ẩn đi ngay khi nhìn kỹ.',
    descEn: 'A light vest whose cloud-stitching vanishes when inspected.',
    aliases: ['mistweave vest', 'van van giap y', 'vest'],
    usable: false,
    equipmentSlot: 'robe',
    requiredStage: 1,
    buyPrice: 80,
    sellPrice: 40,
  },
  {
    id: 'spirit_ring',
    nameVi: 'Nhẫn tụ linh',
    nameEn: 'Spirit-Gathering Ring',
    descVi: 'Vòng bạc mờ, đeo lâu thì đầu ngón tay cũng ấm lên.',
    descEn: 'A dim silver ring that warms the fingertips over time.',
    aliases: ['spirit ring', 'nhan tu linh', 'ring'],
    usable: false,
    equipmentSlot: 'accessory',
    requiredStage: 2,
    buyPrice: 180,
    sellPrice: 90,
  },
  {
    id: 'cloudpiercer_spear',
    nameVi: 'Xuyên vân thương',
    nameEn: 'Cloudpiercer Spear',
    descVi: 'Cán thương sáng, dài và rất không hợp để cất trong túi.',
    descEn: 'A bright long spear, thoroughly unsuitable for a small bag.',
    aliases: ['cloudpiercer spear', 'xuyen van thuong', 'spear'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 3,
    buyPrice: 280,
    sellPrice: 140,
  },
  {
    id: 'herbal_breath_manual',
    nameVi: 'Dược Hơi Quyển',
    nameEn: 'Herbal Breath Manual',
    descVi: 'Mỗi trang còn vương mùi hương thảo vừa phơi nắng.',
    descEn: 'Every page still carries the scent of sun-dried herbs.',
    aliases: ['herbal breath', 'duoc hoi', 'herbal manual'],
    usable: false,
    teachesTechniqueId: 'herbal_breath',
    requiredStage: 1,
    buyPrice: 120,
    sellPrice: 60,
  },
  {
    id: 'iron_skin_manual',
    nameVi: 'Thiết Bì Quyển',
    nameEn: 'Iron Skin Manual',
    descVi: 'Lời mở đầu bảo ngươi đừng thử nó bằng đầu.',
    descEn: 'Its first line asks you not to test it with your head.',
    aliases: ['iron skin', 'thiet bi', 'iron skin manual'],
    usable: false,
    teachesTechniqueId: 'iron_skin',
    requiredStage: 1,
    buyPrice: 110,
    sellPrice: 55,
  },
  {
    id: 'cloudwalk_manual',
    nameVi: 'Vân Du Giản',
    nameEn: 'Cloudwalk Manual',
    descVi: 'Nét chữ trôi như chân người viết chưa bao giờ chạm đất.',
    descEn: 'The handwriting drifts as if its author never touched ground.',
    aliases: ['cloudwalk', 'van du', 'cloudwalk manual'],
    usable: false,
    teachesTechniqueId: 'cloudwalk',
    requiredStage: 2,
    buyPrice: 210,
    sellPrice: 105,
  },
  {
    id: 'peak_cleaver_manual',
    nameVi: 'Phá Phong Đao Phổ',
    nameEn: 'Peak-Cleaving Manual',
    descVi: 'Bìa sách cháy sém, nhưng trang dạy cách chém vẫn còn nguyên.',
    descEn: 'The cover is scorched, but the page on striking remains intact.',
    aliases: ['peak cleaver', 'pha phong', 'peak manual'],
    usable: false,
    teachesTechniqueId: 'peak_cleaver',
    requiredStage: 3,
    buyPrice: 360,
    sellPrice: 180,
  },
]

export function getItem(itemId: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === itemId)
}

export const SHOP_STOCK: string[] = ITEMS.filter((i) => i.buyPrice !== null).map((i) => i.id)
