import type { ItemDef } from '../engine/content-types'
import { ITEM_HERB, ITEM_MANUAL, ITEM_TALISMAN } from '../engine/constants'

export const ITEMS: ItemDef[] = [
  {
    id: ITEM_HERB,
    nameVi: 'Linh thảo',
    nameEn: 'Spirit Herb',
    descVi: 'Cỏ ba lá ngọc, nhai giòn tan, khí ấm lan ra.',
    descEn: 'A jade trefoil; chewy, with warmth spreading after.',
    aliases: ['herb', 'linh thao', 'thao'],
    usable: true,
    effects: { qi: 8 },
    buyPrice: null,
    sellPrice: 12,
  },
  {
    id: 'wooden_staff',
    nameVi: 'Mộc trượng cũ',
    nameEn: 'Old Wooden Staff',
    descVi: 'Cây trượng theo ngươi từ làng; nặng vừa đủ để tự tin hơn.',
    descEn: 'The village staff; just heavy enough to inspire confidence.',
    aliases: ['staff', 'moc truong', 'wooden staff'],
    usable: false,
    equipmentSlot: 'weapon',
    buyPrice: null,
    sellPrice: 3,
  },
  {
    id: 'tattered_robe',
    nameVi: 'Áo vải vá',
    nameEn: 'Patched Cloth Robe',
    descVi: 'Vết vá ngang dọc nhưng vẫn giữ được khí thế.',
    descEn: 'Patched in every direction, yet it retains a certain presence.',
    aliases: ['robe', 'ao vai', 'patched robe'],
    usable: false,
    equipmentSlot: 'robe',
    buyPrice: null,
    sellPrice: 2,
  },
  {
    id: 'pill_hp',
    nameVi: 'Viên hồi nguyên',
    nameEn: 'Restoration Pill',
    descVi: 'Ngọt hậu vị đắng, máu chạy như suối mùa xuân.',
    descEn: 'Sweet then bitter; blood runs like a spring stream.',
    aliases: ['hp pill', 'vien hoi nguyen', 'hoi nguyen', 'healing pill'],
    usable: true,
    effects: { hp: 25 },
    buyPrice: 35,
    sellPrice: 17,
  },
  {
    id: 'pill_qi',
    nameVi: 'Viên tụ khí',
    nameEn: 'Qi-Gathering Pill',
    descVi: 'Tan trên lưỡi như sương, dạ dày ấm áp khí.',
    descEn: 'Melts like dew on the tongue; the belly hums with qi.',
    aliases: ['qi pill', 'vien tu khi', 'tu khi', 'qi'],
    usable: true,
    effects: { qi: 20 },
    buyPrice: 30,
    sellPrice: 15,
  },
  {
    id: ITEM_TALISMAN,
    nameVi: 'Bùa trừ tà',
    nameEn: 'Warding Talisman',
    descVi: 'Nét chữ đỏ còn thơm mùi son, dán lên ngực là yên lòng.',
    descEn: 'Vermilion strokes still smelling of cinnabar; press it to your chest and breathe easy.',
    aliases: ['talisman', 'bua tru ta', 'bua', 'ward'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'jade_charm',
    nameVi: 'Ngọc bội',
    nameEn: 'Jade Charm',
    descVi: 'Lạnh tay, đẹp một cách không cần chứng minh.',
    descEn: 'Cool to the touch, beautiful without needing to prove anything.',
    aliases: ['jade', 'ngoc boi', 'charm', 'ngoc'],
    usable: false,
    equipmentSlot: 'accessory',
    buyPrice: 60,
    sellPrice: 45,
  },
  {
    id: ITEM_MANUAL,
    nameVi: 'Bí kíp cong queo',
    nameEn: 'The Crooked Manual',
    descVi: 'Bản chép tay lệch nét dành riêng cho linh căn khuyết tật.',
    descEn: 'A crooked-handwritten copy made for defective spirit roots.',
    aliases: ['manual', 'bi kip', 'sach'],
    usable: false,
    teachesTechniqueId: 'crooked_circulation',
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'rift_step_scroll',
    nameVi: 'Ngọc giản Khe Bộ',
    nameEn: 'Rift Step Scroll',
    descVi: 'Ngọc giản run khẽ như muốn đi trước chân ngươi.',
    descEn: 'The jade slip trembles as if it wants to step before you do.',
    aliases: ['rift step', 'khe bo', 'rift scroll'],
    usable: false,
    teachesTechniqueId: 'rift_step',
    buyPrice: null,
    sellPrice: 55,
  },
  {
    id: 'ironwood_saber',
    nameVi: 'Thiết mộc đao',
    nameEn: 'Ironwood Saber',
    descVi: 'Đao gỗ đen nặng tay, đổi lại rất biết nói chuyện với giáp mỏng.',
    descEn: 'A heavy blackwood saber that speaks clearly to thin armor.',
    aliases: ['ironwood saber', 'thiet moc dao', 'saber'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 1,
    buyPrice: 90,
    sellPrice: 45,
  },
  {
    id: 'mistweave_vest',
    nameVi: 'Vân văn giáp y',
    nameEn: 'Mistweave Vest',
    descVi: 'Lớp áo nhẹ, đường chỉ mây ẩn đi ngay khi nhìn kỹ.',
    descEn: 'A light vest whose cloud-stitching vanishes when inspected.',
    aliases: ['mistweave vest', 'van van giap y', 'vest'],
    usable: false,
    equipmentSlot: 'robe',
    requiredStage: 1,
    buyPrice: 80,
    sellPrice: 40,
  },
  {
    id: 'spirit_ring',
    nameVi: 'Nhẫn tụ linh',
    nameEn: 'Spirit-Gathering Ring',
    descVi: 'Vòng bạc mờ, đeo lâu thì đầu ngón tay cũng ấm lên.',
    descEn: 'A dim silver ring that warms the fingertips over time.',
    aliases: ['spirit ring', 'nhan tu linh', 'ring'],
    usable: false,
    equipmentSlot: 'accessory',
    requiredStage: 2,
    buyPrice: 180,
    sellPrice: 90,
  },
  {
    id: 'cloudpiercer_spear',
    nameVi: 'Xuyên vân thương',
    nameEn: 'Cloudpiercer Spear',
    descVi: 'Cán thương sáng, dài và rất không hợp để cất trong túi.',
    descEn: 'A bright long spear, thoroughly unsuitable for a small bag.',
    aliases: ['cloudpiercer spear', 'xuyen van thuong', 'spear'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 3,
    buyPrice: 280,
    sellPrice: 140,
  },
  {
    id: 'herbal_breath_manual',
    nameVi: 'Dược Hơi Quyển',
    nameEn: 'Herbal Breath Manual',
    descVi: 'Mỗi trang còn vương mùi hương thảo vừa phơi nắng.',
    descEn: 'Every page still carries the scent of sun-dried herbs.',
    aliases: ['herbal breath', 'duoc hoi', 'herbal manual'],
    usable: false,
    teachesTechniqueId: 'herbal_breath',
    requiredStage: 1,
    buyPrice: 120,
    sellPrice: 60,
  },
  {
    id: 'iron_skin_manual',
    nameVi: 'Thiết Bì Quyển',
    nameEn: 'Iron Skin Manual',
    descVi: 'Lời mở đầu bảo ngươi đừng thử nó bằng đầu.',
    descEn: 'Its first line asks you not to test it with your head.',
    aliases: ['iron skin', 'thiet bi', 'iron skin manual'],
    usable: false,
    teachesTechniqueId: 'iron_skin',
    requiredStage: 1,
    buyPrice: 110,
    sellPrice: 55,
  },
  {
    id: 'cloudwalk_manual',
    nameVi: 'Vân Du Giản',
    nameEn: 'Cloudwalk Manual',
    descVi: 'Nét chữ trôi như chân người viết chưa bao giờ chạm đất.',
    descEn: 'The handwriting drifts as if its author never touched ground.',
    aliases: ['cloudwalk', 'van du', 'cloudwalk manual'],
    usable: false,
    teachesTechniqueId: 'cloudwalk',
    requiredStage: 2,
    buyPrice: 210,
    sellPrice: 105,
  },
  {
    id: 'peak_cleaver_manual',
    nameVi: 'Phá Phong Đao Phổ',
    nameEn: 'Peak-Cleaving Manual',
    descVi: 'Bìa sách cháy sém, nhưng trang dạy cách chém vẫn còn nguyên.',
    descEn: 'The cover is scorched, but the page on striking remains intact.',
    aliases: ['peak cleaver', 'pha phong', 'peak manual'],
    usable: false,
    teachesTechniqueId: 'peak_cleaver',
    requiredStage: 3,
    buyPrice: 360,
    sellPrice: 180,
  },
  {
    id: 'dew_pill',
    nameVi: 'Ngọc lộ đan',
    nameEn: 'Dewdrop Pill',
    descVi: 'Viên đan nhỏ như giọt sương, ngậm miệng là mát cả họng.',
    descEn: 'A pill small as a dewdrop; hold it on the tongue and coolness spreads.',
    aliases: ['dew pill', 'ngoc lo dan', 'dew'],
    usable: true,
    effects: { hp: 15 },
    buyPrice: 25,
    sellPrice: 12,
  },
  {
    id: 'plum_qi_wine',
    nameVi: 'Mai hoa tửu',
    nameEn: 'Plum Qi Wine',
    descVi: 'Một ngụm chua ngọt, khí trong người ùa lên như hoa nở muộn.',
    descEn: 'One tart-sweet sip and your qi blooms late, like plum flowers.',
    aliases: ['wine', 'mai hoa tuu', 'plum wine'],
    usable: true,
    effects: { qi: 12 },
    buyPrice: 22,
    sellPrice: 10,
  },
  {
    id: 'ninefold_pill',
    nameVi: 'Cửu chuyển hồi nguyên đan',
    nameEn: 'Ninefold Restoration Pill',
    descVi: 'Chín vòng khói khi mở nắp hộp; uống xong xương cũng thấy nhẹ.',
    descEn: 'Nine rings of smoke when the box opens; afterward even bones feel light.',
    aliases: ['ninefold pill', 'cuu chuyen dan', 'grand healing pill'],
    usable: true,
    effects: { hp: 50 },
    requiredStage: 2,
    buyPrice: 95,
    sellPrice: 47,
  },
  {
    id: 'marrow_gather_pill',
    nameVi: 'Tụ linh cốt đan',
    nameEn: 'Marrow-Gathering Pill',
    descVi: 'Đắng tận cuống lưỡi, nhưng khí chạy xuống tủy xương mới chịu dừng.',
    descEn: 'Bitter to the root of the tongue; qi only rests once it reaches marrow.',
    aliases: ['marrow pill', 'tu linh cot dan', 'grand qi pill'],
    usable: true,
    effects: { qi: 40 },
    requiredStage: 2,
    buyPrice: 88,
    sellPrice: 44,
  },
  {
    id: 'trail_rations',
    nameVi: 'Lương khô hành tráng',
    nameEn: 'Trail Rations',
    descVi: 'Bánh nếp cứng đầu môi, nhưng no lâu và rất trung thành.',
    descEn: 'Sticky rice cakes that fight back at first bite, then keep you going for hours.',
    aliases: ['rations', 'luong kho', 'food'],
    usable: true,
    effects: { hp: 8 },
    buyPrice: 8,
    sellPrice: 3,
  },
  {
    id: 'moon_moss',
    nameVi: 'Rêu nguyệt',
    nameEn: 'Moonmoss',
    descVi: 'Rêu xanh lục chỉ sáng dưới trăng; dược sư trả giá không thương lượng.',
    descEn: 'Moss that glows only under moonlight; herbalists haggle over it endlessly.',
    aliases: ['moon moss', 'reau nguyet', 'moss'],
    usable: false,
    buyPrice: null,
    sellPrice: 18,
  },
  {
    id: 'cold_iron_ore',
    nameVi: 'Hàn thiết quặng',
    nameEn: 'Cold Iron Ore',
    descVi: 'Đá lạnh đến mức phải quấn vải mới ôm nổi về chợ.',
    descEn: 'So cold you must wrap it in cloth just to carry it to market.',
    aliases: ['iron ore', 'han thiet', 'ore'],
    usable: false,
    buyPrice: null,
    sellPrice: 26,
  },
  {
    id: 'beast_fang',
    nameVi: 'Nha thú',
    nameEn: 'Beast Fang',
    descVi: 'Chiếc răng còn sắc; treo lưng túi thì yêu thú nhỏ né đường.',
    descEn: 'Still sharp at the tip; hung from a satchel it makes lesser beasts detour.',
    aliases: ['fang', 'nha thu', 'tooth'],
    usable: false,
    buyPrice: null,
    sellPrice: 15,
  },
  {
    id: 'cloudsilk_thread',
    nameVi: 'Tơ vân',
    nameEn: 'Cloudsilk Thread',
    descVi: 'Sợi tơ mảnh hơn tóc mà kéo đứt tay cũng chưa chắc đứt.',
    descEn: 'Finer than hair; pull until your arm aches and it still holds.',
    aliases: ['cloudsilk', 'to van', 'silk'],
    usable: false,
    buyPrice: null,
    sellPrice: 22,
  },
  {
    id: 'crane_feather',
    nameVi: 'Vũ hạc',
    nameEn: 'Crane Feather',
    descVi: 'Lông trắng không bao giờ bám bụi; ai cũng bảo nó của tiên nhân.',
    descEn: 'A white plume dust can never settle on; everyone swears it fell from an immortal.',
    aliases: ['crane feather', 'vu hac', 'feather'],
    usable: false,
    buyPrice: null,
    sellPrice: 65,
  },
  {
    id: 'bamboo_saber',
    nameVi: 'Trúc đao thanh mộc',
    nameEn: 'Greenwood Bamboo Saber',
    descVi: 'Gỗ trúc già bọc thép mỏng; nhẹ hơn trượng, nặng hơn lời hứa.',
    descEn: 'Old bamboo bound with a thin steel edge; lighter than a staff, heavier than a promise.',
    aliases: ['bamboo saber', 'truc dao', 'bamboo'],
    usable: false,
    equipmentSlot: 'weapon',
    buyPrice: 45,
    sellPrice: 20,
  },
  {
    id: 'travelers_coat',
    nameVi: 'Hành lữ bào',
    nameEn: "Traveler's Coat",
    descVi: 'Áo dày vá kín cổ; gió núi đọc đi đọc lại vẫn không tìm được khe hở.',
    descEn: 'A thick coat sealed at the collar; mountain wind reads it twice and finds no gap.',
    aliases: ['traveler coat', 'hanh lu bao', 'coat'],
    usable: false,
    equipmentSlot: 'robe',
    buyPrice: 55,
    sellPrice: 26,
  },
  {
    id: 'bone_ward_charm',
    nameVi: 'Xương phù bội',
    nameEn: 'Bone Ward Charm',
    descVi: 'Khắc chữ hộ thân lên xương thú; hơi lạnh tỏa ra rất biết đúng lúc.',
    descEn: 'Ward-script carved into beast bone; its chill arrives exactly when needed.',
    aliases: ['bone charm', 'xuong phu', 'ward charm'],
    usable: false,
    equipmentSlot: 'accessory',
    buyPrice: 38,
    sellPrice: 17,
  },
  {
    id: 'frostfang_saber',
    nameVi: 'Hàn nha đao',
    nameEn: 'Frostfang Saber',
    descVi: 'Mũi đao lạnh như đêm đầu đông; vết cắt cũng im lặng hơn thường lệ.',
    descEn: 'Its edge is cold as the first night of winter; even its cuts are quieter than most.',
    aliases: ['frostfang saber', 'han nha dao', 'frostfang'],
    usable: false,
    equipmentSlot: 'weapon',
    requiredStage: 2,
    buyPrice: 190,
    sellPrice: 92,
  },
  {
    id: 'cloudveil_robe',
    nameVi: 'Vân vi mạc',
    nameEn: 'Cloudveil Robe',
    descVi: 'Tròng áo lên thì sương tự xếp lớp; người khác nhìn ba lần mới thấy ngươi.',
    descEn: 'Wear it and mist arranges itself in layers; look three times before others find you.',
    aliases: ['cloudveil robe', 'van vi mac', 'cloudveil'],
    usable: false,
    equipmentSlot: 'robe',
    requiredStage: 2,
    buyPrice: 170,
    sellPrice: 82,
  },
  {
    id: 'moonstone_pendant',
    nameVi: 'Nguyệt quang bội',
    nameEn: 'Moonstone Pendant',
    descVi: 'Viên đá bắt ánh trăng giữ lại một phần cho chủ nhân.',
    descEn: 'The stone keeps a share of moonlight and lends it quietly to its owner.',
    aliases: ['moonstone pendant', 'nguyet quang boi', 'moonstone'],
    usable: false,
    equipmentSlot: 'accessory',
    requiredStage: 3,
    buyPrice: 260,
    sellPrice: 125,
  },
  {
    id: 'tide_breath_manual',
    nameVi: 'Triều tức quyển',
    nameEn: 'Tide-Breath Manual',
    descVi: 'Trang giấy gợn như mặt nước; đọc xong hơi thở có nhịp riêng.',
    descEn: 'Pages ripple like water; finish it and your breath finds its own tide.',
    aliases: ['tide breath', 'trieu tuc', 'tide manual'],
    usable: false,
    teachesTechniqueId: 'tide_breath',
    requiredStage: 2,
    buyPrice: 230,
    sellPrice: 110,
  },
  {
    id: 'stone_aegis_manual',
    nameVi: 'Thạch kính phổ',
    nameEn: 'Stone Aegis Manual',
    descVi: 'Bìa đá mỏng, chữ khắc sâu; dạy cách đứng vững như chưa từng sợ.',
    descEn: 'A thin stone cover with deep-cut script; it teaches standing as if fear were invented later.',
    aliases: ['stone aegis', 'thach kinh', 'aegis manual'],
    usable: false,
    teachesTechniqueId: 'stone_aegis',
    requiredStage: 3,
    buyPrice: 340,
    sellPrice: 165,
  },
  {
    id: 'evidence_route_mercy',
    nameVi: 'Cuộn điểm danh bảy nhà',
    nameEn: 'Roll call of seven homes',
    descVi: 'Mai Hoa đóng dấu son lên cuộn điểm danh. Đây không phải lời hứa nữa; đây là tên những người có thể đứng ra làm chứng.',
    descEn: 'Meihua presses vermilion onto the roll. This is no longer a promise; these are names that can testify.',
    aliases: ['roll call', 'evidence mercy', 'cuon diem danh'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'evidence_route_wealth',
    nameVi: 'Nửa phù khế của Bảo',
    nameEn: 'Bao’s half-contract ward',
    descVi: 'Bảo bẻ phù làm đôi, giữ một nửa và nhét nửa kia vào tay ngươi. Trên mặt phù có dấu hiệu của kẻ đã trả tiền theo dõi ngươi.',
    descEn: 'Bao snaps the ward in two, keeping one half and pushing the other into your palm. Its face bears the mark of whoever paid to watch you.',
    aliases: ['bao ward', 'evidence wealth', 'pha khe bao'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'evidence_route_truth',
    nameVi: 'Bản sao của cái tên thứ tám',
    nameEn: 'Copy of the eighth name',
    descVi: 'Ngô gấp bản sao thành một mảnh nhỏ vừa đủ để giấu trong tay áo. Nét mực hiện lại trên giấy.',
    descEn: 'Ngo folds the copy into a slip small enough for your sleeve. The ink returns to the page.',
    aliases: ['eighth name', 'evidence truth', 'ban sao ten thu tam'],
    usable: false,
    illustrated: false,
    buyPrice: null,
    sellPrice: null,
  },
  /* --- T07 (expansion-x20): 43 item mới — linh thảo, đan lai, tiền tệ, mồi, đan Linh Thạch --- */
  /* 12 linh thảo Vạn Thảo Cốc — mỗi loại một mùa (xuân 20, hạ 45, thu 60, đông 80) */
  {
    id: 'herb_hong_silk',
    nameVi: 'Hồng tơ thảo',
    nameEn: 'Red Silk Herb',
    descVi: 'Sợi tơ đỏ phủ ven suối từ đầu xuân, ngắt phải đúng lúc sương còn đọng.',
    descEn: 'Red silk threads blanket the streamsides from early spring; cut them while the dew still clings.',
    aliases: ['hong silk', 'red silk herb', 'hong to thao'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'herb_ice_heart',
    nameVi: 'Băng tâm thảo',
    nameEn: 'Ice-Heart Herb',
    descVi: 'Lòng lá trong như băng, chỉ đơm hoa giữa những ngày giá rét mùa đông.',
    descEn: 'Its core is clear as ice; it flowers only in the deepest cold of winter.',
    aliases: ['ice heart', 'ice heart herb', 'bang tam'],
    usable: false,
    buyPrice: 80,
    sellPrice: 40,
  },
  {
    id: 'herb_blood_ginseng',
    nameVi: 'Huyết sâm',
    nameEn: 'Blood Ginseng',
    descVi: 'Rễ đỏ sẫm như máu, thu hoạch vào mùa thu sau ba năm chờ đợi.',
    descEn: 'A dark-red root harvested in autumn after three years of waiting.',
    aliases: ['blood ginseng', 'huyet sam', 'ginseng'],
    usable: false,
    buyPrice: 60,
    sellPrice: 30,
  },
  {
    id: 'herb_cloud_dew',
    nameVi: 'Vân lộ hoa',
    nameEn: 'Cloud-Dew Blossom',
    descVi: 'Hạt sương đậu trên cánh hoa mỗi sớm xuân, tan mất nếu trễ tay một khắc.',
    descEn: 'Dew beads gather on its petals each spring morning and vanish if you linger.',
    aliases: ['cloud dew', 'van lo', 'dew blossom'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'herb_moon_shard',
    nameVi: 'Nguyệt phách thảo',
    nameEn: 'Moon-Shard Herb',
    descVi: 'Lá bạc lấp lánh dưới trăng thu, sáng nhất sau nửa đêm.',
    descEn: 'Silver leaves gleam under the autumn moon, brightest past midnight.',
    aliases: ['moon shard', 'nguyet phach', 'moon herb'],
    usable: false,
    buyPrice: 60,
    sellPrice: 30,
  },
  {
    id: 'herb_fire_lotus',
    nameVi: 'Hỏa liên',
    nameEn: 'Fire Lotus',
    descVi: 'Cánh hoa ấm như than hồng, nở rộ giữa những ngày hè nắng gắt.',
    descEn: 'Petals warm as embers; it blooms through the harshest summer days.',
    aliases: ['fire lotus', 'hoa lien', 'hoi lien'],
    usable: false,
    buyPrice: 45,
    sellPrice: 22,
  },
  {
    id: 'herb_white_banner',
    nameVi: 'Bạch phan chi',
    nameEn: 'White-Banner Ganoderma',
    descVi: 'Nấm mọc như cờ trắng giữa chiều hè, gió lùa qua mới thấy.',
    descEn: 'A fungus rising like a white banner on summer afternoons, visible only when wind moves it.',
    aliases: ['white banner', 'bach phan chi', 'banner fungus'],
    usable: false,
    buyPrice: 45,
    sellPrice: 22,
  },
  {
    id: 'herb_green_vine',
    nameVi: 'Thanh đằng',
    nameEn: 'Green Vine',
    descVi: 'Dây leo xanh mướt bò đầy vách đá từ giữa xuân đến hết mùa.',
    descEn: 'A lush green vine climbing the cliffs from mid-spring to the end of the season.',
    aliases: ['green vine', 'thanh dang', 'vine'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'herb_purple_daisy',
    nameVi: 'Tử cúc',
    nameEn: 'Purple Daisy',
    descVi: 'Cúc tím khoe sắc ven đường lúc thu về, hoàng hôn ngả vàng thì khép cánh.',
    descEn: 'Purple daisies line the paths when autumn arrives, closing their petals at golden dusk.',
    aliases: ['purple daisy', 'tu cuc', 'daisy'],
    usable: false,
    buyPrice: 60,
    sellPrice: 30,
  },
  {
    id: 'herb_earth_marrow',
    nameVi: 'Địa tủy chi',
    nameEn: 'Earth-Marrow Ganoderma',
    descVi: 'Củ chôn sâu dưới đất đá, chỉ đào được khi đất đông cứng giữa mùa đông.',
    descEn: 'A root buried deep in stone, best dug when the winter ground freezes hard.',
    aliases: ['earth marrow', 'dia tui chi', 'dia tuy'],
    usable: false,
    buyPrice: 80,
    sellPrice: 40,
  },
  {
    id: 'herb_wind_bamboo',
    nameVi: 'Phong trúc',
    nameEn: 'Wind Bamboo',
    descVi: 'Tre nhỏ kêu lách tách trong gió xuân, mọc thành từng cụm ven khe núi.',
    descEn: 'A small bamboo rattling in the spring wind, growing in clusters along the ravines.',
    aliases: ['wind bamboo', 'phong truc', 'bamboo'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'herb_void_bamboo',
    nameVi: 'Hư không trúc',
    nameEn: 'Void Bamboo',
    descVi: 'Tre rỗng cả ruột tới tận ngọn, cắm rễ bền bỉ trong tuyết mùa đông.',
    descEn: 'A bamboo hollow to the tip, rooting patiently through the winter snow.',
    aliases: ['void bamboo', 'hu khong truc', 'hollow bamboo'],
    usable: false,
    buyPrice: 80,
    sellPrice: 40,
  },
  /* 12 đan lai — sản phẩm của 12 công thức luyện đan ở Vạn Thảo Cốc (hiệu ứng 20–60) */
  {
    id: 'pill_hybrid_silk_heart',
    nameVi: 'Tơ băng hoàn',
    nameEn: 'Silk-Heart Pill',
    descVi: 'Tơ đỏ xuân ôm lấy băng tâm; viên đan lạnh ngoài, ấm trong.',
    descEn: 'Spring silk wrapped around an ice heart; cold outside, warm within.',
    aliases: ['silk heart pill', 'to bang hoan', 'hybrid silk heart'],
    usable: true,
    effects: { qi: 30 },
    buyPrice: null,
    sellPrice: 15,
  },
  {
    id: 'pill_hybrid_blood_dew',
    nameVi: 'Huyết lộ đan',
    nameEn: 'Blood-Dew Pill',
    descVi: 'Huyết sâm nhúng sương vân, vị đắng gắt lột sạch, còn lại là sức sống.',
    descEn: 'Blood ginseng dipped in cloud dew; the harsh bite is gone, only vigor remains.',
    aliases: ['blood dew pill', 'huyet lo dan', 'hybrid blood dew'],
    usable: true,
    effects: { hp: 40 },
    buyPrice: null,
    sellPrice: 20,
  },
  {
    id: 'pill_hybrid_moon_fire',
    nameVi: 'Nguyệt hỏa đan',
    nameEn: 'Moon-Fire Pill',
    descVi: 'Lửa hạ được trăng thu níu lại; nuốt vào, khí nóng thành vòng xoay đều.',
    descEn: 'Summer fire reined in by autumn moonlight; swallow it and the heat turns into a steady wheel.',
    aliases: ['moon fire pill', 'nguyet hoa dan', 'hybrid moon fire'],
    usable: true,
    effects: { qi: 45 },
    buyPrice: null,
    sellPrice: 22,
  },
  {
    id: 'pill_hybrid_banner_daisy',
    nameVi: 'Phan cúc hoàn',
    nameEn: 'Banner-Daisy Pill',
    descVi: 'Hai mùa gặp nhau trong một viên hoàn nhỏ, máu chạy êm như dòng không sóng.',
    descEn: 'Two seasons meet in one small pill; the blood runs calm as a waveless stream.',
    aliases: ['banner daisy pill', 'phan cuc hoan', 'hybrid banner daisy'],
    usable: true,
    effects: { hp: 30 },
    buyPrice: null,
    sellPrice: 15,
  },
  {
    id: 'pill_hybrid_marrow_bamboo',
    nameVi: 'Tủy trúc đan',
    nameEn: 'Marrow-Bamboo Pill',
    descVi: 'Địa tủy đông cứng chảy qua ruột trúc rỗng; tu xong một đêm, xương nhẹ hẳn.',
    descEn: 'Frozen earth marrow poured through hollow bamboo; one night of training and the bones feel lighter.',
    aliases: ['marrow bamboo pill', 'tui truc dan', 'hybrid marrow bamboo'],
    usable: true,
    effects: { qi: 55 },
    buyPrice: null,
    sellPrice: 27,
  },
  {
    id: 'pill_hybrid_cloud_lotus',
    nameVi: 'Vân liên đan',
    nameEn: 'Cloud-Lotus Pill',
    descVi: 'Sương xuân đọng trên cánh liên; viên đan nhẹ như chưa từng có trọng lượng.',
    descEn: 'Spring dew settled on a lotus petal; the pill weighs no more than breath.',
    aliases: ['cloud lotus pill', 'van lien dan', 'hybrid cloud lotus'],
    usable: true,
    effects: { qi: 35 },
    buyPrice: null,
    sellPrice: 17,
  },
  {
    id: 'pill_hybrid_ice_ginseng',
    nameVi: 'Băng sâm hoàn',
    nameEn: 'Ice-Ginseng Pill',
    descVi: 'Băng tâm giữ nguyên hơi lạnh, huyết sâm phải đợi đông mới chịu tan.',
    descEn: 'The ice heart keeps its chill; blood ginseng only agrees to melt in winter.',
    aliases: ['ice ginseng pill', 'bang sam hoan', 'hybrid ice ginseng'],
    usable: true,
    effects: { hp: 50 },
    buyPrice: null,
    sellPrice: 25,
  },
  {
    id: 'pill_hybrid_dew_daisy',
    nameVi: 'Lộ cúc hoàn',
    nameEn: 'Dew-Daisy Pill',
    descVi: 'Lộ sớm xuân nhỏ lên cúc tím muộn mùa; dịu với cả người mới tu.',
    descEn: 'Early spring dew on a late-season daisy; gentle enough for new cultivators.',
    aliases: ['dew daisy pill', 'lo cuc hoan', 'hybrid dew daisy'],
    usable: true,
    effects: { hp: 20 },
    buyPrice: null,
    sellPrice: 12,
  },
  {
    id: 'pill_hybrid_earth_fire',
    nameVi: 'Địa hỏa đan',
    nameEn: 'Earth-Fire Pill',
    descVi: 'Đất đông mà lửa không chịu đông; viên đan đến xuân vẫn còn ấm.',
    descEn: 'The ground freezes but the fire refuses to; the pill stays warm until spring.',
    aliases: ['earth fire pill', 'dia hoa dan', 'hybrid earth fire'],
    usable: true,
    effects: { qi: 60 },
    buyPrice: null,
    sellPrice: 30,
  },
  {
    id: 'pill_hybrid_silk_dew',
    nameVi: 'Tơ lộ hoàn',
    nameEn: 'Silk-Dew Pill',
    descVi: 'Tơ hồng quấn dây đằng đẫm sương; tức khí chạy mềm như nước.',
    descEn: 'Red silk wound around dew-heavy vine; qi runs soft as water.',
    aliases: ['silk dew pill', 'to lo hoan', 'hybrid silk dew'],
    usable: true,
    effects: { qi: 20 },
    buyPrice: null,
    sellPrice: 12,
  },
  {
    id: 'pill_hybrid_moon_marrow',
    nameVi: 'Nguyệt tủy đan',
    nameEn: 'Moon-Marrow Pill',
    descVi: 'Trăng thu rót xuống địa tủy; ai uống xong thường mơ thấy cả một đời.',
    descEn: 'The autumn moon pours into earth marrow; those who take it dream of whole lifetimes.',
    aliases: ['moon marrow pill', 'nguyet tui dan', 'hybrid moon marrow'],
    usable: true,
    effects: { hp: 60 },
    buyPrice: null,
    sellPrice: 30,
  },
  {
    id: 'pill_hybrid_wind_heart',
    nameVi: 'Phong tâm hoàn',
    nameEn: 'Wind-Heart Pill',
    descVi: 'Gió xuân thổi qua tre mà trong bụng trúc còn một mảnh băng; lắc khe khẽ kêu.',
    descEn: 'Spring wind passes through bamboo, yet a shard of ice remains; it rattles softly when shaken.',
    aliases: ['wind heart pill', 'phong tam hoan', 'hybrid wind heart'],
    usable: true,
    effects: { qi: 40 },
    buyPrice: null,
    sellPrice: 20,
  },
  /* 3 đơn vị tiền — item trưng bày; số dư thật nằm ở state.player.silver / spiritStones (T02) */
  {
    id: 'silver_coin',
    nameVi: 'Bát bạc',
    nameEn: 'Silver Coin',
    descVi: 'Đồng bạc trắng của thương gia; mười bát bạc đổi được một vàng.',
    descEn: 'A merchant’s white silver coin; ten of these trade for one gold.',
    aliases: ['silver coin', 'bat bac', 'silver'],
    usable: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'spirit_stone',
    nameVi: 'Linh thạch',
    nameEn: 'Spirit Stone',
    descVi: 'Linh thạch ấm tay; một viên tương đương mười vàng hay một trăm bạc.',
    descEn: 'A spirit stone warm to the touch; one equals ten gold or a hundred silver.',
    aliases: ['spirit stone', 'linh thach', 'stone'],
    usable: false,
    buyPrice: null,
    sellPrice: null,
  },
  {
    id: 'gold_note',
    nameVi: 'Kim phiếu',
    nameEn: 'Gold Note',
    descVi: 'Kim phiếu của quỹ Bảo, dùng thay vàng nặng khi đi đường xa.',
    descEn: 'A gold note from Bao’s till, standing in for heavy coin on long roads.',
    aliases: ['gold note', 'kim phieu', 'note'],
    usable: false,
    buyPrice: null,
    sellPrice: null,
  },
  /* 12 mồi thuần thú — tham chiếu bởi beasts.ts (T06) */
  {
    id: 'bait_white_tiger',
    nameVi: 'Mồi hổ trắng',
    nameEn: 'White Tiger Bait',
    descVi: 'Xương ướp nhựa dược thơm nồng, hổ trắng ngửi thấy là bỏ cả đường mòn.',
    descEn: 'Bone soaked in pungent medicinal sap; a white tiger will leave its trail for it.',
    aliases: ['white tiger bait', 'moi ho trang', 'tiger bait'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'bait_grey_wolf',
    nameVi: 'Mồi sói xám',
    nameEn: 'Grey Wolf Bait',
    descVi: 'Thịt hun khói trộn bột xương, mùi quen thuộc với cả bầy sói xám.',
    descEn: 'Smoked meat mixed with bone meal, a smell every grey wolf pack knows.',
    aliases: ['grey wolf bait', 'moi soi xam', 'wolf bait'],
    usable: false,
    buyPrice: 15,
    sellPrice: 7,
  },
  {
    id: 'bait_crane_spirit',
    nameVi: 'Mồi hạc linh',
    nameEn: 'Crane-Spirit Bait',
    descVi: 'Hạt ngọc nhỏ hạt cát, rải lên mặt nước là hạc linh chịu hạ cánh.',
    descEn: 'Sand-fine jade grains scattered on water; even a crane spirit will land.',
    aliases: ['crane spirit bait', 'moi hac linh', 'crane bait'],
    usable: false,
    buyPrice: 30,
    sellPrice: 15,
  },
  {
    id: 'bait_fox_spirit',
    nameVi: 'Mồi hồ ly',
    nameEn: 'Fox-Spirit Bait',
    descVi: 'Quả mọng lên men đúng ba ngày, hồ ly tinh đánh hơi được từ nửa dặm.',
    descEn: 'Berries fermented exactly three days; a fox spirit smells it half a mile off.',
    aliases: ['fox spirit bait', 'moi ho ly', 'fox bait'],
    usable: false,
    buyPrice: 25,
    sellPrice: 12,
  },
  {
    id: 'bait_dragon_serpent',
    nameVi: 'Mồi giao long',
    nameEn: 'Dragon-Serpent Bait',
    descVi: 'Cá sống buộc chỉ đỏ, giao long dưới vực không bao giờ chờ được lâu.',
    descEn: 'Live fish tied with red thread; no dragon serpent in the pool can wait long.',
    aliases: ['dragon serpent bait', 'moi giao long', 'serpent bait'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'bait_baby_qilin',
    nameVi: 'Mồi kỳ lân non',
    nameEn: 'Baby-Qilin Bait',
    descVi: 'Cỏ non tưới sương ngọc, kỳ lân non thơm mùi là chạy tới trước cả mẹ nó.',
    descEn: 'Young grass watered with jade dew; a baby qilin runs to it ahead of its mother.',
    aliases: ['baby qilin bait', 'moi ky lan non', 'qilin bait'],
    usable: false,
    buyPrice: 40,
    sellPrice: 20,
  },
  {
    id: 'bait_frost_boar',
    nameVi: 'Mồi heo băng',
    nameEn: 'Frost Boar Bait',
    descVi: 'Củ ráy luộc cùng muối đá, heo băng gặm ngon quên cả phá rào.',
    descEn: 'Boiled taro root with rock salt; a frost boar gnaws contentedly and forgets the fence.',
    aliases: ['frost boar bait', 'moi heo bang', 'boar bait'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'bait_blaze_hound',
    nameVi: 'Mồi khuyển hỏa',
    nameEn: 'Blaze Hound Bait',
    descVi: 'Sáp ong trộn bột nhựa thông, đốt lên khuyển hỏa tưởng đồng loại gọi.',
    descEn: 'Beeswax kneaded with pine resin; light it and a blaze hound hears a kinsman calling.',
    aliases: ['blaze hound bait', 'moi khuyen hoa', 'hound bait'],
    usable: false,
    buyPrice: 20,
    sellPrice: 10,
  },
  {
    id: 'bait_bee_queen',
    nameVi: 'Mồi ong chúa',
    nameEn: 'Bee Queen Bait',
    descVi: 'Mật nguyên đổ vào vỏ bầu, ong chúa lập tổ ngay chỗ để mồi.',
    descEn: 'Raw honey poured into a gourd shell; a bee queen will build right where the bait sits.',
    aliases: ['bee queen bait', 'moi ong chua', 'bee bait'],
    usable: false,
    buyPrice: 15,
    sellPrice: 7,
  },
  {
    id: 'bait_peach_spirit',
    nameVi: 'Mồi đào tinh',
    nameEn: 'Peach-Spirit Bait',
    descVi: 'Đào chín úp bát sứ một đêm, đào tinh mải ngắm bóng mình trong mùi rượu.',
    descEn: 'Ripe peaches left under a porcelain bowl overnight; the peach spirit lingers over its own perfumed reflection.',
    aliases: ['peach spirit bait', 'moi dao tinh', 'peach bait'],
    usable: false,
    buyPrice: 30,
    sellPrice: 15,
  },
  {
    id: 'bait_turtle_imp',
    nameVi: 'Mồi quy tinh',
    nameEn: 'Turtle-Imp Bait',
    descVi: 'Bánh nếp nặn hình rùa, quy tinh cắn mồi mà không chịu rời chân.',
    descEn: 'Sticky rice cakes shaped like turtles; a turtle imp bites and refuses to let go.',
    aliases: ['turtle imp bait', 'moi quy tinh', 'turtle bait'],
    usable: false,
    buyPrice: 25,
    sellPrice: 12,
  },
  {
    id: 'bait_storm_bird',
    nameVi: 'Mồi điểu bão',
    nameEn: 'Storm Bird Bait',
    descVi: 'Dải lụa bạc cột xương cá, điểu bão lao xuống tưởng chớp rơi giữa gió.',
    descEn: 'A strip of silver silk tied to a fishbone; the storm bird dives thinking lightning fell in the wind.',
    aliases: ['storm bird bait', 'moi dieu bao', 'storm bait'],
    usable: false,
    buyPrice: 35,
    sellPrice: 17,
  },
  /* 4 đan hiếm — chỉ đổi bằng Linh Thạch (T11/T12), không bán bằng vàng */
  {
    id: 'pill_ls_ninefold',
    nameVi: 'Cửu chuyển linh đan',
    nameEn: 'Ninefold Spirit Pill',
    descVi: 'Đan chín lò chín lần về, giá chỉ đổi bằng Linh Thạch chứ không nhận vàng.',
    descEn: 'Nine turns across nine furnaces; traded only for Spirit Stones — gold is refused.',
    aliases: ['ninefold pill', 'cuu chuyen linh dan', 'ls ninefold'],
    usable: true,
    effects: { qi: 60 },
    buyPrice: null,
    sellPrice: 300,
  },
  {
    id: 'pill_ls_marrow',
    nameVi: 'Dị tủy linh đan',
    nameEn: 'Marrow-Shift Pill',
    descVi: 'Uống xong tủy xương rét run rồi ấm lại; muốn có thì chỉ đổi bằng Linh Thạch.',
    descEn: 'The marrow shivers then warms; to own one you trade only in Spirit Stones.',
    aliases: ['marrow shift pill', 'di tui linh dan', 'ls marrow'],
    usable: true,
    effects: { hp: 60 },
    buyPrice: null,
    sellPrice: 240,
  },
  {
    id: 'pill_ls_iron',
    nameVi: 'Thiết cốt đan',
    nameEn: 'Iron-Bone Pill',
    descVi: 'Da thịt cứng như đá mài ba ngày; lò đan chỉ nhận Linh Thạch, không nhận vàng.',
    descEn: 'Skin hard as three days of whetstone; the valley accepts Spirit Stones only, never gold.',
    aliases: ['iron bone pill', 'thiet cot dan', 'ls iron'],
    usable: true,
    effects: { hp: 40, qi: 20 },
    buyPrice: null,
    sellPrice: 220,
  },
  {
    id: 'pill_ls_cloud',
    nameVi: 'Lăng vân đan',
    nameEn: 'Cloud-Step Pill',
    descVi: 'Nuốt viên đan mà bước chân nhẹ như lướt mây; giá tính bằng Linh Thạch.',
    descEn: 'Swallow it and your steps turn light as drifting cloud; priced in Spirit Stones.',
    aliases: ['cloud step pill', 'lang van dan', 'ls cloud'],
    usable: true,
    effects: { qi: 50 },
    buyPrice: null,
    sellPrice: 260,
  },
  {
    id: 'sword_starfall_hidden_manual', nameVi: 'Tinh Lạc Kiếm Phổ', nameEn: 'Starfall Sword Manual',
    descVi: 'Kiếm phổ giấu trong vỏ thiên thạch.', descEn: 'A sword manual hidden in a meteorite sheath.',
    aliases: ['starfall manual'], usable: false, teachesTechniqueId: 'sword_starfall_hidden', requiredStage: 4, buyPrice: null, sellPrice: 300,
  },
  {
    id: 'sword_moonlight_edge_hidden_manual', nameVi: 'Nguyệt Quang Kiếm Phổ', nameEn: 'Moonlight Edge Manual',
    descVi: 'Mực bạc chỉ hiện dưới trăng.', descEn: 'Silver ink appears only under moonlight.',
    aliases: ['moonlight edge manual'], usable: false, teachesTechniqueId: 'sword_moonlight_edge_hidden', requiredStage: 5, buyPrice: null, sellPrice: 400,
  },
  {
    id: 'aura_still_water_hidden_manual', nameVi: 'Tĩnh Thủy Quyết', nameEn: 'Still-Water Art Manual',
    descVi: 'Trang giấy lạnh như đáy hồ.', descEn: 'The pages are cold as a lakebed.',
    aliases: ['still water manual'], usable: false, teachesTechniqueId: 'aura_still_water_hidden', requiredStage: 4, buyPrice: null, sellPrice: 280,
  },
  {
    id: 'aura_nine_sun_hidden_manual', nameVi: 'Cửu Dương Khí Quán', nameEn: 'Nine-Sun Aura Manual',
    descVi: 'Chữ đỏ rực như than hồng.', descEn: 'The red script glows like embers.',
    aliases: ['nine sun manual'], usable: false, teachesTechniqueId: 'aura_nine_sun_hidden', requiredStage: 5, buyPrice: null, sellPrice: 420,
  },
  {
    id: 'herbal_root_whisper_hidden_manual', nameVi: 'Rễ Nghe Lời', nameEn: 'Root Whisper Manual',
    descVi: 'Giấy thơm mùi đất sau mưa.', descEn: 'The paper smells of earth after rain.',
    aliases: ['root whisper manual'], usable: false, teachesTechniqueId: 'herbal_root_whisper_hidden', requiredStage: 4, buyPrice: null, sellPrice: 270,
  },
  {
    id: 'herbal_grave_soil_hidden_manual', nameVi: 'Mộ Thổ Thuật', nameEn: 'Grave-Soil Method Manual',
    descVi: 'Bìa sách vương lớp đất mộ khô.', descEn: 'The cover still bears dry grave soil.',
    aliases: ['grave soil manual'], usable: false, teachesTechniqueId: 'herbal_grave_soil_hidden', requiredStage: 5, buyPrice: null, sellPrice: 390,
  },
  {
    id: 'shadow_molt_hidden_manual', nameVi: 'Ảnh Thuế Pháp', nameEn: 'Shadow-Molt Manual',
    descVi: 'Bóng chữ trượt khỏi trang khi chớp mắt.', descEn: 'The script slips off the page when you blink.',
    aliases: ['shadow molt manual'], usable: false, teachesTechniqueId: 'shadow_molt_hidden', requiredStage: 4, buyPrice: null, sellPrice: 290,
  },
  {
    id: 'shadow_eclipse_step_hidden_manual', nameVi: 'Thực Nguyệt Bộ', nameEn: 'Eclipse Step Manual',
    descVi: 'Dấu chân đen in theo chu kỳ trăng.', descEn: 'Black footprints follow the moon’s cycle.',
    aliases: ['eclipse step manual'], usable: false, teachesTechniqueId: 'shadow_eclipse_step_hidden', requiredStage: 5, buyPrice: null, sellPrice: 410,
  },
  {
    id: 'thunder_gasp_hidden_manual', nameVi: 'Lôi Hấp Pháp', nameEn: 'Thunder-Gasp Manual',
    descVi: 'Mỗi trang rung nhẹ khi có giông.', descEn: 'Every page trembles before a storm.',
    aliases: ['thunder gasp manual'], usable: false, teachesTechniqueId: 'thunder_gasp_hidden', requiredStage: 5, buyPrice: null, sellPrice: 430,
  },
]

export function getItem(itemId: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === itemId)
}

export const SHOP_STOCK: string[] = ITEMS.filter((i) => i.buyPrice !== null).map((i) => i.id)
