// Name memories: the 200 erased names — the raw material the System was made of
// (story canon §3, docs/plans/expansion-x20/contracts/story-canon.md).
// Data only. Ids nm_001..nm_200; sources: quest 100, ash 60, night 40
// (nm_161..nm_200 are the four night-ledger pages, 10 names each).

export interface NameMemory {
  id: string
  nameVi: string
  nameEn: string
  source: 'quest' | 'ash' | 'night'
  hintVi: string
  hintEn: string
}

export type NightPageId = 'night_1' | 'night_2' | 'night_3' | 'night_4'

export const NAME_MEMORIES: NameMemory[] = [
  { id: 'nm_001', nameVi: 'Trịnh Bàn', nameEn: 'Trinh Ban', source: 'quest', hintVi: 'Tên khắc trên bảng việc viện dân của Làng Thanh Mộc.', hintEn: 'A name carved on the village side-quest relief board.' },
  { id: 'nm_002', nameVi: 'La Cửu Nương', nameEn: 'La Cuu Nuong', source: 'quest', hintVi: 'Tờ giấy nhiệm vụ bí mật cháy nửa, còn lại đúng tên này.', hintEn: 'A half-burned secret quest slip names only this.' },
  { id: 'nm_003', nameVi: 'Trần Văn Đạt', nameEn: 'Tran Van Dat', source: 'quest', hintVi: 'Tên trong danh sách nhiệm vụ tìm người của một NPC ẩn.', hintEn: 'A hidden NPC find-the-person quest list holds this name.' },
  { id: 'nm_004', nameVi: 'Lê Thị Hạnh', nameEn: 'Le Thi Hanh', source: 'quest', hintVi: 'Tên được nhắc khi chuyện trò thân mật với người quen.', hintEn: 'The name slips out during a warm affinity chat.' },
  { id: 'nm_005', nameVi: 'Phạm Trọng Khánh', nameEn: 'Pham Trong Khanh', source: 'quest', hintVi: 'Cát đồng hồ nhiệm vụ có hạn chảy hết — tên này trôi theo.', hintEn: 'The hourglass of a timed quest ran out — the name drifted with it.' },
  { id: 'nm_006', nameVi: 'Đỗ Thanh Nương', nameEn: 'Do Thanh Nuong', source: 'quest', hintVi: 'Cái tên xuất hiện trong một nhiệm vụ phụ bên khu chợ.', hintEn: 'The name surfaces in a market side quest errand.' },
  { id: 'nm_007', nameVi: 'Nguyễn Bách', nameEn: 'Nguyen Bach', source: 'quest', hintVi: 'Tên nằm dưới nền nơi cất nhiệm vụ bí mật trong hang.', hintEn: 'The name lay beneath a secret quest cache in a cave.' },
  { id: 'nm_008', nameVi: 'Vũ Kim Hoa', nameEn: 'Vu Kim Hoa', source: 'quest', hintVi: 'Người mang tên này từng là mục tiêu của một nhiệm vụ tìm kiếm.', hintEn: 'This bearer was once the target of a find-the-person quest.' },
  { id: 'nm_009', nameVi: 'Bùi Diệp', nameEn: 'Bui Diep', source: 'quest', hintVi: 'Một nhiệm vụ tình thân chỉ mở khi lòng tin chạm mốc — tên này được gọi ra.', hintEn: 'An affinity quest unlocks at deep trust — and speaks this name.' },
  { id: 'nm_010', nameVi: 'Đặng Vân Tiên', nameEn: 'Dang Van Tien', source: 'quest', hintVi: 'Một nhiệm vụ hạn ba ngày từng trao tin về người mang tên này.', hintEn: 'A three-day timed quest once carried word of this bearer.' },
  { id: 'nm_011', nameVi: 'Hồ Bảo La', nameEn: 'Ho Bao La', source: 'quest', hintVi: 'Tiếng đồn việc viện ở rừng còn nhắc tên này.', hintEn: 'Forest side-quest gossip still murmurs this name.' },
  { id: 'nm_012', nameVi: 'Lý Tiểu Ngư', nameEn: 'Ly Tieu Ngu', source: 'quest', hintVi: 'Chỉ ai nhận nhiệm vụ bí mật của khu mỏ mới nhớ nổi tên này.', hintEn: 'Only takers of the mine secret quest recall this name.' },
  { id: 'nm_013', nameVi: 'Vương Mẫn', nameEn: 'Vuong Man', source: 'quest', hintVi: 'Bản đồ nhiệm vụ tìm đường khoanh đúng cái tên này.', hintEn: 'A path-finding quest map circles exactly this name.' },
  { id: 'nm_014', nameVi: 'Ngô Đại Quan', nameEn: 'Ngo Dai Quan', source: 'quest', hintVi: 'Người ta chỉ nhớ tên này khi quan tâm đủ sâu.', hintEn: 'Only a deep affinity bond can recall this name.' },
  { id: 'nm_015', nameVi: 'Dương Tú Anh', nameEn: 'Duong Tu Anh', source: 'quest', hintVi: 'Hạn chót qua đi, chỉ còn tên khắc vội trên cột đình.', hintEn: 'The timed quest deadline passed; only a name hastily carved on the post remains.' },
  { id: 'nm_016', nameVi: 'Tạ Phong', nameEn: 'Ta Phong', source: 'quest', hintVi: 'Một nhiệm vụ phụ ở hồ đã trao tin về người mang tên này.', hintEn: 'A lakeside side quest once traded word of this bearer.' },
  { id: 'nm_017', nameVi: 'Cao Thị Mận', nameEn: 'Cao Thi Man', source: 'quest', hintVi: 'Một nhiệm vụ bí mật sau đầm lầy khắc tên này trên đá.', hintEn: 'A secret quest behind the swamp carved this name on stone.' },
  { id: 'nm_018', nameVi: 'Tô Khanh', nameEn: 'To Khanh', source: 'quest', hintVi: 'Một nhiệm vụ tìm vật trao trả về đúng cái tên bị xóa này.', hintEn: 'A find-the-item quest led back to this erased name.' },
  { id: 'nm_019', nameVi: 'Hà Văn Bằng', nameEn: 'Ha Van Bang', source: 'quest', hintVi: 'Nhật ký thân tình ghi dòng mực nhạt: đúng tên này.', hintEn: 'An affinity journal holds a faint ink line: this very name.' },
  { id: 'nm_020', nameVi: 'Lâm Chi Lăng', nameEn: 'Lam Chi Lang', source: 'quest', hintVi: 'Tờ nháp nhiệm vụ khẩn ghi vội tên này rồi phai.', hintEn: 'An urgent timed quest draft scribbled this name, then faded.' },
  { id: 'nm_021', nameVi: 'Quách Trúc Linh', nameEn: 'Quach Truc Linh', source: 'quest', hintVi: 'Tên khắc trên bảng việc viện dân của Làng Thanh Mộc.', hintEn: 'A name carved on the village side-quest relief board.' },
  { id: 'nm_022', nameVi: 'Chu Phương Phi', nameEn: 'Chu Phuong Phi', source: 'quest', hintVi: 'Tờ giấy nhiệm vụ bí mật cháy nửa, còn lại đúng tên này.', hintEn: 'A half-burned secret quest slip names only this.' },
  { id: 'nm_023', nameVi: 'Phùng Văn Chính', nameEn: 'Phung Van Chinh', source: 'quest', hintVi: 'Tên trong danh sách nhiệm vụ tìm người của một NPC ẩn.', hintEn: 'A hidden NPC find-the-person quest list holds this name.' },
  { id: 'nm_024', nameVi: 'Hàn Tuyết Nhi', nameEn: 'Han Tuyet Nhi', source: 'quest', hintVi: 'Tên được nhắc khi chuyện trò thân mật với người quen.', hintEn: 'The name slips out during a warm affinity chat.' },
  { id: 'nm_025', nameVi: 'Mạc Ngữ Yên', nameEn: 'Mac Ngu Yen', source: 'quest', hintVi: 'Cát đồng hồ nhiệm vụ có hạn chảy hết — tên này trôi theo.', hintEn: 'The hourglass of a timed quest ran out — the name drifted with it.' },
  { id: 'nm_026', nameVi: 'Triệu Hổ', nameEn: 'Trieu Ho', source: 'quest', hintVi: 'Cái tên xuất hiện trong một nhiệm vụ phụ bên khu chợ.', hintEn: 'The name surfaces in a market side quest errand.' },
  { id: 'nm_027', nameVi: 'Tống Khánh Vũ', nameEn: 'Tong Khanh Vu', source: 'quest', hintVi: 'Tên nằm dưới nền nơi cất nhiệm vụ bí mật trong hang.', hintEn: 'The name lay beneath a secret quest cache in a cave.' },
  { id: 'nm_028', nameVi: 'Tần Miên', nameEn: 'Tan Mien', source: 'quest', hintVi: 'Người mang tên này từng là mục tiêu của một nhiệm vụ tìm kiếm.', hintEn: 'This bearer was once the target of a find-the-person quest.' },
  { id: 'nm_029', nameVi: 'Trương Quế', nameEn: 'Truong Que', source: 'quest', hintVi: 'Một nhiệm vụ tình thân chỉ mở khi lòng tin chạm mốc — tên này được gọi ra.', hintEn: 'An affinity quest unlocks at deep trust — and speaks this name.' },
  { id: 'nm_030', nameVi: 'Phí Thị Tâm', nameEn: 'Phi Thi Tam', source: 'quest', hintVi: 'Một nhiệm vụ hạn ba ngày từng trao tin về người mang tên này.', hintEn: 'A three-day timed quest once carried word of this bearer.' },
  { id: 'nm_031', nameVi: 'Chung Trác', nameEn: 'Chung Trac', source: 'quest', hintVi: 'Tiếng đồn việc viện ở rừng còn nhắc tên này.', hintEn: 'Forest side-quest gossip still murmurs this name.' },
  { id: 'nm_032', nameVi: 'Kỳ Băng', nameEn: 'Ky Bang', source: 'quest', hintVi: 'Chỉ ai nhận nhiệm vụ bí mật của khu mỏ mới nhớ nổi tên này.', hintEn: 'Only takers of the mine secret quest recall this name.' },
  { id: 'nm_033', nameVi: 'Sầm Ngọc Bích', nameEn: 'Sam Ngoc Bich', source: 'quest', hintVi: 'Bản đồ nhiệm vụ tìm đường khoanh đúng cái tên này.', hintEn: 'A path-finding quest map circles exactly this name.' },
  { id: 'nm_034', nameVi: 'Diệp Phàm', nameEn: 'Diep Pham', source: 'quest', hintVi: 'Người ta chỉ nhớ tên này khi quan tâm đủ sâu.', hintEn: 'Only a deep affinity bond can recall this name.' },
  { id: 'nm_035', nameVi: 'Cổ Thiềm', nameEn: 'Co Thiem', source: 'quest', hintVi: 'Hạn chót qua đi, chỉ còn tên khắc vội trên cột đình.', hintEn: 'The timed quest deadline passed; only a name hastily carved on the post remains.' },
  { id: 'nm_036', nameVi: 'Âu Dương Xuân', nameEn: 'Au Duong Xuan', source: 'quest', hintVi: 'Một nhiệm vụ phụ ở hồ đã trao tin về người mang tên này.', hintEn: 'A lakeside side quest once traded word of this bearer.' },
  { id: 'nm_037', nameVi: 'Lỗ Văn Quý', nameEn: 'Lo Van Quy', source: 'quest', hintVi: 'Một nhiệm vụ bí mật sau đầm lầy khắc tên này trên đá.', hintEn: 'A secret quest behind the swamp carved this name on stone.' },
  { id: 'nm_038', nameVi: 'Mao Tiểu Điệp', nameEn: 'Mao Tieu Diep', source: 'quest', hintVi: 'Một nhiệm vụ tìm vật trao trả về đúng cái tên bị xóa này.', hintEn: 'A find-the-item quest led back to this erased name.' },
  { id: 'nm_039', nameVi: 'Nghiêm Sương', nameEn: 'Nghiem Suong', source: 'quest', hintVi: 'Nhật ký thân tình ghi dòng mực nhạt: đúng tên này.', hintEn: 'An affinity journal holds a faint ink line: this very name.' },
  { id: 'nm_040', nameVi: 'Tân Thục Nương', nameEn: 'Tan Thuc Nuong', source: 'quest', hintVi: 'Tờ nháp nhiệm vụ khẩn ghi vội tên này rồi phai.', hintEn: 'An urgent timed quest draft scribbled this name, then faded.' },
  { id: 'nm_041', nameVi: 'Từ Hạc', nameEn: 'Tu Hac', source: 'quest', hintVi: 'Tên khắc trên bảng việc viện dân của Làng Thanh Mộc.', hintEn: 'A name carved on the village side-quest relief board.' },
  { id: 'nm_042', nameVi: 'Tiêu Vũ Nương', nameEn: 'Tieu Vu Nuong', source: 'quest', hintVi: 'Tờ giấy nhiệm vụ bí mật cháy nửa, còn lại đúng tên này.', hintEn: 'A half-burned secret quest slip names only this.' },
  { id: 'nm_043', nameVi: 'Trác Văn Viễn', nameEn: 'Trac Van Vien', source: 'quest', hintVi: 'Tên trong danh sách nhiệm vụ tìm người của một NPC ẩn.', hintEn: 'A hidden NPC find-the-person quest list holds this name.' },
  { id: 'nm_044', nameVi: 'Trầm Hương', nameEn: 'Tran Huong', source: 'quest', hintVi: 'Tên được nhắc khi chuyện trò thân mật với người quen.', hintEn: 'The name slips out during a warm affinity chat.' },
  { id: 'nm_045', nameVi: 'Viên Bạch Hà', nameEn: 'Vien Bach Ha', source: 'quest', hintVi: 'Cát đồng hồ nhiệm vụ có hạn chảy hết — tên này trôi theo.', hintEn: 'The hourglass of a timed quest ran out — the name drifted with it.' },
  { id: 'nm_046', nameVi: 'Điền Chấn Nam', nameEn: 'Dien Chan Nam', source: 'quest', hintVi: 'Cái tên xuất hiện trong một nhiệm vụ phụ bên khu chợ.', hintEn: 'The name surfaces in a market side quest errand.' },
  { id: 'nm_047', nameVi: 'Đinh Cẩm', nameEn: 'Dinh Cam', source: 'quest', hintVi: 'Tên nằm dưới nền nơi cất nhiệm vụ bí mật trong hang.', hintEn: 'The name lay beneath a secret quest cache in a cave.' },
  { id: 'nm_048', nameVi: 'Đoàn Thị Loan', nameEn: 'Doan Thi Loan', source: 'quest', hintVi: 'Người mang tên này từng là mục tiêu của một nhiệm vụ tìm kiếm.', hintEn: 'This bearer was once the target of a find-the-person quest.' },
  { id: 'nm_049', nameVi: 'Giang Vân Tụ', nameEn: 'Giang Van Tu', source: 'quest', hintVi: 'Một nhiệm vụ tình thân chỉ mở khi lòng tin chạm mốc — tên này được gọi ra.', hintEn: 'An affinity quest unlocks at deep trust — and speaks this name.' },
  { id: 'nm_050', nameVi: 'Hoa Vô Kỳ', nameEn: 'Hoa Vo Ky', source: 'quest', hintVi: 'Một nhiệm vụ hạn ba ngày từng trao tin về người mang tên này.', hintEn: 'A three-day timed quest once carried word of this bearer.' },
  { id: 'nm_051', nameVi: 'Huỳnh Tá', nameEn: 'Huynh Ta', source: 'quest', hintVi: 'Tiếng đồn việc viện ở rừng còn nhắc tên này.', hintEn: 'Forest side-quest gossip still murmurs this name.' },
  { id: 'nm_052', nameVi: 'Khuất Văn Đỉnh', nameEn: 'Khuat Van Dinh', source: 'quest', hintVi: 'Chỉ ai nhận nhiệm vụ bí mật của khu mỏ mới nhớ nổi tên này.', hintEn: 'Only takers of the mine secret quest recall this name.' },
  { id: 'nm_053', nameVi: 'Kiều Nguyệt Nga', nameEn: 'Kieu Nguyet Nga', source: 'quest', hintVi: 'Bản đồ nhiệm vụ tìm đường khoanh đúng cái tên này.', hintEn: 'A path-finding quest map circles exactly this name.' },
  { id: 'nm_054', nameVi: 'Lưu Kỳ', nameEn: 'Luu Ky', source: 'quest', hintVi: 'Người ta chỉ nhớ tên này khi quan tâm đủ sâu.', hintEn: 'Only a deep affinity bond can recall this name.' },
  { id: 'nm_055', nameVi: 'Mai Tiềm', nameEn: 'Mai Tiem', source: 'quest', hintVi: 'Hạn chót qua đi, chỉ còn tên khắc vội trên cột đình.', hintEn: 'The timed quest deadline passed; only a name hastily carved on the post remains.' },
  { id: 'nm_056', nameVi: 'Mạnh Thu Hà', nameEn: 'Manh Thu Ha', source: 'quest', hintVi: 'Một nhiệm vụ phụ ở hồ đã trao tin về người mang tên này.', hintEn: 'A lakeside side quest once traded word of this bearer.' },
  { id: 'nm_057', nameVi: 'Ninh Vỹ', nameEn: 'Ninh Vy', source: 'quest', hintVi: 'Một nhiệm vụ bí mật sau đầm lầy khắc tên này trên đá.', hintEn: 'A secret quest behind the swamp carved this name on stone.' },
  { id: 'nm_058', nameVi: 'Ôn Như Ý', nameEn: 'On Nhu Y', source: 'quest', hintVi: 'Một nhiệm vụ tìm vật trao trả về đúng cái tên bị xóa này.', hintEn: 'A find-the-item quest led back to this erased name.' },
  { id: 'nm_059', nameVi: 'Phan Kế Bính', nameEn: 'Phan Ke Binh', source: 'quest', hintVi: 'Nhật ký thân tình ghi dòng mực nhạt: đúng tên này.', hintEn: 'An affinity journal holds a faint ink line: this very name.' },
  { id: 'nm_060', nameVi: 'Quyền Thuỵ', nameEn: 'Quyen Thuy', source: 'quest', hintVi: 'Tờ nháp nhiệm vụ khẩn ghi vội tên này rồi phai.', hintEn: 'An urgent timed quest draft scribbled this name, then faded.' },
  { id: 'nm_061', nameVi: 'Sử Văn Tiến', nameEn: 'Su Van Tien', source: 'quest', hintVi: 'Tên khắc trên bảng việc viện dân của Làng Thanh Mộc.', hintEn: 'A name carved on the village side-quest relief board.' },
  { id: 'nm_062', nameVi: 'Sơn Nguyệt', nameEn: 'Son Nguyet', source: 'quest', hintVi: 'Tờ giấy nhiệm vụ bí mật cháy nửa, còn lại đúng tên này.', hintEn: 'A half-burned secret quest slip names only this.' },
  { id: 'nm_063', nameVi: 'Thiệu Hoa Đình', nameEn: 'Thieu Hoa Dinh', source: 'quest', hintVi: 'Tên trong danh sách nhiệm vụ tìm người của một NPC ẩn.', hintEn: 'A hidden NPC find-the-person quest list holds this name.' },
  { id: 'nm_064', nameVi: 'Thôi Bích Khuê', nameEn: 'Thoi Bich Khue', source: 'quest', hintVi: 'Tên được nhắc khi chuyện trò thân mật với người quen.', hintEn: 'The name slips out during a warm affinity chat.' },
  { id: 'nm_065', nameVi: 'Tiền Đa Đa', nameEn: 'Tien Da Da', source: 'quest', hintVi: 'Cát đồng hồ nhiệm vụ có hạn chảy hết — tên này trôi theo.', hintEn: 'The hourglass of a timed quest ran out — the name drifted with it.' },
  { id: 'nm_066', nameVi: 'Tôn Thượng Hương', nameEn: 'Ton Thuong Huong', source: 'quest', hintVi: 'Cái tên xuất hiện trong một nhiệm vụ phụ bên khu chợ.', hintEn: 'The name surfaces in a market side quest errand.' },
  { id: 'nm_067', nameVi: 'Tất Xuân Kiều', nameEn: 'Tat Xuan Kieu', source: 'quest', hintVi: 'Tên nằm dưới nền nơi cất nhiệm vụ bí mật trong hang.', hintEn: 'The name lay beneath a secret quest cache in a cave.' },
  { id: 'nm_068', nameVi: 'Vạn Văn Tú', nameEn: 'Van Van Tu', source: 'quest', hintVi: 'Người mang tên này từng là mục tiêu của một nhiệm vụ tìm kiếm.', hintEn: 'This bearer was once the target of a find-the-person quest.' },
  { id: 'nm_069', nameVi: 'Yên Khả', nameEn: 'Yen Kha', source: 'quest', hintVi: 'Một nhiệm vụ tình thân chỉ mở khi lòng tin chạm mốc — tên này được gọi ra.', hintEn: 'An affinity quest unlocks at deep trust — and speaks this name.' },
  { id: 'nm_070', nameVi: 'Ngải Văn Hạo', nameEn: 'Ngai Van Hao', source: 'quest', hintVi: 'Một nhiệm vụ hạn ba ngày từng trao tin về người mang tên này.', hintEn: 'A three-day timed quest once carried word of this bearer.' },
  { id: 'nm_071', nameVi: 'Nông Thải Lan', nameEn: 'Nong Thai Lan', source: 'quest', hintVi: 'Tiếng đồn việc viện ở rừng còn nhắc tên này.', hintEn: 'Forest side-quest gossip still murmurs this name.' },
  { id: 'nm_072', nameVi: 'Cù Trọng Phủ', nameEn: 'Cu Trong Phu', source: 'quest', hintVi: 'Chỉ ai nhận nhiệm vụ bí mật của khu mỏ mới nhớ nổi tên này.', hintEn: 'Only takers of the mine secret quest recall this name.' },
  { id: 'nm_073', nameVi: 'Giáp Văn Tông', nameEn: 'Giap Van Tong', source: 'quest', hintVi: 'Bản đồ nhiệm vụ tìm đường khoanh đúng cái tên này.', hintEn: 'A path-finding quest map circles exactly this name.' },
  { id: 'nm_074', nameVi: 'Hầu Minh Châu', nameEn: 'Hau Minh Chau', source: 'quest', hintVi: 'Người ta chỉ nhớ tên này khi quan tâm đủ sâu.', hintEn: 'Only a deep affinity bond can recall this name.' },
  { id: 'nm_075', nameVi: 'Hoàng Phi Lộ', nameEn: 'Hoang Phi Lo', source: 'quest', hintVi: 'Hạn chót qua đi, chỉ còn tên khắc vội trên cột đình.', hintEn: 'The timed quest deadline passed; only a name hastily carved on the post remains.' },
  { id: 'nm_076', nameVi: 'Khâu Sơ Lam', nameEn: 'Khau So Lam', source: 'quest', hintVi: 'Một nhiệm vụ phụ ở hồ đã trao tin về người mang tên này.', hintEn: 'A lakeside side quest once traded word of this bearer.' },
  { id: 'nm_077', nameVi: 'Khúc Nhật Diệu', nameEn: 'Khuc Nhat Dieu', source: 'quest', hintVi: 'Một nhiệm vụ bí mật sau đầm lầy khắc tên này trên đá.', hintEn: 'A secret quest behind the swamp carved this name on stone.' },
  { id: 'nm_078', nameVi: 'Lương Văn Sử', nameEn: 'Luong Van Su', source: 'quest', hintVi: 'Một nhiệm vụ tìm vật trao trả về đúng cái tên bị xóa này.', hintEn: 'A find-the-item quest led back to this erased name.' },
  { id: 'nm_079', nameVi: 'Lôi Vĩnh Khang', nameEn: 'Loi Vinh Khang', source: 'quest', hintVi: 'Nhật ký thân tình ghi dòng mực nhạt: đúng tên này.', hintEn: 'An affinity journal holds a faint ink line: this very name.' },
  { id: 'nm_080', nameVi: 'Lục Tiểu Phụng', nameEn: 'Luc Tieu Phung', source: 'quest', hintVi: 'Tờ nháp nhiệm vụ khẩn ghi vội tên này rồi phai.', hintEn: 'An urgent timed quest draft scribbled this name, then faded.' },
  { id: 'nm_081', nameVi: 'Lã Bích Hà', nameEn: 'La Bich Ha', source: 'quest', hintVi: 'Tên khắc trên bảng việc viện dân của Làng Thanh Mộc.', hintEn: 'A name carved on the village side-quest relief board.' },
  { id: 'nm_082', nameVi: 'Ngân Đình', nameEn: 'Ngan Dinh', source: 'quest', hintVi: 'Tờ giấy nhiệm vụ bí mật cháy nửa, còn lại đúng tên này.', hintEn: 'A half-burned secret quest slip names only this.' },
  { id: 'nm_083', nameVi: 'Phó Văn Ưng', nameEn: 'Pho Van Ung', source: 'quest', hintVi: 'Tên trong danh sách nhiệm vụ tìm người của một NPC ẩn.', hintEn: 'A hidden NPC find-the-person quest list holds this name.' },
  { id: 'nm_084', nameVi: 'Phú Văn Cương', nameEn: 'Phu Van Cuong', source: 'quest', hintVi: 'Tên được nhắc khi chuyện trò thân mật với người quen.', hintEn: 'The name slips out during a warm affinity chat.' },
  { id: 'nm_085', nameVi: 'Thân Bất Hoài', nameEn: 'Than Bat Hoai', source: 'quest', hintVi: 'Cát đồng hồ nhiệm vụ có hạn chảy hết — tên này trôi theo.', hintEn: 'The hourglass of a timed quest ran out — the name drifted with it.' },
  { id: 'nm_086', nameVi: 'Thạch Dũng', nameEn: 'Thach Dung', source: 'quest', hintVi: 'Cái tên xuất hiện trong một nhiệm vụ phụ bên khu chợ.', hintEn: 'The name surfaces in a market side quest errand.' },
  { id: 'nm_087', nameVi: 'Võ Tấn Tài', nameEn: 'Vo Tan Tai', source: 'quest', hintVi: 'Tên nằm dưới nền nơi cất nhiệm vụ bí mật trong hang.', hintEn: 'The name lay beneath a secret quest cache in a cave.' },
  { id: 'nm_088', nameVi: 'Trâu Văn Lãm', nameEn: 'Trau Van Lam', source: 'quest', hintVi: 'Người mang tên này từng là mục tiêu của một nhiệm vụ tìm kiếm.', hintEn: 'This bearer was once the target of a find-the-person quest.' },
  { id: 'nm_089', nameVi: 'Vệ Thanh Sơn', nameEn: 'Ve Thanh Son', source: 'quest', hintVi: 'Một nhiệm vụ tình thân chỉ mở khi lòng tin chạm mốc — tên này được gọi ra.', hintEn: 'An affinity quest unlocks at deep trust — and speaks this name.' },
  { id: 'nm_090', nameVi: 'Uông Tú Trân', nameEn: 'Uong Tu Tran', source: 'quest', hintVi: 'Một nhiệm vụ hạn ba ngày từng trao tin về người mang tên này.', hintEn: 'A three-day timed quest once carried word of this bearer.' },
  { id: 'nm_091', nameVi: 'Ân Văn Bạt', nameEn: 'An Van Bat', source: 'quest', hintVi: 'Tiếng đồn việc viện ở rừng còn nhắc tên này.', hintEn: 'Forest side-quest gossip still murmurs this name.' },
  { id: 'nm_092', nameVi: 'Bàng Công Độ', nameEn: 'Bang Cong Do', source: 'quest', hintVi: 'Chỉ ai nhận nhiệm vụ bí mật của khu mỏ mới nhớ nổi tên này.', hintEn: 'Only takers of the mine secret quest recall this name.' },
  { id: 'nm_093', nameVi: 'Bảo Văn Hiếu', nameEn: 'Bao Van Hieu', source: 'quest', hintVi: 'Bản đồ nhiệm vụ tìm đường khoanh đúng cái tên này.', hintEn: 'A path-finding quest map circles exactly this name.' },
  { id: 'nm_094', nameVi: 'Cung Thị Diễm', nameEn: 'Cung Thi Diem', source: 'quest', hintVi: 'Người ta chỉ nhớ tên này khi quan tâm đủ sâu.', hintEn: 'Only a deep affinity bond can recall this name.' },
  { id: 'nm_095', nameVi: 'Đàm Cửu Hùng', nameEn: 'Dam Cuu Hung', source: 'quest', hintVi: 'Hạn chót qua đi, chỉ còn tên khắc vội trên cột đình.', hintEn: 'The timed quest deadline passed; only a name hastily carved on the post remains.' },
  { id: 'nm_096', nameVi: 'Đổng Văn Khuông', nameEn: 'Dong Van Khuong', source: 'quest', hintVi: 'Một nhiệm vụ phụ ở hồ đã trao tin về người mang tên này.', hintEn: 'A lakeside side quest once traded word of this bearer.' },
  { id: 'nm_097', nameVi: 'Doãn Văn Chấn', nameEn: 'Doan Van Chan', source: 'quest', hintVi: 'Một nhiệm vụ bí mật sau đầm lầy khắc tên này trên đá.', hintEn: 'A secret quest behind the swamp carved this name on stone.' },
  { id: 'nm_098', nameVi: 'Hạ Vô Song', nameEn: 'Ha Vo Song', source: 'quest', hintVi: 'Một nhiệm vụ tìm vật trao trả về đúng cái tên bị xóa này.', hintEn: 'A find-the-item quest led back to this erased name.' },
  { id: 'nm_099', nameVi: 'Hình Văn Chi', nameEn: 'Hinh Van Chi', source: 'quest', hintVi: 'Nhật ký thân tình ghi dòng mực nhạt: đúng tên này.', hintEn: 'An affinity journal holds a faint ink line: this very name.' },
  { id: 'nm_100', nameVi: 'Đường Văn Khuê', nameEn: 'Duong Van Khue', source: 'quest', hintVi: 'Tờ nháp nhiệm vụ khẩn ghi vội tên này rồi phai.', hintEn: 'An urgent timed quest draft scribbled this name, then faded.' },
  { id: 'nm_101', nameVi: 'Nghiêu Thuần', nameEn: 'Nghieu Thuan', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_102', nameVi: 'Ngu Sĩ Đạo', nameEn: 'Ngu Si Dao', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_103', nameVi: 'Khổng Khác Đản', nameEn: 'Khong Khac Dan', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_104', nameVi: 'Chúc Cửu', nameEn: 'Chuc Cuu', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_105', nameVi: 'Trình Nhị', nameEn: 'Trinh Nhi', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_106', nameVi: 'Chân Tú Uyển', nameEn: 'Chan Tu Uyen', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_107', nameVi: 'Đái Tông Diêu', nameEn: 'Dai Tong Dieu', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_108', nameVi: 'Đào Văn Ấm', nameEn: 'Dao Van Am', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_109', nameVi: 'Đoạn Kỷ Xuân', nameEn: 'Doan Ky Xuan', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_110', nameVi: 'Tiết Đinh Sơn', nameEn: 'Tiet Dinh Son', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_111', nameVi: 'Hoắc Vân Ca', nameEn: 'Hoac Van Ca', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_112', nameVi: 'Linh Hồ Ẩn', nameEn: 'Linh Ho An', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_113', nameVi: 'Mã Nhân Hưng', nameEn: 'Ma Nhan Hung', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_114', nameVi: 'Mễ Văn Hựu', nameEn: 'Me Van Huu', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_115', nameVi: 'Nhan Trúc Nhĩ', nameEn: 'Nhan Truc Nhi', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_116', nameVi: 'Ngư Văn Tượng', nameEn: 'Ngu Van Tuong', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_117', nameVi: 'Nhiễm Văn Thâm', nameEn: 'Nhiem Van Tham', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_118', nameVi: 'Quan Thị Lộ', nameEn: 'Quan Thi Lo', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_119', nameVi: 'Sài Văn Chương', nameEn: 'Sai Van Chuong', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_120', nameVi: 'Tăng Văn Hoán', nameEn: 'Tang Van Hoan', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_121', nameVi: 'Thái Văn Cẩn', nameEn: 'Thai Van Can', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_122', nameVi: 'Thẩm Ngự Phong', nameEn: 'Tham Ngu Phong', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_123', nameVi: 'Thượng Quan Uyển', nameEn: 'Thuong Quan Uyen', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_124', nameVi: 'Tuân Tử Khiêm', nameEn: 'Tuan Tu Khiem', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_125', nameVi: 'Âu Văn Cự', nameEn: 'Au Van Cu', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_126', nameVi: 'Cốc Văn Lai', nameEn: 'Coc Van Lai', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_127', nameVi: 'Cát Văn Định', nameEn: 'Cat Van Dinh', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_128', nameVi: 'Cầm Thị Loan', nameEn: 'Cam Thi Loan', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_129', nameVi: 'Can Văn Hy', nameEn: 'Can Van Hy', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_130', nameVi: 'Kha Thị Mị', nameEn: 'Kha Thi Mi', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_131', nameVi: 'Khuê Văn Bách', nameEn: 'Khue Van Bach', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_132', nameVi: 'Lâu Văn Kiến', nameEn: 'Lau Van Kien', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_133', nameVi: 'Lăng Văn Sơ', nameEn: 'Lang Van So', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_134', nameVi: 'Mục Quế Anh', nameEn: 'Muc Que Anh', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_135', nameVi: 'Nguyên Văn Trù', nameEn: 'Nguyen Van Tru', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_136', nameVi: 'Nhiếp Văn Đài', nameEn: 'Nhiep Van Dai', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_137', nameVi: 'Nhược Văn Băng', nameEn: 'Nhuoc Van Bang', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_138', nameVi: 'Ông Văn Đình', nameEn: 'Ong Van Dinh', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_139', nameVi: 'Phàn Văn Sủng', nameEn: 'Phan Van Sung', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_140', nameVi: 'Bồng Văn Xuyến', nameEn: 'Bong Van Xuyen', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_141', nameVi: 'Bạch Văn Cẩm', nameEn: 'Bach Van Cam', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_142', nameVi: 'Bội Văn Dật', nameEn: 'Boi Van Dat', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_143', nameVi: 'Bồ Văn Châm', nameEn: 'Bo Van Cham', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_144', nameVi: 'Bế Thị Quế', nameEn: 'Be Thi Que', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_145', nameVi: 'Bành Văn Tổ', nameEn: 'Banh Van To', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_146', nameVi: 'Bao Văn Sách', nameEn: 'Bao Van Sach', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_147', nameVi: 'Chử Văn Tĩnh', nameEn: 'Chu Van Tinh', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_148', nameVi: 'Dục Văn Long', nameEn: 'Duc Van Long', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_149', nameVi: 'Đới Văn Kỳ', nameEn: 'Doi Van Ky', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_150', nameVi: 'Giải Văn Khanh', nameEn: 'Giai Van Khanh', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_151', nameVi: 'Gia Cát Tĩnh', nameEn: 'Gia Cat Tinh', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_152', nameVi: 'Dạ Văn Cầu', nameEn: 'Da Van Cau', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_153', nameVi: 'Dư Văn Khải', nameEn: 'Du Van Khai', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_154', nameVi: 'Dã Văn Ưng', nameEn: 'Da Van Ung', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_155', nameVi: 'Đậu Văn Thành', nameEn: 'Dau Van Thanh', source: 'ash', hintVi: 'Nửa nét chữ trong đống Tro Xương của tư tế Cuu.', hintEn: 'Half a stroke survives in the bone-ash heap of Priest Cuu.' },
  { id: 'nm_156', nameVi: 'Hòa Văn Phỉ', nameEn: 'Hoa Van Phi', source: 'ash', hintVi: 'Tro Xương nơi tư tế Cuu tế lễ còn giữ vệt mực tên này.', hintEn: 'The bone ash of the rite by Priest Cuu keeps an ink smear of this name.' },
  { id: 'nm_157', nameVi: 'Hành Tử Trúc', nameEn: 'Hanh Tu Truc', source: 'ash', hintVi: 'Giữa xương trắng trong đống tro, người ta đọc tên này rồi quên ngay.', hintEn: 'They read this name among the white bones of the ash heap — and forgot at once.' },
  { id: 'nm_158', nameVi: 'Kinh Văn Mãn', nameEn: 'Kinh Van Man', source: 'ash', hintVi: 'Bảng Tro Xương của tư tế Cuu cháy đúng dòng này.', hintEn: 'The ash tablet of Priest Cuu burned precisely this line.' },
  { id: 'nm_159', nameVi: 'Lệ Văn Điềm', nameEn: 'Le Van Diem', source: 'ash', hintVi: 'Tư tế Cuu quét tro lên cái tên, nhưng tro vẫn nhớ.', hintEn: 'Priest Cuu swept ash over the name, yet the ash remembers.' },
  { id: 'nm_160', nameVi: 'Mẫn Văn Âm', nameEn: 'Man Van Am', source: 'ash', hintVi: 'Một mảnh xương khắc tên này nằm ở đáy Tro Xương.', hintEn: 'A bone shard carved with this name lies at the bottom of the ash heap.' },
  { id: 'nm_161', nameVi: 'Vân Sơ Tuyết', nameEn: 'Van So Tuyet', source: 'night', hintVi: 'Trang sổ mở trong đêm sự kiện đầu ở Làng Thanh Mộc.', hintEn: 'A ledger page opened on the first night event at Thanh Moc village.' },
  { id: 'nm_162', nameVi: 'Trúc Văn Tâm', nameEn: 'Truc Van Tam', source: 'night', hintVi: 'Đêm thứ bảy, một trang sổ nhớ tên này.', hintEn: 'On the seventh night, one ledger page recalled this name.' },
  { id: 'nm_163', nameVi: 'Nguyệt Nhi', nameEn: 'Nguyet Nhi', source: 'night', hintVi: 'Gió đêm đầu lật đúng dòng tên này.', hintEn: 'The first night wind turned to exactly this line.' },
  { id: 'nm_164', nameVi: 'Mộc Văn Lễ', nameEn: 'Moc Van Le', source: 'night', hintVi: 'Trang sổ mở trong đêm sự kiện đầu ở Làng Thanh Mộc.', hintEn: 'A ledger page opened on the first night event at Thanh Moc village.' },
  { id: 'nm_165', nameVi: 'Vọng Nguyệt', nameEn: 'Vong Nguyet', source: 'night', hintVi: 'Đêm thứ bảy, một trang sổ nhớ tên này.', hintEn: 'On the seventh night, one ledger page recalled this name.' },
  { id: 'nm_166', nameVi: 'Hoa Lạc Trần', nameEn: 'Hoa Lac Tran', source: 'night', hintVi: 'Gió đêm đầu lật đúng dòng tên này.', hintEn: 'The first night wind turned to exactly this line.' },
  { id: 'nm_167', nameVi: 'Tô Mạch', nameEn: 'To Mach', source: 'night', hintVi: 'Trang sổ mở trong đêm sự kiện đầu ở Làng Thanh Mộc.', hintEn: 'A ledger page opened on the first night event at Thanh Moc village.' },
  { id: 'nm_168', nameVi: 'Vân Thư', nameEn: 'Van Thu', source: 'night', hintVi: 'Đêm thứ bảy, một trang sổ nhớ tên này.', hintEn: 'On the seventh night, one ledger page recalled this name.' },
  { id: 'nm_169', nameVi: 'Lý Ngư Ca', nameEn: 'Ly Ngu Ca', source: 'night', hintVi: 'Gió đêm đầu lật đúng dòng tên này.', hintEn: 'The first night wind turned to exactly this line.' },
  { id: 'nm_170', nameVi: 'Đinh Hương', nameEn: 'Dinh Huong', source: 'night', hintVi: 'Trang sổ mở trong đêm sự kiện đầu ở Làng Thanh Mộc.', hintEn: 'A ledger page opened on the first night event at Thanh Moc village.' },
  { id: 'nm_171', nameVi: 'Bạch Lộ', nameEn: 'Bach Lo', source: 'night', hintVi: 'Trang sổ đêm thứ hai hé tên này trong bóng đèn lồng.', hintEn: 'The second night page revealed this name by lantern light.' },
  { id: 'nm_172', nameVi: 'Tần Sóc', nameEn: 'Tan Soc', source: 'night', hintVi: 'Đêm mười bốn, mực trang sổ thấm ra tên này.', hintEn: 'On the fourteenth night, the page ink bled into this name.' },
  { id: 'nm_173', nameVi: 'Trúc Mai', nameEn: 'Truc Mai', source: 'night', hintVi: 'Chuông đêm hai rung lên, gọi đúng cái tên này.', hintEn: 'The second night bell rang out precisely this name.' },
  { id: 'nm_174', nameVi: 'Vũ Đới Châm', nameEn: 'Vu Doi Cham', source: 'night', hintVi: 'Trang sổ đêm thứ hai hé tên này trong bóng đèn lồng.', hintEn: 'The second night page revealed this name by lantern light.' },
  { id: 'nm_175', nameVi: 'Hạ Trì', nameEn: 'Ha Tri', source: 'night', hintVi: 'Đêm mười bốn, mực trang sổ thấm ra tên này.', hintEn: 'On the fourteenth night, the page ink bled into this name.' },
  { id: 'nm_176', nameVi: 'Mặc Ngữ', nameEn: 'Mac Ngu', source: 'night', hintVi: 'Chuông đêm hai rung lên, gọi đúng cái tên này.', hintEn: 'The second night bell rang out precisely this name.' },
  { id: 'nm_177', nameVi: 'Tô Vân', nameEn: 'To Van', source: 'night', hintVi: 'Trang sổ đêm thứ hai hé tên này trong bóng đèn lồng.', hintEn: 'The second night page revealed this name by lantern light.' },
  { id: 'nm_178', nameVi: 'Nguyễn Văn Cổ', nameEn: 'Nguyen Van Co', source: 'night', hintVi: 'Đêm mười bốn, mực trang sổ thấm ra tên này.', hintEn: 'On the fourteenth night, the page ink bled into this name.' },
  { id: 'nm_179', nameVi: 'Trần Tích', nameEn: 'Tran Tich', source: 'night', hintVi: 'Chuông đêm hai rung lên, gọi đúng cái tên này.', hintEn: 'The second night bell rang out precisely this name.' },
  { id: 'nm_180', nameVi: 'Thủy Văn Nga', nameEn: 'Thuy Van Nga', source: 'night', hintVi: 'Trang sổ đêm thứ hai hé tên này trong bóng đèn lồng.', hintEn: 'The second night page revealed this name by lantern light.' },
  { id: 'nm_181', nameVi: 'Mạt Hoa', nameEn: 'Mat Hoa', source: 'night', hintVi: 'Trang sổ đêm thứ ba chép tên này bằng nét run.', hintEn: 'The third night page wrote this name in a trembling hand.' },
  { id: 'nm_182', nameVi: 'Trình Tuyết', nameEn: 'Trinh Tuyet', source: 'night', hintVi: 'Đêm hai mươi mốt, khói nhang vẽ hình tên này.', hintEn: 'On the twenty-first night, incense smoke shaped this name.' },
  { id: 'nm_183', nameVi: 'Diệp Trần', nameEn: 'Diep Tran', source: 'night', hintVi: 'Trăng đêm ba soi đúng hàng tên này trong sổ.', hintEn: 'The third night moon lit exactly this row of the ledger.' },
  { id: 'nm_184', nameVi: 'Hàn Y', nameEn: 'Han Y', source: 'night', hintVi: 'Trang sổ đêm thứ ba chép tên này bằng nét run.', hintEn: 'The third night page wrote this name in a trembling hand.' },
  { id: 'nm_185', nameVi: 'Cố Văn Khanh', nameEn: 'Co Van Khanh', source: 'night', hintVi: 'Đêm hai mươi mốt, khói nhang vẽ hình tên này.', hintEn: 'On the twenty-first night, incense smoke shaped this name.' },
  { id: 'nm_186', nameVi: 'Vân Trì Loan', nameEn: 'Van Chi Loan', source: 'night', hintVi: 'Trăng đêm ba soi đúng hàng tên này trong sổ.', hintEn: 'The third night moon lit exactly this row of the ledger.' },
  { id: 'nm_187', nameVi: 'Tạ Vãn', nameEn: 'Ta Van', source: 'night', hintVi: 'Trang sổ đêm thứ ba chép tên này bằng nét run.', hintEn: 'The third night page wrote this name in a trembling hand.' },
  { id: 'nm_188', nameVi: 'Liễu Văn Yên', nameEn: 'Lieu Van Yen', source: 'night', hintVi: 'Đêm hai mươi mốt, khói nhang vẽ hình tên này.', hintEn: 'On the twenty-first night, incense smoke shaped this name.' },
  { id: 'nm_189', nameVi: 'Chúc Lan', nameEn: 'Chuc Lan', source: 'night', hintVi: 'Trăng đêm ba soi đúng hàng tên này trong sổ.', hintEn: 'The third night moon lit exactly this row of the ledger.' },
  { id: 'nm_190', nameVi: 'Tang Văn Miên', nameEn: 'Tang Van Mien', source: 'night', hintVi: 'Trang sổ đêm thứ ba chép tên này bằng nét run.', hintEn: 'The third night page wrote this name in a trembling hand.' },
  { id: 'nm_191', nameVi: 'Tiểu Hàn', nameEn: 'Tieu Han', source: 'night', hintVi: 'Trang sổ đêm cuối cùng khép lại trên tên này.', hintEn: 'The final night page closed over this name.' },
  { id: 'nm_192', nameVi: 'Mộ Vân', nameEn: 'Mo Van', source: 'night', hintVi: 'Đêm hai mươi tám, cái tên này cháy thành tro trắng.', hintEn: 'On the twenty-eighth night, this name burned into white ash.' },
  { id: 'nm_193', nameVi: 'Sử Tương', nameEn: 'Su Tuong', source: 'night', hintVi: 'Sổ khép — còn một dòng, đúng tên này.', hintEn: 'The ledger shut — one line left, this very name.' },
  { id: 'nm_194', nameVi: 'Quỳnh Văn Nhi', nameEn: 'Quynh Van Nhi', source: 'night', hintVi: 'Trang sổ đêm cuối cùng khép lại trên tên này.', hintEn: 'The final night page closed over this name.' },
  { id: 'nm_195', nameVi: 'Ngọc Văn Tiên', nameEn: 'Ngoc Van Tien', source: 'night', hintVi: 'Đêm hai mươi tám, cái tên này cháy thành tro trắng.', hintEn: 'On the twenty-eighth night, this name burned into white ash.' },
  { id: 'nm_196', nameVi: 'Vô Ưu', nameEn: 'Vo Uu', source: 'night', hintVi: 'Sổ khép — còn một dòng, đúng tên này.', hintEn: 'The ledger shut — one line left, this very name.' },
  { id: 'nm_197', nameVi: 'Tạ Kiều', nameEn: 'Ta Kieu', source: 'night', hintVi: 'Trang sổ đêm cuối cùng khép lại trên tên này.', hintEn: 'The final night page closed over this name.' },
  { id: 'nm_198', nameVi: 'Trác Uyên', nameEn: 'Trac Uyen', source: 'night', hintVi: 'Đêm hai mươi tám, cái tên này cháy thành tro trắng.', hintEn: 'On the twenty-eighth night, this name burned into white ash.' },
  { id: 'nm_199', nameVi: 'Cửu Uyên', nameEn: 'Cuu Uyen', source: 'night', hintVi: 'Sổ khép — còn một dòng, đúng tên này.', hintEn: 'The ledger shut — one line left, this very name.' },
  { id: 'nm_200', nameVi: 'Vệ Vô Danh', nameEn: 'Ve Vo Danh', source: 'night', hintVi: 'Dòng cuối cùng của sổ — cái tên đã tự xóa chính mình.', hintEn: 'The ledger last line — the name that erased itself.' },
]

/** Night ledger pages: nm_161..nm_200, ten names per page, one page per night event. */
export const NIGHT_PAGES: Record<NightPageId, string[]> = {
  night_1: ['nm_161', 'nm_162', 'nm_163', 'nm_164', 'nm_165', 'nm_166', 'nm_167', 'nm_168', 'nm_169', 'nm_170'],
  night_2: ['nm_171', 'nm_172', 'nm_173', 'nm_174', 'nm_175', 'nm_176', 'nm_177', 'nm_178', 'nm_179', 'nm_180'],
  night_3: ['nm_181', 'nm_182', 'nm_183', 'nm_184', 'nm_185', 'nm_186', 'nm_187', 'nm_188', 'nm_189', 'nm_190'],
  night_4: ['nm_191', 'nm_192', 'nm_193', 'nm_194', 'nm_195', 'nm_196', 'nm_197', 'nm_198', 'nm_199', 'nm_200'],
}

