import type { NpcDef } from '../engine/content-types'

export const NPCS: NpcDef[] = [
  // ─────────────────────────────────────────────
  // 10 CORE NPCs  ≥ 6 lines each
  // ─────────────────────────────────────────────
  {
    id: 'n_elder_meihua',
    nameVi: 'Cụ Mai Hoa',
    nameEn: 'Elder Meihua',
    roleVi: 'trưởng làng',
    roleEn: 'village elder',
    locationId: 'village',
    greetVi: 'Lớn rồi đấy à? Làng này yên bình, nhưng con đường của con thì không đâu.',
    greetEn: 'A grown child already? This village is quiet, but your road will not be.',
    aliases: ['elder', 'meihua', 'cu mai hoa', 'cụ'],
    lines: [
      // Affinity milestones — affinity is set by doTalk incrementing aff_<id>
      { when: { affMin: 1 }, vi: '“Có vẻ ngươi quay lại rồi. Ít nhất ngươi chưa quên lối vào.”', en: '“You came back. At least you have not forgotten the way in.”' },
      { when: { affMin: 3 }, vi: '“Ta đã thấy nhiều người đi qua cánh cửa ấy. Không phải ai cũng có linh căn phế — nhưng ít người chịu nhìn thẳng vào nó.”', en: '“I have seen many walk through that gate. Not all had a defective root — but few are willing to look straight at theirs.”' },
      { when: { affMin: 6 }, vi: '“Ngươi không vội. Đó là điều hiếm thấy ở người mang linh căn phế. Hãy giữ nó.”', en: '“You are not in a hurry. That is rare in one with a defective root. Keep it.”' },
      { when: { affMin: 9 }, vi: '“Ta đã sống đủ lâu để biết: đường cong có khi đi xa hơn đường thẳng.”', en: '“I have lived long enough to know: the crooked road sometimes outlasts the straight one.”' },
      { when: { dayMin: 15 }, vi: '“Mười lăm ngày rồi. Những cái tên kia vẫn còn đó, ngươi biết chứ?”', en: '“Fifteen days now. Those names are still out there — you know that, do you not?”' },
      { when: { questActive: 'q_herb_delivery' }, vi: '“Linh thảo tươi ấy à? Ba nhánh là đủ. Nhớ hái sáng sớm, khi sương còn đọng.”', en: '“The fresh spirit herbs? Three stalks will do. Pick them at dawn, while the dew still clings.”' },
      { when: { questDone: 'q_herb_delivery' }, vi: '“Thuốc của ta nấu xong rồi. Cả làng sẽ khỏe hơn mùa này — có công ngươi.”', en: '“My tonic is brewed. The village will weather this season better — that is in part your doing.”' },
    ],
  },
  {
    id: 'n_storyteller_ngo',
    nameVi: 'Ngo kể chuyện',
    nameEn: 'Ngo the Storyteller',
    roleVi: 'người kể chuyện',
    roleEn: 'storyteller',
    locationId: 'village',
    greetVi: 'Muốn nghe chuyện một vị tiền bối mang linh căn phế vẫn phi thăng chứ? Ngồi xuống đây.',
    greetEn: 'The tale of the elder with a defective root who still ascended? Sit down, then.',
    aliases: ['storyteller', 'ngo', 'ke chuyen'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi ngồi xuống rồi. Ít nhất đã có ý muốn nghe.”', en: '“You have sat down. That is something — the will to listen.”' },
      { when: { affMin: 3 }, vi: '“Ta kể chuyện không phải để ngươi tin. Ta kể để ngươi nhớ: có người đã đi qua và không quên.”', en: '“I do not tell tales so you believe. I tell so you remember: someone walked this before you and did not forget.”' },
      { when: { affMin: 6 }, vi: '“Có một câu chuyện về một ký ức bị xóa khỏi sổ sách. Ngươi muốn nghe không?”', en: '“There is a story about a memory erased from the register. Would you hear it?”' },
      { when: { affMin: 9 }, vi: '“Ta đã kể hết những gì ta nhớ. Phần còn lại nằm trong nếp giấy mà ngươi phải tự tìm.”', en: '“I have told all I recall. The rest lies in the crease of a page you must find yourself.”' },
      { when: { flag: 'story_name_known' }, vi: '“Cái tên ấy không biến mất — nó chỉ bị gấp lại. Ngươi đã nghe thấy nếp gấp ấy.”', en: '“That name did not vanish — it was merely folded away. You heard the crease.”' },
      { when: { scene: 'cave_witness' }, vi: '“Hang Phong Ấn chứa nhiều hơn một vong hồn. Nó giữ cả một đoạn ký ức bị xé đi.”', en: '“The Sealed Cave holds more than a wandering soul. It keeps a fragment of a torn memory.”' },
    ],
  },
  {
    id: 'n_merchant_bao',
    nameVi: 'Thương nhân Bảo',
    nameEn: 'Merchant Bao',
    roleVi: 'thương nhân',
    roleEn: 'merchant',
    locationId: 'market',
    greetVi: 'Mua bán công bằng, giá đã niêm yết — đừng mặc cả đến sái quai hàm nhé!',
    greetEn: 'Fair trades, posted prices, and no haggling!',
    aliases: ['merchant', 'bao', 'thuong nhan'],
    lines: [
      { when: { affMin: 1 }, vi: '“Khách quen à? Giá vẫn niêm yết, nhưng ta có thể nói chuyện.”', en: '“A repeat customer? Prices stay posted, but I can talk.”' },
      { when: { affMin: 3 }, vi: '“Ngươi có cách nhìn lạ. Thường người ta đến chợ vì tiền — ngươi đến vì cái gì?”', en: '“You have an odd look in your eyes. People come to market for coin — what do you come for?”' },
      { when: { affMin: 6 }, vi: '“Ta đã bán nhiều thứ kỳ lạ, nhưng linh căn phế thì đây là lần đầu gặp người chịu nói thẳng.”', en: '“I have sold stranger things, but a defective root willing to speak plainly? First time.”' },
      { when: { affMin: 9 }, vi: '“Nếu ngươi cần bản đồ hay phù hiệu — ta có. Giá tốt cho người không hỏi quá nhiều.”', en: '“If you need maps or wards — I have them. Fair price for someone who does not ask too many questions.”' },
      { when: { flag: 'story_bao_has_map' }, vi: '“Bản đồ kia à? Nó không dẫn đến kho báu. Nó dẫn đến một sự thật mà người ta muốn giấu.”', en: '“That map? It does not lead to treasure. It leads to a truth someone wanted hidden.”' },
      { when: { questActive: 'q_talisman_order' }, vi: '“Bùa trừ tà ấy à? Một cái thôi, và nó phải thật sự hoạt động — ta không bán đồ giả.”', en: '“The warding talisman? One, and it must actually work — I do not sell counterfeits.”' },
    ],
  },
  {
    id: 'n_hermit_coc',
    nameVi: 'Cốc chủ Cốc',
    nameEn: 'Hermit Coc',
    roleVi: 'ẩn sĩ hang đá',
    roleEn: 'cave hermit',
    locationId: 'sealed_cave',
    greetVi: 'Ấn cũ yếu rồi. Mang bùa hoặc mang vận may, chọn đi.',
    greetEn: 'The old seal weakens. Bring a talisman or bring luck. Choose.',
    aliases: ['hermit', 'coc', 'an si'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi vào hang này mà không mang bùa. Dũng cảm hoặc ngốc — ta chưa phân biệt được.”', en: '“You enter this cave without a talisman. Brave or foolish — I have not yet decided which.”' },
      { when: { affMin: 3 }, vi: '“Ta đã sống trong phong ấn này ba mươi năm. Ta nhìn thấy nhiều người vào, và biết ai sẽ ra.”', en: '“I have lived inside this seal for thirty years. I have seen many enter, and I know who will leave.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có linh căn phế. Điều đó không phải lỗi — đó là dấu hiệu.”', en: '“You have a defective root. That is not a flaw — it is a sign.”' },
      { when: { affMin: 9 }, vi: '“Ta sẽ dạy ngươi một đường vận khí. Nó không giống sách nào — nó giống ngươi.”', en: '“I will teach you one circulation path. It follows no textbook — it follows you.”' },
      { when: { dayMin: 20 }, vi: '“Hai mươi ngày. Khe nứt kia đã rộng hơn. Ngươi có cảm nhận được không?”', en: '“Twenty days. That rift has widened. Can you feel it?”' },
      { when: { flag: 'story_ha_bound' }, vi: '“Hà đã đồng ý giúp ngươi. Nhưng đừng gọi cô ấy là vũ khí — cô ấy là một người đã chọn.”', en: '“Ha agreed to help you. But do not call her a weapon — she is someone who chose.”' },
      { when: { flag: 'crooked_circulation' }, vi: '“Ngươi vận công theo sách của ta. Cong queo, sai sách vở — và đúng với ngươi hơn bất kỳ đường thẳng nào.”', en: '“You circulate by my book. Crooked, wrong by every rule — and truer to you than any straight meridian.”' },
    ],
  },
  {
    id: 'n_rival_khoa',
    nameVi: 'Sư đệ Khoa',
    nameEn: 'Rival Khoa',
    roleVi: 'sư đệ cạnh tranh',
    roleEn: 'rival junior brother',
    locationId: 'sect',
    greetVi: 'Linh căn khuyết? Ba tháng nữa ta cho ngươi xem thế nào là thiên tài.',
    greetEn: 'A defective root? Give me three months to show you what genius looks like.',
    aliases: ['rival', 'khoa', 'su de'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi lại đến. Lần này mang bùa chưa?”', en: '“You again. Got a talisman this time?”' },
      { when: { affMin: 3 }, vi: '“Ta không hiểu ngươi. Ngươi có linh căn phế mà không từ bỏ — đó là điều ta không tính được.”', en: '“I do not understand you. You have a defective root yet do not quit — that is something I cannot compute.”' },
      { when: { affMin: 6 }, vi: '“Ta đã luyện ngày đêm. Nhưng ngươi vẫn đứng đây. Đáng ghét.”', en: '“I have trained day and night. Yet you still stand here. Irritating.”' },
      { when: { affMin: 9 }, vi: '“Ta không cần thắng ngươi. Ta cần biết chúng ta đang bảo vệ ai — ngươi có thể nói thật không?”', en: '“I do not need to beat you. I need to know whom we are protecting — can you tell me the truth?”' },
      { when: { scene: 'mirror_choice' }, vi: '“Ta ghét ngươi vì ngươi bỏ chạy, không phải vì linh căn của ngươi. Nếu ngươi dám nói thật, ta sẽ đứng đây nghe.”', en: '“I hate that you ran, not your crooked root. If you dare tell the truth, I will stand here and hear it.”' },
      { when: { flag: 'story_khoa_trusted' }, vi: '“Ta đã nghe hết. Bây giờ ta biết vì sao ngươi chọn như vậy.”', en: '“I heard everything. Now I know why you chose as you did.”' },
    ],
  },
  {
    id: 'n_master_vo',
    nameVi: 'Võ Trưởng Sư',
    nameEn: 'Master Vo',
    roleVi: 'trưởng sư tông môn',
    roleEn: 'sect master',
    locationId: 'sect',
    greetVi: 'Linh căn của ngươi lệch. Vậy thì đi một con đường khác. Đường nào cũng có thể lên đỉnh.',
    greetEn: 'Your root is crooked. Then walk the crooked path. All paths reach the peak.',
    aliases: ['master', 'vo', 'truong su'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đến tìm ta? Không phải để xin lòng thương — ta thấy.”', en: '“You come to me? Not to beg for sympathy — I can see that.”' },
      { when: { affMin: 3 }, vi: '“Ta đã xóa ký ức của cả làng vì sợ họ chết vì nó. Ngươi có muốn biết tại sao?”', en: '“I erased the village memory because I feared it would kill them. Do you want to know why?”' },
      { when: { affMin: 6 }, vi: '“Phá Phong Trảm là công pháp ta giữ lại từ kiếp trước. Nó không chém để giết — nó chém để chứng minh.”', en: '“Peak-Cleaving Strike is the technique I kept from my past life. It does not swing to kill — it swings to prove.”' },
      { when: { affMin: 9 }, vi: '“Ta sẽ cho ngươi xem chiếc gương. Nhưng hãy chắc rằng ngươi không chỉ muốn được tha thứ.”', en: '“I will show you the mirror. But be sure you do not only want forgiveness.”' },
      { when: { questActive: 'q_sealed_cave' }, vi: '“Hang Phong Ấn đang mở ra. Hãy mang bùa hộ thân — ta không muốn mất thêm đệ tử.”', en: '“The Sealed Cave is opening. Carry a ward — I do not wish to lose another disciple.”' },
      { when: { flag: 'story_vo_exposed' }, vi: '“Ngươi đã để lộ sự thật. Giờ ta phải đối mặt với những gì ta đã giấu.”', en: '“You have exposed the truth. Now I must face what I hid.”' },
    ],
  },
  {
    id: 'n_lost_soul_ha',
    nameVi: 'Vong hồn Hà',
    nameEn: 'Lost Soul Ha',
    roleVi: 'vong hồn lang thang',
    roleEn: 'wandering shade',
    locationId: 'sealed_cave',
    greetVi: 'Người sống vào đây... hiếm. Người sống ra được... hiếm hơn.',
    greetEn: 'The living who enter... are rare. The living who leave... rarer.',
    aliases: ['soul', 'ha', 'vong hon'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi nhìn thấy ta. Điều đó... không bình thường.”', en: '“You see me. That is... not normal.”' },
      { when: { affMin: 3 }, vi: '“Ta đã chết để đưa ai đó thoát khỏi kiếp trước. Ngươi... có ký ức gì không?”', en: '“I died to get someone out of the last life. You... do you remember anything?”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang linh căn phế. Giống người ta đã cứu. Có lẽ không phải trùng hợp.”', en: '“You have a defective root. Like the one I saved. Perhaps not coincidence.”' },
      { when: { affMin: 9 }, vi: '“Ta đồng ý nhập vào bùa. Nhưng hãy nhớ: một lời hứa biến thành món nợ.”', en: '“I will enter the talisman. But remember: a promise becomes a debt.”' },
      { when: { flag: 'story_ha_bound' }, vi: '“Ta đang ở trong bùa rồi. Bây giờ ngươi dẫn ta đi — đừng quên điều ngươi đã hứa.”', en: '“I am in the talisman now. Lead me now — do not forget what you promised.”' },
      { when: { dayMin: 10 }, vi: '“Mười ngày rồi. Gió trong hang lạnh hơn. Phong ấn đang yếu đi.”', en: '“Ten days now. The cave wind grows colder. The seal is weakening.”' },
    ],
  },
  {
    id: 'n_innkeeper_hanh',
    nameVi: 'Chủ quán Hạnh',
    nameEn: 'Innkeeper Hanh',
    roleVi: 'chủ quán trọ',
    roleEn: 'innkeeper',
    locationId: 'village',
    greetVi: 'Quán còn một giường. Ngủ cho yên, tu hành mới không loạn nhịp.',
    greetEn: 'One bed left. Sleep well and cultivation comes easier.',
    aliases: ['innkeeper', 'hanh', 'chu quan'],
    lines: [
      { when: { affMin: 1 }, vi: '“Lại ngươi. Giường vẫn còn — lần này trả tiền đàng hoàng nhé.”', en: '“You again. Bed is still available — pay properly this time.”' },
      { when: { affMin: 3 }, vi: '“Ngươi tu hành mà vẫn ngủ muộn. Linh căn phế hay không, ngủ đủ giấc đi.”', en: '“You cultivate yet sleep late. Defective root or not, get your rest.”' },
      { when: { affMin: 6 }, vi: '“Ta đã thấy nhiều người đi qua cánh cửa này. Ngươi khác — ngươi quay lại.”', en: '“I have seen many walk through that door. You are different — you come back.”' },
      { when: { affMin: 9 }, vi: '“Nếu ngươi cần giữ đồ — kho của ta rộng hơn bụng ngươi. Không phí.”', en: '“If you need to store things — my storage outlasts your carry. No charge.”' },
      { when: { dayMin: 10 }, vi: '“Mười ngày rồi. Người ta bắt đầu nhắc đến cái tên kia — ngươi có nghe không?”', en: '“Ten days now. People have begun mentioning that name — have you heard it?”' },
      { when: { questActive: 'q_herb_delivery' }, vi: '“Nghe nói cụ Mai Hoa cần linh thảo. Ruộng ở ngoài làng, đi sớm kẻo nắng.”', en: '“I hear Elder Meihua needs spirit herbs. The plots are outside the village, go early before the sun climbs.”' },
    ],
  },
  {
    id: 'n_alchemist_sam',
    nameVi: 'Luyện dược Sâm',
    nameEn: 'Alchemist Sam',
    roleVi: 'luyện dược sư',
    roleEn: 'alchemist',
    locationId: 'sect',
    greetVi: 'Lò đan nổ lần thứ bảy rồi. Rõ ràng có tiến bộ so với lần thứ sáu.',
    greetEn: 'Seventh furnace explosion this month. Clear progress over number six.',
    aliases: ['alchemist', 'sam', 'luyen duoc'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đến xem nổ à? Lần này ta đặt bùa chắn ở hai phía rồi.”', en: '“Come to watch another explosion? I placed barriers on two sides this time.”' },
      { when: { affMin: 3 }, vi: '“Ta nổ nhiều vì ta thử nhiều thứ. Những người khác sợ nổ — họ giữ công thức cũ.”', en: '“I explode often because I try often. Others fear explosion — they keep old formulas.”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang linh căn phế. Biết không? Linh thảo có thể bù lại cái gì đó — ta chưa chứng minh, nhưng ta nghi ngờ.”', en: '“You have a defective root. You know? Herbs can compensate for something — I have not proven it, but I suspect.”' },
      { when: { affMin: 9 }, vi: '“Ta sắp thành công rồi. Lần nổ tiếp theo sẽ không phải nổ — sẽ là một đan dược thật sự.”', en: '“I am close to success. The next furnace event will not be an explosion — it will be a real elixir.”' },
      { when: { questActive: 'q_herb_delivery' }, vi: '“Linh thảo ấy à? Ta cần loại tươi, hái sáng sớm khi linh khí còn đọng.”', en: '“Those spirit herbs? I need fresh ones, picked at dawn when the qi still clings.”' },
      { when: { flag: 'story_sealed_cave_visited' }, vi: '“Ngươi vào hang rồi? Mang về được gì không? Ta trao đổi.”', en: '“You entered the cave? Bring back anything? I trade.”' },
    ],
  },
  {
    id: 'n_hunter_son',
    nameVi: 'Thợ săn Sơn',
    nameEn: 'Hunter Son',
    roleVi: 'thợ săn',
    roleEn: 'hunter',
    locationId: 'misty_forest',
    greetVi: 'Trong rừng này, kẻ ồn ào về trước. Kẻ im lặng về sau.',
    greetEn: 'In these woods the loud leave first. The silent leave last.',
    aliases: ['hunter', 'son', 'tho san'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi vào rừng mà không mang dao. Dũng cảm — hoặc muốn làm mồi.”', en: '“You enter the woods without a blade. Brave — or hungry for trouble.”' },
      { when: { affMin: 3 }, vi: '“Ta đã đi rừng này hai mươi năm. Linh thảo mọc ở chỗ ít người nhìn thấy — ngươi cần dấu chân nhẹ.”', en: '“I have walked these woods for twenty years. Spirit herbs grow where few look — you need a light foot.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có linh căn phế. Nó không giữ khí — nhưng nó nhạy với đất. Ngươi sẽ thấy những thứ khác không thấy.”', en: '“You have a defective root. It does not hold qi — but it is sensitive to the earth. You will see what others miss.”' },
      { when: { affMin: 9 }, vi: '“Ta đã thấy thứ trong rừng mà ta không thể giết. Ngươi có thể cảm nhận nó không?”', en: '“I have seen things in these woods that I cannot kill. Can you feel them?”' },
      { when: { flag: 'defeated_mist_boar' }, vi: '“Con lợn sương kia à? Ngươi đánh bại nó. Ta không nghĩ ngươi làm được.”', en: '“That mist boar? You beat it. I did not think you could.”' },
      { when: { dayMin: 5 }, vi: '“Năm ngày rồi. Dấu chân trong rừng có nhiều thứ lạ. Ngươi cẩn thận.”', en: '“Five days. Footprints in the forest have changed. Watch yourself.”' },
    ],
  },

  // ─────────────────────────────────────────────
  // 20 SUPPORTING NPCs  ≥ 3 lines each
  // ─────────────────────────────────────────────
  {
    id: 'n_guard_truong',
    nameVi: 'Dân binh Trường',
    nameEn: 'Guard Truong',
    roleVi: 'dân binh',
    roleEn: 'militia guard',
    locationId: 'village',
    greetVi: 'Giữ trật tự nhé. Đêm nay có sương, đi xa nhớ mang bùa.',
    greetEn: 'Keep the peace. Mist tonight; carry a ward if you wander far.',
    aliases: ['guard', 'truong', 'dan binh'],
    lines: [
      { when: { affMin: 1 }, vi: '“Lại đi đâu đấy? Đừng ra ngoài làng khi trời tối.”', en: '“Going somewhere? Do not leave the village after dark.”' },
      { when: { affMin: 3 }, vi: '“Ngươi không phải kẻ gây rối. Ta thấy. Cứ đi đi — nhưng mang bùa.”', en: '“You are not the troublemaking kind. I can tell. Go on — but carry a ward.”' },
      { when: { affMin: 6 }, vi: '“Đêm thứ mười hai sắp đến. Ta đã đặt bùa ở cổng làng. Ngươi biết chuyện gì xảy ra chứ?”', en: '“The twelfth night approaches. I have placed wards at the village gate. You know what happens, do you not?”' },
    ],
  },
  {
    id: 'n_kid_xiaobao',
    nameVi: 'Tiểu Bảo',
    nameEn: 'Xiaobao',
    roleVi: 'đứa trẻ tinh nghịch',
    roleEn: 'mischievous kid',
    locationId: 'village',
    greetVi: 'Anh tu tiên ơi, anh bay được chưa? Bay lên cho em xem với!',
    greetEn: 'Hey mister cultivator, can you fly yet? Fly for me, just a little!',
    aliases: ['kid', 'xiaobao', 'tieu bao', 'child'],
    lines: [
      { when: { affMin: 1 }, vi: '“Anh ơi! Anh có thể biến thành chim không? Em muốn xem!”', en: '“Hey mister! Can you turn into a bird? I wanna see!”' },
      { when: { affMin: 3 }, vi: '“Bà Mai Hoa bảo anh có linh căn lạ. Lạ là gì vậy? Giống kẹo không?”', en: '“Grandma Meihua says you have a weird root. What is weird? Like candy weird?”' },
      { when: { affMin: 6 }, vi: '“Em thấy bà khóc một mình đêm qua. Anh có biết chuyện gì không?”', en: '“I saw Grandma crying alone last night. Do you know what happened?”' },
    ],
  },
  {
    id: 'n_farmer_tu',
    nameVi: 'Nông phu Tư',
    nameEn: 'Farmer Tu',
    roleVi: 'nông phu',
    roleEn: 'farmer',
    locationId: 'village',
    greetVi: 'Ruộng linh thảo năm nay tốt lắm. Đi khẽ thôi, đừng giẫm nát mầm non.',
    greetEn: 'Herb terraces are generous this year. Mind the corn on your way.',
    aliases: ['farmer', 'tu', 'nong phu'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ruộng này không phải đường. Đi nhẹ chân.”', en: '“These fields are not a road. Walk lightly.”' },
      { when: { affMin: 3 }, vi: '“Ngươi muốn hái linh thảo? Ba nhánh tươi, hái buổi sáng. Cây biết ơn người nhẹ tay.”', en: '“You want spirit herbs? Three fresh stalks, pick in the morning. The plants remember the gentle hand.”' },
      { when: { affMin: 6 }, vi: '“Ta thấy cụ Mai Hoa lo lắng gần đây. Chắc chuyện gì đó không hay.”', en: '“I have seen Elder Meihua worried lately. Something unpleasant is surely afoot.”' },
    ],
  },
  {
    id: 'n_fortune_lien',
    nameVi: 'Bà đồng Liên',
    nameEn: 'Fortune Lien',
    roleVi: 'bói vé số',
    roleEn: 'lottery seer',
    locationId: 'market',
    greetVi: 'Một ngày một lượt thôi con, trời cũng cần ngủ mà.',
    greetEn: 'One draw a day, child; even Heaven needs its sleep.',
    aliases: ['fortune', 'lien', 'ba dong', 'lottery'],
    lines: [
      { when: { affMin: 1 }, vi: '“Một lượt thôi nhé. Số mệnh không thể vặn nhiều lần trong một ngày.”', en: '“One draw only. Fate cannot be twisted more than once a day.”' },
      { when: { affMin: 3 }, vi: '“Ngươi mang linh căn phế. Điều đó có nghĩa là ngươi không thuộc về một con đường định sẵn.”', en: '“You have a defective root. That means you do not belong to a predestined road.”' },
      { when: { affMin: 6 }, vi: '“Ta thấy ngươi trong tấm vé số — không phải số trúng, mà là con đường phía trước.”', en: '“I see you in the lottery ticket — not the winning number, but the road ahead.”' },
    ],
  },
  {
    id: 'n_cook_phung',
    nameVi: 'Đầu bếp Phụng',
    nameEn: 'Cook Phung',
    roleVi: 'đầu bếp',
    roleEn: 'cook',
    locationId: 'market',
    greetVi: 'Bánh bao nóng đây! Bụng đói thì lấy đâu sức mà tu tiên?',
    greetEn: 'Hot steamed buns! Cultivate on an empty stomach, will you?',
    aliases: ['cook', 'phung', 'dau bep'],
    lines: [
      { when: { affMin: 1 }, vi: '“Bánh bao nóng! Một đồng hai cái, không mặc cả.”', en: '“Hot buns! One coin for two, no haggling.”' },
      { when: { affMin: 3 }, vi: '“Ngươi gầy quá. Tu hành mà không ăn no thì khí không lên được.”', en: '“You are too thin. Cultivation without a full belly means qi will not rise.”' },
      { when: { affMin: 6 }, vi: '“Mùi bánh bao có thể thu hút ai đó bất ngờ. Ngươi có gặp ai gần đây không?”', en: '“The smell of steamed buns can attract someone unexpected. Have you met anyone nearby?”' },
    ],
  },
  {
    id: 'n_smith_duc',
    nameVi: 'Thợ rèn Đức',
    nameEn: 'Smith Duc',
    roleVi: 'thợ rèn',
    roleEn: 'blacksmith',
    locationId: 'market',
    greetVi: 'Lửa này tôi giữ ba chục năm rồi, chưa bỏ cuộc lần nào.',
    greetEn: 'I have kept this forge thirty years; it has never seen me quit.',
    aliases: ['smith', 'duc', 'tho ren'],
    lines: [
      { when: { affMin: 1 }, vi: '“Cần dao? Cần bùa? Lửa không nói dối.”', en: '“Need a blade? Need a ward? Fire does not lie.”' },
      { when: { affMin: 3 }, vi: '“Linh căn phế không ảnh hưởng đến việc rèn. Thép không phân biệt — nó chỉ biết lửa và tay.”', en: '“A defective root does not affect forging. Steel does not discriminate — it only knows fire and hand.”' },
      { when: { affMin: 6 }, vi: '“Ta đã rèn bùa cho cả làng. Cái nào cũng hoạt động — miễn là người mang nó không sợ.”', en: '“I have forged wards for the whole village. Every one works — as long as the bearer does not fear.”' },
    ],
  },
  {
    id: 'n_scholar_minh',
    nameVi: 'Học giả Minh',
    nameEn: 'Scholar Minh',
    roleVi: 'học giả',
    roleEn: 'scholar',
    locationId: 'market',
    greetVi: 'Linh căn phế ư? Cứ gọi là "linh căn khác biệt" cho thuận tai.',
    greetEn: 'Defective root? Let us say "unconventional root" instead.',
    aliases: ['scholar', 'minh', 'hoc gia'],
    lines: [
      { when: { affMin: 1 }, vi: '“Linh căn của ngươi không lệch — nó chỉ đi đường riêng.”', en: '“Your root is not crooked — it simply takes a different road.”' },
      { when: { affMin: 3 }, vi: '“Ta đã đọc sáu mươi quyển cổ về tu tiên. Không quyển nào nói linh căn phế là kết thúc.”', en: '“I have read sixty ancient texts on cultivation. Not one says a defective root is the end.”' },
      { when: { affMin: 6 }, vi: '“Có một cuốn sách ở Thanh Vân Các nói về những người như ngươi. Ta có thể dẫn đường.”', en: '“There is a book at the Azure Pavilion about people like you. I can show you the way.”' },
    ],
  },
  {
    id: 'n_pedlar_quyen',
    nameVi: 'Hàng rong Quyền',
    nameEn: 'Pedlar Quyen',
    roleVi: 'hàng rong',
    roleEn: 'pedlar',
    locationId: 'market',
    greetVi: 'Mua vé số không? Không thì xem ngọc bội mới về sáng nay.',
    greetEn: 'Lottery ticket? No? Then jade charms, fresh off this morning cart.',
    aliases: ['pedlar', 'quyen', 'hang rong'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngọc bội mới! Bảo hộ cho người đi đường xa.”', en: '“New jade charms! Protection for the long road ahead.”' },
      { when: { affMin: 3 }, vi: '“Ta bán nhiều thứ — ngọc, vé, tin đồn. Tin đồn là rẻ nhất và đắt nhất.”', en: '“I sell many things — jade, tickets, rumors. Rumors are cheapest and costliest.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có vẻ cần một lời định hướng. Ta nghe được nhiều thứ ở chợ.”', en: '“You seem to need guidance. I hear many things at the market.”' },
    ],
  },
  {
    id: 'n_tea_ma',
    nameVi: 'Bà Ma trà quán',
    nameEn: 'Tea Granny Ma',
    roleVi: 'bà chủ quán trà',
    roleEn: 'tea house owner',
    locationId: 'market',
    greetVi: 'Trà nóng một ấm, tin đồn một đĩa. Ăn cả hai nhé?',
    greetEn: 'One pot of hot tea, one plate of rumors. Take both?',
    aliases: ['tea', 'ma', 'tra quan'],
    lines: [
      { when: { affMin: 1 }, vi: '“Trà nóng. Ngồi xuống — có chuyện hay để kể.”', en: '“Hot tea. Sit down — there are good stories to tell.”' },
      { when: { affMin: 3 }, vi: '“Cứ mười hai năm, dân làng lại quên một người. Đêm nay là đêm thứ mười hai.”', en: '“Every twelve years the village forgets one person. Tonight is the twelfth night.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có nghe kể về một linh căn phế đã phi thăng không? Ngô có thể kể — ông ấy ngồi ở góc kia.”', en: '“Have you heard the tale of the defective root who ascended? Ngo can tell — he sits in that corner.”' },
    ],
  },
  {
    id: 'n_tailor_yen',
    nameVi: 'Thợ may Yến',
    nameEn: 'Tailor Yen',
    roleVi: 'thợ may',
    roleEn: 'tailor',
    locationId: 'market',
    greetVi: 'Áo tu hành rách khuỷu rồi kìa. Để ta vá cho gọn gàng nhé?',
    greetEn: 'Your robe is fraying at the elbow. Let me fold it into style.',
    aliases: ['tailor', 'yen', 'tho may'],
    lines: [
      { when: { affMin: 1 }, vi: '“Áo ngươi rách khuỷu. Đừng để tuổi trẻ mặc áo nghèo.”', en: '“Your robe is frayed at the elbow. Do not let youth wear poverty.”' },
      { when: { affMin: 3 }, vi: '“Ta có thể vá áo để ngươi trông có vẻ hơn. Không phải trong mắt người khác — trong mắt chính ngươi.”', en: '“I can mend your robe so you look better. Not in others\' eyes — in your own.”' },
      { when: { affMin: 6 }, vi: '“Ngươi tu hành mà áo không xứng. Để ta giúp — lần này không lấy tiền.”', en: '“You cultivate yet your robe does not match. Let me help — this time I will not charge.”' },
    ],
  },
  {
    id: 'n_senior_lan',
    nameVi: 'Sư tỷ Lan',
    nameEn: 'Senior Lan',
    roleVi: 'sư tỷ',
    roleEn: 'senior sister',
    locationId: 'sect',
    greetVi: 'Kinh nghiệm của tỷ: đừng luyện khi đang giận. Rất đau.',
    greetEn: 'Senior wisdom: never train while angry. It hurts. A lot.',
    aliases: ['senior', 'lan', 'su ty'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi mới à? Luyện ở sân phía đông, đừng động vào lò đan của Sâm.”', en: '“New here? Train in the east court, do not touch Sam\'s furnace.”' },
      { when: { affMin: 3 }, vi: '“Sư phụ Võ nói ngươi có linh căn phế. Điều đó không quan trọng — quan trọng là ngươi không bỏ cuộc.”', en: '“Master Vo says you have a defective root. That does not matter — what matters is you do not quit.”' },
      { when: { affMin: 6 }, vi: '“Ta đã thấy nhiều đệ tử. Ngươi có thứ không ai có — sự kiên nhẫn.”', en: '“I have seen many disciples. You have something no one else does — patience.”' },
    ],
  },
  {
    id: 'n_keeper_anh',
    nameVi: 'Quản kho Ánh',
    nameEn: 'Keeper Anh',
    roleVi: 'quản lý nhà kho',
    roleEn: 'warehouse keeper',
    locationId: 'sect',
    greetVi: 'Nhà kho chỉ chứa được năm chục món. Nhiều hơn thì phải ký giấy, nét mực không nhẹ đâu.',
    greetEn: 'Storage holds fifty items. More than that needs paperwork.',
    aliases: ['keeper', 'anh', 'quan kho', 'storage'],
    lines: [
      { when: { affMin: 1 }, vi: '“Gửi đồ à? Năm chục món, nhiều hơn thì ký giấy.”', en: '“Storing something? Fifty items, more requires paperwork.”' },
      { when: { affMin: 3 }, vi: '“Ngươi mang gì vào kho? Ta phải ghi lại. Luật của tông môn.”', en: '“What are you storing? I must log it. Sect rules.”' },
      { when: { affMin: 6 }, vi: '“Ta đã giữ đồ cho nhiều đệ tử. Ngươi là người ít phiền nhất.”', en: '“I have kept things for many disciples. You are the least troublesome one.”' },
    ],
  },
  {
    id: 'n_monk_thien',
    nameVi: 'Sa môn Thiện',
    nameEn: 'Monk Thien',
    roleVi: 'sa môn',
    roleEn: 'monk',
    locationId: 'sect',
    greetVi: 'Hôm nay ngươi đã uống nước chưa? Uống được một ngụm đã là phúc rồi.',
    greetEn: 'Have you drunk water today? If yes, that is already fortune.',
    aliases: ['monk', 'thien', 'sa mon'],
    lines: [
      { when: { affMin: 1 }, vi: '“Nước có ở đây. Uống trước khi nói chuyện.”', en: '“Water is here. Drink before speaking.”' },
      { when: { affMin: 3 }, vi: '“Ta không nói nhiều. Nhưng ta nghe — và ta nhớ.”', en: '“I do not speak much. But I listen — and I remember.”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang linh căn phế. Điều đó có nghĩa ngươi không bị ràng buộc bởi những kỳ vọng.”', en: '“You have a defective root. That means you are not bound by expectations.”' },
    ],
  },
  {
    id: 'n_herbalist_dan',
    nameVi: 'Dược sư Đàn',
    nameEn: 'Herbalist Dan',
    roleVi: 'dược sư ruộng thuốc',
    roleEn: 'terrace herbalist',
    locationId: 'herb_field',
    greetVi: 'Hái nhẹ tay, cây biết ơn lắm. Hái xấu tay, cây biết luôn.',
    greetEn: 'Pick gently and the plants remember kindly. Pick roughly, they remember too.',
    aliases: ['herbalist', 'dan', 'duoc su'],
    lines: [
      { when: { affMin: 1 }, vi: '“Cây này sống được vì ta không vội vàng. Ngươi cũng vậy đi.”', en: '“These plants live because I am not in a hurry. Try being the same.”' },
      { when: { affMin: 3 }, vi: '“Linh thảo mọc nơi ít người nhìn. Ngươi có đôi mắt để thấy những gì người khác bỏ qua.”', en: '“Spirit herbs grow where few look. You have eyes to see what others miss.”' },
      { when: { affMin: 6 }, vi: '“Ta đã trồng cây này hai mươi năm. Nó biết ai chăm sóc nó. Ngươi có vẻ như người chăm sóc.”', en: '“I have grown this plant for twenty years. It knows who tends it. You look like someone who tends.”' },
    ],
  },
  {
    id: 'n_gatherer_hue',
    nameVi: 'Thợ hái Huệ',
    nameEn: 'Gatherer Hue',
    roleVi: 'thợ hái',
    roleEn: 'herb gatherer',
    locationId: 'herb_field',
    greetVi: 'Sáng nay sương ngọt, linh thảo thơm hơn mọi ngày.',
    greetEn: 'Sweet dew this morning; the spirit herbs smell better than ever.',
    aliases: ['gatherer', 'hue', 'tho hai'],
    lines: [
      { when: { affMin: 1 }, vi: '“Sương sớm là tốt nhất. Đi sớm, về sớm, còn cả ngày.”', en: '“Morning dew is best. Go early, come back early, have the day left.”' },
      { when: { affMin: 3 }, vi: '“Ta đã hái linh thảo ba mươi năm. Ta biết chỗ nào tốt — và không nói ai.”', en: '“I have gathered spirit herbs for thirty years. I know the good spots — and tell no one.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có vẻ không vội vàng. Đó là đức tính tốt cho người hái thảo.”', en: '“You do not seem to be in a hurry. That is a good trait for a herb gatherer.”' },
    ],
  },
  {
    id: 'n_ox_cart_hien',
    nameVi: 'Xe bò Hiền',
    nameEn: 'Ox-Cart Hien',
    roleVi: 'phu xe',
    roleEn: 'cart driver',
    locationId: 'herb_field',
    greetVi: 'Đi bộ tới chợ mỏi chân không? Con bò này còn biết cười cơ đấy.',
    greetEn: 'Tired of walking to market? This ox knows how to smile.',
    aliases: ['cart', 'hien', 'xe bo'],
    lines: [
      { when: { affMin: 1 }, vi: '“Cần chuyến xe? Đi chợ hay về làng?”', en: '“Need a ride? To market or back to the village?”' },
      { when: { affMin: 3 }, vi: '“Con bò này tên là Đào. Nó không phải bò thường — nó nhớ đường.”', en: '“This ox is named Dao. He is not an ordinary ox — he remembers the way.”' },
      { when: { affMin: 6 }, vi: '“Ta chở nhiều người lạ. Ngươi là người ít nói nhất — ta thích.”', en: '“I have carried many strangers. You are the quietest — I like that.”' },
    ],
  },
  {
    id: 'n_woodcutter_bong',
    nameVi: 'Tiều phu Bồng',
    nameEn: 'Woodcutter Bong',
    roleVi: 'tiều phu',
    roleEn: 'woodcutter',
    locationId: 'misty_forest',
    greetVi: 'Cây này tôi không chặt. Nó nói chuyện trong mơ của tôi.',
    greetEn: 'I do not cut this tree. It talks in my dreams.',
    aliases: ['woodcutter', 'bong', 'tieu phu'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi vào rừng sâu rồi. Cẩn thận những thứ không có tên.”', en: '“You have come deep into the forest. Beware of things without names.”' },
      { when: { affMin: 3 }, vi: '“Ta chặt cây ba mươi năm. Chỉ có một cây ta không chạm — nó nói trong giấc mơ của ta.”', en: '“I have cut trees for thirty years. Only one I never touch — it speaks in my dreams.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có linh căn phế. Có lẽ ngươi cũng nghe được điều ta nghe.”', en: '“You have a defective root. Perhaps you can hear what I hear too.”' },
    ],
  },
  {
    id: 'n_exile_ba',
    nameVi: 'Kẻ lưu đày Bá',
    nameEn: 'Exile Ba',
    roleVi: 'kẻ lưu đày',
    roleEn: 'exile',
    locationId: 'cursed_rift',
    greetVi: 'Đừng lại gần khe nứt. Ta đã đứng đây đủ lâu để biết.',
    greetEn: 'Stay away from the rift. I have stood here long enough to know.',
    aliases: ['exile', 'ba', 'luu day'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đến khe nứt này à? Không phải du khách. Ngươi đến vì điều gì?”', en: '“You come to this rift? Not a tourist. What do you come for?”' },
      { when: { affMin: 3 }, vi: '“Ta đã bị lưu đày ở đây mười năm. Khe nứt lấy đi nhiều thứ — ký ức, tên, hy vọng.”', en: '“I have been exiled here ten years. The rift takes many things — memory, name, hope.”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang linh căn phế. Có lẽ ngươi cũng mang thứ gì đó bị lấy đi.”', en: '“You have a defective root. Perhaps you also carry something that was taken.”' },
    ],
  },
  {
    id: 'n_exorcist_diem',
    nameVi: 'Trừ tà Diễm',
    nameEn: 'Exorcist Diem',
    roleVi: 'trừ tà sư',
    roleEn: 'exorcist',
    locationId: 'cursed_rift',
    greetVi: 'Việc ở đây chưa xong. Nhưng trà thì hết rồi.',
    greetEn: 'My work here is unfinished. My tea, however, is finished.',
    aliases: ['exorcist', 'diem', 'tru ta'],
    lines: [
      { when: { affMin: 1 }, vi: '“Khe nứt này không phải nơi dành cho người yếu. Ngươi có bùa không?”', en: '“This rift is no place for the weak. Do you have a ward?”' },
      { when: { affMin: 3 }, vi: '“Ta trừ tà ở đây năm năm. Mỗi lần ta nghĩ xong — khe lại mở ra thêm.”', en: '“I have exorcised here for five years. Each time I think I am done — the rift opens further.”' },
      { when: { affMin: 6 }, vi: '“Ngươi có linh căn phế. Điều đó có thể là lợi thế — khe nứt không thể tìm thấy những gì không có quy luật.”', en: '“You have a defective root. That may be an advantage — the rift cannot find what has no pattern.”' },
    ],
  },
  {
    id: 'n_crane_spirit',
    nameVi: 'Tiên hạc',
    nameEn: 'Crane Spirit',
    roleVi: 'linh hạc',
    roleEn: 'crane spirit',
    locationId: 'cloud_peak',
    greetVi: 'Gió ở đây chỉ kể tên những ai chịu bước tiếp.',
    greetEn: 'This wind speaks only the names of those who kept walking.',
    aliases: ['crane', 'tien hac', 'spirit crane'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi lên đỉnh này rồi. Ít người đi đến đây.”', en: '“You have climbed to this peak. Few walk this far.”' },
      { when: { affMin: 3 }, vi: '“Ta đã sống trên đỉnh này nhiều kiếp. Ta nhớ những người đi qua — và những người dừng lại.”', en: '“I have lived on this peak through many lives. I remember those who passed — and those who stopped.”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang linh căn phế. Đỉnh này không phân biệt — nó chỉ ghi nhận những ai đến.”', en: '“You have a defective root. This peak does not discriminate — it only notes those who arrive.”' },
    ],
  },

  // ─────────────────────────────────────────────
  // 10 NEW CULTIVATORS (W2 world expansion)  ≥ 3 lines each
  // ─────────────────────────────────────────────
  {
    id: 'n_herbalist_lan',
    nameVi: 'Dược nương Lan',
    nameEn: 'Herbalist Lan',
    roleVi: 'tu sĩ Vạn Thảo Cốc',
    roleEn: 'valley cultivator',
    locationId: 'thousand_herbs_valley',
    greetVi: 'Vạn Thảo Cốc không đón người vội vàng. Đi chậm, ngửi kỹ, mới thấy dược khí.',
    greetEn: 'Thousand Herbs Valley turns away the hurried. Walk slow, smell deep, and the medicine finds you.',
    aliases: ['herbalist', 'lan', 'duoc nuong'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi không như kẻ đi lạc. Ngươi có con mắt của người hái thuốc.”', en: '“You do not look lost. You carry the eye of a herb gatherer.”' },
      { when: { affMin: 3 }, vi: '“Sương ở đây còn giữ hơi thuốc của cả trăm năm. Ngươi nghe được không?”', en: '“This valley dew still holds a hundred years of medicine. Can you hear it?”' },
      { when: { flag: 'story_route_ready' }, vi: '“Ta nghe nói phong ấn sắp vỡ. Nếu ngươi vào hang, nhớ mang một nắm bồ công anh — nó dịu lửa tà khí.”', en: '“I hear the seal is about to break. If you enter the cave, carry a fistful of dandelion — it soothes baleful fire.”' },
    ],
  },
  {
    id: 'n_swordsman_diep',
    nameVi: 'Kiếm khách Diệp',
    nameEn: 'Swordsman Diep',
    roleVi: 'tu sĩ sa mạc',
    roleEn: 'dune swordsman',
    locationId: 'blackwind_dunes',
    greetVi: 'Cát Hắc Phong nuốt bước chân người do dự. Đi đứng đàng hoàng, hoặc đừng đi.',
    greetEn: 'Blackwind sand swallows the hesitant. Walk with resolve, or do not walk at all.',
    aliases: ['swordsman', 'diep', 'kiem khach'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi cầm kiếm như cầm cành củi. Nhưng dáng đứng thì không như người thường.”', en: '“You hold a sword like firewood. But your stance is not that of a commoner.”' },
      { when: { affMin: 3 }, vi: '“Một đường kiếm hay không nằm ở tay, mà ở chỗ ngươi sẵn sàng đứng vững khi gió tới.”', en: '“A fine sword path is not in the hand, but in where you choose to stand when the wind comes.”' },
      { when: { affMin: 6 }, vi: '“Ta luyện kiếm trong bão cát ba mươi năm. Ngươi có linh căn lệch — vậy mà đứng đây. Ta nể.”', en: '“I have trained my blade in sandstorms for thirty years. Your root is crooked, yet here you stand. I respect that.”' },
    ],
  },
  {
    id: 'n_monk_nhu',
    nameVi: 'Tăng nhân Như',
    nameEn: 'Monk Nhu',
    roleVi: 'tu sĩ Hàn Băng Phong',
    roleEn: 'frozen peak monk',
    locationId: 'frozen_peak',
    greetVi: 'Băng trên đỉnh không lạnh vì tuyết. Nó lạnh vì cô độc. Ngồi xuống mà nghe.',
    greetEn: 'The ice up here is not cold from snow. It is cold from solitude. Sit and listen.',
    aliases: ['monk', 'nhu', 'tang nhan'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ít người lên tới Hàn Băng Phong mà còn thở đều như ngươi.”', en: '“Few reach Frozen Peak still breathing as evenly as you.”' },
      { when: { affMin: 3 }, vi: '“Cái lạnh này là một vị sư. Nó dạy ngươi buông — hoặc dạy ngươi chịu đựng.”', en: '“This cold is a teacher. It teaches you to let go — or to endure.”' },
      { when: { affMin: 6 }, vi: '“Ta thấy vết hàn thấu xương trong ngươi. Không phải từ tuyết — từ điều ngươi cố quên.”', en: '“I see a frost that reaches your bones. Not from snow — from what you try to forget.”' },
    ],
  },
  {
    id: 'n_broker_tieu',
    nameVi: 'Kinh kỷ Tiêu',
    nameEn: 'Broker Tieu',
    roleVi: 'tu sĩ hành thương',
    roleEn: 'itinerant broker',
    locationId: 'wandering_market',
    greetVi: 'Chợ di động bán thứ gì cũng có, trừ một thứ: câu trả lời cho kẻ chưa biết mình hỏi gì.',
    greetEn: 'The traveling market sells almost anything — except an answer for one who does not yet know their question.',
    aliases: ['broker', 'tieu', 'kinh ky'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đi theo đoàn xe này bao xa rồi? Ta nhớ mặt mọi người — lần đầu thấy ngươi.”', en: '“How far have you followed this caravan? I remember every face — this is your first.”' },
      { when: { affMin: 3 }, vi: '“Tin đồn là hàng rẻ nhất và đắt nhất ở chợ. Ngươi muốn mua loại nào?”', en: '“Rumors are the cheapest and costliest good at market. Which kind are you buying?”' },
      { when: { affMin: 6 }, vi: '“Có một món hàng ta để dành cho người biết điều — một manh mối về cái tên bị xóa. Giá là một câu chuyện thật.”', en: '“I keep one good aside for the discerning — a lead on the erased name. The price is a true story.”' },
    ],
  },
  {
    id: 'n_fisher_yen',
    nameVi: 'Ngư ông Yến',
    nameEn: 'Fisher Yen',
    roleVi: 'tu sĩ hồ Nguyệt Ảnh',
    roleEn: 'moon lake fisher',
    locationId: 'moon_lake',
    greetVi: 'Hồ này giữ trăng cả ban ngày. Ta câu không phải cá — ta câu những gì chìm dưới ánh trăng.',
    greetEn: 'This lake keeps moonlight even by day. I fish not for fish — but for what sinks beneath the moon.',
    aliases: ['fisher', 'yen', 'ngu ong'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đứng yên đủ lâu để không làm cá sợ. Vậy là ngươi biết nghe.”', en: '“You stood still long enough not to spook the fish. So you know how to listen.”' },
      { when: { affMin: 3 }, vi: '“Dưới đáy hồ có một thành cũ. Đêm trăng rằm, ta nghe tiếng chuông nổi lên.”', en: '“An old city rests beneath this lake. On full-moon nights I hear its bells rise.”' },
      { when: { affMin: 6 }, vi: '“Ngươi mang theo điều gì đó chìm trong người. Câu nó lên, kẻo nó chết trong đáy.”', en: '“You carry something sunk inside you. Reel it up, before it dies on the bottom.”' },
    ],
  },
  {
    id: 'n_relic_hunter_bach',
    nameVi: 'Đạo nhân Bạch',
    nameEn: 'Relic Hunter Bach',
    roleVi: 'tu sĩ nhặt tro',
    roleEn: 'ash relic hunter',
    locationId: 'bone_ash_ruins',
    greetVi: 'Tro xương không phải rác. Nó là ký ức của một thành phố từng đứng đây.',
    greetEn: 'Bone ash is not refuse. It is the memory of a city that once stood here.',
    aliases: ['relic hunter', 'bach', 'dao nhan'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đi qua đống tro này mà không dừng. Ngươi không thấy gì cả.”', en: '“You walked past this ash without pausing. You see nothing.”' },
      { when: { affMin: 3 }, vi: '“Mỗi mảnh tro giữ một cái tên. Ngươi muốn ta chỉ cho ngươi cách nghe tên trong tro không?”', en: '“Each ash keeps a name. Do you want me to teach you how to hear names in ash?”' },
      { when: { flag: 'story_name_known' }, vi: '“Ngươi biết cái tên bị xóa. Vậy ngươi hiểu vì sao ta nhặt tro — kẻ nào đó phải nhớ chúng.”', en: '“You know the erased name. Then you understand why I gather ash — someone must remember them.”' },
    ],
  },
  {
    id: 'n_beast_tamer_le',
    nameVi: 'Ngự thú sư Lê',
    nameEn: 'Beast Tamer Le',
    roleVi: 'tu sĩ Linh Thú Lĩnh',
    roleEn: 'ridge beast tamer',
    locationId: 'spirit_beast_ridge',
    greetVi: 'Linh thú không sợ kẻ mạnh. Nó sợ kẻ không biết sợ đúng lúc.',
    greetEn: 'Spirit beasts do not fear the strong. They fear one who never fears at the right moment.',
    aliases: ['beast tamer', 'le', 'ngu thu'],
    lines: [
      { when: { affMin: 1 }, vi: '“Đừng nhìn chằm chằm con bạch hổ kia. Nó đang quyết định xem ngươi là bữa ăn hay là khách.”', en: '“Do not stare at that white tiger. It is deciding whether you are a meal or a guest.”' },
      { when: { affMin: 3 }, vi: '“Linh căn của ngươi không giữ khí, nhưng nó rung theo nhịp đất. Linh thú cảm nhận được điều đó.”', en: '“Your root holds no qi, but it hums with the earth’s rhythm. Beasts feel that.”' },
      { when: { affMin: 6 }, vi: '“Ta có một con yêu lang thuần hóa một nửa. Ngươi muốn thử dắt nó không? Nó chỉ nghe người biết nhún nhường.”', en: '“I have a half-tamed demon wolf. Care to try leading it? It only obeys one who knows humility.”' },
    ],
  },
  {
    id: 'n_pavilion_disciple_anh',
    nameVi: 'Đệ tử Ánh',
    nameEn: 'Disciple Anh',
    roleVi: 'đệ tử Thanh Vân Các',
    roleEn: 'pavilion disciple',
    locationId: 'azure_pavilion',
    greetVi: 'Thanh Vân Các không cho mượn sách cho kẻ không chịu học. Ngươi chịu học không?',
    greetEn: 'Azure Pavilion does not lend books to the unwilling. Are you willing to learn?',
    aliases: ['disciple', 'anh', 'de tu'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi nhìn kệ sách như nhìn núi. Vậy là có ý chí.”', en: '“You look at the shelves like a mountain. That is will.”' },
      { when: { affMin: 3 }, vi: '“Có một quyển sách nói về linh căn phế — không phải để khinh, mà để hiểu. Ngươi muốn đọc không?”', en: '“There is a book about defective roots — not to mock, but to understand. Would you read it?”' },
      { when: { affMin: 6 }, vi: '“Sư phụ bảo: kẻ lên được Thanh Vân Các mà không mượn quyển nào, là kẻ chỉ muốn đứng gần tri thức. Ngươi như vậy.”', en: '“My master says: one who climbs to the pavilion and borrows nothing only wants to stand near knowledge. That is you.”' },
    ],
  },
  {
    id: 'n_wandering_blade_phong',
    nameVi: 'Phiêu kiếm Phong',
    nameEn: 'Wandering Blade Phong',
    roleVi: 'tu sĩ giang hồ',
    roleEn: 'itinerant swordsman',
    locationId: 'market',
    greetVi: 'Chợ là nơi tốt nhất để nghe tin đồn về chính mình. Ngươi đã nghe về ngươi chưa?',
    greetEn: 'The market is the best place to hear rumors about yourself. Have you heard yours yet?',
    aliases: ['blade', 'phong', 'phieu kiem'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi không phải người buôn bán. Ngươi mang hơi thở của đường xa.”', en: '“You are no merchant. You carry the breath of the open road.”' },
      { when: { affMin: 3 }, vi: '“Ta đã đi khắp nơi tìm một người mang linh căn phế mà không oán trời. Ngươi là người đầu tiên.”', en: '“I have traveled everywhere seeking one with a defective root who does not curse heaven. You are the first.”' },
      { when: { affMin: 6 }, vi: '“Nếu ngươi cần một thanh kiếm mượn tạm — hoặc một người đứng sau lưng — hãy tìm ta ở chợ.”', en: '“If you ever need a borrowed blade — or someone at your back — find me at the market.”' },
    ],
  },
  {
    id: 'n_rogue_cultivator_nhat',
    nameVi: 'Tán tu Nhất',
    nameEn: 'Rogue Cultivator Nhat',
    roleVi: 'tán tu rừng sương',
    roleEn: 'forest rogue cultivator',
    locationId: 'misty_forest',
    greetVi: 'Rừng này giữ nhiều bí mật hơn ngươi tưởng. Và ít người sống để kể lại hơn ngươi nghĩ.',
    greetEn: 'This forest keeps more secrets than you imagine. And fewer live to tell them than you think.',
    aliases: ['rogue', 'nhat', 'tan tu'],
    lines: [
      { when: { affMin: 1 }, vi: '“Ngươi đi vào rừng sương một mình. Dũng cảm — hoặc chưa hiểu chuyện gì đang chờ.”', en: '“You walk into the mist alone. Brave — or unaware of what waits.”' },
      { when: { affMin: 3 }, vi: '“Ta tu luyện ngoài tông môn vì tông môn không chứa được ta. Ngươi có linh căn phế — chắc ngươi hiểu cảm giác bị bỏ lại.”', en: '“I cultivate outside sects because sects could not hold me. You have a defective root — you know what it is to be set aside.”' },
      { when: { affMin: 6 }, vi: '“Ta biết một con đường tắt trong rừng, không ai dám đi. Đi với ta — nhưng đừng hỏi vì sao ta biết.”', en: '“I know a shortcut through these woods that no one dares take. Come with me — but do not ask how I know it.”' },
    ],
  },
]

export function getNpc(npcId: string): NpcDef | undefined {
  return NPCS.find((n) => n.id === npcId)
}

export function npcsAt(locationId: string): NpcDef[] {
  return NPCS.filter((n) => n.locationId === locationId)
}
