import type { NpcDef } from '../engine/content-types'

export const NPCS: NpcDef[] = [
  {
    id: 'n_elder_meihua',
    nameVi: 'Cụ Mai Hoa',
    nameEn: 'Elder Meihua',
    roleVi: 'tù trưởng làng',
    roleEn: 'village elder',
    locationId: 'village',
    greetVi: 'Đứa nhỏ mới lớn à? Làng này yên bình, nhưng con đường của con thì không.',
    greetEn: 'A grown child already? This village is quiet, but your road will not be.',
    aliases: ['elder', 'meihua', 'cu mai hoa', 'cụ'],
  },
  {
    id: 'n_guard_truong',
    nameVi: 'Dân binh Trường',
    nameEn: 'Guard Truong',
    roleVi: 'dân binh',
    roleEn: 'militia guard',
    locationId: 'village',
    greetVi: 'Giữ trật tự nhé. Đêm nay có sương, đi xa nhớ mang bùa.',
    greetEn: 'Keep the peace. Mist tonight; carry a ward if you wander far.',
    aliases: ['guard', 'truong', 'dan binh'],
  },
  {
    id: 'n_kid_xiaobao',
    nameVi: 'Tiểu Bảo',
    nameEn: 'Xiaobao',
    roleVi: 'đứa trẻ tinh nghịch',
    roleEn: 'mischievous kid',
    locationId: 'village',
    greetVi: 'Anh tu tiên ơi, anh bay được chưa? Bay lên cho em xem với!',
    greetEn: 'Hey mister cultivator, can you fly yet? Fly for me, just a little!',
    aliases: ['kid', 'xiaobao', 'tieu bao', 'child'],
  },
  {
    id: 'n_innkeeper_hanh',
    nameVi: 'Chủ quán Hạnh',
    nameEn: 'Innkeeper Hanh',
    roleVi: 'chủ quán trọ',
    roleEn: 'innkeeper',
    locationId: 'village',
    greetVi: 'Phòng còn một giường. Ngủ ngon thì tu luyện mới mau.',
    greetEn: 'One bed left. Sleep well and cultivation comes easier.',
    aliases: ['innkeeper', 'hanh', 'chu quan'],
  },
  {
    id: 'n_farmer_tu',
    nameVi: 'Nông phu Tư',
    nameEn: 'Farmer Tu',
    roleVi: 'nông phu',
    roleEn: 'farmer',
    locationId: 'village',
    greetVi: 'Ruộng linh thảo năm nay tốt lắm. Đi cẩn thận kẻo dẫm ngô.',
    greetEn: 'Herb terraces are generous this year. Mind the corn on your way.',
    aliases: ['farmer', 'tu', 'nong phu'],
  },
  {
    id: 'n_storyteller_ngo',
    nameVi: 'Ngo kể chuyện',
    nameEn: 'Ngo the Storyteller',
    roleVi: 'người kể chuyện',
    roleEn: 'storyteller',
    locationId: 'village',
    greetVi: 'Nghe chuyện vị tiền bối linh căn khuyết vẫn phi thăng không? Ngồi xuống đây.',
    greetEn: 'The tale of the elder with a defective root who still ascended? Sit down, then.',
    aliases: ['storyteller', 'ngo', 'ke chuyen'],
  },
  {
    id: 'n_merchant_bao',
    nameVi: 'Thương nhân Bảo',
    nameEn: 'Merchant Bao',
    roleVi: 'thương nhân',
    roleEn: 'merchant',
    locationId: 'market',
    greetVi: 'Mua bán công bằng, giá niêm yết, không trả giá đâu!',
    greetEn: 'Fair trades, posted prices, and no haggling!',
    aliases: ['merchant', 'bao', 'thuong nhan'],
  },
  {
    id: 'n_fortune_lien',
    nameVi: 'Bà đồng Liên',
    nameEn: 'Fortune Lien',
    roleVi: 'bói vé số',
    roleEn: 'lottery seer',
    locationId: 'market',
    greetVi: 'Một ngày một lượt thôi con, trời cũng cần ngủ mà.',
    greetEn: 'One draw a day, child; even Heaven needs its sleep.',
    aliases: ['fortune', 'lien', 'ba dong', 'lottery'],
  },
  {
    id: 'n_cook_phung',
    nameVi: 'Đầu bếp Phụng',
    nameEn: 'Cook Phung',
    roleVi: 'đầu bếp',
    roleEn: 'cook',
    locationId: 'market',
    greetVi: 'Bánh bao nóng đây! Tu tiên đói bụng thì tu cái gì?',
    greetEn: 'Hot steamed buns! Cultivate on an empty stomach, will you?',
    aliases: ['cook', 'phung', 'dau bep'],
  },
  {
    id: 'n_smith_duc',
    nameVi: 'Thợ rèn Đức',
    nameEn: 'Smith Duc',
    roleVi: 'thợ rèn',
    roleEn: 'blacksmith',
    locationId: 'market',
    greetVi: 'Lửa này tôi giữ ba chục năm rồi, chưa bỏ cuộc lần nào.',
    greetEn: 'I have kept this forge thirty years; it has never seen me quit.',
    aliases: ['smith', 'duc', 'tho ren'],
  },
  {
    id: 'n_scholar_minh',
    nameVi: 'Học giả Minh',
    nameEn: 'Scholar Minh',
    roleVi: 'học giả',
    roleEn: 'scholar',
    locationId: 'market',
    greetVi: 'Linh căn khuyết tật? Gọi là "linh căn khác biệt" cho dễ nghe.',
    greetEn: 'Defective root? Let us say "unconventional root" instead.',
    aliases: ['scholar', 'minh', 'hoc gia'],
  },
  {
    id: 'n_pedlar_quyen',
    nameVi: 'Hàng rong Quyền',
    nameEn: 'Pedlar Quyen',
    roleVi: 'hàng rong',
    roleEn: 'pedlar',
    locationId: 'market',
    greetVi: 'Vé số không? Không thì ngọc bội, vừa về hàng sáng nay.',
    greetEn: 'Lottery ticket? No? Then jade charms, fresh off this morning cart.',
    aliases: ['pedlar', 'quyen', 'hang rong'],
  },
  {
    id: 'n_tea_ma',
    nameVi: 'Bà Ma trà quán',
    nameEn: 'Tea Granny Ma',
    roleVi: 'bà chủ quán trà',
    roleEn: 'tea house owner',
    locationId: 'market',
    greetVi: 'Trà nóng một ấm, tin đồn một đĩa. Ăn cả hai nhé?',
    greetEn: 'One pot of hot tea, one plate of rumors. Take both?',
    aliases: ['tea', 'ma', 'tra quan'],
  },
  {
    id: 'n_tailor_yen',
    nameVi: 'Thợ may Yến',
    nameEn: 'Tailor Yen',
    roleVi: 'thợ may',
    roleEn: 'tailor',
    locationId: 'market',
    greetVi: 'Áo tu hành rách khuỷu rồi kìa. Xếp lại cho đẹp chứ?',
    greetEn: 'Your robe is fraying at the elbow. Let me fold it into style.',
    aliases: ['tailor', 'yen', 'tho may'],
  },
  {
    id: 'n_master_vo',
    nameVi: 'Võ Trưởng Sư',
    nameEn: 'Master Vo',
    roleVi: 'trưởng sư tông môn',
    roleEn: 'sect master',
    locationId: 'sect',
    greetVi: 'Linh căn của ngươi cong. Vậy thì đi đường cong. Đường nào cũng lên đỉnh.',
    greetEn: 'Your root is crooked. Then walk the crooked path. All paths reach the peak.',
    aliases: ['master', 'vo', 'truong su'],
  },
  {
    id: 'n_senior_lan',
    nameVi: 'Sư tỷ Lan',
    nameEn: 'Senior Lan',
    roleVi: 'sư tỷ',
    roleEn: 'senior sister',
    locationId: 'sect',
    greetVi: 'Kinh nghiệm của tỷ: đừng luyện khi đang giận. Rất đau.',
    greetEn: 'Senior wisdom: never train while angry. It hurts. A lot.',
    aliases: ['senior', 'lan', 'su ty'],
  },
  {
    id: 'n_keeper_anh',
    nameVi: 'Quản kho Ánh',
    nameEn: 'Keeper Anh',
    roleVi: 'quản lý nhà kho',
    roleEn: 'warehouse keeper',
    locationId: 'sect',
    greetVi: 'Nh kho chứa được năm chục món. Nhiều hơn thì ký tên giấy trắng đen.',
    greetEn: 'Storage holds fifty items. More than that needs paperwork.',
    aliases: ['keeper', 'anh', 'quan kho', 'storage'],
  },
  {
    id: 'n_monk_thien',
    nameVi: 'Sa môn Thiện',
    nameEn: 'Monk Thien',
    roleVi: 'sa môn',
    roleEn: 'monk',
    locationId: 'sect',
    greetVi: 'Hôm nay ngươi đã uống nước chưa? Uống chưa thì đã là phúc.',
    greetEn: 'Have you drunk water today? If yes, that is already fortune.',
    aliases: ['monk', 'thien', 'sa mon'],
  },
  {
    id: 'n_rival_khoa',
    nameVi: 'Sư đệ Khoa',
    nameEn: 'Rival Khoa',
    roleVi: 'sư đệ cạnh tranh',
    roleEn: 'rival junior brother',
    locationId: 'sect',
    greetVi: 'Linh căn khuyết? Ba tháng nữa ta cho ngươi xem thế nào là thiên tài.',
    greetEn: 'A defective root? Give me three months to show you what genius looks like.',
    aliases: ['rival', 'khoa', 'su de'],
  },
  {
    id: 'n_alchemist_sam',
    nameVi: 'Luyện dược Sâm',
    nameEn: 'Alchemist Sam',
    roleVi: 'luyện dược sư',
    roleEn: 'alchemist',
    locationId: 'sect',
    greetVi: 'Lò nổ lần thứ bảy rồi. Tiến bộ rõ rệt so với lần thứ sáu.',
    greetEn: 'Seventh furnace explosion this month. Clear progress over number six.',
    aliases: ['alchemist', 'sam', 'luyen duoc'],
  },
  {
    id: 'n_herbalist_dan',
    nameVi: 'Dược sư Đàn',
    nameEn: 'Herbalist Dan',
    roleVi: 'dược sư ruộng thuốc',
    roleEn: 'terrace herbalist',
    locationId: 'herb_field',
    greetVi: 'Hái nhẹ tay, cây biết ơn lắm. Hái xấu tay, cây biết luôn.',
    greetEn: 'Pick gently and the plants remember kindly. Pick roughly, they remember too.',
    aliases: ['herbalist', 'dan', 'duoc su'],
  },
  {
    id: 'n_gatherer_hue',
    nameVi: 'Thợ hái Huệ',
    nameEn: 'Gatherer Hue',
    roleVi: 'thợ hái',
    roleEn: 'herb gatherer',
    locationId: 'herb_field',
    greetVi: 'Sáng nay sương ngọt, linh thảo thơm hơn mọi ngày.',
    greetEn: 'Sweet dew this morning; the spirit herbs smell better than ever.',
    aliases: ['gatherer', 'hue', 'tho hai'],
  },
  {
    id: 'n_ox_cart_hien',
    nameVi: 'Xe bò Hiền',
    nameEn: 'Ox-Cart Hien',
    roleVi: 'phu xe',
    roleEn: 'cart driver',
    locationId: 'herb_field',
    greetVi: 'Đi bộ tới chợ mỏi chân không? Con bò này biết cười đấy.',
    greetEn: 'Tired of walking to market? This ox knows how to smile.',
    aliases: ['cart', 'hien', 'xe bo'],
  },
  {
    id: 'n_hunter_son',
    nameVi: 'Thợ săn Sơn',
    nameEn: 'Hunter Son',
    roleVi: 'thợ săn',
    roleEn: 'hunter',
    locationId: 'misty_forest',
    greetVi: 'Trong rừng này, kẻ ồn ào về trước. Kẻ im lặng về sau.',
    greetEn: 'In these woods the loud leave first. The silent leave last.',
    aliases: ['hunter', 'son', 'tho san'],
  },
  {
    id: 'n_woodcutter_bong',
    nameVi: 'Tiều phu Bồng',
    nameEn: 'Woodcutter Bong',
    roleVi: 'tiều phu',
    roleEn: 'woodcutter',
    locationId: 'misty_forest',
    greetVi: 'Cây này tôi không chặt. Nó nói chuyện trong mơ của tôi.',
    greetEn: 'I do not cut this tree. It talks in my dreams.',
    aliases: ['woodcutter', 'bong', 'tieu phu'],
  },
  {
    id: 'n_hermit_coc',
    nameVi: 'Cốc chủ Cốc',
    nameEn: 'Hermit Coc',
    roleVi: 'ẩn sĩ hang đá',
    roleEn: 'cave hermit',
    locationId: 'sealed_cave',
    greetVi: 'Ấn cũ yếu rồi. Mang bùa hoặc mang vận may, chọn đi.',
    greetEn: 'The old seal weakens. Bring a talisman or bring luck. Choose.',
    aliases: ['hermit', 'coc', 'an si'],
  },
  {
    id: 'n_lost_soul_ha',
    nameVi: 'Vong hồn Hà',
    nameEn: 'Lost Soul Ha',
    roleVi: 'vong hồn lang thang',
    roleEn: 'wandering shade',
    locationId: 'sealed_cave',
    greetVi: 'Người sống vào đây... hiếm. Người sống ra được... hiếm hơn.',
    greetEn: 'The living who enter... are rare. The living who leave... rarer.',
    aliases: ['soul', 'ha', 'vong hon'],
  },
  {
    id: 'n_exile_ba',
    nameVi: 'Kẻ lưu đày Bá',
    nameEn: 'Exile Ba',
    roleVi: 'kẻ lưu đày',
    roleEn: 'exile',
    locationId: 'cursed_rift',
    greetVi: 'Đừng lại gần khe nứt. Ta đã đứng đây đủ lâu để biết.',
    greetEn: 'Stay away from the rift. I have stood here long enough to know.',
    aliases: ['exile', 'ba', 'luu day'],
  },
  {
    id: 'n_exorcist_diem',
    nameVi: 'Trừ tà Diễm',
    nameEn: 'Exorcist Diem',
    roleVi: 'trừ tà sư',
    roleEn: 'exorcist',
    locationId: 'cursed_rift',
    greetVi: 'Việc ở đây chưa xong. Nhưng trà thì hết rồi.',
    greetEn: 'My work here is unfinished. My tea, however, is finished.',
    aliases: ['exorcist', 'diem', 'tru ta'],
  },
  {
    id: 'n_crane_spirit',
    nameVi: 'Tiên hạc',
    nameEn: 'Crane Spirit',
    roleVi: 'linh hạc',
    roleEn: 'crane spirit',
    locationId: 'cloud_peak',
    greetVi: 'Gió ở đây chỉ kể tên những ai chịu bước tiếp.',
    greetEn: 'This wind speaks only the names of those who kept walking.',
    aliases: ['crane', 'tien hac', 'spirit crane'],
  },
]

export function getNpc(npcId: string): NpcDef | undefined {
  return NPCS.find((n) => n.id === npcId)
}

export function npcsAt(locationId: string): NpcDef[] {
  return NPCS.filter((n) => n.locationId === locationId)
}
