import type { RefinementRecipeDef } from '../engine/content-types'

/**
 * The market buys every ingredient individually, but these exchanges let a
 * player carry a compact survival tool back into danger instead.  The values
 * intentionally do not dominate a straight sale: safety and momentum compete
 * with immediate capital for manuals and equipment.
 */
export const RECIPES: RefinementRecipeDef[] = [
  {
    id: 'warding_exchange',
    nameVi: 'Bùa hồi lộ',
    nameEn: 'Homeward Ward',
    descVi: 'Ép một chiếc nha thú và linh thảo thành bùa hộ thân, đủ che một lần bước vào hiểm địa.',
    descEn: 'Press a beast fang and spirit herb into one protective ward, enough to cover a single step into high danger.',
    locationId: 'market',
    ingredients: { beast_fang: 1, spirit_herb: 1 },
    output: { itemId: 'warding_talisman', qty: 1 },
  },
  {
    id: 'qi_tonic_exchange',
    nameVi: 'Tán tụ khí',
    nameEn: 'Qi-Gathering Powder',
    descVi: 'Nghiền linh thảo thành bột mịn; đổi hai bó lấy một lần tu luyện không bị hụt hơi.',
    descEn: 'Grind spirit herbs into a fine powder; trade two bundles for one cultivation push without running dry.',
    locationId: 'market',
    ingredients: { spirit_herb: 2 },
    output: { itemId: 'pill_qi', qty: 1 },
  },
  {
    id: 'moonmoss_exchange',
    nameVi: 'Hoàn nguyên sương nguyệt',
    nameEn: 'Moonmoss Restoration',
    descVi: 'Rêu nguyệt và linh thảo đổi thành một viên hồi nguyên: bớt tiền trong túi, thêm đường về nhà.',
    descEn: 'Moonmoss and a spirit herb become a restoration pill: less coin in your purse, more road home.',
    locationId: 'market',
    ingredients: { moon_moss: 1, spirit_herb: 1 },
    output: { itemId: 'pill_hp', qty: 1 },
  },
  /* --- T07 (expansion-x20): 12 công thức đan lai ở Vạn Thảo Cốc ---
   * Nguyên liệu chỉ dùng linh thảo (herb_*), mỗi công thức ra đúng một pill_hybrid_*. */
  {
    id: 'r_hybrid_silk_heart',
    nameVi: 'Đan lai tơ băng',
    nameEn: 'Silk-Heart Hybrid Pill',
    descVi: 'Hai nắm hồng tơ thảo cùng một nhánh băng tâm, ép chung một lò nhỏ.',
    descEn: 'Two handfuls of red silk herb and one sprig of ice-heart, pressed into one small furnace.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_hong_silk: 2, herb_ice_heart: 1 },
    output: { itemId: 'pill_hybrid_silk_heart', qty: 1 },
  },
  {
    id: 'r_hybrid_blood_dew',
    nameVi: 'Đan lai huyết lộ',
    nameEn: 'Blood-Dew Hybrid Pill',
    descVi: 'Huyết sâm dằm nhừ trong sương vân, nhả ra một viên đan đỏ nhạt.',
    descEn: 'Blood ginseng simmered into cloud dew, yielding one pale red pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_blood_ginseng: 2, herb_cloud_dew: 1 },
    output: { itemId: 'pill_hybrid_blood_dew', qty: 1 },
  },
  {
    id: 'r_hybrid_moon_fire',
    nameVi: 'Đan lai nguyệt hỏa',
    nameEn: 'Moon-Fire Hybrid Pill',
    descVi: 'Hỏa liên cháy trước, nguyệt phách rắc sau để dập lại thành viên hoàn.',
    descEn: 'Fire lotus burns first, moon-shard scattered after to temper it into one pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_fire_lotus: 2, herb_moon_shard: 1 },
    output: { itemId: 'pill_hybrid_moon_fire', qty: 1 },
  },
  {
    id: 'r_hybrid_banner_daisy',
    nameVi: 'Đan lai phan cúc',
    nameEn: 'Banner-Daisy Hybrid Pill',
    descVi: 'Bạch phan chi và tử cúc phơi chung một chiều, giã chung một cối.',
    descEn: 'White-banner fungus and purple daisy dried through one afternoon, ground in one mortar.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_white_banner: 2, herb_purple_daisy: 1 },
    output: { itemId: 'pill_hybrid_banner_daisy', qty: 1 },
  },
  {
    id: 'r_hybrid_marrow_bamboo',
    nameVi: 'Đan lai tủy trúc',
    nameEn: 'Marrow-Bamboo Hybrid Pill',
    descVi: 'Địa tủy nấu nhừ, rót qua ruột hư trúc để lọc bớt khí lạnh.',
    descEn: 'Earth marrow simmered soft, then poured through hollow void bamboo to strain the chill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_earth_marrow: 2, herb_void_bamboo: 1 },
    output: { itemId: 'pill_hybrid_marrow_bamboo', qty: 1 },
  },
  {
    id: 'r_hybrid_cloud_lotus',
    nameVi: 'Đan lai vân liên',
    nameEn: 'Cloud-Lotus Hybrid Pill',
    descVi: 'Vân lộ hoa đặt trên cánh hỏa liên, hấp cách thủy đến khi hai mùi hòa làm một.',
    descEn: 'Cloud-dew blossom set on a fire-lotus petal, steamed until the two scents become one.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_cloud_dew: 2, herb_fire_lotus: 1 },
    output: { itemId: 'pill_hybrid_cloud_lotus', qty: 1 },
  },
  {
    id: 'r_hybrid_ice_ginseng',
    nameVi: 'Đan lai băng sâm',
    nameEn: 'Ice-Ginseng Hybrid Pill',
    descVi: 'Băng tâm bọc huyết sâm, vùi tro ấm qua đêm là thành viên hoàn.',
    descEn: 'Ice-heart wrapped around blood ginseng, buried in warm ash overnight until it becomes a pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_ice_heart: 2, herb_blood_ginseng: 1 },
    output: { itemId: 'pill_hybrid_ice_ginseng', qty: 1 },
  },
  {
    id: 'r_hybrid_dew_daisy',
    nameVi: 'Đan lai lộ cúc',
    nameEn: 'Dew-Daisy Hybrid Pill',
    descVi: 'Vân lộ hoa vắt lên cúc tím, chưng lấy nước cốt rồi kết thành hoàn.',
    descEn: 'Cloud-dew blossom laid over purple daisy, steamed for its essence, then set into a pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_cloud_dew: 2, herb_purple_daisy: 1 },
    output: { itemId: 'pill_hybrid_dew_daisy', qty: 1 },
  },
  {
    id: 'r_hybrid_earth_fire',
    nameVi: 'Đan lai địa hỏa',
    nameEn: 'Earth-Fire Hybrid Pill',
    descVi: 'Địa tủy chôn dưới than hồng cùng cánh hỏa liên, đào lên là đan.',
    descEn: 'Earth marrow buried under embers with fire-lotus petals; dig it up and it is a pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_earth_marrow: 2, herb_fire_lotus: 1 },
    output: { itemId: 'pill_hybrid_earth_fire', qty: 1 },
  },
  {
    id: 'r_hybrid_silk_dew',
    nameVi: 'Đan lai tơ lộ',
    nameEn: 'Silk-Dew Hybrid Pill',
    descVi: 'Hồng tơ thảo quấn lấy thanh đằng đẫm sương, bó lại rồi nướng trên đá nóng.',
    descEn: 'Red silk herb wound around dew-heavy green vine, bound and baked on a hot stone.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_hong_silk: 2, herb_green_vine: 1 },
    output: { itemId: 'pill_hybrid_silk_dew', qty: 1 },
  },
  {
    id: 'r_hybrid_moon_marrow',
    nameVi: 'Đan lai nguyệt tủy',
    nameEn: 'Moon-Marrow Hybrid Pill',
    descVi: 'Nguyệt phách để chung với địa tủy dưới trăng thu, sáng ra thành đan.',
    descEn: 'Moon-shard laid with earth marrow under the autumn moon; by morning it is a pill.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_moon_shard: 2, herb_earth_marrow: 1 },
    output: { itemId: 'pill_hybrid_moon_marrow', qty: 1 },
  },
  {
    id: 'r_hybrid_wind_heart',
    nameVi: 'Đan lai phong tâm',
    nameEn: 'Wind-Heart Hybrid Pill',
    descVi: 'Phong trúc gõ nhỏ cùng băng tâm, lắc trong ống trúc cho đến khi nghe kêu khe khẽ.',
    descEn: 'Wind bamboo crushed with ice-heart, shaken in a bamboo tube until it rattles softly.',
    locationId: 'thousand_herbs_valley',
    ingredients: { herb_wind_bamboo: 2, herb_ice_heart: 1 },
    output: { itemId: 'pill_hybrid_wind_heart', qty: 1 },
  },
]

export function getRecipe(recipeId: string): RefinementRecipeDef | undefined {
  return RECIPES.find((recipe) => recipe.id === recipeId)
}
