import type { EnemyDef, EquipmentDef, Element, TalentDef, TechniqueDef } from '../engine/content-types'

// These tables are content-only: the reducer stores stable ids, so new content
// can be appended without rewriting a player's deterministic save.
export const TALENTS: TalentDef[] = [
  {
    id: 'tenacious_root',
    nameVi: 'Linh Căn Lì Lợm',
    nameEn: 'Stubborn Spirit Root',
    descVi: 'Linh căn phế không nhanh, nhưng chưa từng chịu tắt.',
    descEn: 'A defective root is slow, but refuses to go out.',
    requiredStage: 0,
    tier: 0,
    selectable: false,
    attackBonus: 0,
    defenseBonus: 1,
    trainingBonus: 0,
  },
  {
    id: 'iron_bones',
    nameVi: 'Gân Cốt Sắt',
    nameEn: 'Iron Bones',
    descVi: 'Đau thì đau, nhưng xương vẫn đứng thẳng.',
    descEn: 'Pain is pain; the bones still stand straight.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 2,
    trainingBonus: 0,
  },
  {
    id: 'wild_herbalist',
    nameVi: 'Dược Sư Cỏ Dại',
    nameEn: 'Wild Herbalist',
    descVi: 'Mỗi lần vận công, mùi cỏ thuốc khiến khí mạch ngoan hơn.',
    descEn: 'Herb scent makes the meridians a little more obedient.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 0,
    trainingBonus: 1,
  },
  {
    id: 'fortunate_fool',
    nameVi: 'Kẻ Ngốc Có Phúc',
    nameEn: 'Fortunate Fool',
    descVi: 'Ra đòn có vẻ hồ đồ, nhưng thường trúng đúng chỗ.',
    descEn: 'The swing looks foolish, yet often lands exactly right.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 2,
    defenseBonus: 0,
    trainingBonus: 0,
  },
  {
    id: 'mist_listener',
    nameVi: 'Thính Sương',
    nameEn: 'Mist Listener',
    descVi: 'Nghe được nhịp thở trong màn sương trước khi nguy hiểm ló mặt.',
    descEn: 'You hear breath in the fog before danger shows its face.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 1,
    defenseBonus: 1,
    trainingBonus: 0,
  },
  {
    id: 'merchant_instinct',
    nameVi: 'Mắt Thương Nhân',
    nameEn: 'Merchant Instinct',
    descVi: 'Biết món nào đáng bán, và lúc nào nên im lặng mặc cả.',
    descEn: 'You know what to sell, and when silence is the better bargain.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 0,
    trainingBonus: 2,
  },
  {
    id: 'rune_scar',
    nameVi: 'Ấn Tích Phong Phù',
    nameEn: 'Seal Scar',
    descVi: 'Một vết phù cũ nhắc cơ thể ngươi cách chịu đòn.',
    descEn: 'An old ward-scar teaches your body how to take a hit.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 3,
    trainingBonus: 0,
  },
  {
    id: 'rift_gambler',
    nameVi: 'Kẻ Đánh Cược Khe Nứt',
    nameEn: 'Rift Gambler',
    descVi: 'Có người thấy vực sâu. Ngươi thấy một lần tung xúc xắc nữa.',
    descEn: 'Others see an abyss. You see one more roll of the dice.',
    requiredStage: 3,
    tier: 3,
    selectable: true,
    attackBonus: 3,
    defenseBonus: 0,
    trainingBonus: 0,
  },
  {
    id: 'cloud_heart',
    nameVi: 'Tâm Mây',
    nameEn: 'Cloud Heart',
    descVi: 'Tâm không tranh với gió, nên khí mạch đi xa hơn.',
    descEn: 'The heart does not argue with the wind, so qi travels farther.',
    requiredStage: 3,
    tier: 3,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 1,
    trainingBonus: 2,
  },
  {
    id: 'peak_breaker',
    nameVi: 'Phá Phong',
    nameEn: 'Peak Breaker',
    descVi: 'Mỗi lần lùi nửa bước, ngươi học thêm cách bước tới.',
    descEn: 'Every half-step back teaches you how to step forward.',
    requiredStage: 4,
    tier: 4,
    selectable: true,
    attackBonus: 3,
    defenseBonus: 2,
    trainingBonus: 1,
  },
]

export const TECHNIQUES: TechniqueDef[] = [
  {
    id: 'basic_staff_form',
    nameVi: 'Mộc Trượng Thức',
    nameEn: 'Wooden Staff Form',
    descVi: 'Ba thế đơn giản để giữ yêu quái ngoài tầm răng.',
    descEn: 'Three plain forms for keeping monsters beyond biting range.',
    requiredStage: 0,
    maxLevel: 1,
    power: 2,
    trainingBonus: 0,
    benefitVi: 'Đáng tin, không đòi giá.',
    benefitEn: 'Reliable, and it asks for nothing.',
  },
  {
    id: 'crooked_circulation',
    nameVi: 'Chu Thiên Cong Queo',
    nameEn: 'Crooked Circulation',
    descVi: 'Đường khí sai sách vở, lại vừa khít linh căn phế.',
    descEn: 'Wrong by every textbook, yet perfect for a defective root.',
    requiredStage: 0,
    maxLevel: 1,
    power: 3,
    trainingBonus: 1,
    sourceItemId: 'old_manual',
    benefitVi: 'Tu luyện nhanh hơn một nhịp.',
    benefitEn: 'Cultivation moves one beat faster.',
    costVi: 'Trầm tư quá nhiều — bán hàng luôn lỗ 2 lượng.',
    costEn: 'Too lost in thought — every sale earns 2 gold less.',
    sellPenalty: 2,
  },
  {
    id: 'rift_step',
    nameVi: 'Khe Bộ',
    nameEn: 'Rift Step',
    descVi: 'Một bước lệch nhịp, né mũi vuốt ngay trước khi nó tới.',
    descEn: 'One off-beat step, dodging the claw just before it arrives.',
    requiredStage: 2,
    maxLevel: 1,
    power: 5,
    trainingBonus: 0,
    sourceItemId: 'rift_step_scroll',
    benefitVi: 'Đòn mạnh hơn hẳn.',
    benefitEn: 'Strikes land far harder.',
    costVi: 'Chân luôn muốn xé gió — hái thuốc tốn 4 khí.',
    costEn: 'The legs keep wanting to tear the wind — gathering drains 4 qi.',
    gatherQiDrain: 4,
  },
  {
    id: 'herbal_breath',
    nameVi: 'Dược Hơi Thuật',
    nameEn: 'Herbal Breath Method',
    descVi: 'Mượn mùi cỏ thuốc để dẫn khí qua những chỗ hay tắc.',
    descEn: 'Use herb-scent to guide qi through its habitual blockages.',
    requiredStage: 1,
    maxLevel: 1,
    power: 4,
    trainingBonus: 2,
    sourceItemId: 'herbal_breath_manual',
    benefitVi: 'Tu luyện nhanh gấp bội.',
    benefitEn: 'Cultivation speeds up manifold.',
    costVi: 'Đầu ngập mùi thuốc — bán hàng lỗ 3 lượng.',
    costEn: 'The head swims with herb-scent — every sale earns 3 gold less.',
    sellPenalty: 3,
  },
  {
    id: 'iron_skin',
    nameVi: 'Thiết Bì Quyết',
    nameEn: 'Iron Skin Art',
    descVi: 'Da không thành sắt thật, nhưng đủ khiến cú đấm phải suy nghĩ.',
    descEn: 'Your skin is not truly iron, but a punch must think twice.',
    requiredStage: 1,
    maxLevel: 1,
    power: 3,
    trainingBonus: 0,
    sourceItemId: 'iron_skin_manual',
    benefitVi: 'Da dày, chịu đòn hơn.',
    benefitEn: 'Thicker skin, harder to hurt.',
    costVi: 'Thân nặng hơn — hái thuốc tốn 2 khí.',
    costEn: 'A heavier frame — gathering drains 2 qi.',
    gatherQiDrain: 2,
  },
  {
    id: 'cloudwalk',
    nameVi: 'Vân Du Bộ',
    nameEn: 'Cloudwalk Steps',
    descVi: 'Bước chân nhẹ như đang mượn đường của mây.',
    descEn: 'Your feet grow light, borrowing paths from the clouds.',
    requiredStage: 2,
    maxLevel: 1,
    power: 6,
    trainingBonus: 1,
    sourceItemId: 'cloudwalk_manual',
    benefitVi: 'Mạnh và tu luyện vẫn tiến.',
    benefitEn: 'Strong, and cultivation still advances.',
    costVi: 'Tâm đã lên mây — bán hàng lỗ 2 lượng.',
    costEn: 'The heart is off among the clouds — every sale earns 2 gold less.',
    sellPenalty: 2,
  },
  {
    id: 'peak_cleaver',
    nameVi: 'Phá Phong Trảm',
    nameEn: 'Peak-Cleaving Strike',
    descVi: 'Một nhát không chém núi, nhưng đủ chém đứt nỗi sợ.',
    descEn: 'It will not cleave a mountain, but it can split your fear.',
    requiredStage: 3,
    maxLevel: 1,
    power: 8,
    trainingBonus: 0,
    benefitVi: 'Đòn mạnh nhất trong tay ngươi.',
    benefitEn: 'The hardest strike you own.',
    costVi: 'Mỗi hơi thở là một trận đánh — hái thuốc tốn 5 khí.',
    costEn: 'Every breath is a battle — gathering drains 5 qi.',
    gatherQiDrain: 5,
    sourceItemId: 'peak_cleaver_manual',
  },
  {
    id: 'tide_breath',
    nameVi: 'Triều Tức Thuật',
    nameEn: 'Tide-Breath Method',
    descVi: 'Hít vào như thủy triều lên, ra đòn lúc nước rút.',
    descEn: 'Inhale as the tide rises; strike the moment it withdraws.',
    requiredStage: 2,
    maxLevel: 1,
    power: 6,
    trainingBonus: 2,
    sourceItemId: 'tide_breath_manual',
  },
  {
    id: 'stone_aegis',
    nameVi: 'Thạch Kính Quyết',
    nameEn: 'Stone Aegis Art',
    descVi: 'Đứng vững như bàn thạch; đòn tới thì đá chịu thay.',
    descEn: 'Stand like bedrock; let stone take what was aimed at you.',
    requiredStage: 3,
    maxLevel: 1,
    power: 7,
    trainingBonus: 1,
    sourceItemId: 'stone_aegis_manual',
  },
  // ── 9 chiêu ẨN (T08, expansion-x20) — mở qua sách bí `<id>_manual` do T07 tạo.
  // requiredStage luôn cao hơn mọi chiêu cũ; benefit/cost là pattern hai mặt
  // Phase 3 (cost khớp field gatherQiDrain/sellPenalty như các chiêu cũ).
  {
    id: 'sword_starfall_hidden',
    nameVi: 'Tinh Lạc Thức',
    nameEn: 'Starfall Form',
    descVi: 'Nhát kiếm rơi như sao băng — thấy rồi thì đã muộn.',
    descEn: 'A cut that falls like a meteor — seen only after it lands.',
    requiredStage: 4,
    maxLevel: 1,
    power: 9,
    trainingBonus: 0,
    benefitVi: 'Đòn mạnh hơn cả Phá Phong Trảm.',
    benefitEn: 'Strikes harder than even the Peak-Cleaving Strike.',
    costVi: 'Vai như mang trời đè — hái thuốc tốn 6 khí.',
    costEn: 'The shoulders carry a falling sky — gathering drains 6 qi.',
    gatherQiDrain: 6,
    sourceItemId: 'sword_starfall_hidden_manual',
  },
  {
    id: 'sword_moonlight_edge_hidden',
    nameVi: 'Nguyệt Quang Nhận',
    nameEn: 'Moonlight Edge',
    descVi: 'Lưỡi kiếm mòn vẹn dưới trăng, không còn chỗ nào cùn.',
    descEn: 'An edge worn perfect under the moon; nothing left to dull.',
    requiredStage: 5,
    maxLevel: 1,
    power: 10,
    trainingBonus: 0,
    benefitVi: 'Nhát kiếm sắc nhất trong đời ngươi.',
    benefitEn: 'The sharpest cut you will ever own.',
    costVi: 'Đêm nào cũng thức canh kiếm — hái thuốc tốn 7 khí.',
    costEn: 'Sleepless nights spent on the blade — gathering drains 7 qi.',
    gatherQiDrain: 7,
    sourceItemId: 'sword_moonlight_edge_hidden_manual',
  },
  {
    id: 'aura_still_water_hidden',
    nameVi: 'Tĩnh Thủy Quyết',
    nameEn: 'Still-Water Art',
    descVi: 'Khí trong đan điền lặng như mặt hồ chết, mà sâu không đáy.',
    descEn: 'Qi lies still as a dead lake — and bottomless.',
    requiredStage: 4,
    maxLevel: 1,
    power: 7,
    trainingBonus: 2,
    benefitVi: 'Tu luyện nhanh và khí dày hơn.',
    benefitEn: 'Faster cultivation and a deeper well of qi.',
    costVi: 'Tâm quá tĩnh, quên cả giá thị trường — bán hàng lỗ 4 lượng.',
    costEn: 'A mind too still remembers no market price — every sale earns 4 gold less.',
    sellPenalty: 4,
    sourceItemId: 'aura_still_water_hidden_manual',
  },
  {
    id: 'aura_nine_sun_hidden',
    nameVi: 'Cửu Dương Khí Quán',
    nameEn: 'Nine-Sun Aura',
    descVi: 'Chín mặt trời nhỏ cháy trong lồng ngực — nóng, và sống sót.',
    descEn: 'Nine small suns burn in the chest — hot, and survivable.',
    requiredStage: 5,
    maxLevel: 1,
    power: 8,
    trainingBonus: 3,
    benefitVi: 'Tu luyện nhanh gấp mọi phép tắc thông thường.',
    benefitEn: 'Cultivation outruns every ordinary rule.',
    costVi: 'Cả người như lò lửa — bán hàng lỗ 5 lượng.',
    costEn: 'The whole body is a furnace — every sale earns 5 gold less.',
    sellPenalty: 5,
    sourceItemId: 'aura_nine_sun_hidden_manual',
  },
  {
    id: 'herbal_root_whisper_hidden',
    nameVi: 'Rễ Nghe Lời',
    nameEn: 'Root Whisper',
    descVi: 'Cỏ cây kể cho ngươi nghe chúng cần gì — và ngươi nghe được.',
    descEn: 'The plants tell you what they need — and you can hear it.',
    requiredStage: 4,
    maxLevel: 1,
    power: 6,
    trainingBonus: 3,
    benefitVi: 'Tu luyện nhanh nhất trong các phép dược.',
    benefitEn: 'The fastest cultivation of any herbal method.',
    costVi: 'Nghe cỏ nói chuyện cả ngày — bán hàng lỗ 4 lượng.',
    costEn: 'All day spent listening to grass — every sale earns 4 gold less.',
    sellPenalty: 4,
    sourceItemId: 'herbal_root_whisper_hidden_manual',
  },
  {
    id: 'herbal_grave_soil_hidden',
    nameVi: 'Mộ Thổ Thuật',
    nameEn: 'Grave-Soil Method',
    descVi: 'Học từ đất mộ — nơi cây mọc tốt nhất là nơi có nhiều chuyện đã kết.',
    descEn: 'Learned from grave-earth; the best growth happens where things end.',
    requiredStage: 5,
    maxLevel: 1,
    power: 7,
    trainingBonus: 4,
    benefitVi: 'Tu luyện nhanh chưa từng có.',
    benefitEn: 'Cultivation fast beyond precedent.',
    costVi: 'Bàn tay mang mùi đất mộ — hái thuốc tốn 3 khí.',
    costEn: 'Hands that smell of grave-earth — gathering drains 3 qi.',
    gatherQiDrain: 3,
    sourceItemId: 'herbal_grave_soil_hidden_manual',
  },
  {
    id: 'shadow_molt_hidden',
    nameVi: 'Thoát Ảnh Thức',
    nameEn: 'Shadow Molt Form',
    descVi: 'Bỏ lại một cái bóng cũ tại chỗ — kẻ địch cứ nói chuyện với nó.',
    descEn: 'Leave an old shadow behind; the enemy keeps negotiating with it.',
    requiredStage: 4,
    maxLevel: 1,
    power: 8,
    trainingBonus: 1,
    benefitVi: 'Đòn mạnh và bước né thêm tự tin.',
    benefitEn: 'Harder strikes, and a dodge that trusts itself.',
    costVi: 'Mỗi lần thoát xác là mất một lớp khí — hái thuốc tốn 6 khí.',
    costEn: 'Every molt peels away a layer of qi — gathering drains 6 qi.',
    gatherQiDrain: 6,
    sourceItemId: 'shadow_molt_hidden_manual',
  },
  {
    id: 'shadow_eclipse_step_hidden',
    nameVi: 'Thực Bộ',
    nameEn: 'Eclipse Step',
    descVi: 'Một bước đi giữa mặt trời và mặt trăng — không bên nào thấy ngươi.',
    descEn: 'A step taken between sun and moon; neither side sees you.',
    requiredStage: 5,
    maxLevel: 1,
    power: 9,
    trainingBonus: 1,
    benefitVi: 'Đòn mạnh nhất trong các phép thân pháp.',
    benefitEn: 'The hardest strike of any footwork art.',
    costVi: 'Mắt luôn nửa tối — hái thuốc tốn 7 khí.',
    costEn: 'The eyes stay half-dark — gathering drains 7 qi.',
    gatherQiDrain: 7,
    sourceItemId: 'shadow_eclipse_step_hidden_manual',
  },
  {
    id: 'thunder_gasp_hidden',
    nameVi: 'Lôi Hí Quyết',
    nameEn: 'Thunder-Gasp Art',
    descVi: 'Một hơi thở nuốt sét, một hơi thở phun lại — giữa hai hơi là cái chết.',
    descEn: 'One breath swallows the bolt, one breath returns it — between them lies death.',
    requiredStage: 4,
    maxLevel: 1,
    power: 10,
    trainingBonus: 0,
    benefitVi: 'Đòn mạnh nhất mà Hệ Thống từng ghi nhận ở ngươi.',
    benefitEn: 'The hardest strike the System has ever recorded on you.',
    costVi: 'Lồng ngực lúc nào cũng khét — hái thuốc tốn 8 khí.',
    costEn: 'The chest is always scorched — gathering drains 8 qi.',
    gatherQiDrain: 8,
    sourceItemId: 'thunder_gasp_hidden_manual',
  },
  // ── P1-1 system signature techniques: each System has one. The id carries
  // the system shortname so the reducer can gate "wrong system learns wrong
  // technique" without a per-System lookup table.
  {
    id: 'system_battle_signature',
    nameVi: 'Hệ Thống Chiến Đấu — Ấn Ký',
    nameEn: 'Battle System — Sigil',
    descVi: 'Hệ Thống khắc lên tay ngươi một vết dao. Từ nay đòn nào cũng có khía cắt.',
    descEn: 'The System carves a blade-mark on your palm. Every strike now carries a notch.',
    requiredStage: 2,
    maxLevel: 1,
    power: 6,
    trainingBonus: 0,
    benefitVi: 'Đòn chiến đấu mang hình Hệ Thống.',
    benefitEn: 'A strike that wears the System’s shape.',
    costVi: 'Vai mỏi — hái thuốc tốn 1 khí.',
    costEn: 'The shoulder tires — gathering drains 1 qi.',
    gatherQiDrain: 1,
    sourceItemId: 'beast_fang',
    requiredSystem: 'sys_battle',
  },
  {
    id: 'system_alchemy_signature',
    nameVi: 'Hệ Thống Luyện Đan — Ấn Ký',
    nameEn: 'Alchemy System — Sigil',
    descVi: 'Hệ Thống đóng dấu lên lò tay. Đan không chín cũng chín phần nào.',
    descEn: 'The System stamps a mark on your palm. Pills finish ripening even off-fire.',
    requiredStage: 2,
    maxLevel: 1,
    power: 3,
    trainingBonus: 2,
    benefitVi: 'Tu luyện nhanh hơn qua đường luyện đan.',
    benefitEn: 'Cultivation quickens through alchemy.',
    costVi: 'Mũi lúc nào cũng ngửi mùi thuốc — bán hàng lỗ 2 lượng.',
    costEn: 'The nose keeps smelling herbs — every sale earns 2 gold less.',
    sellPenalty: 2,
    sourceItemId: 'dew_pill',
    requiredSystem: 'sys_alchemy',
  },
  {
    id: 'system_merchant_signature',
    nameVi: 'Hệ Thống Hội Thương — Ấn Ký',
    nameEn: 'Merchant System — Sigil',
    descVi: 'Hệ Thống vạch sẵn con số trên mu bàn tay. Ngươi chỉ việc đọc.',
    descEn: 'The System draws the price on the back of your hand. You just read it.',
    requiredStage: 2,
    maxLevel: 1,
    power: 2,
    trainingBonus: 1,
    benefitVi: 'Đường buôn bán thuận hơn.',
    benefitEn: 'Trade runs smoother.',
    costVi: 'Đầu lúc nào cũng tính — hái thuốc tốn 2 khí.',
    costEn: 'The head keeps counting — gathering drains 2 qi.',
    gatherQiDrain: 2,
    sourceItemId: 'spirit_stone',
    requiredSystem: 'sys_merchant',
  },
  {
    id: 'system_lottery_signature',
    nameVi: 'Hệ Thống Cờ Bạc — Ấn Ký',
    nameEn: 'Lottery System — Sigil',
    descVi: 'Hệ Thống khắc một hình xúc xắc lên xương. Tung lên thì số hiện.',
    descEn: 'The System brands a die on your knuckle. Roll it and the pips show.',
    requiredStage: 2,
    maxLevel: 1,
    power: 4,
    trainingBonus: 0,
    benefitVi: 'Vận may theo mỗi cú tung.',
    benefitEn: 'Luck rides every toss.',
    costVi: 'Không phải lúc nào cũng trúng — bán hàng lỗ 1 lượng.',
    costEn: 'Not every toss wins — every sale earns 1 gold less.',
    sellPenalty: 1,
    sourceItemId: 'jade_charm',
    requiredSystem: 'sys_lottery',
  },
  {
    id: 'system_explorer_signature',
    nameVi: 'Hệ Thống Vạn Dặm — Ấn Ký',
    nameEn: 'Explorer System — Sigil',
    descVi: 'Hệ Thống vẽ la bàn lên mu chân. Bước tới đâu, đường về hiện ra.',
    descEn: 'The System draws a compass on the sole of your foot. The way home appears with every step.',
    requiredStage: 2,
    maxLevel: 1,
    power: 5,
    trainingBonus: 0,
    benefitVi: 'Bước xa không lạc.',
    benefitEn: 'Far steps never lose the way.',
    costVi: 'Bắp chân cứng — hái thuốc tốn 1 khí.',
    costEn: 'Calves stay tense — gathering drains 1 qi.',
    gatherQiDrain: 1,
    sourceItemId: 'trail_rations',
    requiredSystem: 'sys_explorer',
  },
  {
    id: 'system_assassin_signature',
    nameVi: 'Hệ Thống Ám Sát — Ấn Ký',
    nameEn: 'Assassin System — Sigil',
    descVi: 'Hệ Thống khắc mũi kim vào đốt ngón. Đường tới cổ họng kẻ thù đã vạch sẵn.',
    descEn: 'The System notches a needle into your fingertip. The path to an enemy’s throat is already drawn.',
    requiredStage: 2,
    maxLevel: 1,
    power: 7,
    trainingBonus: 0,
    benefitVi: 'Đòn trúng chỗ hiểm.',
    benefitEn: 'Strikes find the weak spot.',
    costVi: 'Tay lúc nào cũng lạnh — hái thuốc tốn 2 khí.',
    costEn: 'The hands stay cold — gathering drains 2 qi.',
    gatherQiDrain: 2,
    sourceItemId: 'beast_fang',
    requiredSystem: 'sys_assassin',
  },
  {
    id: 'system_healer_signature',
    nameVi: 'Hệ Thống Dưỡng Sinh — Ấn Ký',
    nameEn: 'Healer System — Sigil',
    descVi: 'Hệ Thống vẽ mạch lên cổ tay. Mỗi nhịp đập đo được, mỗi vết thương tính được.',
    descEn: 'The System traces meridians on your wrist. Each pulse is measured, each wound priced.',
    requiredStage: 2,
    maxLevel: 1,
    power: 2,
    trainingBonus: 3,
    benefitVi: 'Tu luyện qua đường dưỡng sinh.',
    benefitEn: 'Cultivation via the healer’s path.',
    costVi: 'Bàn tay lúc nào cũng sờ mạch — bán hàng lỗ 2 lượng.',
    costEn: 'Hands always reading pulses — every sale earns 2 gold less.',
    sellPenalty: 2,
    sourceItemId: 'pill_hp',
    requiredSystem: 'sys_healer',
  },
  {
    id: 'system_artisan_signature',
    nameVi: 'Hệ Thống Luyện Khí — Ấn Ký',
    nameEn: 'Artisan System — Sigil',
    descVi: 'Hệ Thống đóng dấu lên lòng bàn tay. Hễ chạm kim loại, lửa tự cháy đúng nhiệt.',
    descEn: 'The System brands your palm. Touch metal and the fire finds its heat.',
    requiredStage: 2,
    maxLevel: 1,
    power: 4,
    trainingBonus: 1,
    benefitVi: 'Rèn đúc thuận hơn.',
    benefitEn: 'Forge-work runs cleaner.',
    costVi: 'Tay lúc nào cũng nóng — hái thuốc tốn 1 khí.',
    costEn: 'Hands always warm — gathering drains 1 qi.',
    gatherQiDrain: 1,
    sourceItemId: 'cold_iron_ore',
    requiredSystem: 'sys_artisan',
  },
  {
    id: 'system_scholar_signature',
    nameVi: 'Hệ Thống Tàng Thư — Ấn Ký',
    nameEn: 'Scholar System — Sigil',
    descVi: 'Hệ Thống viết một chữ lên trán. Chữ ấy đọc xong thì trang sách lật.',
    descEn: 'The System writes one character on your brow. Read it and the page turns itself.',
    requiredStage: 2,
    maxLevel: 1,
    power: 3,
    trainingBonus: 3,
    benefitVi: 'Tu luyện nhanh qua sách cổ.',
    benefitEn: 'Cultivation accelerates through the old books.',
    costVi: 'Mắt mỏi — bán hàng lỗ 2 lượng.',
    costEn: 'Eyes tire — every sale earns 2 gold less.',
    sellPenalty: 2,
    sourceItemId: 'iron_skin_manual',
    requiredSystem: 'sys_scholar',
  },
  {
    id: 'system_void_signature',
    nameVi: 'Hệ Thống Hư Vô — Ấn Ký',
    nameEn: 'Void System — Sigil',
    descVi: 'Hệ Thống để lại một vệt sáng — rồi quên mất nó đã từng ở đó.',
    descEn: 'The System leaves one bright stroke — then forgets it was ever there.',
    requiredStage: 2,
    maxLevel: 1,
    power: 8,
    trainingBonus: 0,
    benefitVi: 'Một đòn mang hình dạng khe nứt.',
    benefitEn: 'A strike that wears the shape of a rift.',
    costVi: 'Tâm lúc nào cũng trống — hái thuốc tốn 4 khí.',
    costEn: 'The heart stays hollow — gathering drains 4 qi.',
    gatherQiDrain: 4,
    sourceItemId: 'rift_step_scroll',
    requiredSystem: 'sys_void',
  },
]

export const EQUIPMENT: EquipmentDef[] = [
  {
    id: 'wooden_staff',
    itemId: 'wooden_staff',
    slot: 'weapon',
    nameVi: 'Mộc Trượng Cũ',
    nameEn: 'Old Wooden Staff',
    descVi: 'Không sắc, nhưng rất thuyết phục khi vung đúng lúc.',
    descEn: 'Not sharp, but persuasive when swung at the right moment.',
    attackBonus: 2,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'tattered_robe',
    itemId: 'tattered_robe',
    slot: 'robe',
    nameVi: 'Áo Vải Vá',
    nameEn: 'Patched Cloth Robe',
    descVi: 'Vá nhiều hơn vải mới, vẫn che được gió.',
    descEn: 'More patch than cloth, still keeps the wind out.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'jade_charm',
    itemId: 'jade_charm',
    slot: 'accessory',
    nameVi: 'Ngọc Bội Hộ Tâm',
    nameEn: 'Heartward Jade Charm',
    descVi: 'Một miếng ngọc mát tay, giữ tâm không loạn lúc nguy.',
    descEn: 'Cool jade that steadies the heart when danger closes in.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 5,
  },
  {
    id: 'ironwood_saber',
    itemId: 'ironwood_saber',
    slot: 'weapon',
    nameVi: 'Thiết Mộc Đao',
    nameEn: 'Ironwood Saber',
    descVi: 'Thớ gỗ đen cứng đến mức yêu thú cũng biết né.',
    descEn: 'Blackwood grain so hard that beasts learn to dodge it.',
    attackBonus: 4,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'mistweave_vest',
    itemId: 'mistweave_vest',
    slot: 'robe',
    nameVi: 'Vân Văn Giáp Y',
    nameEn: 'Mistweave Vest',
    descVi: 'Sợi mây dệt kín vết rách trước khi gió kịp lùa vào.',
    descEn: 'Cloud-thread closes a tear before the wind can find it.',
    attackBonus: 0,
    defenseBonus: 3,
    qiBonus: 2,
  },
  {
    id: 'spirit_ring',
    itemId: 'spirit_ring',
    slot: 'accessory',
    nameVi: 'Nhẫn Tụ Linh',
    nameEn: 'Spirit-Gathering Ring',
    descVi: 'Một vòng bạc mờ, giữ lại chút khí lẽ ra đã tan.',
    descEn: 'A dim silver band that catches qi otherwise lost to the air.',
    attackBonus: 1,
    defenseBonus: 1,
    qiBonus: 10,
  },
  {
    id: 'cloudpiercer_spear',
    itemId: 'cloudpiercer_spear',
    slot: 'weapon',
    nameVi: 'Xuyên Vân Thương',
    nameEn: 'Cloudpiercer Spear',
    descVi: 'Mũi thương dài, thẳng và không có ý định xin lỗi.',
    descEn: 'Long, straight, and in no mood to apologize.',
    attackBonus: 7,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'bamboo_saber',
    itemId: 'bamboo_saber',
    slot: 'weapon',
    nameVi: 'Trúc Đao Thanh Mộc',
    nameEn: 'Greenwood Bamboo Saber',
    descVi: 'Gọn nhẹ cho người đi đường, ra đòn thì khỏi chê.',
    descEn: 'Light on the road, and nothing to sneer at when it lands.',
    attackBonus: 3,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'travelers_coat',
    itemId: 'travelers_coat',
    slot: 'robe',
    nameVi: 'Hành Lữ Bào',
    nameEn: "Traveler's Coat",
    descVi: 'Chặn gió núi trước khi nó kịp đọc tên ngươi.',
    descEn: 'Stops mountain wind before it learns your name.',
    attackBonus: 0,
    defenseBonus: 2,
    qiBonus: 1,
  },
  {
    id: 'bone_ward_charm',
    itemId: 'bone_ward_charm',
    slot: 'accessory',
    nameVi: 'Xương Phù Bội',
    nameEn: 'Bone Ward Charm',
    descVi: 'Chữ hộ thân khắc sâu, hơi lạnh canh chừng thay ngươi.',
    descEn: 'Deep-carved ward script; its cold watches over you.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 2,
  },
  {
    id: 'frostfang_saber',
    itemId: 'frostfang_saber',
    slot: 'weapon',
    nameVi: 'Hàn Nha Đao',
    nameEn: 'Frostfang Saber',
    descVi: 'Lạnh hơn lời từ chối của trưởng lão, và sắc hơn nhiều.',
    descEn: 'Colder than an elder\u2019s refusal, and far sharper.',
    attackBonus: 5,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'cloudveil_robe',
    itemId: 'cloudveil_robe',
    slot: 'robe',
    nameVi: 'Vân Vi Mạc',
    nameEn: 'Cloudveil Robe',
    descVi: 'Sương tự xếp lớp che khuyết điểm của linh căn phế.',
    descEn: 'Mist layers itself politely over a defective root\u2019s shortcomings.',
    attackBonus: 0,
    defenseBonus: 4,
    qiBonus: 4,
  },
  {
    id: 'moonstone_pendant',
    itemId: 'moonstone_pendant',
    slot: 'accessory',
    nameVi: 'Nguyệt Quang Bội',
    nameEn: 'Moonstone Pendant',
    descVi: 'Giữ lại một phần ánh trăng, cho mượn lúc tối nhất.',
    descEn: 'It keeps part of the moon and lends it back on your darkest nights.',
    attackBonus: 1,
    defenseBonus: 2,
    qiBonus: 8,
  },
]

export const ENEMIES: EnemyDef[] = [
  {
    id: 'mist_boar',
    locationId: 'misty_forest',
    nameVi: 'Trư Nha Sương',
    nameEn: 'Mist-Tusk Boar',
    descVi: 'Nó hắt hơi ra sương rồi lao tới như một tảng đá có răng.',
    descEn: 'It sneezes fog and charges like a rock with teeth.',
    maxHp: 32,
    attack: 7,
    rewardGold: 16,
    rewardItems: { spirit_herb: 1, beast_fang: 1 },
    element: 'Mộc',
    behaviorPattern: 'aggressive',
    requiredStage: 0,
    exp: 8,
  },
  {
    id: 'seal_wraith',
    locationId: 'sealed_cave',
    nameVi: 'Oán Linh Phong Ấn',
    nameEn: 'Sealbound Wraith',
    descVi: 'Một bóng người bị bùa cũ kéo dài thành làn khói lạnh.',
    descEn: 'An old ward stretches a human shadow into cold smoke.',
    maxHp: 54,
    attack: 11,
    rewardGold: 42,
    rewardItems: { old_manual: 1, moon_moss: 1, cold_iron_ore: 1 },
    element: 'Kim',
    behaviorPattern: 'defensive',
    defense: 2,
    requiredStage: 2,
    exp: 24,
  },
  {
    id: 'rift_hound',
    locationId: 'cursed_rift',
    nameVi: 'Liệt Khuyển Khe Nứt',
    nameEn: 'Rift Hound',
    descVi: 'Bốn chân nó đứng ở đây, tiếng gầm lại vọng từ nơi khác.',
    descEn: 'Its paws stand here; its growl arrives from somewhere else.',
    maxHp: 72,
    attack: 15,
    rewardGold: 80,
    rewardItems: { rift_step_scroll: 1, crane_feather: 1, cloudsilk_thread: 1 },
    element: 'Thổ',
    behaviorPattern: 'ranged',
    requiredStage: 3,
    exp: 48,
  },
  {
    id: 'white_tiger',
    locationId: 'misty_forest',
    nameVi: 'Bạch Hổ Lạc Đàn',
    nameEn: 'Stray White Tiger',
    descVi: 'Vằn trắng của nó lẫn vào sương, chỉ còn tiếng móng vuốt cào đất.',
    descEn: 'Its pale stripes dissolve into fog; only claws scraping earth remain.',
    maxHp: 46,
    attack: 10,
    rewardGold: 28,
    rewardItems: { beast_fang: 2 },
    element: 'Kim',
    behaviorPattern: 'counter',
    defense: 1,
    requiredStage: 1,
    exp: 14,
  },
  {
    id: 'venom_snake',
    locationId: 'herb_field',
    nameVi: 'Xà Độc Lục Văn',
    nameEn: 'Verdant Venom Snake',
    descVi: 'Nó cuộn dưới linh thảo, răng nanh còn trong hơn sương sớm.',
    descEn: 'It coils below spirit herbs, its fangs clearer than morning dew.',
    maxHp: 28,
    attack: 6,
    rewardGold: 14,
    rewardItems: { spirit_herb: 2 },
    element: 'Mộc',
    behaviorPattern: 'poison',
    requiredStage: 0,
    exp: 9,
    statusOnHit: 'poison',
  },
  {
    id: 'spirit_crane',
    locationId: 'cloud_peak',
    nameVi: 'Linh Hạc Tầm Vân',
    nameEn: 'Cloud-Seeking Spirit Crane',
    descVi: 'Nó vỗ cánh một cái, lưỡi gió đã đến trước bóng mình.',
    descEn: 'One wingbeat sends wind-blades ahead of its own shadow.',
    maxHp: 68,
    attack: 14,
    rewardGold: 72,
    rewardItems: { crane_feather: 2, cloudsilk_thread: 1 },
    element: 'Thủy',
    behaviorPattern: 'ranged',
    requiredStage: 3,
    exp: 42,
  },
  {
    id: 'shadow_leopard',
    locationId: 'misty_forest',
    nameVi: 'Hắc Báo Ẩn Ảnh',
    nameEn: 'Shadow Leopard',
    descVi: 'Bóng nó chạy trước thân; nhìn thấy là đã muộn một nhịp.',
    descEn: 'Its shadow runs ahead of its body; seeing it costs you a beat.',
    maxHp: 42,
    attack: 11,
    rewardGold: 30,
    rewardItems: { beast_fang: 1 },
    element: 'Kim',
    behaviorPattern: 'flee',
    requiredStage: 1,
    exp: 16,
  },
  {
    id: 'cave_bear',
    locationId: 'sealed_cave',
    nameVi: 'Thạch Hùng Thủ Hang',
    nameEn: 'Cave-Guarding Stone Bear',
    descVi: 'Lông nó bết bụi đá, mỗi cái vươn vai làm trần hang rơi cát.',
    descEn: 'Its fur is crusted with stone dust; each stretch shakes sand from the ceiling.',
    maxHp: 76,
    attack: 13,
    rewardGold: 64,
    rewardItems: { beast_fang: 2, cold_iron_ore: 1 },
    element: 'Thổ',
    behaviorPattern: 'defensive',
    defense: 4,
    requiredStage: 2,
    exp: 35,
  },
  {
    id: 'blaze_rock_beast',
    locationId: 'cursed_rift',
    nameVi: 'Thiêu Thạch Thú',
    nameEn: 'Blazestone Beast',
    descVi: 'Dung nham rỉ qua khe giáp đá của nó như máu của một ngọn núi.',
    descEn: 'Lava seeps through its stone plates like a mountain’s blood.',
    maxHp: 94,
    attack: 18,
    rewardGold: 96,
    rewardItems: { cold_iron_ore: 2, cloudsilk_thread: 1 },
    element: 'Hỏa',
    behaviorPattern: 'aggressive',
    defense: 3,
    requiredStage: 3,
    exp: 56,
  },
  {
    id: 'rival_swordsman',
    locationId: 'misty_forest',
    nameVi: 'Tán Tu Kiếm Khách',
    nameEn: 'Wandering Swordsman',
    descVi: 'Hắn xin đường bằng mũi kiếm, rồi quên mất cách trả lại.',
    descEn: 'He asks for the road with a sword point, then forgets to give it back.',
    maxHp: 48,
    attack: 12,
    rewardGold: 36,
    rewardItems: { bamboo_saber: 1 },
    element: 'Kim',
    behaviorPattern: 'counter',
    defense: 2,
    requiredStage: 1,
    exp: 18,
  },
  {
    id: 'lost_sect_disciple',
    locationId: 'herb_field',
    nameVi: 'Đệ Tử Tông Môn Lạc Đàn',
    nameEn: 'Lost Sect Disciple',
    descVi: 'Áo đồng phục rách ở tay, ánh mắt lại sắc như vừa nghe lệnh truy sát.',
    descEn: 'His uniform is torn at the sleeve, yet his gaze is sharp with a hunt order.',
    maxHp: 44,
    attack: 9,
    rewardGold: 32,
    rewardItems: { spirit_herb: 1, pill_qi: 1 },
    element: 'Mộc',
    behaviorPattern: 'defensive',
    defense: 2,
    requiredStage: 1,
    exp: 17,
  },
  {
    id: 'merchant_assassin',
    locationId: 'cloud_peak',
    nameVi: 'Thương Nhân Ám Sát',
    nameEn: 'Merchant Assassin',
    descVi: 'Hắn vẫn giữ nụ cười bán hàng khi kim độc đã rời tay áo.',
    descEn: 'He keeps a merchant’s smile even as poisoned needles leave his sleeve.',
    maxHp: 78,
    attack: 16,
    rewardGold: 110,
    rewardItems: { moonstone_pendant: 1 },
    element: 'Kim',
    behaviorPattern: 'poison',
    defense: 2,
    requiredStage: 3,
    exp: 50,
    statusOnHit: 'poison',
  },
  {
    id: 'rogue_alchemist',
    locationId: 'sealed_cave',
    nameVi: 'Luyện Dược Sư Gian',
    nameEn: 'Rogue Alchemist',
    descVi: 'Mùi thuốc cháy bám theo hắn; bình nào cũng có thứ không nên uống.',
    descEn: 'Burnt medicine clings to him; every vial holds something you should not drink.',
    maxHp: 62,
    attack: 12,
    rewardGold: 68,
    rewardItems: { pill_hp: 1, pill_qi: 1 },
    element: 'Hỏa',
    behaviorPattern: 'heal_self',
    requiredStage: 2,
    exp: 31,
  },
  {
    id: 'wandering_exorcist',
    locationId: 'cursed_rift',
    nameVi: 'Du Phương Trừ Tà Nhân',
    nameEn: 'Wandering Exorcist',
    descVi: 'Bùa vàng của y viết cho quỷ, nhưng ánh mắt lại đo đạc người sống.',
    descEn: 'His yellow wards are written for ghosts, but his eyes measure the living.',
    maxHp: 82,
    attack: 15,
    rewardGold: 92,
    rewardItems: { warding_talisman: 1, moon_moss: 1 },
    element: 'Thổ',
    behaviorPattern: 'heal_self',
    defense: 3,
    requiredStage: 3,
    exp: 52,
  },
  {
    id: 'heretic_master',
    locationId: 'sealed_cave',
    nameVi: 'Sư Phụ Tà Đạo',
    nameEn: 'Heretical Master',
    descVi: 'Ông ta gọi ngươi là đồ đệ trước khi hỏi tên, như thể đã chờ từ lâu.',
    descEn: 'He calls you disciple before asking your name, as if he has waited for years.',
    maxHp: 128,
    attack: 21,
    rewardGold: 180,
    rewardItems: { old_manual: 1, cloudveil_robe: 1 },
    element: 'Hỏa',
    behaviorPattern: 'summon',
    defense: 4,
    requiredStage: 3,
    exp: 90,
  },
  {
    id: 'yellow_robe',
    locationId: 'cursed_rift',
    nameVi: 'Hoàng Y Nhân',
    nameEn: 'Yellow-Robed Stranger',
    descVi: 'Áo vàng của hắn sạch đến mức khe nứt cũng không dám chạm bụi vào.',
    descEn: 'His yellow robe is so clean that even the rift will not touch it with dust.',
    maxHp: 150,
    attack: 23,
    rewardGold: 220,
    rewardItems: { rift_step_scroll: 1, moonstone_pendant: 1 },
    element: 'Thổ',
    behaviorPattern: 'drain_qi',
    defense: 5,
    requiredStage: 4,
    exp: 110,
  },
  {
    id: 'nine_tails',
    locationId: 'cloud_peak',
    nameVi: 'Cửu Vĩ Hồ',
    nameEn: 'Nine-Tailed Fox',
    descVi: 'Chín cái đuôi quét thành một vòng trăng non, mỗi cái đều biết nói dối.',
    descEn: 'Nine tails sweep into a crescent moon, and each knows how to lie.',
    maxHp: 116,
    attack: 20,
    rewardGold: 170,
    rewardItems: { crane_feather: 2, moonstone_pendant: 1 },
    element: 'Hỏa',
    behaviorPattern: 'summon',
    defense: 3,
    requiredStage: 3,
    exp: 84,
  },
  {
    id: 'poison_toad',
    locationId: 'herb_field',
    nameVi: 'Thiềm Thừ Độc Sương',
    nameEn: 'Poison-Mist Toad',
    descVi: 'Nó phun một làn sương tím lên lá non rồi chờ kẻ tham lam cúi xuống.',
    descEn: 'It breathes violet mist over young leaves and waits for greed to bend close.',
    maxHp: 38,
    attack: 8,
    rewardGold: 24,
    rewardItems: { spirit_herb: 1, moon_moss: 1 },
    element: 'Thủy',
    behaviorPattern: 'poison',
    requiredStage: 1,
    exp: 13,
    statusOnHit: 'poison',
  },
  // ── Combat 9+ behavior-driven foes ──────────────────────────────────────────
  // Fresh entries exercise the new behavior field: one leaves poison stacks on
  // defeat, the other enrages at half HP. Both also carry behaviorPattern so
  // the existing reply logic still fires (combat 9+ composes on top of it).
  {
    id: 'withering_centipede',
    locationId: 'cursed_rift',
    nameVi: 'Rết Ngàn Đốt',
    nameEn: 'Withering Centipede',
    descVi: 'Ngàn đốt nối nhau thành một sợi dây sống; càng đánh càng độc.',
    descEn: 'A thousand legs woven into a living rope — strike it and the venom deepens.',
    maxHp: 36,
    attack: 9,
    rewardGold: 30,
    rewardItems: { moon_moss: 2 },
    element: 'Mộc',
    behaviorPattern: 'poison',
    behavior: 'poison',
    requiredStage: 1,
    exp: 14,
    statusOnHit: 'poison',
  },
  {
    id: 'ember_lord_warden',
    locationId: 'frozen_peak',
    nameVi: 'Hỏa Vệ Đỉnh Tuyết',
    nameEn: 'Ember-Lord Warden',
    descVi: 'Một ngọn lửa già giữ đỉnh tuyết; máu càng mỏng, lửa càng dữ.',
    descEn: 'An old flame keeps the frozen peak; the thinner its blood, the fiercer it burns.',
    maxHp: 58,
    attack: 11,
    rewardGold: 48,
    rewardItems: { cold_iron_ore: 2, moon_moss: 1 },
    element: 'Hỏa',
    behaviorPattern: 'aggressive',
    behavior: 'phase2',
    requiredStage: 2,
    exp: 22,
  },
  {
    id: 'cloud_peak_sovereign',
    locationId: 'cloud_peak',
    nameVi: 'Vân Đỉnh Ma Quân',
    nameEn: 'Cloud Peak Sovereign',
    descVi: 'Chúa tể ẩn dật nơi đỉnh mây, khi sắp bại sẽ phục hồi chân nguyên cuồng nộ.',
    descEn: 'Sovereign of the clouds; when near defeat, rekindles supreme demonic origin.',
    maxHp: 120,
    attack: 16,
    rewardGold: 100,
    rewardItems: { cold_iron_ore: 5, moon_moss: 3 },
    element: 'Thủy',
    behaviorPattern: 'aggressive',
    behavior: 'boss',
    requiredStage: 3,
    exp: 50,
  },
]

export function getTalent(id: string): TalentDef | undefined {
  return TALENTS.find((talent) => talent.id === id)
}

export function getTechnique(id: string): TechniqueDef | undefined {
  return TECHNIQUES.find((technique) => technique.id === id)
}

export function getEquipmentByItem(itemId: string): EquipmentDef | undefined {
  return EQUIPMENT.find((equipment) => equipment.itemId === itemId)
}

export function getEnemy(id: string): EnemyDef | undefined {
  return ENEMIES.find((enemy) => enemy.id === id)
}

export function enemyAt(locationId: string): EnemyDef | undefined {
  return ENEMIES.find((enemy) => enemy.locationId === locationId)
}

// W6 combat depth: a location may hold several enemies. Only ones the player's
// stage can survive may spawn (requiredStage filter). The reducer picks a
// deterministic index from this pool; the UI reads the same pool. Boss
// story-flag gating (EnemyDef.requiredFlag) is queued for the W6 engine pass.
export function eligibleEnemiesAt(locationId: string, stage: number): EnemyDef[] {
  return ENEMIES.filter(
    (enemy) => enemy.locationId === locationId && stage >= (enemy.requiredStage ?? 0),
  )
}

// ── W6 combat-depth pure helpers ─────────────────────────────────────────────
// Ngũ Hành production cycle: Thủy khắc Hỏa, Hỏa khắc Kim, Kim khắc Mộc,
// Mộc khắc Thổ, Thổ khắc Thủy (attacker → defender it counters).
export const ELEMENT_COUNTERS: Record<Element, Element> = {
  Thủy: 'Hỏa',
  Hỏa: 'Kim',
  Kim: 'Mộc',
  Mộc: 'Thổ',
  Thổ: 'Thủy',
}

export const ELEMENT_NAMES: Record<Element, { vi: string; en: string }> = {
  Mộc: { vi: 'Mộc', en: 'Wood' },
  Kim: { vi: 'Kim', en: 'Metal' },
  Hỏa: { vi: 'Hỏa', en: 'Fire' },
  Thủy: { vi: 'Thủy', en: 'Water' },
  Thổ: { vi: 'Thổ', en: 'Earth' },
}

// The defective root is Mộc hỗn tạp (constants.ts); its combat element is Mộc.
export const PLAYER_ELEMENT: Element = 'Mộc'

// Attacker→defender damage multiplier: ×1.5 when the attacker counters the
// defender, ×0.7 on the reciprocal, ×1.0 otherwise.
export function elementMultiplier(attacker: Element, defender: Element): number {
  if (ELEMENT_COUNTERS[attacker] === defender) return 1.5
  if (ELEMENT_COUNTERS[defender] === attacker) return 0.7
  return 1.0
}

// Consecutive combat_attack multiplier: 2nd strike ×1.5, 3rd+ ×2.0. Streak 0
// (defend/use_item just reset it) and 1 both mean a plain strike.
export function comboMultiplier(streak: number): number {
  if (streak >= 3) return 2.0
  if (streak === 2) return 1.5
  return 1.0
}
