import type { EnemyDef, EquipmentDef, TalentDef, TechniqueDef } from '../engine/content-types'

// These tables are content-only: the reducer stores stable ids, so new content
// can be appended without rewriting a player's deterministic save.
export const TALENTS: TalentDef[] = [
  {
    id: 'tenacious_root',
    nameVi: 'Linh Căn Lì Lợm',
    nameEn: 'Stubborn Spirit Root',
    descVi: 'Linh căn phế không nhanh, nhưng chưa từng chịu tắt.',
    descEn: 'A defective root is slow, but refuses to go out.',
    requiredStage: 0,
    tier: 0,
    selectable: false,
    attackBonus: 0,
    defenseBonus: 1,
    trainingBonus: 0,
  },
  {
    id: 'iron_bones',
    nameVi: 'Gân Cốt Sắt',
    nameEn: 'Iron Bones',
    descVi: 'Đau thì đau, nhưng xương vẫn đứng thẳng.',
    descEn: 'Pain is pain; the bones still stand straight.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 2,
    trainingBonus: 0,
  },
  {
    id: 'wild_herbalist',
    nameVi: 'Dược Sư Cỏ Dại',
    nameEn: 'Wild Herbalist',
    descVi: 'Mỗi lần vận công, mùi cỏ thuốc khiến khí mạch ngoan hơn.',
    descEn: 'Herb scent makes the meridians a little more obedient.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 0,
    trainingBonus: 1,
  },
  {
    id: 'fortunate_fool',
    nameVi: 'Kẻ Ngốc Có Phúc',
    nameEn: 'Fortunate Fool',
    descVi: 'Ra đòn có vẻ hồ đồ, nhưng thường trúng đúng chỗ.',
    descEn: 'The swing looks foolish, yet often lands exactly right.',
    requiredStage: 1,
    tier: 1,
    selectable: true,
    attackBonus: 2,
    defenseBonus: 0,
    trainingBonus: 0,
  },
  {
    id: 'mist_listener',
    nameVi: 'Thính Sương',
    nameEn: 'Mist Listener',
    descVi: 'Nghe được nhịp thở trong màn sương trước khi nguy hiểm ló mặt.',
    descEn: 'You hear breath in the fog before danger shows its face.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 1,
    defenseBonus: 1,
    trainingBonus: 0,
  },
  {
    id: 'merchant_instinct',
    nameVi: 'Mắt Thương Nhân',
    nameEn: 'Merchant Instinct',
    descVi: 'Biết món nào đáng bán, và lúc nào nên im lặng mặc cả.',
    descEn: 'You know what to sell, and when silence is the better bargain.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 0,
    trainingBonus: 2,
  },
  {
    id: 'rune_scar',
    nameVi: 'Ấn Tích Phong Phù',
    nameEn: 'Seal Scar',
    descVi: 'Một vết phù cũ nhắc cơ thể ngươi cách chịu đòn.',
    descEn: 'An old ward-scar teaches your body how to take a hit.',
    requiredStage: 2,
    tier: 2,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 3,
    trainingBonus: 0,
  },
  {
    id: 'rift_gambler',
    nameVi: 'Kẻ Đánh Cược Khe Nứt',
    nameEn: 'Rift Gambler',
    descVi: 'Có người thấy vực sâu. Ngươi thấy một lần tung xúc xắc nữa.',
    descEn: 'Others see an abyss. You see one more roll of the dice.',
    requiredStage: 3,
    tier: 3,
    selectable: true,
    attackBonus: 3,
    defenseBonus: 0,
    trainingBonus: 0,
  },
  {
    id: 'cloud_heart',
    nameVi: 'Tâm Mây',
    nameEn: 'Cloud Heart',
    descVi: 'Tâm không tranh với gió, nên khí mạch đi xa hơn.',
    descEn: 'The heart does not argue with the wind, so qi travels farther.',
    requiredStage: 3,
    tier: 3,
    selectable: true,
    attackBonus: 0,
    defenseBonus: 1,
    trainingBonus: 2,
  },
  {
    id: 'peak_breaker',
    nameVi: 'Phá Phong',
    nameEn: 'Peak Breaker',
    descVi: 'Mỗi lần lùi nửa bước, ngươi học thêm cách bước tới.',
    descEn: 'Every half-step back teaches you how to step forward.',
    requiredStage: 4,
    tier: 4,
    selectable: true,
    attackBonus: 3,
    defenseBonus: 2,
    trainingBonus: 1,
  },
]

export const TECHNIQUES: TechniqueDef[] = [
  {
    id: 'basic_staff_form',
    nameVi: 'Mộc Trượng Thức',
    nameEn: 'Wooden Staff Form',
    descVi: 'Ba thế đơn giản để giữ yêu quái ngoài tầm răng.',
    descEn: 'Three plain forms for keeping monsters beyond biting range.',
    requiredStage: 0,
    maxLevel: 1,
    power: 2,
    trainingBonus: 0,
  },
  {
    id: 'crooked_circulation',
    nameVi: 'Chu Thiên Cong Queo',
    nameEn: 'Crooked Circulation',
    descVi: 'Đường khí sai sách vở, lại vừa khít linh căn phế.',
    descEn: 'Wrong by every textbook, yet perfect for a defective root.',
    requiredStage: 0,
    maxLevel: 1,
    power: 3,
    trainingBonus: 1,
    sourceItemId: 'old_manual',
  },
  {
    id: 'rift_step',
    nameVi: 'Khe Bộ',
    nameEn: 'Rift Step',
    descVi: 'Một bước lệch nhịp, né mũi vuốt ngay trước khi nó tới.',
    descEn: 'One off-beat step, dodging the claw just before it arrives.',
    requiredStage: 2,
    maxLevel: 1,
    power: 5,
    trainingBonus: 0,
    sourceItemId: 'rift_step_scroll',
  },
  {
    id: 'herbal_breath',
    nameVi: 'Dược Hơi Thuật',
    nameEn: 'Herbal Breath Method',
    descVi: 'Mượn mùi cỏ thuốc để dẫn khí qua những chỗ hay tắc.',
    descEn: 'Use herb-scent to guide qi through its habitual blockages.',
    requiredStage: 1,
    maxLevel: 1,
    power: 4,
    trainingBonus: 2,
    sourceItemId: 'herbal_breath_manual',
  },
  {
    id: 'iron_skin',
    nameVi: 'Thiết Bì Quyết',
    nameEn: 'Iron Skin Art',
    descVi: 'Da không thành sắt thật, nhưng đủ khiến cú đấm phải suy nghĩ.',
    descEn: 'Your skin is not truly iron, but a punch must think twice.',
    requiredStage: 1,
    maxLevel: 1,
    power: 3,
    trainingBonus: 0,
    sourceItemId: 'iron_skin_manual',
  },
  {
    id: 'cloudwalk',
    nameVi: 'Vân Du Bộ',
    nameEn: 'Cloudwalk Steps',
    descVi: 'Bước chân nhẹ như đang mượn đường của mây.',
    descEn: 'Your feet grow light, borrowing paths from the clouds.',
    requiredStage: 2,
    maxLevel: 1,
    power: 6,
    trainingBonus: 1,
    sourceItemId: 'cloudwalk_manual',
  },
  {
    id: 'peak_cleaver',
    nameVi: 'Phá Phong Trảm',
    nameEn: 'Peak-Cleaving Strike',
    descVi: 'Một nhát không chém núi, nhưng đủ chém đứt nỗi sợ.',
    descEn: 'It will not cleave a mountain, but it can split your fear.',
    requiredStage: 3,
    maxLevel: 1,
    power: 8,
    trainingBonus: 0,
    sourceItemId: 'peak_cleaver_manual',
  },
  {
    id: 'tide_breath',
    nameVi: 'Triều Tức Thuật',
    nameEn: 'Tide-Breath Method',
    descVi: 'Hít vào như thủy triều lên, ra đòn lúc nước rút.',
    descEn: 'Inhale as the tide rises; strike the moment it withdraws.',
    requiredStage: 2,
    maxLevel: 1,
    power: 6,
    trainingBonus: 2,
    sourceItemId: 'tide_breath_manual',
  },
  {
    id: 'stone_aegis',
    nameVi: 'Thạch Kính Quyết',
    nameEn: 'Stone Aegis Art',
    descVi: 'Đứng vững như bàn thạch; đòn tới thì đá chịu thay.',
    descEn: 'Stand like bedrock; let stone take what was aimed at you.',
    requiredStage: 3,
    maxLevel: 1,
    power: 7,
    trainingBonus: 1,
    sourceItemId: 'stone_aegis_manual',
  },
]

export const EQUIPMENT: EquipmentDef[] = [
  {
    id: 'wooden_staff',
    itemId: 'wooden_staff',
    slot: 'weapon',
    nameVi: 'Mộc Trượng Cũ',
    nameEn: 'Old Wooden Staff',
    descVi: 'Không sắc, nhưng rất thuyết phục khi vung đúng lúc.',
    descEn: 'Not sharp, but persuasive when swung at the right moment.',
    attackBonus: 2,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'tattered_robe',
    itemId: 'tattered_robe',
    slot: 'robe',
    nameVi: 'Áo Vải Vá',
    nameEn: 'Patched Cloth Robe',
    descVi: 'Vá nhiều hơn vải mới, vẫn che được gió.',
    descEn: 'More patch than cloth, still keeps the wind out.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'jade_charm',
    itemId: 'jade_charm',
    slot: 'accessory',
    nameVi: 'Ngọc Bội Hộ Tâm',
    nameEn: 'Heartward Jade Charm',
    descVi: 'Một miếng ngọc mát tay, giữ tâm không loạn lúc nguy.',
    descEn: 'Cool jade that steadies the heart when danger closes in.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 5,
  },
  {
    id: 'ironwood_saber',
    itemId: 'ironwood_saber',
    slot: 'weapon',
    nameVi: 'Thiết Mộc Đao',
    nameEn: 'Ironwood Saber',
    descVi: 'Thớ gỗ đen cứng đến mức yêu thú cũng biết né.',
    descEn: 'Blackwood grain so hard that beasts learn to dodge it.',
    attackBonus: 4,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'mistweave_vest',
    itemId: 'mistweave_vest',
    slot: 'robe',
    nameVi: 'Vân Văn Giáp Y',
    nameEn: 'Mistweave Vest',
    descVi: 'Sợi mây dệt kín vết rách trước khi gió kịp lùa vào.',
    descEn: 'Cloud-thread closes a tear before the wind can find it.',
    attackBonus: 0,
    defenseBonus: 3,
    qiBonus: 2,
  },
  {
    id: 'spirit_ring',
    itemId: 'spirit_ring',
    slot: 'accessory',
    nameVi: 'Nhẫn Tụ Linh',
    nameEn: 'Spirit-Gathering Ring',
    descVi: 'Một vòng bạc mờ, giữ lại chút khí lẽ ra đã tan.',
    descEn: 'A dim silver band that catches qi otherwise lost to the air.',
    attackBonus: 1,
    defenseBonus: 1,
    qiBonus: 10,
  },
  {
    id: 'cloudpiercer_spear',
    itemId: 'cloudpiercer_spear',
    slot: 'weapon',
    nameVi: 'Xuyên Vân Thương',
    nameEn: 'Cloudpiercer Spear',
    descVi: 'Mũi thương dài, thẳng và không có ý định xin lỗi.',
    descEn: 'Long, straight, and in no mood to apologize.',
    attackBonus: 7,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'bamboo_saber',
    itemId: 'bamboo_saber',
    slot: 'weapon',
    nameVi: 'Trúc Đao Thanh Mộc',
    nameEn: 'Greenwood Bamboo Saber',
    descVi: 'Gọn nhẹ cho người đi đường, ra đòn thì khỏi chê.',
    descEn: 'Light on the road, and nothing to sneer at when it lands.',
    attackBonus: 3,
    defenseBonus: 0,
    qiBonus: 0,
  },
  {
    id: 'travelers_coat',
    itemId: 'travelers_coat',
    slot: 'robe',
    nameVi: 'Hành Lữ Bào',
    nameEn: "Traveler's Coat",
    descVi: 'Chặn gió núi trước khi nó kịp đọc tên ngươi.',
    descEn: 'Stops mountain wind before it learns your name.',
    attackBonus: 0,
    defenseBonus: 2,
    qiBonus: 1,
  },
  {
    id: 'bone_ward_charm',
    itemId: 'bone_ward_charm',
    slot: 'accessory',
    nameVi: 'Xương Phù Bội',
    nameEn: 'Bone Ward Charm',
    descVi: 'Chữ hộ thân khắc sâu, hơi lạnh canh chừng thay ngươi.',
    descEn: 'Deep-carved ward script; its cold watches over you.',
    attackBonus: 0,
    defenseBonus: 1,
    qiBonus: 2,
  },
  {
    id: 'frostfang_saber',
    itemId: 'frostfang_saber',
    slot: 'weapon',
    nameVi: 'Hàn Nha Đao',
    nameEn: 'Frostfang Saber',
    descVi: 'Lạnh hơn lời từ chối của trưởng lão, và sắc hơn nhiều.',
    descEn: 'Colder than an elder\u2019s refusal, and far sharper.',
    attackBonus: 5,
    defenseBonus: 1,
    qiBonus: 0,
  },
  {
    id: 'cloudveil_robe',
    itemId: 'cloudveil_robe',
    slot: 'robe',
    nameVi: 'Vân Vi Mạc',
    nameEn: 'Cloudveil Robe',
    descVi: 'Sương tự xếp lớp che khuyết điểm của linh căn phế.',
    descEn: 'Mist layers itself politely over a defective root\u2019s shortcomings.',
    attackBonus: 0,
    defenseBonus: 4,
    qiBonus: 4,
  },
  {
    id: 'moonstone_pendant',
    itemId: 'moonstone_pendant',
    slot: 'accessory',
    nameVi: 'Nguyệt Quang Bội',
    nameEn: 'Moonstone Pendant',
    descVi: 'Giữ lại một phần ánh trăng, cho mượn lúc tối nhất.',
    descEn: 'It keeps part of the moon and lends it back on your darkest nights.',
    attackBonus: 1,
    defenseBonus: 2,
    qiBonus: 8,
  },
]

export const ENEMIES: EnemyDef[] = [
  {
    id: 'mist_boar',
    locationId: 'misty_forest',
    nameVi: 'Trư Nha Sương',
    nameEn: 'Mist-Tusk Boar',
    descVi: 'Nó hắt hơi ra sương rồi lao tới như một tảng đá có răng.',
    descEn: 'It sneezes fog and charges like a rock with teeth.',
    maxHp: 32,
    attack: 7,
    rewardGold: 16,
    rewardItems: { spirit_herb: 1, beast_fang: 1 },
  },
  {
    id: 'seal_wraith',
    locationId: 'sealed_cave',
    nameVi: 'Oán Linh Phong Ấn',
    nameEn: 'Sealbound Wraith',
    descVi: 'Một bóng người bị bùa cũ kéo dài thành làn khói lạnh.',
    descEn: 'An old ward stretches a human shadow into cold smoke.',
    maxHp: 54,
    attack: 11,
    rewardGold: 42,
    rewardItems: { old_manual: 1, moon_moss: 1, cold_iron_ore: 1 },
  },
  {
    id: 'rift_hound',
    locationId: 'cursed_rift',
    nameVi: 'Liệt Khuyển Khe Nứt',
    nameEn: 'Rift Hound',
    descVi: 'Bốn chân nó đứng ở đây, tiếng gầm lại vọng từ nơi khác.',
    descEn: 'Its paws stand here; its growl arrives from somewhere else.',
    maxHp: 72,
    attack: 15,
    rewardGold: 80,
    rewardItems: { rift_step_scroll: 1, crane_feather: 1, cloudsilk_thread: 1 },
  },
]

export function getTalent(id: string): TalentDef | undefined {
  return TALENTS.find((talent) => talent.id === id)
}

export function getTechnique(id: string): TechniqueDef | undefined {
  return TECHNIQUES.find((technique) => technique.id === id)
}

export function getEquipmentByItem(itemId: string): EquipmentDef | undefined {
  return EQUIPMENT.find((equipment) => equipment.itemId === itemId)
}

export function getEnemy(id: string): EnemyDef | undefined {
  return ENEMIES.find((enemy) => enemy.id === id)
}

export function enemyAt(locationId: string): EnemyDef | undefined {
  return ENEMIES.find((enemy) => enemy.locationId === locationId)
}
