// T11 — shop-per-NPC data. Declarative content only; lookup/pricing helpers
// live in src/engine/shopStock.ts (pure) and are wired into the buy/sell flow
// by T12. Currency tiers: common goods in gold (Vàng) / silver (Bạc), rare
// goods in Linh Thạch (LS). Engine-side rate: 1 LS = 10 gold = 100 silver.
// Every shop has >=1 priceSilver entry; sam / banker_tin / name_collector_tra
// have >=2 priceLS entries. Herbs are seasonal stock (stockDay: 'season').

export interface ShopEntry {
  itemId: string
  priceGold?: number
  priceSilver?: number
  priceLS?: number
  stockDay?: 'always' | 'season'
}

export interface ShopDef {
  npcId: string
  labelVi: string
  labelEn: string
  entries: ShopEntry[]
}

/** NPCs that "keep to themselves" and run no shop — frozen 6-id whitelist. */
export const NPCS_WITHOUT_SHOP: string[] = [
  'n_gardener_thin',
  'n_judge_quang',
  'n_ice_hermit_bang',
  'n_lost_soul_ha',
  'n_crane_spirit',
  'n_monk_nhu',
]

export const SHOPS: ShopDef[] = [
  {
    npcId: 'n_merchant_bao',
    labelVi: 'Quầy vũ khí của lão Bảo',
    labelEn: "Old Bao's Weapon Stall",
    entries: [
      { itemId: 'wooden_staff', priceGold: 15 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'cloudpiercer_spear', priceGold: 190 },
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'cloudveil_robe', priceGold: 280 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
    ],
  },
  {
    npcId: 'n_cook_phung',
    labelVi: 'Bếp nàng Phụng',
    labelEn: "Phung's Kitchen",
    entries: [
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
    ],
  },
  {
    npcId: 'n_smith_duc',
    labelVi: 'Lò rèn của thợ Đức',
    labelEn: "Smith Duc's Forge",
    entries: [
      { itemId: 'cold_iron_ore', priceSilver: 180 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'cloudpiercer_spear', priceGold: 190 },
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'cloudveil_robe', priceGold: 280 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
    ],
  },
    {
    npcId: 'n_scholar_minh',
    labelVi: 'Kệ sách của Học giả Minh',
    labelEn: "Scholar Minh's Study Shelf",
    entries: [
      { itemId: 'herbal_breath_manual', priceGold: 90 },
      { itemId: 'iron_skin_manual', priceGold: 110 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'peak_cleaver_manual', priceGold: 170 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'stone_aegis_manual', priceGold: 220 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_cloud_lotus', priceGold: 70 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_pedlar_quyen',
    labelVi: 'Rổ bùa ngọc của Quỳnh',
    labelEn: "Pedlar Quyen's Talisman Basket",
    entries: [
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_silk_dew', priceGold: 55 },
      { itemId: 'pill_hybrid_wind_heart', priceGold: 65 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'tattered_robe', priceGold: 8 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_tea_ma',
    labelVi: 'Quầy trà của bà Mã',
    labelEn: "Madam Ma's Tea Counter",
    entries: [
      { itemId: 'plum_qi_wine', priceSilver: 80 },
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
    {
    npcId: 'n_tailor_yen',
    labelVi: 'Tiệm may của Yến',
    labelEn: "Tailor Yen's Shop",
    entries: [
      { itemId: 'tattered_robe', priceSilver: 500 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'cloudveil_robe', priceGold: 280 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
    ],
  },
  {
    npcId: 'n_fortune_lien',
    labelVi: 'Bàn vé số của cô Liên',
    labelEn: "Fortune Lien's Lottery Table",
    entries: [
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_banker_tin',
    labelVi: 'Quầy đổi bạc của chủ tiệm Tín',
    labelEn: "Banker Tin's Money Counter",
    entries: [
      { itemId: 'silver_coin', priceGold: 1 },
      { itemId: 'spirit_stone', priceGold: 9 },
      { itemId: 'gold_note', priceSilver: 95 },
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'pill_ls_marrow', priceLS: 3 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
    ],
  },
    {
    npcId: 'n_master_vo',
    labelVi: 'Vật phẩm tông môn của Sư phụ Võ',
    labelEn: "Master Vo's Sect Wares",
    entries: [
      { itemId: 'iron_skin_manual', priceGold: 110 },
      { itemId: 'peak_cleaver_manual', priceGold: 170 },
      { itemId: 'stone_aegis_manual', priceGold: 220 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'pill_hp', priceSilver: 120 },
    ],
  },
  {
    npcId: 'n_rival_khoa',
    labelVi: 'Kèo cược của Khoa',
    labelEn: "Rival Khoa's Wager Goods",
    entries: [
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'cloudpiercer_spear', priceGold: 190 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceSilver: 100 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'beast_fang', priceGold: 28 },
    ],
  },
  {
    npcId: 'n_senior_lan',
    labelVi: 'Giá đồ của đàn tỷ Lan',
    labelEn: "Senior Lan's Shelf",
    entries: [
      { itemId: 'herbal_breath_manual', priceGold: 90 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'pill_hybrid_silk_heart', priceGold: 55 },
      { itemId: 'pill_hybrid_moon_fire', priceGold: 75 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
    {
    npcId: 'n_keeper_anh',
    labelVi: 'Tủ đồ của thủ giá Anh',
    labelEn: "Keeper Anh's Cabinet",
    entries: [
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_earth_fire', priceGold: 65 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
  {
    npcId: 'n_monk_thien',
    labelVi: 'Bàn trà của thiền sư Thiện',
    labelEn: "Monk Thien's Tea Table",
    entries: [
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'pill_hybrid_dew_daisy', priceGold: 55 },
      { itemId: 'trail_rations', priceSilver: 30 },
    ],
  },
  {
    npcId: 'n_alchemist_sam',
    labelVi: 'Đan phòng của Lô Sam',
    labelEn: "Alchemist Sam's Pill Room",
    entries: [
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'marrow_gather_pill', priceGold: 95 },
      { itemId: 'pill_hybrid_silk_heart', priceGold: 55 },
      { itemId: 'pill_hybrid_blood_dew', priceGold: 60 },
      { itemId: 'pill_hybrid_moon_fire', priceGold: 75 },
      { itemId: 'pill_hybrid_marrow_bamboo', priceGold: 85 },
      { itemId: 'pill_hybrid_ice_ginseng', priceGold: 80 },
      { itemId: 'herb_blood_ginseng', priceGold: 40, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'pill_ls_marrow', priceLS: 3 },
      { itemId: 'moon_moss', priceSilver: 500 },
    ],
  },
    {
    npcId: 'n_pavilion_disciple_anh',
    labelVi: 'Khay đồ của đệ tử Thanh Vân Các',
    labelEn: "Pavilion Disciple Anh's Tray",
    entries: [
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'stone_aegis_manual', priceGold: 220 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'pill_hp', priceSilver: 90 },
    ],
  },
  {
    npcId: 'n_elder_meihua',
    labelVi: 'Rương đồ của cụ Mai Hoa',
    labelEn: "Elder Meihua's Chest",
    entries: [
      { itemId: 'herbal_breath_manual', priceGold: 90 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'iron_skin_manual', priceGold: 110 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
  {
    npcId: 'n_storyteller_ngo',
    labelVi: 'Vật lạ của ông kể chuyện Ngô',
    labelEn: "Storyteller Ngo's Curios",
    entries: [
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_moon_marrow', priceGold: 70 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
    {
    npcId: 'n_innkeeper_hanh',
    labelVi: 'Quầy thuê giường của chủ trọ Hạnh',
    labelEn: "Innkeeper Hanh's Lodging Counter",
    entries: [
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceSilver: 80 },
      { itemId: 'pill_hp', priceSilver: 120 },
      { itemId: 'pill_qi', priceSilver: 180 },
      { itemId: 'moon_moss', priceSilver: 50 },
      { itemId: 'jade_charm', priceSilver: 1500 },
      { itemId: 'herb_cloud_dew', priceSilver: 2000 },
      { itemId: 'dew_pill', priceSilver: 3000 },
      { itemId: 'travelers_coat', priceSilver: 3600 },
      { itemId: 'tattered_robe', priceSilver: 700 },
      { itemId: 'crane_feather', priceSilver: 5500 },
      { itemId: 'beast_fang', priceSilver: 2600 },
    ],
  },
  {
    npcId: 'n_guard_truong',
    labelVi: 'Đồ dùng của cảnh vệ Trường',
    labelEn: "Guard Truong's Kit",
    entries: [
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'plum_qi_wine', priceSilver: 80 },
    ],
  },
  {
    npcId: 'n_kid_xiaobao',
    labelVi: 'Túi đồ của bé Tiểu Bảo',
    labelEn: "Xiaobao's Little Pouch",
    entries: [
      { itemId: 'trail_rations', priceSilver: 30 },
      { itemId: 'plum_qi_wine', priceSilver: 60 },
      { itemId: 'jade_charm', priceSilver: 1200 },
      { itemId: 'moon_moss', priceSilver: 40 },
      { itemId: 'bait_bee_queen', priceGold: 12 },
      { itemId: 'bait_turtle_imp', priceGold: 10 },
      { itemId: 'bait_white_tiger', priceGold: 25 },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'bamboo_saber', priceGold: 30 },
    ],
  },
    {
    npcId: 'n_farmer_tu',
    labelVi: 'Hạt giống của ông Tư',
    labelEn: "Farmer Tu's Seeds",
    entries: [
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'moon_moss', priceSilver: 50 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'silver_coin', priceGold: 1 },
    ],
  },
  {
    npcId: 'n_woodcutter_bong',
    labelVi: 'Đồ đốn gỗ của Bông',
    labelEn: "Woodcutter Bong's Goods",
    entries: [
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'wooden_staff', priceGold: 15 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceSilver: 90 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'travelers_coat', priceGold: 40 },
    ],
  },
  {
    npcId: 'n_herbalist_dan',
    labelVi: 'Sạp dược liệu của dược sư Đan',
    labelEn: "Herbalist Dan's Stall",
    entries: [
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_blood_ginseng', priceGold: 40, stockDay: 'season' },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'moon_moss', priceSilver: 50 },
      { itemId: 'pill_hp', priceGold: 9 },
    ],
  },
    {
    npcId: 'n_gatherer_hue',
    labelVi: 'Rổ hái của Huệ',
    labelEn: "Gatherer Hue's Basket",
    entries: [
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
  {
    npcId: 'n_ox_cart_hien',
    labelVi: 'Đoàn xe bò của Hiền',
    labelEn: "Hien's Ox Cart",
    entries: [
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moon_moss', priceGold: 7 },
    ],
  },
  {
    npcId: 'n_hunter_son',
    labelVi: 'Bẫy và mồi của thợ săn Sơn',
    labelEn: "Hunter Son's Traps",
    entries: [
      { itemId: 'bait_grey_wolf', priceGold: 15 },
      { itemId: 'bait_fox_spirit', priceGold: 18 },
      { itemId: 'bait_blaze_hound', priceGold: 20 },
      { itemId: 'bait_frost_boar', priceGold: 20 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'cold_iron_ore', priceGold: 22 },
    ],
  },
    {
    npcId: 'n_rogue_cultivator_nhat',
    labelVi: 'Hàng chợ đen của tu sĩ Nhật',
    labelEn: "Nhat's Black-market Goods",
    entries: [
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_earth_fire', priceGold: 65 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_hermit_coc',
    labelVi: 'Đồ trong hang ẩn sĩ Cốc',
    labelEn: "Hermit Coc's Cave Goods",
    entries: [
      { itemId: 'stone_aegis_manual', priceGold: 220 },
      { itemId: 'pill_hybrid_banner_daisy', priceGold: 60 },
      { itemId: 'iron_skin_manual', priceGold: 110 },
      { itemId: 'pill_hybrid_earth_fire', priceGold: 65 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'pill_hybrid_wind_heart', priceGold: 65 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'pill_ls_marrow', priceLS: 3 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_exile_ba',
    labelVi: 'Đồ bỏ lại của kẻ lưu đày Ba',
    labelEn: "Exile Ba's Leftovers",
    entries: [
      { itemId: 'tattered_robe', priceGold: 8 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'plum_qi_wine', priceSilver: 70 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
    {
    npcId: 'n_exorcist_diem',
    labelVi: 'Bùa trừ tà của đạo sĩ Diễm',
    labelEn: "Exorcist Diem's Wards",
    entries: [
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_dew_daisy', priceGold: 55 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
  {
    npcId: 'n_wandering_blade_phong',
    labelVi: 'Đao và rượu của kiếm khách Phong',
    labelEn: "Blade Phong's Gear",
    entries: [
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'cloudpiercer_spear', priceGold: 190 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'plum_qi_wine', priceSilver: 90 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
    ],
  },
  {
    npcId: 'n_herbalist_lan',
    labelVi: 'Vườn thuốc của dược sư Lan',
    labelEn: "Herbalist Lan's Garden",
    entries: [
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'herb_blood_ginseng', priceGold: 40, stockDay: 'season' },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'pill_hybrid_blood_dew', priceGold: 60 },
      { itemId: 'pill_hybrid_moon_fire', priceGold: 75 },
      { itemId: 'pill_hybrid_ice_ginseng', priceGold: 80 },
      { itemId: 'pill_hybrid_cloud_lotus', priceGold: 70 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
    {
    npcId: 'n_archivist_thu',
    labelVi: 'Kệ sách của thủ thư Thư',
    labelEn: "Archivist Thu's Bookshelf",
    entries: [
      { itemId: 'herbal_breath_manual', priceGold: 90 },
      { itemId: 'iron_skin_manual', priceGold: 110 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'peak_cleaver_manual', priceGold: 170 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'stone_aegis_manual', priceGold: 220 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'pill_hybrid_silk_heart', priceGold: 55 },
      { itemId: 'pill_hybrid_cloud_lotus', priceGold: 70 },
      { itemId: 'pill_hybrid_moon_marrow', priceGold: 70 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_relic_hunter_bach',
    labelVi: 'Cổ vật của thợ săn cổ vật Bạch',
    labelEn: "Relic Hunter Bach's Finds",
    entries: [
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
  {
    npcId: 'n_ash_priest_cuu',
    labelVi: 'Nghi lễ của tư tế tro Cửu',
    labelEn: "Ash Priest Cuu's Rites",
    entries: [
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'pill_ls_marrow', priceLS: 3 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
    {
    npcId: 'n_name_collector_tra',
    labelVi: 'Cửa hàng ký ức của Trà',
    labelEn: "Tra's Memory Shop",
    entries: [
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'pill_hybrid_silk_dew', priceGold: 55 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
  {
    npcId: 'n_beast_tamer_le',
    labelVi: 'Mồi của huấn thú sư Lễ',
    labelEn: "Beast Tamer Le's Baits",
    entries: [
      { itemId: 'bait_white_tiger', priceGold: 25 },
      { itemId: 'bait_grey_wolf', priceGold: 15 },
      { itemId: 'bait_crane_spirit', priceGold: 18 },
      { itemId: 'bait_fox_spirit', priceGold: 18 },
      { itemId: 'bait_dragon_serpent', priceGold: 24 },
      { itemId: 'bait_baby_qilin', priceGold: 28 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_tamer_hac',
    labelVi: 'Trường huấn thú của Hạc',
    labelEn: "Tamer Hac's Yard",
    entries: [
      { itemId: 'bait_frost_boar', priceGold: 20 },
      { itemId: 'bait_blaze_hound', priceGold: 20 },
      { itemId: 'bait_bee_queen', priceGold: 12 },
      { itemId: 'bait_peach_spirit', priceGold: 16 },
      { itemId: 'bait_turtle_imp', priceGold: 10 },
      { itemId: 'bait_storm_bird', priceGold: 22 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moon_moss', priceSilver: 50 },
    ],
  },
    {
    npcId: 'n_beast_singer_my',
    labelVi: 'Đồ của người hát gọi thú Mỹ',
    labelEn: "Beast Singer My's Songgoods",
    entries: [
      { itemId: 'bait_crane_spirit', priceGold: 18 },
      { itemId: 'bait_peach_spirit', priceGold: 16 },
      { itemId: 'bait_bee_queen', priceGold: 12 },
      { itemId: 'bait_dragon_serpent', priceGold: 24 },
      { itemId: 'bait_baby_qilin', priceGold: 28 },
      { itemId: 'bait_storm_bird', priceGold: 22 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'plum_qi_wine', priceSilver: 70 },
    ],
  },
  {
    npcId: 'n_broker_tieu',
    labelVi: 'Sạp môi giới của Tiếu',
    labelEn: "Broker Tieu's Booth",
    entries: [
      { itemId: 'silver_coin', priceGold: 1 },
      { itemId: 'spirit_stone', priceGold: 9 },
      { itemId: 'gold_note', priceSilver: 95 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
    ],
  },
  {
    npcId: 'n_swordsman_diep',
    labelVi: 'Kiếm và rượu của kiếm khách Điệp',
    labelEn: "Swordsman Diep's Gear",
    entries: [
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'ironwood_saber', priceGold: 70 },
      { itemId: 'cloudpiercer_spear', priceGold: 190 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'plum_qi_wine', priceSilver: 90 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'tide_breath_manual', priceGold: 200 },
    ],
  },
    {
    npcId: 'n_fisher_yen',
    labelVi: 'Cần và mồi của ngư phu Yến',
    labelEn: "Fisher Yen's Tackle",
    entries: [
      { itemId: 'bait_turtle_imp', priceGold: 10 },
      { itemId: 'bait_dragon_serpent', priceGold: 24 },
      { itemId: 'bait_crane_spirit', priceGold: 18 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'bamboo_saber', priceGold: 30 },
    ],
  },
  {
    npcId: 'n_dice_master_luc',
    labelVi: 'Bàn xúc xắc của bậc thầy Lục',
    labelEn: "Dice Master Luc's Table",
    entries: [
      { itemId: 'ninefold_pill', priceGold: 130 },
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'silver_coin', priceGold: 1 },
      { itemId: 'trail_rations', priceSilver: 40 },
    ],
  },
  {
    npcId: 'n_map_seller_man',
    labelVi: 'Bản đồ cổ của người bán bản đồ Mận',
    labelEn: "Map Seller Man's Maps",
    entries: [
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_hybrid_wind_heart', priceGold: 65 },
      { itemId: 'cloudwalk_manual', priceGold: 140 },
      { itemId: 'pill_hybrid_cloud_lotus', priceGold: 70 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
    ],
  },
    {
    npcId: 'n_caravan_duong',
    labelVi: 'Hàng hoá của thủ lĩnh thương đoàn Dương',
    labelEn: "Caravan Duong's Wares",
    entries: [
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'silver_coin', priceGold: 1 },
      { itemId: 'spirit_stone', priceGold: 9 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'beast_fang', priceGold: 28 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'gold_note', priceSilver: 95 },
    ],
  },
  {
    npcId: 'n_dune_guide_sa',
    labelVi: 'Đồ dẫn đường sa mạc của Sa',
    labelEn: "Dune Guide Sa's Kit",
    entries: [
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'trail_rations', priceGold: 6 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'bait_blaze_hound', priceGold: 20 },
      { itemId: 'bait_frost_boar', priceGold: 20 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'plum_qi_wine', priceSilver: 70 },
    ],
  },
  {
    npcId: 'n_snow_guard_han',
    labelVi: 'Đồ giữ tuyết của vệ binh Hàn',
    labelEn: "Snow Guard Han's Kit",
    entries: [
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'mistweave_vest', priceGold: 55 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'herb_ice_heart', priceGold: 28, stockDay: 'season' },
      { itemId: 'bait_frost_boar', priceGold: 20 },
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
    ],
  },
    {
    npcId: 'n_lake_keeper_trang',
    labelVi: 'Đồ giữ hồ của Trang',
    labelEn: "Lake Keeper Trang's Goods",
    entries: [
      { itemId: 'tide_breath_manual', priceGold: 200 },
      { itemId: 'pill_hybrid_dew_daisy', priceGold: 55 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'herb_moon_shard', priceGold: 30, stockDay: 'season' },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
  {
    npcId: 'n_ferryman_cau',
    labelVi: 'Thuyền của phu đò Cậu',
    labelEn: "Ferryman Cau's Boat",
    entries: [
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'travelers_coat', priceGold: 40 },
      { itemId: 'bait_turtle_imp', priceGold: 10 },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'herb_cloud_dew', priceGold: 24, stockDay: 'season' },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'bamboo_saber', priceGold: 30 },
      { itemId: 'silver_coin', priceGold: 1 },
      { itemId: 'dew_pill', priceGold: 35 },
    ],
  },
  {
    npcId: 'n_auctioneer_hoan',
    labelVi: 'Sàn đấu giá của Hoàn',
    labelEn: "Auctioneer Hoan's Floor",
    entries: [
      { itemId: 'pill_ls_ninefold', priceLS: 4 },
      { itemId: 'pill_ls_marrow', priceLS: 3 },
      { itemId: 'pill_ls_iron', priceLS: 3 },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'gold_note', priceSilver: 95 },
      { itemId: 'spirit_stone', priceGold: 9 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'frostfang_saber', priceGold: 340 },
      { itemId: 'cloudveil_robe', priceGold: 280 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'jade_charm', priceGold: 18 },
    ],
  },
    {
    npcId: 'n_gardener_vien',
    labelVi: 'Vườn ươm của người giữ vườn Viên',
    labelEn: "Gardener Vien's Nursery",
    entries: [
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_white_banner', priceGold: 26, stockDay: 'season' },
      { itemId: 'herb_green_vine', priceGold: 16, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'herb_earth_marrow', priceGold: 28, stockDay: 'season' },
      { itemId: 'herb_wind_bamboo', priceGold: 20, stockDay: 'season' },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'moon_moss', priceGold: 7 },
      { itemId: 'trail_rations', priceSilver: 40 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'silver_coin', priceGold: 1 },
    ],
  },
  {
    npcId: 'n_beekeeper_oanh',
    labelVi: 'Mật linh của bà nuôi ong Oanh',
    labelEn: "Beekeeper Oanh's Hive",
    entries: [
      { itemId: 'herb_hong_silk', priceGold: 18, stockDay: 'season' },
      { itemId: 'herb_fire_lotus', priceGold: 34, stockDay: 'season' },
      { itemId: 'herb_purple_daisy', priceGold: 22, stockDay: 'season' },
      { itemId: 'trail_rations', priceSilver: 30 },
      { itemId: 'plum_qi_wine', priceGold: 12 },
      { itemId: 'pill_hp', priceGold: 9 },
      { itemId: 'dew_pill', priceGold: 35 },
      { itemId: 'bait_bee_queen', priceGold: 12 },
      { itemId: 'bait_peach_spirit', priceGold: 16 },
      { itemId: 'crane_feather', priceGold: 60 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
    ],
  },
  {
    npcId: 'n_ward_carver_khue',
    labelVi: 'Bàn khắc bùa của thợ Khuê',
    labelEn: "Ward Carver Khue's Bench",
    entries: [
      { itemId: 'bone_ward_charm', priceGold: 26 },
      { itemId: 'jade_charm', priceGold: 18 },
      { itemId: 'spirit_ring', priceGold: 160 },
      { itemId: 'moonstone_pendant', priceGold: 210 },
      { itemId: 'rift_step_scroll', priceGold: 120 },
      { itemId: 'pill_ls_cloud', priceLS: 5 },
      { itemId: 'pill_qi', priceGold: 14 },
      { itemId: 'herb_void_bamboo', priceGold: 45, stockDay: 'season' },
      { itemId: 'cold_iron_ore', priceGold: 22 },
      { itemId: 'cloudsilk_thread', priceGold: 45 },
      { itemId: 'plum_qi_wine', priceSilver: 70 },
    ],
  },
]

















