import type { SkillNode } from '../engine/content-types'

// 5 branches × 20 tiers = 100 nodes. Each branch opens at tier 1 with stage
// requirement 0; later tiers gate on the stage, a level threshold, or a
// previously-known technique. Costs in `cost.skillPoints` are calibrated so a
// 5-stage run can afford roughly one branch's worth of unlocks; optional gold
// and item requirements give the higher tiers real world gates without
// inventing new currencies.
//
// Effects use the union from SkillNode.effect.kind. Numeric `value` is the
// flat bonus the node contributes; kind-specific fields (aoeRadius, status,
// stack, etc.) live alongside `value` as additional `key: number | string`
// pairs so the reducer can read whichever it needs.
//
// `conflictsWith` is symmetric by construction: if A conflicts with B then B
// conflicts with A. Conflicts only mark an effect theme, not a numeric cap —
// picking both is rejected with `ITEM_UNAVAILABLE` rather than halved.

const branches = ['sword', 'aura', 'herbal', 'shadow', 'thunder'] as const

type Branch = (typeof branches)[number]

interface Seed {
  id: string
  branch: Branch
  tier: number
  nameVi: string
  nameEn: string
  descVi: string
  descEn: string
  cost: SkillNode['cost']
  require: SkillNode['require']
  effect: SkillNode['effect']
  conflictsWith?: string[]
}

const SEEDS: Seed[] = [
  // ── Kiếm (Sword): sát thương, crit, đòn chí mạng, hồi hp khi giết ─────
  { id: 'sword_t1', branch: 'sword', tier: 1, nameVi: 'Lưỡi Kiếm Khai Môn', nameEn: 'First Blade',
    descVi: 'Học cách mở một đường kiếm ngắn nhưng chắc.', descEn: 'Open a short, sure sword line.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'attack', value: 1 } },
  { id: 'sword_t2', branch: 'sword', tier: 2, nameVi: 'Cưa Cổ Tay', nameEn: 'Wrist-Saw',
    descVi: 'Đòn cắt ngang, chỉ cần đúng cổ tay là đủ.', descEn: 'A slash across the wrist is enough.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'attack', value: 1 } },
  { id: 'sword_t3', branch: 'sword', tier: 3, nameVi: 'Mũi Kiếm Lạnh', nameEn: 'Cold Point',
    descVi: 'Giữ mũi kiếm đủ lạnh để da đối phương cứng lại.', descEn: 'Keep the tip cold enough to harden the enemy\'s skin.',
    cost: { skillPoints: 1 }, require: { stage: 0, techniques: ['basic_staff_form'] },
    effect: { kind: 'attack', value: 2 } },
  { id: 'sword_t4', branch: 'sword', tier: 4, nameVi: 'Trảm Theo Mạch', nameEn: 'Meridian Slash',
    descVi: 'Đường kiếm đi theo mạch khí, làm tay địch tê cứng.', descEn: 'Follow the meridian; the enemy\'s hand goes numb.',
    cost: { skillPoints: 1, gold: 40 }, require: { stage: 0 },
    effect: { kind: 'status', value: 1, status: 'numb' } },
  { id: 'sword_t5', branch: 'sword', tier: 5, nameVi: 'Kiếm Khí Rò Rỉ', nameEn: 'Leaking Edge',
    descVi: 'Kiếm khí không giấu được, nhưng đủ khiến địch tránh bước.', descEn: 'Edge qi cannot be hidden — it still makes the enemy sidestep.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'attack', value: 2 } },
  { id: 'sword_t6', branch: 'sword', tier: 6, nameVi: 'Vết Cắt Mỏng', nameEn: 'Thin Scar',
    descVi: 'Một vết cắt mỏng nhưng sâu — để lại vết tích.', descEn: 'A thin cut that runs deep; it leaves a mark.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'attack', value: 2 } },
  { id: 'sword_t7', branch: 'sword', tier: 7, nameVi: 'Chí Mạng Ngắn', nameEn: 'Short Critical',
    descVi: 'Tìm điểm yếu bằng một nhát ngắn — may ra thì trúng.', descEn: 'A short thrust may find the weak point.',
    cost: { skillPoints: 2 }, require: { stage: 1 },
    effect: { kind: 'attack', value: 3, crit: 5 } },
  { id: 'sword_t8', branch: 'sword', tier: 8, nameVi: 'Xuyên Giáp Nhẹ', nameEn: 'Light Pierce',
    descVi: 'Mũi kiếm biết luồn qua kẽ hở của giáp mỏng.', descEn: 'The tip slips through thin armour gaps.',
    cost: { skillPoints: 2, item: 'ironwood_saber' }, require: { stage: 1 },
    effect: { kind: 'attack', value: 3 } },
  { id: 'sword_t9', branch: 'sword', tier: 9, nameVi: 'Lưỡi Cắt Ngang', nameEn: 'Crosswise Edge',
    descVi: 'Hai nhát chéo nhau; địch chỉ tránh được một.', descEn: 'Two crossing slashes; the enemy dodges one.',
    cost: { skillPoints: 2 }, require: { stage: 2, techniques: ['rift_step'] },
    effect: { kind: 'attack', value: 3 } },
  { id: 'sword_t10', branch: 'sword', tier: 10, nameVi: 'Chém Vỡ Khiên', nameEn: 'Shield Breaker',
    descVi: 'Đủ lực để chém vỡ một tấm khiên mỏng.', descEn: 'Force enough to split a thin shield.',
    cost: { skillPoints: 2, gold: 80 }, require: { stage: 2 },
    effect: { kind: 'attack', value: 4 } },
  { id: 'sword_t11', branch: 'sword', tier: 11, nameVi: 'Hồi Khí Khi Trúng', nameEn: 'Heal on Strike',
    descVi: 'Mỗi nhát trúng — khí huyết trở lại một chút.', descEn: 'Each landing strike returns a sliver of blood-qi.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'heal', value: 2, trigger: 'onHit' } },
  { id: 'sword_t12', branch: 'sword', tier: 12, nameVi: 'Hấp Huyết Nhẹ', nameEn: 'Light Drain',
    descVi: 'Rút một phần sức sống của địch qua lưỡi kiếm.', descEn: 'Drain a sliver of life through the blade.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'heal', value: 1, drain: true },
    conflictsWith: ['aura_t12'] },
  { id: 'sword_t13', branch: 'sword', tier: 13, nameVi: 'Chí Mạng Sâu', nameEn: 'Deep Critical',
    descVi: 'Tìm điểm yếu ở tầng sâu hơn, gây đòn nhân đôi.', descEn: 'Find the deeper weak point for a doubled blow.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'attack', value: 5, crit: 10 } },
  { id: 'sword_t14', branch: 'sword', tier: 14, nameVi: 'Trảm Bất Ngờ', nameEn: 'Sudden Cut',
    descVi: 'Đòn chí mạng không báo trước — tỉnh thì đã muộn.', descEn: 'A critical slash with no warning — too late when noticed.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'attack', value: 4, crit: 8 } },
  { id: 'sword_t15', branch: 'sword', tier: 15, nameVi: 'Hồi Huyết Khi Giết', nameEn: 'Kill Heal',
    descVi: 'Giết xong — máu trở về một nhịp.', descEn: 'A kill returns a beat of blood-qi.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'heal', value: 8, trigger: 'onKill' } },
  { id: 'sword_t16', branch: 'sword', tier: 16, nameVi: 'Đâm Tim', nameEn: 'Heart Pierce',
    descVi: 'Một nhát thẳng vào chỗ yếu nhất trên người.', descEn: 'A single thrust at the weakest spot.',
    cost: { skillPoints: 3, item: 'frostfang_saber' }, require: { stage: 3 },
    effect: { kind: 'attack', value: 6 } },
  { id: 'sword_t17', branch: 'sword', tier: 17, nameVi: 'Kiếm Ảnh', nameEn: 'Blade Echo',
    descVi: 'Đường kiếm để lại một bóng — đòn thứ hai tới ngay sau.', descEn: 'A shadow remains — the second strike follows at once.',
    cost: { skillPoints: 3 }, require: { stage: 4 },
    effect: { kind: 'attack', value: 5, echo: 1 } },
  { id: 'sword_t18', branch: 'sword', tier: 18, nameVi: 'Hồi Huyết Lớn', nameEn: 'Greater Kill Heal',
    descVi: 'Giết — máu trở về đủ cho một lần nữa.', descEn: 'A kill — blood-qi enough for one more.',
    cost: { skillPoints: 4 }, require: { stage: 4 },
    effect: { kind: 'heal', value: 14, trigger: 'onKill' } },
  { id: 'sword_t19', branch: 'sword', tier: 19, nameVi: 'Xuyên Phá', nameEn: 'Piercing Ruin',
    descVi: 'Một nhát xuyên qua cả giáp lẫn ý chí.', descEn: 'One thrust through both armour and will.',
    cost: { skillPoints: 4, item: 'cloudpiercer_spear' }, require: { stage: 4 },
    effect: { kind: 'attack', value: 8 } },
  { id: 'sword_t20', branch: 'sword', tier: 20, nameVi: 'Trảm Phong Thần', nameEn: 'Wind-Cleaving Strike',
    descVi: 'Một nhát cuối — gió cũng phải tránh đường.', descEn: 'One final slash — even the wind yields.',
    cost: { skillPoints: 5 }, require: { stage: 5 },
    effect: { kind: 'attack', value: 12, crit: 15 } },

  // ── Khí (Aura): qi pool lớn, defence, guard, drain hp từ qi ──────────
  { id: 'aura_t1', branch: 'aura', tier: 1, nameVi: 'Hơi Thở Dài', nameEn: 'Long Breath',
    descVi: 'Kéo dài hơi thở để có thêm một chút linh khí.', descEn: 'Stretch the breath for an extra sip of qi.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'buff', value: 4, stat: 'qi' } },
  { id: 'aura_t2', branch: 'aura', tier: 2, nameVi: 'Lớp Khí Mỏng', nameEn: 'Thin Qi Veil',
    descVi: 'Một lớp khí mỏng quanh người, đỡ được một cú đấm.', descEn: 'A thin qi layer absorbs a single punch.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'buff', value: 1, stat: 'defense' } },
  { id: 'aura_t3', branch: 'aura', tier: 3, nameVi: 'Bình Khí Trong Đan', nameEn: 'Steady Dantian',
    descVi: 'Đan điền ổn định — linh khí không thoát ra ngoài.', descEn: 'A steady dantian; qi no longer leaks.',
    cost: { skillPoints: 1 }, require: { stage: 0, techniques: ['basic_staff_form'] },
    effect: { kind: 'buff', value: 6, stat: 'qi' } },
  { id: 'aura_t4', branch: 'aura', tier: 4, nameVi: 'Giáp Khí', nameEn: 'Qi Shell',
    descVi: 'Lớp khí dày hơn — đỡ được hai cú đấm.', descEn: 'A thicker qi shell; two punches absorbed.',
    cost: { skillPoints: 1, gold: 40 }, require: { stage: 0 },
    effect: { kind: 'buff', value: 2, stat: 'defense' } },
  { id: 'aura_t5', branch: 'aura', tier: 5, nameVi: 'Bể Khí Trước Bụng', nameEn: 'Belly Pool',
    descVi: 'Khí đọng lại trước bụng, sẵn sàng dùng khi cần.', descEn: 'Qi pools in front of the belly, ready when called.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'buff', value: 8, stat: 'qi' } },
  { id: 'aura_t6', branch: 'aura', tier: 6, nameVi: 'Thủ Bài Khí', nameEn: 'Qi Guard',
    descVi: 'Khi thủ thế, lớp khí thêm một lớp đỡ.', descEn: 'While defending, the qi layer thickens.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'buff', value: 3, stat: 'guard' } },
  { id: 'aura_t7', branch: 'aura', tier: 7, nameVi: 'Hấp Thu Nhẹ', nameEn: 'Light Absorb',
    descVi: 'Hấp thu một phần sát thương vào đan điền.', descEn: 'Absorb a sliver of damage into the dantian.',
    cost: { skillPoints: 2 }, require: { stage: 1 },
    effect: { kind: 'buff', value: 1, stat: 'defense' } },
  { id: 'aura_t8', branch: 'aura', tier: 8, nameVi: 'Khí Dựng Khiên', nameEn: 'Qi Rampart',
    descVi: 'Khiên khí dựng lên khi bị đánh mạnh.', descEn: 'A qi rampart rises on hard hits.',
    cost: { skillPoints: 2, item: 'mistweave_vest' }, require: { stage: 1 },
    effect: { kind: 'buff', value: 4, stat: 'guard' } },
  { id: 'aura_t9', branch: 'aura', tier: 9, nameVi: 'Linh Khí Rộng', nameEn: 'Wider Stream',
    descVi: 'Linh khí chảy rộng hơn, đủ cho cả ngày dài.', descEn: 'A wider qi stream sustains the whole day.',
    cost: { skillPoints: 2 }, require: { stage: 2, techniques: ['herbal_breath'] },
    effect: { kind: 'buff', value: 10, stat: 'qi' } },
  { id: 'aura_t10', branch: 'aura', tier: 10, nameVi: 'Bể Khí Sâu', nameEn: 'Deep Pool',
    descVi: 'Bể khí sâu thêm — chứa được cả một buổi tu luyện.', descEn: 'A deeper pool holds an entire cultivation bout.',
    cost: { skillPoints: 2, gold: 80 }, require: { stage: 2 },
    effect: { kind: 'buff', value: 14, stat: 'qi' } },
  { id: 'aura_t11', branch: 'aura', tier: 11, nameVi: 'Phản Chấn Khí', nameEn: 'Qi Rebound',
    descVi: 'Khi bị đánh, khí đẩy ngược lại — địch giật mình.', descEn: 'On hit, qi rebounds — the enemy flinches.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'buff', value: 2, stat: 'defense' } },
  { id: 'aura_t12', branch: 'aura', tier: 12, nameVi: 'Neo Sự Sống', nameEn: 'Life Anchor',
    descVi: 'Khí neo giữ huyết — mất máu chậm hơn.', descEn: 'Qi anchors the blood; bleeding slows.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'heal', value: 1, drain: false },
    conflictsWith: ['sword_t12'] },
  { id: 'aura_t13', branch: 'aura', tier: 13, nameVi: 'Lớp Khí Dày', nameEn: 'Dense Veil',
    descVi: 'Lớp khí đủ dày để đỡ một đòn tầm trung.', descEn: 'A veil thick enough to stop a mid-weight blow.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'buff', value: 5, stat: 'defense' } },
  { id: 'aura_t14', branch: 'aura', tier: 14, nameVi: 'Rút Khí Hồi Huyết', nameEn: 'Qi-to-Blood',
    descVi: 'Đổi khí lấy huyết — chậm nhưng chắc.', descEn: 'Trade qi for blood — slow but steady.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'heal', value: 3, costQi: 4 } },
  { id: 'aura_t15', branch: 'aura', tier: 15, nameVi: 'Khiên Dày', nameEn: 'Thick Rampart',
    descVi: 'Khiên khí dày hơn nữa — đỡ được đòn mạnh.', descEn: 'An even thicker rampart; strong blows bounce off.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'buff', value: 6, stat: 'guard' } },
  { id: 'aura_t16', branch: 'aura', tier: 16, nameVi: 'Hồ Khí Trữ', nameEn: 'Qi Reservoir',
    descVi: 'Hồ khí mở ra — dự trữ cho cả ngày dài.', descEn: 'A qi reservoir opens; the day\'s reserve.',
    cost: { skillPoints: 3, item: 'spirit_ring' }, require: { stage: 3 },
    effect: { kind: 'buff', value: 18, stat: 'qi' } },
  { id: 'aura_t17', branch: 'aura', tier: 17, nameVi: 'Lớp Khí Bất Khả Xâm', nameEn: 'Impenetrable Veil',
    descVi: 'Lớp khí gần như không thể xuyên qua.', descEn: 'A veil almost nothing pierces.',
    cost: { skillPoints: 3 }, require: { stage: 4 },
    effect: { kind: 'buff', value: 7, stat: 'defense' } },
  { id: 'aura_t18', branch: 'aura', tier: 18, nameVi: 'Hấp Thu Khí', nameEn: 'Qi Absorb',
    descVi: 'Hấp thu khí từ đòn đánh vào đan điền.', descEn: 'Absorb qi from incoming blows back to the dantian.',
    cost: { skillPoints: 4 }, require: { stage: 4 },
    effect: { kind: 'buff', value: 2, stat: 'qi', trigger: 'onHit' } },
  { id: 'aura_t19', branch: 'aura', tier: 19, nameVi: 'Tường Khí', nameEn: 'Qi Wall',
    descVi: 'Tường khí dựng đứng — địch phải đợi nhịp thở của ngươi.', descEn: 'A wall of qi; the enemy waits for your breath.',
    cost: { skillPoints: 4, item: 'cloudveil_robe' }, require: { stage: 4 },
    effect: { kind: 'buff', value: 9, stat: 'guard' } },
  { id: 'aura_t20', branch: 'aura', tier: 20, nameVi: 'Đan Điền Vô Tận', nameEn: 'Boundless Dantian',
    descVi: 'Đan điền mở rộng vô tận — khí không bao giờ cạn.', descEn: 'The dantian opens without bound; qi never runs dry.',
    cost: { skillPoints: 5 }, require: { stage: 5 },
    effect: { kind: 'buff', value: 30, stat: 'qi' } },

  // ── Dược (Herbal): hồi hp/qi, buff tạm, gây độc, giảm danger khi move ──
  { id: 'herbal_t1', branch: 'herbal', tier: 1, nameVi: 'Nếm Cỏ Thuốc', nameEn: 'Taste the Grass',
    descVi: 'Biết cỏ nào ăn được, cỏ nào không.', descEn: 'Know which grass is safe.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'heal', value: 2, trigger: 'gather' } },
  { id: 'herbal_t2', branch: 'herbal', tier: 2, nameVi: 'Hơi Thuốc Nhẹ', nameEn: 'Light Scent',
    descVi: 'Hơi thuốc nhẹ làm tâm tĩnh lại một chút.', descEn: 'A light herbal scent steadies the heart.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'heal', value: 2, stat: 'hp' } },
  { id: 'herbal_t3', branch: 'herbal', tier: 3, nameVi: 'Hít Sâu Mùi Thuốc', nameEn: 'Deep Inhale',
    descVi: 'Hít sâu mùi thuốc — khí trong phổi tăng nhẹ.', descEn: 'A deep inhale; qi rises a sliver.',
    cost: { skillPoints: 1 }, require: { stage: 0, techniques: ['basic_staff_form'] },
    effect: { kind: 'heal', value: 2, stat: 'qi' } },
  { id: 'herbal_t4', branch: 'herbal', tier: 4, nameVi: 'Băng Lá Trên Vết Thương', nameEn: 'Leaf Bandage',
    descVi: 'Đắp lá tươi — máu cầm nhanh hơn.', descEn: 'Fresh leaves; blood stops faster.',
    cost: { skillPoints: 1, gold: 30 }, require: { stage: 0 },
    effect: { kind: 'heal', value: 4, stat: 'hp' } },
  { id: 'herbal_t5', branch: 'herbal', tier: 5, nameVi: 'Giảm Nguy Hiểm', nameEn: 'Lesser Danger Sense',
    descVi: 'Biết chỗ nào ít hiểm — đi đường nhẹ hơn.', descEn: 'Read the safer paths; walking is easier.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'utility', value: 1, stat: 'danger' } },
  { id: 'herbal_t6', branch: 'herbal', tier: 6, nameVi: 'Đắp Thuốc Cầm Máu', nameEn: 'Styptic Poultice',
    descVi: 'Thuốc đắp cầm máu — vết thương ngoài da lành nhanh.', descEn: 'A poultice that closes surface wounds fast.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'heal', value: 6, stat: 'hp' } },
  { id: 'herbal_t7', branch: 'herbal', tier: 7, nameVi: 'Hương Khí Thuật', nameEn: 'Scented Qi',
    descVi: 'Hương thuốc dẫn khí qua chỗ tắc — linh khí thêm.', descEn: 'Scent guides qi through blockages; extra qi.',
    cost: { skillPoints: 2 }, require: { stage: 1 },
    effect: { kind: 'heal', value: 4, stat: 'qi' } },
  { id: 'herbal_t8', branch: 'herbal', tier: 8, nameVi: 'Bào Chế Nhẹ', nameEn: 'Light Refining',
    descVi: 'Biết cách bào chế cỏ thành viên thuốc nhỏ.', descEn: 'Refine grass into small pills.',
    cost: { skillPoints: 2, item: 'dew_pill' }, require: { stage: 1 },
    effect: { kind: 'heal', value: 8, stat: 'hp' } },
  { id: 'herbal_t9', branch: 'herbal', tier: 9, nameVi: 'Độc Dược Nhẹ', nameEn: 'Light Poison',
    descVi: 'Chấm chút độc vào đầu mũi tên — địch chậm lại.', descEn: 'Tip with light poison; the enemy slows.',
    cost: { skillPoints: 2 }, require: { stage: 2, techniques: ['herbal_breath'] },
    effect: { kind: 'status', value: 1, status: 'poison' } },
  { id: 'herbal_t10', branch: 'herbal', tier: 10, nameVi: 'Giảm Hiểm Sâu', nameEn: 'Deep Danger Sense',
    descVi: 'Đi đường núi cũng biết chỗ nào an toàn.', descEn: 'Even mountain paths reveal their safe line.',
    cost: { skillPoints: 2, gold: 80 }, require: { stage: 2 },
    effect: { kind: 'utility', value: 2, stat: 'danger' } },
  { id: 'herbal_t11', branch: 'herbal', tier: 11, nameVi: 'Hồi Nguyên Lớn', nameEn: 'Greater Restore',
    descVi: 'Viên thuốc tự tay — hồi cả khí lẫn huyết.', descEn: 'A hand-made pill; blood and qi both rise.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'heal', value: 12, stat: 'hp' } },
  { id: 'herbal_t12', branch: 'herbal', tier: 12, nameVi: 'Khí Dược Trung Cấp', nameEn: 'Mid Qi Pill',
    descVi: 'Viên khí dược trung cấp — hồi linh khí vừa đủ.', descEn: 'A mid-grade qi pill; qi restored to last.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'heal', value: 10, stat: 'qi' } },
  { id: 'herbal_t13', branch: 'herbal', tier: 13, nameVi: 'Độc Mờ Răng', nameEn: 'Tooth-Hidden Poison',
    descVi: 'Độc ngấm qua da — địch ăn đòn cũng trúng độc.', descEn: 'Contact poison; the enemy is tainted by touch.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'status', value: 2, status: 'poison' } },
  { id: 'herbal_t14', branch: 'herbal', tier: 14, nameVi: 'Hương Kinh Dịch', nameEn: 'Terror Scent',
    descVi: 'Mùi thuốc lạ khiến yêu thú tránh xa.', descEn: 'A strange scent keeps beasts at bay.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'utility', value: 1, stat: 'aggro' } },
  { id: 'herbal_t15', branch: 'herbal', tier: 15, nameVi: 'Hồi Sinh Lực', nameEn: 'Lifeforce Pill',
    descVi: 'Viên thuốc đặc biệt — hồi sinh lực cả ngày.', descEn: 'A special pill; lifeforce restored for a day.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'heal', value: 20, stat: 'hp' } },
  { id: 'herbal_t16', branch: 'herbal', tier: 16, nameVi: 'Tẩy Độc', nameEn: 'Antidote',
    descVi: 'Biết cách tẩy độc bản thân sau một trận.', descEn: 'Cleanse self after a fight.',
    cost: { skillPoints: 3, item: 'plum_qi_wine' }, require: { stage: 3 },
    effect: { kind: 'utility', value: 1, stat: 'cleanse' } },
  { id: 'herbal_t17', branch: 'herbal', tier: 17, nameVi: 'Độc Tẩm Mũi Kiếm', nameEn: 'Blade Poison',
    descVi: 'Tẩm độc vào mũi kiếm — mỗi nhát trúng đều ngấm.', descEn: 'Coat the blade; every strike seeps.',
    cost: { skillPoints: 3 }, require: { stage: 4 },
    effect: { kind: 'status', value: 3, status: 'poison' } },
  { id: 'herbal_t18', branch: 'herbal', tier: 18, nameVi: 'Hồi Nguyên Hoàn', nameEn: 'Restore Pill',
    descVi: 'Viên hoàn cứu tinh — hồi cả huyết lẫn khí.', descEn: 'A rescue pill; both blood and qi.',
    cost: { skillPoints: 4 }, require: { stage: 4 },
    effect: { kind: 'heal', value: 24, stat: 'hp' } },
  { id: 'herbal_t19', branch: 'herbal', tier: 19, nameVi: 'Hương Ngự Yêu', nameEn: 'Beast-Taming Scent',
    descVi: 'Hương thuốc đặc biệt khiến yêu thú e sợ.', descEn: 'A scent that makes beasts fear you.',
    cost: { skillPoints: 4, item: 'ninefold_pill' }, require: { stage: 4 },
    effect: { kind: 'utility', value: 2, stat: 'aggro' } },
  { id: 'herbal_t20', branch: 'herbal', tier: 20, nameVi: 'Đan Trường Sinh', nameEn: 'Longevity Pill',
    descVi: 'Một viên đan — sinh lực như vừa mở cửa đan điền.', descEn: 'A single pill; lifeforce gushes back.',
    cost: { skillPoints: 5 }, require: { stage: 5 },
    effect: { kind: 'heal', value: 40, stat: 'hp' } },

  // ── Ẩn (Shadow): né tránh, cướp pháp khí, tàng hình, retreat free ─────
  { id: 'shadow_t1', branch: 'shadow', tier: 1, nameVi: 'Bước Nhẹ', nameEn: 'Soft Step',
    descVi: 'Bước chân nhẹ hơn — yêu thú khó phát hiện.', descEn: 'Lighter footfalls; beasts notice less.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'dodge', value: 1 } },
  { id: 'shadow_t2', branch: 'shadow', tier: 2, nameVi: 'Hơi Thở Thấp', nameEn: 'Low Breath',
    descVi: 'Hơi thở thấp xuống — thân mình mờ đi.', descEn: 'Breath drops low; the body fades.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'dodge', value: 1 } },
  { id: 'shadow_t3', branch: 'shadow', tier: 3, nameVi: 'Tránh Lệch', nameEn: 'Off-Step',
    descVi: 'Bước lệch — đòn đánh trượt nửa gang tay.', descEn: 'A sidestep; the strike misses by half a span.',
    cost: { skillPoints: 1 }, require: { stage: 0, techniques: ['basic_staff_form'] },
    effect: { kind: 'dodge', value: 2 } },
  { id: 'shadow_t4', branch: 'shadow', tier: 4, nameVi: 'Thân Ảnh', nameEn: 'Shadow Body',
    descVi: 'Thân mình như cái bóng — đòn đánh xuyên qua.', descEn: 'Body as a shadow; strikes pass through.',
    cost: { skillPoints: 1, gold: 40 }, require: { stage: 0 },
    effect: { kind: 'dodge', value: 2 } },
  { id: 'shadow_t5', branch: 'shadow', tier: 5, nameVi: 'Rút Lui Không Mất', nameEn: 'Free Retreat',
    descVi: 'Rút lui lần đầu — không mất gì cả.', descEn: 'The first retreat costs nothing.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'utility', value: 1, stat: 'retreat' } },
  { id: 'shadow_t6', branch: 'shadow', tier: 6, nameVi: 'Né Đòn Liên Hoàn', nameEn: 'Chain-Dodge',
    descVi: 'Né được hai đòn liên tiếp — nhịp thở địch bị ngắt.', descEn: 'Dodge two strikes in a row; the enemy\'s rhythm breaks.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'dodge', value: 3 } },
  { id: 'shadow_t7', branch: 'shadow', tier: 7, nameVi: 'Tàng Hình', nameEn: 'Veil',
    descVi: 'Tàng hình tạm thời — địch mất phương hướng.', descEn: 'A short veil; the enemy loses track.',
    cost: { skillPoints: 2 }, require: { stage: 1 },
    effect: { kind: 'utility', value: 1, stat: 'aggro' } },
  { id: 'shadow_t8', branch: 'shadow', tier: 8, nameVi: 'Lấy Vật Lạ', nameEn: 'Lightfingers',
    descVi: 'Lấy đồ vật nhỏ mà chủ nhân không hay.', descEn: 'Take small things without the owner noticing.',
    cost: { skillPoints: 2, item: 'tattered_robe' }, require: { stage: 1 },
    effect: { kind: 'utility', value: 1, stat: 'pickpocket' } },
  { id: 'shadow_t9', branch: 'shadow', tier: 9, nameVi: 'Bước Khe Nứt', nameEn: 'Rift Step',
    descVi: 'Bước qua khe nứt không gian — địch không theo kịp.', descEn: 'Step through a spatial rift; the enemy can\'t follow.',
    cost: { skillPoints: 2 }, require: { stage: 2, techniques: ['rift_step'] },
    effect: { kind: 'dodge', value: 4 } },
  { id: 'shadow_t10', branch: 'shadow', tier: 10, nameVi: 'Rút Lui Hai Lần', nameEn: 'Double Retreat',
    descVi: 'Hai lần rút lui miễn phí — mỗi trận.', descEn: 'Two free retreats per fight.',
    cost: { skillPoints: 2, gold: 80 }, require: { stage: 2 },
    effect: { kind: 'utility', value: 2, stat: 'retreat' } },
  { id: 'shadow_t11', branch: 'shadow', tier: 11, nameVi: 'Né Tất Cả', nameEn: 'Clean Miss',
    descVi: 'Né trọn vẹn một đòn — địch mất cả đà.', descEn: 'A clean miss; the enemy\'s momentum dies.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'dodge', value: 5 } },
  { id: 'shadow_t12', branch: 'shadow', tier: 12, nameVi: 'Giảm Tham Chiến', nameEn: 'Lower Aggro',
    descVi: 'Giảm sự chú ý của địch — đòn đến muộn hơn.', descEn: 'Lower aggro; the enemy\'s strikes arrive later.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'utility', value: 2, stat: 'aggro' } },
  { id: 'shadow_t13', branch: 'shadow', tier: 13, nameVi: 'Cướp Pháp Khí', nameEn: 'Seal-Stealer',
    descVi: 'Cướp một lớp phù trên người địch — tạm thời.', descEn: 'Steal a seal-layer off the enemy, briefly.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'utility', value: 1, stat: 'seal' } },
  { id: 'shadow_t14', branch: 'shadow', tier: 14, nameVi: 'Ảnh Phân Thân', nameEn: 'Shadow Clone',
    descVi: 'Bóng ngắn — địch đánh vào khoảng không.',
    descEn: 'A short-lived shadow; the enemy strikes empty air.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'dodge', value: 6 } },
  { id: 'shadow_t15', branch: 'shadow', tier: 15, nameVi: 'Tàng Hình Lâu', nameEn: 'Long Veil',
    descVi: 'Tàng hình lâu hơn — đi qua hai khu vực không bị phát hiện.', descEn: 'A longer veil; cross two regions unseen.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'utility', value: 2, stat: 'aggro' } },
  { id: 'shadow_t16', branch: 'shadow', tier: 16, nameVi: 'Né Chí Mạng', nameEn: 'Critical Miss',
    descVi: 'Né đòn chí mạng — địch mất một nhịp thở.', descEn: 'Dodge a critical hit; the enemy loses a breath.',
    cost: { skillPoints: 3, item: 'travelers_coat' }, require: { stage: 3 },
    effect: { kind: 'dodge', value: 7 } },
  { id: 'shadow_t17', branch: 'shadow', tier: 17, nameVi: 'Lấy Đồ Trên Người', nameEn: 'Pocket-Thief',
    descVi: 'Lấy đồ trên người địch giữa trận — tạm thời.', descEn: 'Lift a thing off the enemy mid-fight.',
    cost: { skillPoints: 3 }, require: { stage: 4 },
    effect: { kind: 'utility', value: 2, stat: 'pickpocket' } },
  { id: 'shadow_t18', branch: 'shadow', tier: 18, nameVi: 'Rút Lui Hoàn Toàn', nameEn: 'Free Escape',
    descVi: 'Rút lui hoàn toàn — không mất máu, không mất tiến độ.', descEn: 'A full retreat; no blood, no progress lost.',
    cost: { skillPoints: 4 }, require: { stage: 4 },
    effect: { kind: 'utility', value: 3, stat: 'retreat' } },
  { id: 'shadow_t19', branch: 'shadow', tier: 19, nameVi: 'Phong Ấn Mờ', nameEn: 'Sealed-Dodge',
    descVi: 'Né xong — phong ấn mờ để địch không bám theo.', descEn: 'Dodge and leave a faint seal; pursuit blurs.',
    cost: { skillPoints: 4, item: 'bone_ward_charm' }, require: { stage: 4 },
    effect: { kind: 'dodge', value: 8 } },
  { id: 'shadow_t20', branch: 'shadow', tier: 20, nameVi: 'Hư Vô Bộ', nameEn: 'Void Stride',
    descVi: 'Bước vào hư vô — địch đánh mà không thấy đâu.', descEn: 'Step into the void; the enemy strikes nothing.',
    cost: { skillPoints: 5 }, require: { stage: 5 },
    effect: { kind: 'dodge', value: 12 } },

  // ── Lôi (Thunder): burst đơn, AoE nhỏ, status tê/bỏng, knockback ─────
  { id: 'thunder_t1', branch: 'thunder', tier: 1, nameVi: 'Tia Lôi Đầu', nameEn: 'First Spark',
    descVi: 'Học cách tạo ra một tia lôi nhỏ ở đầu ngón tay.', descEn: 'A small spark at the fingertip.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'attack', value: 1 } },
  { id: 'thunder_t2', branch: 'thunder', tier: 2, nameVi: 'Sét Đánh Cạnh', nameEn: 'Side-Strike',
    descVi: 'Một tia sét nhỏ đánh cạnh — địch giật mình.', descEn: 'A small bolt at the side; the enemy flinches.',
    cost: { skillPoints: 1 }, require: { stage: 0 },
    effect: { kind: 'status', value: 1, status: 'shock' } },
  { id: 'thunder_t3', branch: 'thunder', tier: 3, nameVi: 'Bùng Nổ Nhỏ', nameEn: 'Small Burst',
    descVi: 'Bùng nổ lân cận — địch gần bị đẩy lùi.', descEn: 'A small burst; nearby foes stagger back.',
    cost: { skillPoints: 1 }, require: { stage: 0, techniques: ['basic_staff_form'] },
    effect: { kind: 'aoe', value: 1, aoeRadius: 1 } },
  { id: 'thunder_t4', branch: 'thunder', tier: 4, nameVi: 'Tê Tay', nameEn: 'Numb Hand',
    descVi: 'Sét nhỏ chạy qua tay địch — cầm kiếm lỏng đi.', descEn: 'A small bolt numbs the grip.',
    cost: { skillPoints: 1, gold: 40 }, require: { stage: 0 },
    effect: { kind: 'status', value: 1, status: 'numb' } },
  { id: 'thunder_t5', branch: 'thunder', tier: 5, nameVi: 'Bùng Nổ Cục Bộ', nameEn: 'Local Burst',
    descVi: 'Một vụ nổ cục bộ trong phạm vi một bước.', descEn: 'A local burst within one step.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'aoe', value: 2, aoeRadius: 1 } },
  { id: 'thunder_t6', branch: 'thunder', tier: 6, nameVi: 'Bỏng Nhẹ', nameEn: 'Light Burn',
    descVi: 'Sét đánh cháy — địch bị bỏng nhẹ trên da.', descEn: 'A bolt burns the skin lightly.',
    cost: { skillPoints: 1 }, require: { stage: 1 },
    effect: { kind: 'status', value: 1, status: 'burn' } },
  { id: 'thunder_t7', branch: 'thunder', tier: 7, nameVi: 'Tia Lôi Xuyên', nameEn: 'Piercing Bolt',
    descVi: 'Tia lôi xuyên qua kẽ hở của giáp nhẹ.', descEn: 'A bolt pierces light armour gaps.',
    cost: { skillPoints: 2 }, require: { stage: 1 },
    effect: { kind: 'attack', value: 2 } },
  { id: 'thunder_t8', branch: 'thunder', tier: 8, nameVi: 'Đẩy Lùi', nameEn: 'Knockback',
    descVi: 'Đòn sét đẩy địch lùi — tạo khoảng cách.', descEn: 'The bolt knocks the enemy back.',
    cost: { skillPoints: 2, item: 'bamboo_saber' }, require: { stage: 1 },
    effect: { kind: 'utility', value: 1, stat: 'knockback' } },
  { id: 'thunder_t9', branch: 'thunder', tier: 9, nameVi: 'Bùng Nổ Diện Rộng', nameEn: 'Wider Burst',
    descVi: 'Bùng nổ rộng hơn — nhiều mục tiêu cùng lúc.', descEn: 'A wider burst; many targets at once.',
    cost: { skillPoints: 2 }, require: { stage: 2, techniques: ['cloudwalk'] },
    effect: { kind: 'aoe', value: 3, aoeRadius: 2 } },
  { id: 'thunder_t10', branch: 'thunder', tier: 10, nameVi: 'Tê Toàn Thân', nameEn: 'Full Numb',
    descVi: 'Sét lớn — địch tê toàn thân một nhịp thở.', descEn: 'A big bolt; the enemy is numb for a breath.',
    cost: { skillPoints: 2, gold: 80 }, require: { stage: 2 },
    effect: { kind: 'status', value: 2, status: 'numb' } },
  { id: 'thunder_t11', branch: 'thunder', tier: 11, nameVi: 'Bỏng Sâu', nameEn: 'Deep Burn',
    descVi: 'Sét cháy sâu dưới da — địch đau dai dẳng.', descEn: 'A bolt burns deep; lingering pain.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'status', value: 2, status: 'burn' } },
  { id: 'thunder_t12', branch: 'thunder', tier: 12, nameVi: 'Tia Chớp Đôi', nameEn: 'Twin Bolt',
    descVi: 'Hai tia chớp cùng lúc — khó tránh hơn.', descEn: 'Two bolts at once; harder to dodge.',
    cost: { skillPoints: 2 }, require: { stage: 2 },
    effect: { kind: 'attack', value: 3, hits: 2 } },
  { id: 'thunder_t13', branch: 'thunder', tier: 13, nameVi: 'Đánh Xa', nameEn: 'Far Bolt',
    descVi: 'Tia sét đánh từ xa — địch không kịp phản ứng.', descEn: 'A bolt from afar; no time to react.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'attack', value: 4, range: 1 } },
  { id: 'thunder_t14', branch: 'thunder', tier: 14, nameVi: 'Bùng Nổ Chuỗi', nameEn: 'Chain Burst',
    descVi: 'Bùng nổ chuỗi — sát thương lan ra xung quanh.', descEn: 'A chain burst; damage radiates.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'aoe', value: 4, aoeRadius: 2 } },
  { id: 'thunder_t15', branch: 'thunder', tier: 15, nameVi: 'Đẩy Lùi Mạnh', nameEn: 'Heavy Knockback',
    descVi: 'Sét đánh đẩy địch lùi hai bước — đủ thở.', descEn: 'A bolt shoves the enemy back two steps; room to breathe.',
    cost: { skillPoints: 3 }, require: { stage: 3 },
    effect: { kind: 'utility', value: 2, stat: 'knockback' } },
  { id: 'thunder_t16', branch: 'thunder', tier: 16, nameVi: 'Tê Liệt', nameEn: 'Paralysis',
    descVi: 'Sét lớn — địch tê liệt tạm thời.', descEn: 'A big bolt; the enemy is briefly paralysed.',
    cost: { skillPoints: 3, item: 'cloudpiercer_spear' }, require: { stage: 3 },
    effect: { kind: 'status', value: 3, status: 'numb' } },
  { id: 'thunder_t17', branch: 'thunder', tier: 17, nameVi: 'Sét Bỏng', nameEn: 'Burning Bolt',
    descVi: 'Sét đánh cháy địch — lửa cháy dai dẳng.', descEn: 'A bolt that scorches; the fire lingers.',
    cost: { skillPoints: 3 }, require: { stage: 4 },
    effect: { kind: 'status', value: 3, status: 'burn' } },
  { id: 'thunder_t18', branch: 'thunder', tier: 18, nameVi: 'Bão Sét', nameEn: 'Thunderstorm',
    descVi: 'Nhiều tia sét cùng lúc — cả khu vực chao đảo.', descEn: 'Many bolts at once; the area trembles.',
    cost: { skillPoints: 4 }, require: { stage: 4 },
    effect: { kind: 'aoe', value: 5, aoeRadius: 3 } },
  { id: 'thunder_t19', branch: 'thunder', tier: 19, nameVi: 'Sét Xoáy', nameEn: 'Cyclone Bolt',
    descVi: 'Tia sét xoáy — hút địch lại gần rồi đánh bật.', descEn: 'A cyclone bolt; pulls in, then blasts out.',
    cost: { skillPoints: 4, item: 'frostfang_saber' }, require: { stage: 4 },
    effect: { kind: 'aoe', value: 6, aoeRadius: 2, knockback: 2 } },
  { id: 'thunder_t20', branch: 'thunder', tier: 20, nameVi: 'Lôi Minh Chấn', nameEn: 'Heaven-Shaking Bolt',
    descVi: 'Một tia sét cuối cùng — trời đất cùng rung.', descEn: 'A final bolt; heaven and earth shake.',
    cost: { skillPoints: 5 }, require: { stage: 5 },
    effect: { kind: 'aoe', value: 8, aoeRadius: 3 } },
]

const NODES: readonly SkillNode[] = SEEDS.map((seed) => ({ ...seed }))

const ALL_IDS = NODES.map((node) => node.id)
const UNIQUE = new Set(ALL_IDS)
if (UNIQUE.size !== ALL_IDS.length) throw new Error('skill-tree: duplicate node id')

const TIER_BY_BRANCH: Readonly<Record<typeof branches[number], ReadonlyArray<SkillNode>>> = (() => {
  const map: Record<string, SkillNode[]> = {}
  for (const branch of branches) map[branch] = []
  for (const node of NODES) {
    const list = map[node.branch]
    if (list === undefined) throw new Error(`skill-tree: unknown branch ${node.branch}`)
    list.push(node)
  }
  for (const branch of branches) {
    const list = map[branch]!
    list.sort((a, b) => a.tier - b.tier)
  }
  return map as Record<typeof branches[number], ReadonlyArray<SkillNode>>
})()

for (const branch of branches) {
  const list = TIER_BY_BRANCH[branch]!
  if (list.length !== 20) throw new Error(`skill-tree: ${branch} must have 20 tiers, has ${list.length}`)
  for (let i = 0; i < 20; i++) {
    const expected = i + 1
    const node = list[i]
    if (node === undefined) throw new Error(`skill-tree: ${branch} missing tier ${String(expected)}`)
    if (node.tier !== expected) {
      throw new Error(`skill-tree: ${branch} tier index ${String(i)} expected ${String(expected)}, got ${String(node.tier)}`)
    }
  }
}

if (NODES.length !== 100) throw new Error(`skill-tree: expected 100 nodes, got ${String(NODES.length)}`)

export const SKILL_TREES: Readonly<Record<typeof branches[number], ReadonlyArray<SkillNode>>> = TIER_BY_BRANCH
export const SKILL_NODES: readonly SkillNode[] = NODES
export const SKILL_BRANCHES = branches

export function getSkillNode(id: string): SkillNode | undefined {
  return NODES.find((node) => node.id === id)
}

export function skillNodesInBranch(branch: typeof branches[number]): ReadonlyArray<SkillNode> {
  return TIER_BY_BRANCH[branch] ?? []
}
