import type { StorySceneDef } from '../engine/content-types'

// The plot follows remembered deeds, rather than a prescribed map route.
export const STORY_SCENES: StorySceneDef[] = [
  { id: 'letter_at_dawn', chapter: 1, titleVi: 'Lá thư không có người gửi', titleEn: 'The Letter With No Sender', textVi: 'Trước cổng làng, một phong thư mang nét chữ của chính ngươi ở kiếp trước: “Đừng tin kẻ gọi ngươi là đồ phế.” Bên trong là nửa bản đồ dẫn tới hang Phong Ấn và chiếc trâm ngọc đã mất của cụ Mai Hoa.', textEn: 'At the village gate lies a letter in your past-life hand: “Do not trust anyone who calls you broken.” Inside: half a map to the Sealed Cave and Elder Meihua’s missing jade pin.', choices: [
    { id: 'return_pin', labelVi: 'Trả trâm ngọc cho cụ Mai Hoa, rồi hỏi bà về nét chữ', labelEn: 'Return Meihua’s jade pin and ask about the handwriting', consequenceVi: 'Cụ Mai Hoa sẽ tin ngươi với một bí mật cũ.', consequenceEn: 'Elder Meihua will trust you with an old secret.', nextSceneId: 'market_rumor', effects: { story_mercy: 1, story_meihua_trusted: true } },
    { id: 'study_letter', labelVi: 'Giấu trâm, giải mã lá thư trước khi ai khác thấy', labelEn: 'Hide the pin and decipher the letter before anyone sees it', consequenceVi: 'Ngươi đổi lòng tin lấy một mảnh chân tướng.', consequenceEn: 'You trade trust for a piece of truth.', nextSceneId: 'market_rumor', effects: { story_truth: 1, story_meihua_betrayed: true } },
    { id: 'sell_pin', labelVi: 'Mang trâm đến chợ, xem bí mật này đáng giá bao nhiêu', labelEn: 'Take the pin to market and learn what this secret is worth', consequenceVi: 'Tin đồn về ngươi bắt đầu có giá.', consequenceEn: 'Rumours about you begin to carry a price.', nextSceneId: 'market_rumor', effects: { story_wealth: 1, story_bao_paid: true } },
  ] },
  { id: 'market_rumor', chapter: 2, titleVi: 'Một thành phố dưới lớp sương', titleEn: 'A City Beneath the Mist', textVi: 'Bà Ma kể rằng cứ mười hai năm, dân làng lại quên một người. Đêm nay là đêm thứ mười hai. Bảo muốn mua nửa bản đồ; người kể chuyện Ngô bảo cái tên bị quên là tên của chính ngươi.', textEn: 'Tea Granny Ma says that every twelve years the village forgets one person. Tonight is the twelfth night. Bao wants the half-map; Storyteller Ngo says the forgotten name is yours.', choices: [
    { id: 'warn_village', labelVi: 'Tin lời bà Ma, đi gõ từng cửa để cảnh báo', labelEn: 'Trust Granny Ma and warn the village door by door', consequenceVi: 'Người dân sẽ nhớ ai đã đứng về phía họ.', consequenceEn: 'The villagers will remember who stood beside them.', nextSceneId: 'cave_witness', effects: { story_mercy: 1, story_village_warned: true } },
    { id: 'buy_silence', labelVi: 'Bán bản đồ cho Bảo để đổi lấy bùa hộ thân', labelEn: 'Sell the map to Bao for a ward of your own', consequenceVi: 'Ngươi có được an toàn, nhưng Bảo có một nửa chìa khóa.', consequenceEn: 'You gain safety, but Bao gains half a key.', nextSceneId: 'cave_witness', effects: { story_wealth: 1, story_bao_has_map: true } },
    { id: 'ask_ngo', labelVi: 'Ngồi với Ngô đến sáng, bắt ông kể trọn câu chuyện', labelEn: 'Sit with Ngo until dawn and make him tell the whole story', consequenceVi: 'Một cái tên được trả về ký ức của ngươi.', consequenceEn: 'A name is restored to your memory.', nextSceneId: 'cave_witness', effects: { story_truth: 1, story_name_known: true } },
  ] },
  { id: 'cave_witness', chapter: 3, titleVi: 'Nhân chứng trong phong ấn', titleEn: 'The Witness in the Seal', textVi: 'Ở hang Phong Ấn, vong hồn Hà nhận ra ngươi. Cô không phải ma canh cửa: cô đã chết để đưa ngươi thoát khỏi kiếp trước. Cô nói Tông chủ Võ giữ ký ức của cả làng trong một chiếc gương.', textEn: 'In the Sealed Cave, Ha recognizes you. She is not a gate-ghost: she died to get you out in the last life. Master Vo keeps the village’s memories inside a mirror.', choices: [
    { id: 'free_ha', labelVi: 'Phá một góc phong ấn để Hà được tự do, dù hang có thể sụp', labelEn: 'Break part of the seal to free Ha, even if the cave may fall', consequenceVi: 'Ngươi chọn một người thật thay vì kế hoạch hoàn hảo.', consequenceEn: 'You choose one real person over a perfect plan.', nextSceneId: 'sect_trial', effects: { story_mercy: 1, story_ha_free: true } },
    { id: 'bind_ha', labelVi: 'Xin Hà nhập vào bùa để dẫn đường qua chiếc gương', labelEn: 'Ask Ha to enter a talisman and guide you through the mirror', consequenceVi: 'Cô đồng ý, nhưng một lời hứa biến thành món nợ.', consequenceEn: 'She agrees, but a promise becomes a debt.', nextSceneId: 'sect_trial', effects: { story_power: 1, story_ha_bound: true } },
    { id: 'record_ha', labelVi: 'Chép lời Hà từng chữ, để không ai bóp méo chứng cứ', labelEn: 'Record Ha’s testimony word for word so no one can bend it', consequenceVi: 'Ngươi mang bằng chứng, và trách nhiệm với nó.', consequenceEn: 'You carry proof, and responsibility for it.', nextSceneId: 'sect_trial', effects: { story_truth: 1, story_ha_testimony: true } },
  ] },
  { id: 'sect_trial', chapter: 4, titleVi: 'Phiên xét xử không có bị cáo', titleEn: 'A Trial With No Defendant', textVi: 'Tông chủ Võ thừa nhận đã dùng gương để xóa ký ức về một cuộc tàn sát; ông nói đó là cách duy nhất giữ làng sống sót. Sư đệ Khoa đứng bên ông. “Sự thật có cứu nổi ai không?” Khoa hỏi.', textEn: 'Master Vo admits he used the mirror to erase memory of a massacre; he says it was the only way to keep the village alive. Rival Khoa stands beside him. “Can truth save anyone?” he asks.', choices: [
    { id: 'expose_vo', labelVi: 'Đưa lời Hà ra trước tông môn, buộc mọi người nhớ lại', labelEn: 'Read Ha’s testimony before the sect and force everyone to remember', consequenceVi: 'Sự thật sẽ làm đau, nhưng không còn thuộc về một người.', consequenceEn: 'Truth will hurt, but it will no longer belong to one person.', nextSceneId: 'mirror_choice', effects: { story_truth: 1, story_vo_exposed: true } },
    { id: 'keep_seal', labelVi: 'Giữ gương kín và yêu cầu Võ giao quyền canh giữ cho dân làng', labelEn: 'Keep the mirror sealed and demand Vo give its custody to the villagers', consequenceVi: 'Ngươi chọn trật tự, nhưng đổi chủ chiếc lồng.', consequenceEn: 'You choose order, but change the keeper of the cage.', nextSceneId: 'mirror_choice', effects: { story_order: 2, story_village_custody: true } },
    { id: 'take_mirror', labelVi: 'Cướp gương trước khi phiên xét xử biến thành thanh trừng', labelEn: 'Take the mirror before the trial becomes a purge', consequenceVi: 'Trong tay ngươi là ký ức của cả một vùng đất.', consequenceEn: 'In your hands rests a whole region’s memory.', nextSceneId: 'mirror_choice', effects: { story_power: 2, story_mirror_stolen: true } },
  ] },
  { id: 'mirror_choice', chapter: 5, titleVi: 'Kiếp trước nhìn lại', titleEn: 'The Previous Life Looks Back', textVi: 'Mặt gương cho ngươi thấy điều không ai nói: ở kiếp trước, chính ngươi đã xin Võ xóa ký ức vì không chịu nổi cái chết của Hà. Cái “kẻ thù” ngươi đuổi theo chỉ là ngươi, trước khi trốn chạy.', textEn: 'The mirror shows what no one said: in the last life, you asked Vo to erase memory because you could not bear Ha’s death. The enemy you chased was yourself, before you ran.', choices: [
    { id: 'confess', labelVi: 'Nói sự thật với Khoa và nhận phần lỗi của mình', labelEn: 'Tell Khoa the truth and accept your share of blame', consequenceVi: 'Một kẻ đối đầu có thể trở thành nhân chứng.', consequenceEn: 'An adversary may become a witness.', nextSceneId: 'last_page', effects: { story_mercy: 1, story_khoa_trusted: true } },
    { id: 'inherit_self', labelVi: 'Nhập ký ức kiếp trước, dùng nó làm sức mạnh', labelEn: 'Merge with the past-life memory and wield it as strength', consequenceVi: 'Ngươi không còn bị quá khứ đuổi theo; ngươi mang nó đi.', consequenceEn: 'The past no longer chases you; you carry it.', nextSceneId: 'last_page', effects: { story_power: 1, story_memory_merged: true } },
    { id: 'leave_blank', labelVi: 'Xóa tên mình khỏi gương, để kiếp này không nợ kiếp trước', labelEn: 'Erase your name from the mirror so this life owes the last none', consequenceVi: 'Có những phần thưởng chỉ đến khi ngươi chịu buông tay.', consequenceEn: 'Some rewards arrive only when you let go.', nextSceneId: 'last_page', effects: { story_renounce: 2, story_name_erased: true } },
  ] },
  { id: 'last_page', chapter: 6, titleVi: 'Trang cuối không viết sẵn', titleEn: 'The Last Page Is Not Written', textVi: 'Bình minh không xóa được gì, nhưng nó cho ngươi một lần quyết định xem ký ức này sẽ thuộc về ai. Không còn sư phụ, ma quỷ hay tiền kiếp nào chọn thay ngươi.', textEn: 'Dawn erases nothing, but gives you one decision: who will own this memory. No master, ghost, or prior life can choose for you now.', choices: [
    { id: 'open_last_page', labelVi: 'Mở gương trước mọi người và chấp nhận hậu quả', labelEn: 'Open the mirror before everyone and accept the fallout', consequenceVi: 'Cách ngươi tìm sự thật sẽ định đoạt điều còn lại.', consequenceEn: 'How you pursued truth will decide what remains.', nextSceneId: null, final: true },
    { id: 'share_last_page', labelVi: 'Đưa quyết định cho những người đã cùng chịu đựng', labelEn: 'Give the choice to those who bore the cost with you', consequenceVi: 'Người ngươi đã đối xử tử tế sẽ đáp lời.', consequenceEn: 'The people you treated with care will answer.', nextSceneId: null, final: true },
    { id: 'burn_last_page', labelVi: 'Đốt gương và tự viết một đời không có lời tiên tri', labelEn: 'Burn the mirror and write a life with no prophecy', consequenceVi: 'Tự do cũng có cái giá riêng của nó.', consequenceEn: 'Freedom has its own cost.', nextSceneId: null, final: true },
  ] },
]

export function getStoryScene(sceneId: string): StorySceneDef | undefined {
  return STORY_SCENES.find((scene) => scene.id === sceneId)
}
