import type { StorySceneDef } from '../engine/content-types'

// The plot follows remembered deeds, rather than a prescribed map route.
export const STORY_SCENES: StorySceneDef[] = [
  { id: 'letter_at_dawn', chapter: 1, titleVi: 'Lá thư không có người gửi', titleEn: 'The Letter With No Sender', textVi: 'Trước cổng làng, một phong thư mang nét chữ của chính ngươi ở kiếp trước: “Đừng tin kẻ gọi ngươi là đồ phế.” Bên trong là nửa bản đồ dẫn tới hang Phong Ấn và chiếc trâm ngọc đã mất của cụ Mai Hoa.', textEn: 'At the village gate lies a letter in your past-life hand: “Do not trust anyone who calls you broken.” Inside: half a map to the Sealed Cave and Elder Meihua’s missing jade pin.', choices: [
    { id: 'return_pin', labelVi: 'Trả trâm ngọc cho cụ Mai Hoa, rồi hỏi bà về nét chữ', labelEn: 'Return Meihua’s jade pin and ask about the handwriting', consequenceVi: 'Cụ Mai Hoa sẽ tin ngươi với một bí mật cũ.', consequenceEn: 'Elder Meihua will trust you with an old secret.', nextSceneId: 'market_rumor', effects: { story_mercy: 1, story_meihua_trusted: true } },
    { id: 'study_letter', labelVi: 'Giấu trâm, giải mã lá thư trước khi ai khác thấy', labelEn: 'Hide the pin and decipher the letter before anyone sees it', consequenceVi: 'Ngươi đổi lòng tin lấy một mảnh chân tướng.', consequenceEn: 'You trade trust for a piece of truth.', nextSceneId: 'market_rumor', effects: { story_truth: 1, story_meihua_betrayed: true } },
    { id: 'sell_pin', labelVi: 'Mang trâm đến chợ, xem bí mật này đáng giá bao nhiêu', labelEn: 'Take the pin to market and learn what this secret is worth', consequenceVi: 'Tin đồn về ngươi bắt đầu có giá.', consequenceEn: 'Rumours about you begin to carry a price.', nextSceneId: 'market_rumor', effects: { story_wealth: 1, story_bao_paid: true } },
  ] },
  { id: 'market_rumor', chapter: 2, titleVi: 'Một thành phố dưới lớp sương', titleEn: 'A City Beneath the Mist', textVi: 'Bà Ma kể rằng cứ mười hai năm, dân làng lại quên một người. Đêm nay là đêm thứ mười hai. Bảo muốn mua nửa bản đồ; người kể chuyện Ngô bảo cái tên bị quên là tên của chính ngươi.', textEn: 'Tea Granny Ma says that every twelve years the village forgets one person. Tonight is the twelfth night. Bao wants the half-map; Storyteller Ngo says the forgotten name is yours.', choices: [
    { id: 'warn_village', labelVi: 'Tin lời bà Ma, đi gõ từng cửa để cảnh báo', labelEn: 'Trust Granny Ma and warn the village door by door', consequenceVi: 'Người dân sẽ nhớ ai đã đứng về phía họ.', consequenceEn: 'The villagers will remember who stood beside them.', nextSceneId: 'village_vow', effects: { story_mercy: 1, story_village_warned: true, story_route: 'mercy' } },
    { id: 'buy_silence', labelVi: 'Bán bản đồ cho Bảo để đổi lấy bùa hộ thân', labelEn: 'Sell the map to Bao for a ward of your own', consequenceVi: 'Ngươi có được an toàn, nhưng Bảo có một nửa chìa khóa.', consequenceEn: 'You gain safety, but Bao gains half a key.', nextSceneId: 'market_bargain', effects: { story_wealth: 1, story_bao_has_map: true, story_route: 'wealth' } },
    { id: 'ask_ngo', labelVi: 'Ngồi với Ngô đến sáng, bắt ông kể trọn câu chuyện', labelEn: 'Sit with Ngo until dawn and make him tell the whole story', consequenceVi: 'Một cái tên được trả về ký ức của ngươi.', consequenceEn: 'A name is restored to your memory.', nextSceneId: 'memory_trail', effects: { story_truth: 1, story_name_known: true, story_route: 'truth' } },
    // Phase 4 (design review 2026-08): each Hồi I choice unlocks one extra
    // lead in Hồi II — trust buys Meihua's road, the sold pin buys Bao's road,
    // the deciphered letter buys a road of your own.
    { id: 'walk_with_meihua', labelVi: 'Cùng cụ Mai Hoa đi từng nhà, như người đã trả trâm xứng đáng được đi', labelEn: 'Walk door to door with Meihua, as one who returned the pin deserves to', consequenceVi: 'Người đã tin ngươi sẽ dẫn ngươi đi đường gần nhất.', consequenceEn: 'The one who trusts you takes you the shortest way.', nextSceneId: 'village_vow', effects: { story_mercy: 1, story_route: 'mercy' }, requires: { story_meihua_trusted: true } },
    { id: 'sell_map_premium', labelVi: 'Bán nửa bản đồ cho Bảo với giá của kẻ đã bán trâm — hắn biết ngươi giữ chữ tín thương nhân', labelEn: 'Sell the half-map to Bao at the price owed to someone who already sold him the pin', consequenceVi: 'An toàn đắt hơn, nhưng ngươi biết mình không bị hét giá.', consequenceEn: 'Safety costs more, but you know you were not gouged.', nextSceneId: 'market_bargain', effects: { story_wealth: 1, story_bao_has_map: true, story_route: 'wealth' }, requires: { story_bao_paid: true } },
    { id: 'decode_letter', labelVi: 'Dùng nét chữ đã giải mã từ đêm qua, đọc tiếp nửa bản đồ không cần ai chỉ', labelEn: 'Use the hand you deciphered last night to read the half-map with no teacher', consequenceVi: 'Ngươi tự mình đọc được điều kẻ khác phải mua.', consequenceEn: 'You read for yourself what others must buy.', nextSceneId: 'memory_trail', effects: { story_truth: 1, story_route: 'truth', story_letter_decoded: true }, requires: { story_meihua_betrayed: true } },
  ] },
  { id: 'village_vow', chapter: 2, titleVi: 'Đêm không để ai bị quên', titleEn: 'A Night That Forgets No One', textVi: 'Mai Hoa không dẫn ngươi tới hang ngay. Bà trao cho ngươi một bó dây đỏ, bắt ngươi buộc tên từng nhà lên cổng. “Cứu một làng không phải là đứng trước nó,” bà cằn nhằn, “là nhớ xem ai chưa được ai gọi về ăn cơm.” Trên mỗi sợi dây, linh căn phế của ngươi nghe thấy một tiếng thì thầm bị cắt mất.', textEn: 'Meihua does not take you to the cave at once. She gives you red thread and makes you tie every household name to its gate. “Saving a village is not standing in front of it,” she grumbles. “It is noticing who has not been called home for supper.” In each thread, your defective root hears a severed whisper.', choices: [
    { id: 'keep_roll_call', labelVi: 'Đi cùng Mai Hoa, gọi tên từng người cho tới sáng', labelEn: 'Walk with Meihua and call every name until dawn', consequenceVi: 'Cả làng có một đêm để nhớ nhau trước khi sương che mất.', consequenceEn: 'The village gets one night to remember itself before the mist closes.', nextSceneId: 'cave_witness', effects: { story_mercy: 1, story_meihua_companion: true }, requires: { story_route_ready: true }, playerDelta: { progress: 12 } },
    { id: 'listen_to_thread', labelVi: 'Dùng linh căn phế lần theo tiếng thì thầm bị cắt', labelEn: 'Use your defective root to trace the severed whisper', consequenceVi: 'Ngươi thấy dấu phong ấn, nhưng linh khí trong người bị rút khô.', consequenceEn: 'You see the seal’s scar, but the effort drains your qi.', nextSceneId: 'cave_witness', effects: { story_truth: 1, story_memory_echo: true, story_root_strained: true }, requires: { story_route_ready: true }, playerDelta: { qi: -14 } },
    { id: 'leave_watch', labelVi: 'Chia bó dây cho bọn trẻ, dựng một vòng canh có tiếng cười', labelEn: 'Give the thread to the children and build a laughing watch', consequenceVi: 'Ngươi có người canh đường vào hang, đổi bằng một đêm không ngủ.', consequenceEn: 'You gain eyes on the road to the cave, at the price of a sleepless night.', nextSceneId: 'cave_witness', effects: { story_order: 1, story_village_watch: true }, requires: { story_route_ready: true }, playerDelta: { hp: -6 } },
  ] },
  { id: 'market_bargain', chapter: 2, titleVi: 'Cái giá của nửa tấm bản đồ', titleEn: 'The Price of Half a Map', textVi: 'Bảo không hề bỏ đi sau khi mua bản đồ. Hắn dẫn ngươi qua lối sau chợ, nơi ba quầy hàng đang tranh nhau một mảnh phù. “Ta không mua bí mật,” hắn nói. “Ta mua người biết bí mật sẽ làm ai đó hoảng.” Hắn đẩy về phía ngươi một bùa hộ thân nứt góc — đủ tốt để sống, không đủ tốt để tin.', textEn: 'Bao does not leave after buying the map. He leads you through the market’s back lane, where three stalls are fighting over a broken ward. “I do not buy secrets,” he says. “I buy people who know whose secret will make them panic.” He slides you a chipped ward: good enough to survive, not good enough to trust.', choices: [
    { id: 'buy_ward', labelVi: 'Bỏ tiền mua bùa, giữ Bảo làm người dẫn đường có giá', labelEn: 'Pay for the ward and keep Bao as a guide with a price', consequenceVi: 'Bùa chặn được một luồng tà khí; Bảo cũng nói cho ngươi một lối tắt.', consequenceEn: 'The ward blocks one bad current, and Bao gives you a shortcut.', nextSceneId: 'cave_witness', effects: { story_bao_companion: true, story_ward_bought: true }, requires: { story_route_ready: true }, playerDelta: { gold: -18, qi: 8 } },
    { id: 'turn_rumor', labelVi: 'Dùng tin đồn dụ kẻ mua khác lộ mặt, rồi chốt giá cao hơn', labelEn: 'Use the rumour to flush out another buyer, then name a higher price', consequenceVi: 'Ngươi có thêm tiền và một kẻ lạ biết tên mình.', consequenceEn: 'You gain coin and a stranger who now knows your name.', nextSceneId: 'cave_witness', effects: { story_wealth: 1, story_market_debt: true }, requires: { story_route_ready: true }, playerDelta: { gold: 24 } },
    { id: 'trade_truth', labelVi: 'Đổi lợi nhuận lấy tên người đã thuê Bảo theo dõi ngươi', labelEn: 'Trade profit for the name of whoever hired Bao to watch you', consequenceVi: 'Thương đạo mở ra một đầu mối; Bảo mất một phần tin ngươi.', consequenceEn: 'Commerce opens a lead; Bao loses a measure of trust in you.', nextSceneId: 'cave_witness', effects: { story_truth: 1, story_bao_watched_you: true }, requires: { story_route_ready: true }, playerDelta: { gold: -6 } },
  ] },
  { id: 'memory_trail', chapter: 2, titleVi: 'Tên gọi sau lớp mực xóa', titleEn: 'The Name Beneath Erased Ink', textVi: 'Ngô kéo ngươi vào trà quán, đặt bảy bát trà thành một vòng. Mỗi bát là một ký ức dân làng đã đánh rơi; giữa vòng là tên của ngươi, bị gạch như một lỗi chính tả. “Phế căn của ngươi không chứa linh khí tốt,” ông cười khan, “nhưng nó nghe được chỗ câu chuyện bị xé.”', textEn: 'Ngo pulls you into the teahouse and arranges seven cups in a circle. Each holds a memory a villager dropped; at the centre is your name, crossed out like a typo. “Your defective root does not hold qi well,” he says. “But it can hear where a story was torn.”', choices: [
    { id: 'trace_erased_name', labelVi: 'Đặt tay lên bát trà, nghe linh căn phế lần theo nét mực xóa', labelEn: 'Put your hand over the tea and let your defective root follow the erased ink', consequenceVi: 'Một ký ức trả về, nhưng Qi của ngươi lệch như nước chảy ngược.', consequenceEn: 'A memory returns, but your qi runs crooked like upstream water.', nextSceneId: 'cave_witness', effects: { story_truth: 1, story_memory_echo: true, story_root_strained: true, story_ngo_companion: true }, requires: { story_route_ready: true }, playerDelta: { qi: -16, progress: 14 } },
    { id: 'tell_ngo_joke', labelVi: 'Bắt Ngô kể cả đoạn buồn cười nhất mà ông cố giấu', labelEn: 'Make Ngo tell the funniest part he tried to hide', consequenceVi: 'Một câu đùa cũ làm người trong quán nhớ ra đường vào rừng.', consequenceEn: 'An old joke makes the teahouse remember the road into the woods.', nextSceneId: 'cave_witness', effects: { story_mercy: 1, story_ngo_companion: true, story_forest_path_known: true }, requires: { story_route_ready: true }, playerDelta: { qi: 6 } },
    { id: 'copy_names', labelVi: 'Chép bảy cái tên vào sổ, không để một ai bị đổi thành số liệu', labelEn: 'Copy all seven names into your notebook; let no one become a statistic', consequenceVi: 'Ngươi có bằng chứng để đối chất, và một cuốn sổ phải bảo vệ.', consequenceEn: 'You gain evidence for the trial and a notebook that must be protected.', nextSceneId: 'cave_witness', effects: { story_truth: 1, story_names_recorded: true }, requires: { story_route_ready: true }, playerDelta: { progress: 8 } },
  ] },
  { id: 'cave_witness', chapter: 3, titleVi: 'Nhân chứng trong phong ấn', titleEn: 'The Witness in the Seal', textVi: 'Ở hang Phong Ấn, vong hồn Hà nhận ra ngươi. Cô không phải ma canh cửa: cô đã chết để đưa ngươi thoát khỏi kiếp trước. Cô nói Tông chủ Võ giữ ký ức của cả làng trong một chiếc gương.', textEn: 'In the Sealed Cave, Ha recognizes you. She is not a gate-ghost: she died to get you out in the last life. Master Vo keeps the village’s memories inside a mirror.', choices: [
    { id: 'free_ha', labelVi: 'Phá một góc phong ấn để Hà được tự do, dù hang có thể sụp', labelEn: 'Break part of the seal to free Ha, even if the cave may fall', consequenceVi: 'Ngươi chọn một người thật thay vì kế hoạch hoàn hảo.', consequenceEn: 'You choose one real person over a perfect plan.', nextSceneId: 'sect_trial', effects: { story_mercy: 1, story_ha_free: true } },
    { id: 'bind_ha', labelVi: 'Xin Hà nhập vào bùa để dẫn đường qua chiếc gương', labelEn: 'Ask Ha to enter a talisman and guide you through the mirror', consequenceVi: 'Cô đồng ý, nhưng một lời hứa biến thành món nợ.', consequenceEn: 'She agrees, but a promise becomes a debt.', nextSceneId: 'sect_trial', effects: { story_power: 1, story_ha_bound: true }, requires: { story_proof_withhold: true } },
    { id: 'record_ha', labelVi: 'Chép lời Hà từng chữ, để không ai bóp méo chứng cứ', labelEn: 'Record Ha’s testimony word for word so no one can bend it', consequenceVi: 'Ngươi mang bằng chứng, và trách nhiệm với nó.', consequenceEn: 'You carry proof, and responsibility for it.', nextSceneId: 'sect_trial', effects: { story_truth: 1, story_ha_testimony: true }, requires: { story_proof_present: true } },
    { id: 'call_roll_witnesses', labelVi: 'Đọc cuộn điểm danh, gọi những nhà còn nhớ tên Hà', labelEn: 'Read the roll call and summon the homes that remember Ha', consequenceVi: 'Những cái tên được gọi đứng ra làm nhân chứng cho Hà.', consequenceEn: 'The named households step forward as Ha’s witnesses.', nextSceneId: 'sect_trial', effects: { story_mercy: 1, story_cave_roll_called: true }, requires: { story_route_proof: 'mercy' }, playerDelta: { progress: 6 } },
    { id: 'redeem_bao_ward', labelVi: 'Đổi nửa phù khế lấy đường lui cho Hà', labelEn: 'Trade Bao’s half-ward for Ha’s escape route', consequenceVi: 'Món nợ có giá, nhưng Hà có một lối thoát thật.', consequenceEn: 'The debt costs coin, but Ha gains a real way out.', nextSceneId: 'sect_trial', effects: { story_cave_ward_redeemed: true }, requires: { story_route_proof: 'wealth' }, playerDelta: { gold: -8 } },
    { id: 'name_the_eighth', labelVi: 'Đọc cái tên thứ tám để phá vết mực trên phong ấn', labelEn: 'Read the eighth name to break the seal’s scraped ink', consequenceVi: 'Tên trở về trên đá; linh căn phế trả giá bằng khí lực.', consequenceEn: 'The name returns to stone; your defective root pays in qi.', nextSceneId: 'sect_trial', effects: { story_cave_eighth_name: true }, requires: { story_route_proof: 'truth' }, playerDelta: { qi: -8, progress: 4 } },
  ] },
  { id: 'sect_trial', chapter: 4, titleVi: 'Phiên xét xử không có bị cáo', titleEn: 'A Trial With No Defendant', textVi: 'Tông chủ Võ thừa nhận đã dùng gương để xóa ký ức về một cuộc tàn sát; ông nói đó là cách duy nhất giữ làng sống sót. Sư đệ Khoa đứng bên ông. “Sự thật có cứu nổi ai không?” Khoa hỏi.', textEn: 'Master Vo admits he used the mirror to erase memory of a massacre; he says it was the only way to keep the village alive. Rival Khoa stands beside him. “Can truth save anyone?” he asks.', choices: [
    { id: 'expose_vo', labelVi: 'Đưa lời Hà ra trước tông môn, buộc mọi người nhớ lại', labelEn: 'Read Ha’s testimony before the sect and force everyone to remember', consequenceVi: 'Sự thật sẽ làm đau, nhưng không còn thuộc về một người.', consequenceEn: 'Truth will hurt, but it will no longer belong to one person.', nextSceneId: 'mirror_choice', effects: { story_truth: 1, story_vo_exposed: true }, requires: { story_proof_present: true } },
    { id: 'keep_seal', labelVi: 'Giữ gương kín và yêu cầu Võ giao quyền canh giữ cho dân làng', labelEn: 'Keep the mirror sealed and demand Vo give its custody to the villagers', consequenceVi: 'Ngươi chọn trật tự, nhưng đổi chủ chiếc lồng.', consequenceEn: 'You choose order, but change the keeper of the cage.', nextSceneId: 'mirror_choice', effects: { story_order: 2, story_village_custody: true } },
    { id: 'take_mirror', labelVi: 'Cướp gương trước khi phiên xét xử biến thành thanh trừng', labelEn: 'Take the mirror before the trial becomes a purge', consequenceVi: 'Trong tay ngươi là ký ức của cả một vùng đất.', consequenceEn: 'In your hands rests a whole region’s memory.', nextSceneId: 'mirror_choice', effects: { story_power: 2, story_mirror_stolen: true }, requires: { story_proof_withhold: true } },
    { id: 'let_roll_testify', labelVi: 'Để những nhà trong cuộn điểm danh tự đứng ra nói', labelEn: 'Let the households on the roll testify for themselves', consequenceVi: 'Lời chứng không còn nằm trong tay một người.', consequenceEn: 'Testimony no longer rests in one person’s hands.', nextSceneId: 'mirror_choice', effects: { story_trial_roll_testimony: true }, requires: { story_route_proof: 'mercy' }, playerDelta: { progress: 6 } },
    { id: 'settle_ward_debt', labelVi: 'Nộp nửa phù khế, buộc Võ trả giá bằng vàng của mình', labelEn: 'Present the half-ward and make Vo pay from his own coffers', consequenceVi: 'Một khoản nợ được ghi trước tông môn, không còn mua được im lặng.', consequenceEn: 'A debt is entered before the sect; it can no longer buy silence.', nextSceneId: 'mirror_choice', effects: { story_trial_debt_settled: true }, requires: { story_route_proof: 'wealth' }, playerDelta: { gold: 10 } },
    { id: 'restore_eighth_name', labelVi: 'Đặt cái tên thứ tám vào sổ tông môn', labelEn: 'Enter the eighth name into the sect register', consequenceVi: 'Một cái tên trở về luật lệ, nhưng ngươi phải chống lại tiếng vọng trong mình.', consequenceEn: 'A name returns to the law, but you must bear its echo.', nextSceneId: 'mirror_choice', effects: { story_trial_eighth_restored: true }, requires: { story_route_proof: 'truth' }, playerDelta: { qi: -8, progress: 4 } },
  ] },
  { id: 'mirror_choice', chapter: 5, titleVi: 'Kiếp trước nhìn lại', titleEn: 'The Previous Life Looks Back', textVi: 'Mặt gương cho ngươi thấy điều không ai nói: ở kiếp trước, chính ngươi đã xin Võ xóa ký ức vì không chịu nổi cái chết của Hà. Cái “kẻ thù” ngươi đuổi theo chỉ là ngươi, trước khi trốn chạy.', textEn: 'The mirror shows what no one said: in the last life, you asked Vo to erase memory because you could not bear Ha’s death. The enemy you chased was yourself, before you ran.', choices: [
    { id: 'confess', labelVi: 'Nói sự thật với Khoa và nhận phần lỗi của mình', labelEn: 'Tell Khoa the truth and accept your share of blame', consequenceVi: 'Một kẻ đối đầu có thể trở thành nhân chứng.', consequenceEn: 'An adversary may become a witness.', nextSceneId: 'last_page', effects: { story_mercy: 1, story_khoa_trusted: true } },
    { id: 'inherit_self', labelVi: 'Nhập ký ức kiếp trước, dùng nó làm sức mạnh', labelEn: 'Merge with the past-life memory and wield it as strength', consequenceVi: 'Ngươi không còn bị quá khứ đuổi theo; ngươi mang nó đi.', consequenceEn: 'The past no longer chases you; you carry it.', nextSceneId: 'last_page', effects: { story_power: 1, story_memory_merged: true } },
    { id: 'leave_blank', labelVi: 'Xóa tên mình khỏi gương, để kiếp này không nợ kiếp trước', labelEn: 'Erase your name from the mirror so this life owes the last none', consequenceVi: 'Có những phần thưởng chỉ đến khi ngươi chịu buông tay.', consequenceEn: 'Some rewards arrive only when you let go.', nextSceneId: 'last_page', effects: { story_renounce: 2, story_name_erased: true } },
  ] },
  { id: 'last_page', chapter: 6, titleVi: 'Trang cuối không viết sẵn', titleEn: 'The Last Page Is Not Written', textVi: 'Bình minh không xóa được gì, nhưng nó cho ngươi một lần quyết định xem ký ức này sẽ thuộc về ai. Không còn sư phụ, ma quỷ hay tiền kiếp nào chọn thay ngươi.', textEn: 'Dawn erases nothing, but gives you one decision: who will own this memory. No master, ghost, or prior life can choose for you now.', choices: [
    { id: 'open_last_page', labelVi: 'Mở gương trước mọi người và chấp nhận hậu quả', labelEn: 'Open the mirror before everyone and accept the fallout', consequenceVi: 'Cách ngươi tìm sự thật sẽ định đoạt điều còn lại.', consequenceEn: 'How you pursued truth will decide what remains.', nextSceneId: null, final: true },
    { id: 'share_last_page', labelVi: 'Đưa quyết định cho những người đã cùng chịu đựng', labelEn: 'Give the choice to those who bore the cost with you', consequenceVi: 'Người ngươi đã đối xử tử tế sẽ đáp lời.', consequenceEn: 'The people you treated with care will answer.', nextSceneId: null, final: true },
    { id: 'burn_last_page', labelVi: 'Đốt gương và tự viết một đời không có lời tiên tri', labelEn: 'Burn the mirror and write a life with no prophecy', consequenceVi: 'Tự do cũng có cái giá riêng của nó.', consequenceEn: 'Freedom has its own cost.', nextSceneId: null, final: true },
  ] },
]

export function getStoryScene(sceneId: string): StorySceneDef | undefined {
  return STORY_SCENES.find((scene) => scene.id === sceneId)
}
