import type { QuestDef } from '../engine/content-types'

const turnIn = (id: string, vi: string, en: string, completeItems?: Record<string, number>, completeFlags?: string[]): QuestDef['steps'][number] => ({
  id,
  descVi: vi,
  descEn: en,
  completeItems,
  completeFlags,
  isTurnInStep: true,
})

export const SYSTEM_QUESTS: QuestDef[] = [
  // ---------------------------------------------------------------------------
  // 1. Battle System (sys_battle) — minGold: 40, maxGold: 80, minLS: 0, maxLS: 2
  // itemPool: ninefold_pill, marrow_gather_pill, beast_fang, cold_iron_ore, ironwood_saber, frostfang_saber, cloudveil_robe
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_battle_01',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu I】 Thử Thách Máu',
    nameEn: '【Battle I】 Trial of Blood',
    descVi: 'Hệ Thống yêu cầu chiến đấu. Thu thập nanh thú chiến lợi phẩm.',
    descEn: 'The System demands combat. Collect beast fangs as trophies.',
    difficulty: 3,
    rewardGold: 45,
    rewardItems: { beast_fang: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 01'],
    steps: [turnIn('t1', 'Giao nanh thú cho Hệ Thống.', 'Deliver beast fangs to the System.', { beast_fang: 1 })],
  },
  {
    id: 'q_sys_battle_02',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu II】 Rèn Luyện Thép',
    nameEn: '【Battle II】 Steel Tempering',
    descVi: 'Hệ Thống muốn thử độ cứng của gân cốt ngươi.',
    descEn: 'The System tests your structural endurance.',
    difficulty: 5,
    rewardGold: 55,
    rewardItems: { cold_iron_ore: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 02'],
    steps: [turnIn('t1', 'Nộp quặng sắt lạnh.', 'Submit cold iron ore.', { cold_iron_ore: 1 })],
  },
  {
    id: 'q_sys_battle_03',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu III】 Thần Binh Xuất Thế',
    nameEn: '【Battle III】 Weapon Awakened',
    descVi: 'Hệ Thống đòi hỏi một thanh đao sắt gỗ để ghi nhận chỉ số.',
    descEn: 'The System requires an ironwood saber to log combat data.',
    difficulty: 6,
    rewardGold: 65,
    rewardItems: { marrow_gather_pill: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 03'],
    steps: [turnIn('t1', 'Nộp đao sắt gỗ.', 'Hand over ironwood saber.', { ironwood_saber: 1 })],
  },
  {
    id: 'q_sys_battle_04',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu IV】 Hán Băng Sương Đao',
    nameEn: '【Battle IV】 Frostfang Blade',
    descVi: 'Hệ Thống muốn xem sát khí của Sương Đao.',
    descEn: 'The System seeks the lethal edge of the Frostfang Saber.',
    difficulty: 8,
    rewardGold: 75,
    rewardItems: { frostfang_saber: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 04'],
    steps: [turnIn('t1', 'Dâng Nanh Sương Đao.', 'Present Frostfang Saber.', { frostfang_saber: 1 })],
  },
  {
    id: 'q_sys_battle_05',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu V】 Cửu Chuyển Cứu Mạng',
    nameEn: '【Battle V】 Ninefold Recovery',
    descVi: 'Hệ Thống kiểm tra khả năng phục hồi tổn thương sau trận đánh.',
    descEn: 'The System measures post-battle trauma recovery.',
    difficulty: 7,
    rewardGold: 70,
    rewardItems: { ninefold_pill: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 05'],
    steps: [turnIn('t1', 'Nộp Cửu Chuyển Đan.', 'Submit Ninefold Pill.', { ninefold_pill: 1 })],
  },
  {
    id: 'q_sys_battle_06',
    requiredSystemId: 'sys_battle',
    giverNpcId: null,
    nameVi: '【Chiến Đấu VI】 Bào Y Vân Sương',
    nameEn: '【Battle VI】 Cloudveil Garment',
    descVi: 'Hệ Thống yêu cầu trang bị Vân Sương Bào để tính giáp.',
    descEn: 'The System needs Cloudveil Robe to calculate armor ratings.',
    difficulty: 9,
    rewardGold: 80,
    rewardItems: { cloudveil_robe: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys battle 06'],
    steps: [turnIn('t1', 'Giao Vân Sương Bào.', 'Deliver Cloudveil Robe.', { cloudveil_robe: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 2. Alchemy System (sys_alchemy) — minGold: 25, maxGold: 55, minLS: 0, maxLS: 2
  // itemPool: pill_hp, pill_qi, dew_pill, marrow_gather_pill, herb_hong_silk, herb_ice_heart, herb_fire_lotus, pill_hybrid_moon_fire
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_alchemy_01',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan I】 Nhập Môn Thảo Dược',
    nameEn: '【Alchemy I】 Herb Entry',
    descVi: 'Hệ Thống thu thập Hồi Xuân Đan để phân tích chất lượng.',
    descEn: 'The System collects HP Pills for quality analysis.',
    difficulty: 2,
    rewardGold: 30,
    rewardItems: { pill_hp: 2 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 01'],
    steps: [turnIn('t1', 'Giao Hồi Xuân Đan.', 'Deliver HP Pill.', { pill_hp: 1 })],
  },
  {
    id: 'q_sys_alchemy_02',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan II】 Khí Huyết Song Thu',
    nameEn: '【Alchemy II】 Dual Qi Pill',
    descVi: 'Hệ Thống cần Dưỡng Khí Đan để đếm linh khí tích tụ.',
    descEn: 'The System requires Qi Pills to trace spiritual build-up.',
    difficulty: 4,
    rewardGold: 35,
    rewardItems: { pill_qi: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 02'],
    steps: [turnIn('t1', 'Nộp Dưỡng Khí Đan.', 'Submit Qi Pill.', { pill_qi: 1 })],
  },
  {
    id: 'q_sys_alchemy_03',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan III】 Sương Mai Tụ Khí',
    nameEn: '【Alchemy III】 Dew Extraction',
    descVi: 'Hệ Thống ghi chú sự ngưng tụ của Cam Lồ Đan.',
    descEn: 'The System tracks condensation rates of Dew Pills.',
    difficulty: 5,
    rewardGold: 40,
    rewardItems: { dew_pill: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 03'],
    steps: [turnIn('t1', 'Nộp Cam Lồ Đan.', 'Hand over Dew Pill.', { dew_pill: 1 })],
  },
  {
    id: 'q_sys_alchemy_04',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan IV】 Băng Hỏa Dung Hòa',
    nameEn: '【Alchemy IV】 Ice & Fire Fusion',
    descVi: 'Hệ Thống đòi hỏi dược liệu Băng Tâm và Hỏa Liên.',
    descEn: 'The System demands Ice Heart and Fire Lotus herbs.',
    difficulty: 7,
    rewardGold: 50,
    rewardItems: { pill_hybrid_moon_fire: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 04'],
    steps: [turnIn('t1', 'Nộp Hỏa Sen Thảo.', 'Present Fire Lotus Herb.', { herb_fire_lotus: 1 })],
  },
  {
    id: 'q_sys_alchemy_05',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan V】 Tụ Tủy Nguyệt Quang',
    nameEn: '【Alchemy V】 Marrow Moon Fusion',
    descVi: 'Hệ Thống đo lường Tụ Tủy Đan dưới tác động nhiệt.',
    descEn: 'The System measures Marrow Gather Pill thermal limits.',
    difficulty: 8,
    rewardGold: 55,
    rewardItems: { marrow_gather_pill: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 05'],
    steps: [turnIn('t1', 'Nộp Tụ Tủy Đan.', 'Submit Marrow Gather Pill.', { marrow_gather_pill: 1 })],
  },
  {
    id: 'q_sys_alchemy_06',
    requiredSystemId: 'sys_alchemy',
    giverNpcId: null,
    nameVi: '【Luyện Đan VI】 Hồng Tơ Thảo',
    nameEn: '【Alchemy VI】 Red Silk Herb',
    descVi: 'Hệ Thống yêu cầu mẫu dược liệu Hồng Tơ Thảo hiếm.',
    descEn: 'The System requests a rare Hong Silk Herb sample.',
    difficulty: 6,
    rewardGold: 45,
    rewardItems: { herb_hong_silk: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys alchemy 06'],
    steps: [turnIn('t1', 'Giao Hồng Tơ Thảo.', 'Deliver Hong Silk Herb.', { herb_hong_silk: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 3. Merchant System (sys_merchant) — minGold: 30, maxGold: 60, minLS: 0, maxLS: 3
  // itemPool: silver_coin, spirit_stone, gold_note, trail_rations, plum_qi_wine, cloudsilk_thread, moon_moss, travelers_coat
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_merchant_01',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương I】 Giao Dịch Bạc',
    nameEn: '【Merchant I】 Silver Trade',
    descVi: 'Hệ Thống đòi hỏi lưu thông tiền bạc.',
    descEn: 'The System demands circulation of silver currency.',
    difficulty: 3,
    rewardGold: 35,
    rewardItems: { silver_coin: 3 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 01'],
    steps: [turnIn('t1', 'Nộp tiền bạc.', 'Submit silver coins.', { silver_coin: 1 })],
  },
  {
    id: 'q_sys_merchant_02',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương II】 Nguồn Lương Thảo',
    nameEn: '【Merchant II】 Supply Rations',
    descVi: 'Hệ Thống cần lương khô dự trữ cho thương đoàn.',
    descEn: 'The System needs trail rations banked for caravans.',
    difficulty: 4,
    rewardGold: 40,
    rewardItems: { trail_rations: 3 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 02'],
    steps: [turnIn('t1', 'Nộp lương khô.', 'Hand over trail rations.', { trail_rations: 1 })],
  },
  {
    id: 'q_sys_merchant_03',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương III】 Rượu Mận Thơm',
    nameEn: '【Merchant III】 Plum Wine Deal',
    descVi: 'Hệ Thống mua Rượu Mận Dưỡng Khí để đấu giá.',
    descEn: 'The System acquires Plum Qi Wine for auctioning.',
    difficulty: 5,
    rewardGold: 45,
    rewardItems: { plum_qi_wine: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 03'],
    steps: [turnIn('t1', 'Nộp Rượu Mận.', 'Submit Plum Qi Wine.', { plum_qi_wine: 1 })],
  },
  {
    id: 'q_sys_merchant_04',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương IV】 Tơ Vân Thắt',
    nameEn: '【Merchant IV】 Cloudsilk Investment',
    descVi: 'Hệ Thống gom Chỉ Vân Tơ cho hợp đồng may mặc.',
    descEn: 'The System cornered the market on Cloudsilk Thread.',
    difficulty: 6,
    rewardGold: 50,
    rewardItems: { cloudsilk_thread: 2 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 04'],
    steps: [turnIn('t1', 'Giao Chỉ Vân Tơ.', 'Deliver Cloudsilk Thread.', { cloudsilk_thread: 1 })],
  },
  {
    id: 'q_sys_merchant_05',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương V】 Áo Hành Khách',
    nameEn: '【Merchant V】 Traveler Coat Exchange',
    descVi: 'Hệ Thống cần Áo Bào Hành Khách để thẩm định thương xa.',
    descEn: 'The System appraises a Traveler’s Coat for logistics.',
    difficulty: 7,
    rewardGold: 55,
    rewardItems: { travelers_coat: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 05'],
    steps: [turnIn('t1', 'Nộp Áo Bào Hành Khách.', 'Submit Traveler Coat.', { travelers_coat: 1 })],
  },
  {
    id: 'q_sys_merchant_06',
    requiredSystemId: 'sys_merchant',
    giverNpcId: null,
    nameVi: '【Hội Thương VI】 Kim Phiếu Thượng Hạng',
    nameEn: '【Merchant VI】 High Gold Note',
    descVi: 'Hệ Thống giao dịch Kim Phiếu mệnh giá cao.',
    descEn: 'The System settles high-value Gold Notes.',
    difficulty: 8,
    rewardGold: 60,
    rewardItems: { gold_note: 1 },
    rewardSpiritStones: 3,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys merchant 06'],
    steps: [turnIn('t1', 'Nộp Kim Phiếu.', 'Hand over Gold Note.', { gold_note: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 4. Lottery System (sys_lottery) — minGold: 20, maxGold: 90, minLS: 0, maxLS: 1
  // itemPool: pill_hp, pill_qi, jade_charm, silver_coin, spirit_stone, moonstone_pendant, dew_pill, trail_rations
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_lottery_01',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc I】 Đặt Cược Nhỏ',
    nameEn: '【Lottery I】 Small Wager',
    descVi: 'Hệ Thống tính xác suất đặt cược Hồi Xuân Đan.',
    descEn: 'The System calculates probability for an HP Pill wager.',
    difficulty: 2,
    rewardGold: 25,
    rewardItems: { pill_hp: 2 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 01'],
    steps: [turnIn('t1', 'Đặt cược Hồi Xuân Đan.', 'Wager HP Pill.', { pill_hp: 1 })],
  },
  {
    id: 'q_sys_lottery_02',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc II】 Báu Vật Nhỏ',
    nameEn: '【Lottery II】 Minor Trinket',
    descVi: 'Hệ Thống yêu cầu Ngọc Bùa cho cuộc quay thưởng.',
    descEn: 'The System requests a Jade Charm for the draw.',
    difficulty: 4,
    rewardGold: 45,
    rewardItems: { jade_charm: 1 },
    rewardSpiritStones: 0,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 02'],
    steps: [turnIn('t1', 'Nộp Ngọc Bùa.', 'Submit Jade Charm.', { jade_charm: 1 })],
  },
  {
    id: 'q_sys_lottery_03',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc III】 Đồng Tiền May Mắn',
    nameEn: '【Lottery III】 Lucky Coin',
    descVi: 'Hệ Thống cược đồng bạc lấy vận may.',
    descEn: 'The System wagers a silver coin on luck.',
    difficulty: 5,
    rewardGold: 60,
    rewardItems: { silver_coin: 4 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 03'],
    steps: [turnIn('t1', 'Nộp tiền bạc cược.', 'Submit silver coin wager.', { silver_coin: 1 })],
  },
  {
    id: 'q_sys_lottery_04',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc IV】 Mặt Đỏ Đen',
    nameEn: '【Lottery IV】 Moonstone Gamble',
    descVi: 'Hệ Thống tính toán rủi ro trên Mặt Đá Nguyệt Quang.',
    descEn: 'The System calculates risk on a Moonstone Pendant.',
    difficulty: 7,
    rewardGold: 75,
    rewardItems: { moonstone_pendant: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 04'],
    steps: [turnIn('t1', 'Nộp Mặt Đá Nguyệt Quang.', 'Hand over Moonstone Pendant.', { moonstone_pendant: 1 })],
  },
  {
    id: 'q_sys_lottery_05',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc V】 Cược Lớn Cam Lồ',
    nameEn: '【Lottery V】 Dew High-Stakes',
    descVi: 'Hệ Thống thử thách cược Cam Lồ Đan nhận phần thưởng độc đắc.',
    descEn: 'The System challenges a Dew Pill bet for the jackpot.',
    difficulty: 8,
    rewardGold: 85,
    rewardItems: { dew_pill: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 05'],
    steps: [turnIn('t1', 'Cược Cam Lồ Đan.', 'Wager Dew Pill.', { dew_pill: 1 })],
  },
  {
    id: 'q_sys_lottery_06',
    requiredSystemId: 'sys_lottery',
    giverNpcId: null,
    nameVi: '【Cờ Bạc VI】 Độc Đắc Linh Thạch',
    nameEn: '【Lottery VI】 Spirit Stone Jackpot',
    descVi: 'Hệ Thống giải ngân khoản cược lớn nhất.',
    descEn: 'The System settles the grand jackpot roll.',
    difficulty: 9,
    rewardGold: 90,
    rewardItems: { spirit_stone: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys lottery 06'],
    steps: [turnIn('t1', 'Nộp Linh Thạch cược.', 'Submit Spirit Stone bet.', { spirit_stone: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 5. Explorer System (sys_explorer) — minGold: 25, maxGold: 60, minLS: 0, maxLS: 2
  // itemPool: trail_rations, cloudwalk_manual, tide_breath_manual, rift_step_scroll, moonstone_pendant, crane_feather, moon_moss, bait_crane_spirit
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_explorer_01',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm I】 Hành Trang Khởi Đầu',
    nameEn: '【Explorer I】 Rations Setup',
    descVi: 'Hệ Thống cần lương khô chuẩn bị cho chuyến thám hiểm dài.',
    descEn: 'The System needs trail rations to prep an expedition.',
    difficulty: 3,
    rewardGold: 30,
    rewardItems: { trail_rations: 2 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 01'],
    steps: [turnIn('t1', 'Giao lương khô.', 'Deliver trail rations.', { trail_rations: 1 })],
  },
  {
    id: 'q_sys_explorer_02',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm II】 Rêu Nguyệt Quang',
    nameEn: '【Explorer II】 Moon Moss Sample',
    descVi: 'Hệ Thống thu thập Rêu Nguyệt Quang ở khu vực hoang dã.',
    descEn: 'The System gathers Moon Moss from the wild.',
    difficulty: 4,
    rewardGold: 35,
    rewardItems: { moon_moss: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 02'],
    steps: [turnIn('t1', 'Nộp Rêu Nguyệt Quang.', 'Submit Moon Moss.', { moon_moss: 1 })],
  },
  {
    id: 'q_sys_explorer_03',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm III】 Lông Hạc Rừng Sương',
    nameEn: '【Explorer III】 Crane Feather Lead',
    descVi: 'Hệ Thống dò tìm Lông Hạc Linh trên bản đồ.',
    descEn: 'The System maps Crane Feathers in mist zone.',
    difficulty: 5,
    rewardGold: 40,
    rewardItems: { crane_feather: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 03'],
    steps: [turnIn('t1', 'Nộp Lông Hạc Linh.', 'Hand over Crane Feather.', { crane_feather: 1 })],
  },
  {
    id: 'q_sys_explorer_04',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm IV】 Bí Kíp Vân Bộ',
    nameEn: '【Explorer IV】 Cloudwalk Secrets',
    descVi: 'Hệ Thống đối chiếu Vân Bộ Pháp Quyển với địa hình.',
    descEn: 'The System cross-references Cloudwalk Manual with terrain.',
    difficulty: 7,
    rewardGold: 50,
    rewardItems: { cloudwalk_manual: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 04'],
    steps: [turnIn('t1', 'Giao Vân Bộ Pháp Quyển.', 'Deliver Cloudwalk Manual.', { cloudwalk_manual: 1 })],
  },
  {
    id: 'q_sys_explorer_05',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm V】 Dẫn Thú Hạc Linh',
    nameEn: '【Explorer V】 Crane Spirit Baiting',
    descVi: 'Hệ Thống dùng mồi dụ Hạc Linh để mở đường ẩn.',
    descEn: 'The System uses Crane Spirit Bait to unlock hidden paths.',
    difficulty: 8,
    rewardGold: 55,
    rewardItems: { bait_crane_spirit: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 05'],
    steps: [turnIn('t1', 'Nộp Mồi Dẫn Hạc Linh.', 'Submit Crane Spirit Bait.', { bait_crane_spirit: 1 })],
  },
  {
    id: 'q_sys_explorer_06',
    requiredSystemId: 'sys_explorer',
    giverNpcId: null,
    nameVi: '【Vạn Dặm VI】 Cuộn Bước Hư Không',
    nameEn: '【Explorer VI】 Rift Step Discovery',
    descVi: 'Hệ Thống giải mã Cuộn Bước Hư Không ở biên giới.',
    descEn: 'The System deciphers Rift Step Scroll at the frontier.',
    difficulty: 9,
    rewardGold: 60,
    rewardItems: { rift_step_scroll: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys explorer 06'],
    steps: [turnIn('t1', 'Nộp Cuộn Bước Hư Không.', 'Hand over Rift Step Scroll.', { rift_step_scroll: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 6. Assassin System (sys_assassin) — minGold: 45, maxGold: 85, minLS: 0, maxLS: 3
  // itemPool: shadow_eclipse_step_hidden_manual, shadow_molt_hidden_manual, ironwood_saber, frostfang_saber, rift_step_scroll, beast_fang
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_assassin_01',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát I】 Thu Nanh Hung Thú',
    nameEn: '【Assassin I】 Beast Fang Strike',
    descVi: 'Hệ Thống đòi hỏi nanh thú làm lưỡi ám khí.',
    descEn: 'The System claims beast fangs for throwing blades.',
    difficulty: 4,
    rewardGold: 50,
    rewardItems: { beast_fang: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 01'],
    steps: [turnIn('t1', 'Nộp Nanh Thú.', 'Submit Beast Fang.', { beast_fang: 1 })],
  },
  {
    id: 'q_sys_assassin_02',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát II】 Sát Khí Đao Đen',
    nameEn: '【Assassin II】 Ironwood Ambush',
    descVi: 'Hệ Thống yêu cầu Đao Sắt Gỗ cho phi vụ trong bóng tối.',
    descEn: 'The System needs an Ironwood Saber for shadow ops.',
    difficulty: 5,
    rewardGold: 55,
    rewardItems: { ironwood_saber: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 02'],
    steps: [turnIn('t1', 'Giao Đao Sắt Gỗ.', 'Deliver Ironwood Saber.', { ironwood_saber: 1 })],
  },
  {
    id: 'q_sys_assassin_03',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát III】 Đoạt Mạng Sương Đao',
    nameEn: '【Assassin III】 Frostfang Elimination',
    descVi: 'Hệ Thống muốn thử nghiệm tốc độ chém của Nanh Sương Đao.',
    descEn: 'The System tests execution speed of Frostfang Saber.',
    difficulty: 7,
    rewardGold: 65,
    rewardItems: { frostfang_saber: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 03'],
    steps: [turnIn('t1', 'Nộp Nanh Sương Đao.', 'Present Frostfang Saber.', { frostfang_saber: 1 })],
  },
  {
    id: 'q_sys_assassin_04',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát IV】 Tận Thực Bộ Phủ',
    nameEn: '【Assassin IV】 Eclipse Step Mastery',
    descVi: 'Hệ Thống tìm kiếm Tận Thực Phân Thân Bộ Tàn Quyển.',
    descEn: 'The System seeks Shadow Eclipse Step Hidden Manual.',
    difficulty: 8,
    rewardGold: 75,
    rewardItems: { shadow_eclipse_step_hidden_manual: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 04'],
    steps: [turnIn('t1', 'Nộp Tận Thực Bộ Tàn Quyển.', 'Hand over Shadow Eclipse Step Manual.', { shadow_eclipse_step_hidden_manual: 1 })],
  },
  {
    id: 'q_sys_assassin_05',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát V】 Kim Thiền Thoát Xác',
    nameEn: '【Assassin V】 Shadow Molt Escape',
    descVi: 'Hệ Thống thu thập Phù Thiền Chi Thuật Tàn Quyển.',
    descEn: 'The System acquires Shadow Molt Hidden Manual.',
    difficulty: 9,
    rewardGold: 80,
    rewardItems: { shadow_molt_hidden_manual: 1 },
    rewardSpiritStones: 3,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 05'],
    steps: [turnIn('t1', 'Giao Phù Thiền Chi Thuật Tàn Quyển.', 'Deliver Shadow Molt Manual.', { shadow_molt_hidden_manual: 1 })],
  },
  {
    id: 'q_sys_assassin_06',
    requiredSystemId: 'sys_assassin',
    giverNpcId: null,
    nameVi: '【Ám Sát VI】 Dịch Chuyển Hư Không',
    nameEn: '【Assassin VI】 Rift Shift Execution',
    descVi: 'Hệ Thống dùng Cuộn Bước Hư Không để thoát thân sạch sẽ.',
    descEn: 'The System uses Rift Step Scroll for clean exits.',
    difficulty: 8,
    rewardGold: 85,
    rewardItems: { rift_step_scroll: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys assassin 06'],
    steps: [turnIn('t1', 'Nộp Cuộn Bước Hư Không.', 'Hand over Rift Step Scroll.', { rift_step_scroll: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 7. Healer System (sys_healer) — minGold: 20, maxGold: 50, minLS: 0, maxLS: 2
  // itemPool: pill_hp, pill_qi, dew_pill, ninefold_pill, marrow_gather_pill, herb_blood_ginseng, pill_hybrid_blood_dew
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_healer_01',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh I】 Cứu Thương Cơ Bản',
    nameEn: '【Healer I】 Basic Healing',
    descVi: 'Hệ Thống tích trữ Hồi Xuân Đan cứu chữa ký chủ.',
    descEn: 'The System stockpiles HP Pills for host triage.',
    difficulty: 2,
    rewardGold: 25,
    rewardItems: { pill_hp: 2 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 01'],
    steps: [turnIn('t1', 'Nộp Hồi Xuân Đan.', 'Submit HP Pill.', { pill_hp: 1 })],
  },
  {
    id: 'q_sys_healer_02',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh II】 Huyết Sâm Bổ Khí',
    nameEn: '【Healer II】 Blood Ginseng Vitality',
    descVi: 'Hệ Thống thu thập Huyết Sâm Thảo để điều hòa nhịp tim.',
    descEn: 'The System gathers Blood Ginseng Herb for pulse tuning.',
    difficulty: 4,
    rewardGold: 30,
    rewardItems: { herb_blood_ginseng: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 02'],
    steps: [turnIn('t1', 'Nộp Huyết Sâm Thảo.', 'Submit Blood Ginseng Herb.', { herb_blood_ginseng: 1 })],
  },
  {
    id: 'q_sys_healer_03',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh III】 Cam Lồ Dưỡng Thần',
    nameEn: '【Healer III】 Dew Nourishment',
    descVi: 'Hệ Thống chiết xuất Cam Lồ Đan giữ tinh thần minh mẫn.',
    descEn: 'The System extracts Dew Pill to maintain clarity.',
    difficulty: 5,
    rewardGold: 35,
    rewardItems: { dew_pill: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 03'],
    steps: [turnIn('t1', 'Giao Cam Lồ Đan.', 'Deliver Dew Pill.', { dew_pill: 1 })],
  },
  {
    id: 'q_sys_healer_04',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh IV】 Huyết Lồ Hỗn Hợp',
    nameEn: '【Healer IV】 Blood Dew Hybrid',
    descVi: 'Hệ Thống bào chế Huyết Lồ Đan dung hòa sinh lực.',
    descEn: 'The System concocts Blood Dew Hybrid Pill for vitality.',
    difficulty: 6,
    rewardGold: 40,
    rewardItems: { pill_hybrid_blood_dew: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 04'],
    steps: [turnIn('t1', 'Nộp Huyết Lồ Đan.', 'Hand over Blood Dew Hybrid Pill.', { pill_hybrid_blood_dew: 1 })],
  },
  {
    id: 'q_sys_healer_05',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh V】 Tụ Tủy Hoán Cốt',
    nameEn: '【Healer V】 Marrow Regeneration',
    descVi: 'Hệ Thống dùng Tụ Tủy Đan tái tạo xương khớp.',
    descEn: 'The System uses Marrow Gather Pill for bone repair.',
    difficulty: 7,
    rewardGold: 45,
    rewardItems: { marrow_gather_pill: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 05'],
    steps: [turnIn('t1', 'Nộp Tụ Tủy Đan.', 'Submit Marrow Gather Pill.', { marrow_gather_pill: 1 })],
  },
  {
    id: 'q_sys_healer_06',
    requiredSystemId: 'sys_healer',
    giverNpcId: null,
    nameVi: '【Dưỡng Sinh VI】 Cửu Chuyển Hoàn Hồn',
    nameEn: '【Healer VI】 Ninefold Miracle',
    descVi: 'Hệ Thống giữ Cửu Chuyển Đan làm mốc sinh tử cuối.',
    descEn: 'The System holds Ninefold Pill as the final lifesaver.',
    difficulty: 8,
    rewardGold: 50,
    rewardItems: { ninefold_pill: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys healer 06'],
    steps: [turnIn('t1', 'Dâng Cửu Chuyển Đan.', 'Present Ninefold Pill.', { ninefold_pill: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 8. Artisan System (sys_artisan) — minGold: 30, maxGold: 65, minLS: 0, maxLS: 2
  // itemPool: cold_iron_ore, cloudsilk_thread, crane_feather, jade_charm, bone_ward_charm, stone_aegis_manual, iron_skin_manual, peak_cleaver_manual
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_artisan_01',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí I】 Nguyên Liệu Quặng',
    nameEn: '【Artisan I】 Ore Foundation',
    descVi: 'Hệ Thống thu thập Quặng Sắt Lạnh đúc phôi bảo khí.',
    descEn: 'The System collects Cold Iron Ore for forging.',
    difficulty: 3,
    rewardGold: 35,
    rewardItems: { cold_iron_ore: 2 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 01'],
    steps: [turnIn('t1', 'Nộp Quặng Sắt Lạnh.', 'Submit Cold Iron Ore.', { cold_iron_ore: 1 })],
  },
  {
    id: 'q_sys_artisan_02',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí II】 Dây Tơ May Khí',
    nameEn: '【Artisan II】 Cloudsilk Weaving',
    descVi: 'Hệ Thống dùng Chỉ Vân Tơ khâu phù chú.',
    descEn: 'The System uses Cloudsilk Thread to weave wards.',
    difficulty: 4,
    rewardGold: 40,
    rewardItems: { cloudsilk_thread: 2 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 02'],
    steps: [turnIn('t1', 'Giao Chỉ Vân Tơ.', 'Deliver Cloudsilk Thread.', { cloudsilk_thread: 1 })],
  },
  {
    id: 'q_sys_artisan_03',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí III】 Phù Khế Xương Thú',
    nameEn: '【Artisan III】 Bone Ward Forging',
    descVi: 'Hệ Thống chạm khắc Phù Trụ Xương Thú.',
    descEn: 'The System engraves Bone Ward Charms.',
    difficulty: 6,
    rewardGold: 50,
    rewardItems: { bone_ward_charm: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 03'],
    steps: [turnIn('t1', 'Nộp Phù Trụ Xương Thú.', 'Hand over Bone Ward Charm.', { bone_ward_charm: 1 })],
  },
  {
    id: 'q_sys_artisan_04',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí IV】 Thiết Bì Chi Thuật',
    nameEn: '【Artisan IV】 Iron Skin Manual',
    descVi: 'Hệ Thống nghiên cứu Thiết Bì Chi Thuật Quyển.',
    descEn: 'The System studies Iron Skin Manual for armor tuning.',
    difficulty: 7,
    rewardGold: 55,
    rewardItems: { iron_skin_manual: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 04'],
    steps: [turnIn('t1', 'Nộp Thiết Bì Chi Thuật Quyển.', 'Submit Iron Skin Manual.', { iron_skin_manual: 1 })],
  },
  {
    id: 'q_sys_artisan_05',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí V】 Kim Thạch Chi Thuật',
    nameEn: '【Artisan V】 Stone Aegis Technique',
    descVi: 'Hệ Thống tích hợp Kim Thạch Chi Thuật Quyển.',
    descEn: 'The System integrates Stone Aegis Manual.',
    difficulty: 8,
    rewardGold: 60,
    rewardItems: { stone_aegis_manual: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 05'],
    steps: [turnIn('t1', 'Giao Kim Thạch Chi Thuật Quyển.', 'Deliver Stone Aegis Manual.', { stone_aegis_manual: 1 })],
  },
  {
    id: 'q_sys_artisan_06',
    requiredSystemId: 'sys_artisan',
    giverNpcId: null,
    nameVi: '【Luyện Khí VI】 Phá Phong Đao Quyển',
    nameEn: '【Artisan VI】 Peak Cleaver Craft',
    descVi: 'Hệ Thống thẩm định Phá Phong Trảm Quyển.',
    descEn: 'The System appraises Peak Cleaver Manual.',
    difficulty: 9,
    rewardGold: 65,
    rewardItems: { peak_cleaver_manual: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys artisan 06'],
    steps: [turnIn('t1', 'Nộp Phá Phong Trảm Quyển.', 'Present Peak Cleaver Manual.', { peak_cleaver_manual: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 9. Scholar System (sys_scholar) — minGold: 20, maxGold: 55, minLS: 0, maxLS: 2
  // itemPool: herbal_breath_manual, iron_skin_manual, cloudwalk_manual, tide_breath_manual, stone_aegis_manual, rift_step_scroll, moonstone_pendant, spirit_stone
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_scholar_01',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư I】 Thảo Mộc Chi Khí',
    nameEn: '【Scholar I】 Herbal Breath Study',
    descVi: 'Hệ Thống thu chép Thảo Mộc Chi Khí Quyển.',
    descEn: 'The System transcribes Herbal Breath Manual.',
    difficulty: 3,
    rewardGold: 25,
    rewardItems: { herbal_breath_manual: 1 },
    rewardSpiritStones: 0,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 01'],
    steps: [turnIn('t1', 'Nộp Thảo Mộc Chi Khí Quyển.', 'Submit Herbal Breath Manual.', { herbal_breath_manual: 1 })],
  },
  {
    id: 'q_sys_scholar_02',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư II】 Triều Tích Chi Khí',
    nameEn: '【Scholar II】 Tide Breath Analysis',
    descVi: 'Hệ Thống khảo cứu Triều Tích Chi Khí Quyển.',
    descEn: 'The System analyzes Tide Breath Manual.',
    difficulty: 4,
    rewardGold: 30,
    rewardItems: { tide_breath_manual: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 02'],
    steps: [turnIn('t1', 'Giao Triều Tích Chi Khí Quyển.', 'Deliver Tide Breath Manual.', { tide_breath_manual: 1 })],
  },
  {
    id: 'q_sys_scholar_03',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư III】 Vân Bộ Luận',
    nameEn: '【Scholar III】 Cloudwalk Treatise',
    descVi: 'Hệ Thống biên dịch Vân Bộ Pháp Quyển.',
    descEn: 'The System translates Cloudwalk Manual.',
    difficulty: 5,
    rewardGold: 35,
    rewardItems: { cloudwalk_manual: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 03'],
    steps: [turnIn('t1', 'Nộp Vân Bộ Pháp Quyển.', 'Hand over Cloudwalk Manual.', { cloudwalk_manual: 1 })],
  },
  {
    id: 'q_sys_scholar_04',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư IV】 Ngọc Đá Nguyệt Quang',
    nameEn: '【Scholar IV】 Moonstone Lore',
    descVi: 'Hệ Thống ghi chép văn tự trên Mặt Đá Nguyệt Quang.',
    descEn: 'The System records inscriptions on Moonstone Pendant.',
    difficulty: 6,
    rewardGold: 40,
    rewardItems: { moonstone_pendant: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 04'],
    steps: [turnIn('t1', 'Nộp Mặt Đá Nguyệt Quang.', 'Submit Moonstone Pendant.', { moonstone_pendant: 1 })],
  },
  {
    id: 'q_sys_scholar_05',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư V】 Linh Thạch Cổ',
    nameEn: '【Scholar V】 Spirit Stone Codex',
    descVi: 'Hệ Thống đo lường hoa văn Linh Thạch.',
    descEn: 'The System measures Spirit Stone glyphs.',
    difficulty: 7,
    rewardGold: 45,
    rewardItems: { spirit_stone: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 05'],
    steps: [turnIn('t1', 'Dâng Linh Thạch.', 'Present Spirit Stone.', { spirit_stone: 1 })],
  },
  {
    id: 'q_sys_scholar_06',
    requiredSystemId: 'sys_scholar',
    giverNpcId: null,
    nameVi: '【Tàng Thư VI】 Cuộn Rách Hư Không',
    nameEn: '【Scholar VI】 Rift Scroll Translation',
    descVi: 'Hệ Thống lưu trữ Cuộn Bước Hư Không.',
    descEn: 'The System archives Rift Step Scroll.',
    difficulty: 8,
    rewardGold: 55,
    rewardItems: { rift_step_scroll: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys scholar 06'],
    steps: [turnIn('t1', 'Nộp Cuộn Bước Hư Không.', 'Hand over Rift Step Scroll.', { rift_step_scroll: 1 })],
  },

  // ---------------------------------------------------------------------------
  // 10. Void System (sys_void) — minGold: 50, maxGold: 100, minLS: 1, maxLS: 5
  // itemPool: pill_ls_cloud, pill_ls_iron, pill_ls_marrow, pill_ls_ninefold, spirit_stone, rift_step_scroll, stone_aegis_manual
  // ---------------------------------------------------------------------------
  {
    id: 'q_sys_void_01',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô I】 Dẫn Linh Đan',
    nameEn: '【Void I】 Cloud Spirit Pill',
    descVi: 'Hệ Thống nuốt chửng Vân Bộ Linh Đan để củng cố hư vô.',
    descEn: 'The System consumes Cloud Spirit Pill into the void.',
    difficulty: 5,
    rewardGold: 60,
    rewardItems: { pill_ls_cloud: 1 },
    rewardSpiritStones: 1,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 01'],
    steps: [turnIn('t1', 'Nộp Vân Bộ Linh Đan.', 'Submit Cloud Spirit Pill.', { pill_ls_cloud: 1 })],
  },
  {
    id: 'q_sys_void_02',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô II】 Thiết Bì Linh Đan',
    nameEn: '【Void II】 Iron Skin Spirit Pill',
    descVi: 'Hệ Thống hấp thụ Thiết Bì Linh Đan.',
    descEn: 'The System absorbs Iron Skin Spirit Pill.',
    difficulty: 6,
    rewardGold: 70,
    rewardItems: { pill_ls_iron: 1 },
    rewardSpiritStones: 2,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 02'],
    steps: [turnIn('t1', 'Giao Thiết Bì Linh Đan.', 'Deliver Iron Skin Spirit Pill.', { pill_ls_iron: 1 })],
  },
  {
    id: 'q_sys_void_03',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô III】 Tủy Linh Đan',
    nameEn: '【Void III】 Marrow Spirit Pill',
    descVi: 'Hệ Thống chuyển hóa Tụ Tủy Linh Đan.',
    descEn: 'The System converts Marrow Spirit Pill.',
    difficulty: 7,
    rewardGold: 80,
    rewardItems: { pill_ls_marrow: 1 },
    rewardSpiritStones: 3,
    deadlineDays: 3,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 03'],
    steps: [turnIn('t1', 'Nộp Tụ Tủy Linh Đan.', 'Hand over Marrow Spirit Pill.', { pill_ls_marrow: 1 })],
  },
  {
    id: 'q_sys_void_04',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô IV】 Cửu Chuyển Linh Đan',
    nameEn: '【Void IV】 Ninefold Spirit Pill',
    descVi: 'Hệ Thống tế lễ Cửu Chuyển Linh Đan.',
    descEn: 'The System sacrifices Ninefold Spirit Pill.',
    difficulty: 9,
    rewardGold: 90,
    rewardItems: { pill_ls_ninefold: 1 },
    rewardSpiritStones: 4,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 04'],
    steps: [turnIn('t1', 'Nộp Cửu Chuyển Linh Đan.', 'Present Ninefold Spirit Pill.', { pill_ls_ninefold: 1 })],
  },
  {
    id: 'q_sys_void_05',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô V】 Phong Ấn Hư Không',
    nameEn: '【Void V】 Rift Step Binding',
    descVi: 'Hệ Thống đồng hóa Cuộn Bước Hư Không.',
    descEn: 'The System assimilates Rift Step Scroll.',
    difficulty: 8,
    rewardGold: 85,
    rewardItems: { rift_step_scroll: 1 },
    rewardSpiritStones: 3,
    deadlineDays: 2,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 05'],
    steps: [turnIn('t1', 'Giao Cuộn Bước Hư Không.', 'Deliver Rift Step Scroll.', { rift_step_scroll: 1 })],
  },
  {
    id: 'q_sys_void_06',
    requiredSystemId: 'sys_void',
    giverNpcId: null,
    nameVi: '【Hư Vô VI】 Cực Hạn Linh Thạch',
    nameEn: '【Void VI】 Extreme Spirit Stone',
    descVi: 'Hệ Thống thu phí tối cao bằng Linh Thạch tinh khiết.',
    descEn: 'The System extracts prime Spirit Stones for void energy.',
    difficulty: 10,
    rewardGold: 100,
    rewardItems: { spirit_stone: 1 },
    rewardSpiritStones: 5,
    deadlineDays: 1,
    secret: true,
    requiredItems: {},
    requiredFlags: [],
    aliases: ['sys void 06'],
    steps: [turnIn('t1', 'Dâng Linh Thạch.', 'Present Spirit Stone.', { spirit_stone: 1 })],
  },
]
